In [102]:
import pandas as pd 
import numpy as np

In [103]:
matches=pd.read_csv("../team_data/mathces.csv")
matches

,home_team,away_team,home_team_goals,away_team_goals,home_team_age,away_team_age,date
0,Czech Republic,Denmark,3,1,29.363636,26.727273,2026-03-31T18:45:00Z
1,Hungary,Czech Republic,1,1,27.272727,27.000000,2023-09-10T16:00:00Z
2,Czech Republic,Saudi Arabia,1,1,26.090909,26.272727,2025-09-08T17:15:00Z
3,Czech Republic,Turkey,1,2,27.090909,25.818182,2024-06-26T19:00:00Z
4,Czech Republic,Albania,2,0,27.363636,26.363636,2024-10-11T18:45:00Z
...,...,...,...,...,...,...,...
1833,Canada,Guatemala,1,0,26.000000,26.181818,2026-01-18T03:30:00Z
1834,Canada,Guatemala,5,6,25.727273,27.090909,2025-06-29T20:00:00Z
1835,Guatemala,Canada,0,0,27.909091,28.727273,2023-07-02T01:30:00Z
1836,Japan,Canada,4,1,26.545455,26.909091,2023-10-13T10:35:00Z
1837,Venezuela,Canada,3,4,28.000000,27.090909,2024-07-06T01:00:00Z

In [104]:
matches.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1838 entries, 0 to 1837
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   home_team        1838 non-null   object
 1   away_team        1838 non-null   object
 2   home_team_goals  1838 non-null   int64
 3   away_team_goals  1838 non-null   int64
 4   home_team_age    1838 non-null   float64
 5   away_team_age    1838 non-null   float64
 6   date             1838 non-null   object
dtypes: float64(2), int64(2), object(3)
memory usage: 100.6+ KB

In [105]:
rank=pd.read_csv("../team_data/fifa_ranking-2024-06-20.csv")
rank.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 69020 entries, 0 to 69019
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   rank             69011 non-null  float64
 1   country_full     69020 non-null  object
 2   country_abrv     69020 non-null  object
 3   total_points     69020 non-null  float64
 4   previous_points  69020 non-null  float64
 5   rank_change      69020 non-null  int64
 6   confederation    67472 non-null  object
 7   rank_date        69020 non-null  object
dtypes: float64(3), int64(1), object(4)
memory usage: 4.2+ MB

In [106]:
rank["rank_date"] = pd.to_datetime(rank["rank_date"], utc=True)

In [107]:
rank=rank[rank["rank_date"].dt.year>=2022]
rank

,rank,country_full,country_abrv,total_points,previous_points,rank_change,confederation,rank_date
64104,128.0,Antigua and Barbuda,ATG,1131.07,1131.07,1,CONCACAF,2022-02-10 00:00:00+00:00
64105,136.0,Rwanda,RWA,1097.16,1095.34,1,CAF,2022-02-10 00:00:00+00:00
64106,135.0,Latvia,LVA,1100.03,1100.03,1,UEFA,2022-02-10 00:00:00+00:00
64107,127.0,Angola,ANG,1131.72,1131.72,1,CAF,2022-02-10 00:00:00+00:00
64108,134.0,Turkmenistan,TKM,1117.60,1117.60,1,AFC,2022-02-10 00:00:00+00:00
...,...,...,...,...,...,...,...,...
69015,74.0,Ghana,Ghana,1346.00,1351.00,-2,NaN,2026-04-01 00:00:00+00:00
69016,76.0,Bolivia,Bolivia,1329.00,1331.00,0,NaN,2026-04-01 00:00:00+00:00
69017,82.0,Curaçao,Curaçao,1295.00,1303.00,-1,NaN,2026-04-01 00:00:00+00:00
69018,83.0,Haiti,Haiti,1292.00,1294.00,0,NaN,2026-04-01 00:00:00+00:00
69019,85.0,New Zealand,New Zealand,1282.00,1279.00,0,NaN,2026-04-01 00:00:00+00:00

In [108]:
world_cup_2026_teams = [
    # Hosts
    "Canada", "Mexico", "USA",

    # AFC (Asia)
    "Australia", "IR Iran", "Japan", "Jordan", "Korea Republic",
    "Qatar", "Saudi Arabia", "Uzbekistan",

    # CAF (Africa)
    "Algeria", "Cabo Verde", "Côte d'Ivoire", "Egypt", "Ghana",
    "Morocco", "Senegal", "South Africa", "Tunisia",

    # CONCACAF (North & Central America, Caribbean)
    "Curacao", "Haiti", "Panama",

    # CONMEBOL (South America)
    "Argentina", "Brazil", "Colombia", "Ecuador", "Paraguay", "Uruguay",

    # OFC (Oceania)
    "New Zealand",

    # UEFA (Europe)
    "Austria", "Belgium", "Bosnia and Herzegovina", "Croatia", "Czechia",
    "England", "France", "Germany", "Netherlands", "Norway",
    "Portugal", "Scotland", "Spain", "Sweden", "Switzerland", "Turkey",

    # Play-Off Tournament winners
    "Bolivia", "Congo DR", "Iraq"
]
print(len(world_cup_2026_teams))
rank=rank[rank["country_full"].isin(world_cup_2026_teams)]
rank

49

,rank,country_full,country_abrv,total_points,previous_points,rank_change,confederation,rank_date
64145,111.0,New Zealand,NZL,1161.66,1165.81,1,OFC,2022-02-10 00:00:00+00:00
64223,29.0,Korea Republic,KOR,1522.85,1507.24,-4,AFC,2022-02-10 00:00:00+00:00
64224,30.0,Austria,AUT,1511.56,1511.56,-1,UEFA,2022-02-10 00:00:00+00:00
64225,31.0,Czechia,CZE,1510.42,1510.42,-1,UEFA,2022-02-10 00:00:00+00:00
64227,33.0,Canada,CAN,1497.82,1462.32,-7,CONCACAF,2022-02-10 00:00:00+00:00
...,...,...,...,...,...,...,...,...
69013,63.0,Jordan,Jordan,1391.00,1389.00,1,NaN,2026-04-01 00:00:00+00:00
69015,74.0,Ghana,Ghana,1346.00,1351.00,-2,NaN,2026-04-01 00:00:00+00:00
69016,76.0,Bolivia,Bolivia,1329.00,1331.00,0,NaN,2026-04-01 00:00:00+00:00
69018,83.0,Haiti,Haiti,1292.00,1294.00,0,NaN,2026-04-01 00:00:00+00:00
69019,85.0,New Zealand,New Zealand,1282.00,1279.00,0,NaN,2026-04-01 00:00:00+00:00

In [109]:
rank["confederation"]=rank.groupby("country_full")["confederation"].transform("first")
rank

/tmp/ipykernel_5108/146620998.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  rank["confederation"]=rank.groupby("country_full")["confederation"].transform("first")

,rank,country_full,country_abrv,total_points,previous_points,rank_change,confederation,rank_date
64145,111.0,New Zealand,NZL,1161.66,1165.81,1,OFC,2022-02-10 00:00:00+00:00
64223,29.0,Korea Republic,KOR,1522.85,1507.24,-4,AFC,2022-02-10 00:00:00+00:00
64224,30.0,Austria,AUT,1511.56,1511.56,-1,UEFA,2022-02-10 00:00:00+00:00
64225,31.0,Czechia,CZE,1510.42,1510.42,-1,UEFA,2022-02-10 00:00:00+00:00
64227,33.0,Canada,CAN,1497.82,1462.32,-7,CONCACAF,2022-02-10 00:00:00+00:00
...,...,...,...,...,...,...,...,...
69013,63.0,Jordan,Jordan,1391.00,1389.00,1,AFC,2026-04-01 00:00:00+00:00
69015,74.0,Ghana,Ghana,1346.00,1351.00,-2,CAF,2026-04-01 00:00:00+00:00
69016,76.0,Bolivia,Bolivia,1329.00,1331.00,0,CONMEBOL,2026-04-01 00:00:00+00:00
69018,83.0,Haiti,Haiti,1292.00,1294.00,0,CONCACAF,2026-04-01 00:00:00+00:00
69019,85.0,New Zealand,New Zealand,1282.00,1279.00,0,OFC,2026-04-01 00:00:00+00:00

In [110]:
rank=rank.reset_index()
rank=rank.drop(columns=["country_abrv","index"])
rank

,rank,country_full,total_points,previous_points,rank_change,confederation,rank_date
0,111.0,New Zealand,1161.66,1165.81,1,OFC,2022-02-10 00:00:00+00:00
1,29.0,Korea Republic,1522.85,1507.24,-4,AFC,2022-02-10 00:00:00+00:00
2,30.0,Austria,1511.56,1511.56,-1,UEFA,2022-02-10 00:00:00+00:00
3,31.0,Czechia,1510.42,1510.42,-1,UEFA,2022-02-10 00:00:00+00:00
4,33.0,Canada,1497.82,1462.32,-7,CONCACAF,2022-02-10 00:00:00+00:00
...,...,...,...,...,...,...,...
2097,63.0,Jordan,1391.00,1389.00,1,AFC,2026-04-01 00:00:00+00:00
2098,74.0,Ghana,1346.00,1351.00,-2,CAF,2026-04-01 00:00:00+00:00
2099,76.0,Bolivia,1329.00,1331.00,0,CONMEBOL,2026-04-01 00:00:00+00:00
2100,83.0,Haiti,1292.00,1294.00,0,CONCACAF,2026-04-01 00:00:00+00:00
2101,85.0,New Zealand,1282.00,1279.00,0,OFC,2026-04-01 00:00:00+00:00

In [111]:
rank_date=np.unique(rank["rank_date"])
rank_date

array([Timestamp('2022-02-10 00:00:00+0000', tz='UTC'),
       Timestamp('2022-03-31 00:00:00+0000', tz='UTC'),
       Timestamp('2022-06-23 00:00:00+0000', tz='UTC'),
       Timestamp('2022-08-25 00:00:00+0000', tz='UTC'),
       Timestamp('2022-10-06 00:00:00+0000', tz='UTC'),
       Timestamp('2022-12-22 00:00:00+0000', tz='UTC'),
       Timestamp('2023-04-06 00:00:00+0000', tz='UTC'),
       Timestamp('2023-06-29 00:00:00+0000', tz='UTC'),
       Timestamp('2023-07-20 00:00:00+0000', tz='UTC'),
       Timestamp('2023-09-21 00:00:00+0000', tz='UTC'),
       Timestamp('2023-10-26 00:00:00+0000', tz='UTC'),
       Timestamp('2023-11-30 00:00:00+0000', tz='UTC'),
       Timestamp('2023-12-21 00:00:00+0000', tz='UTC'),
       Timestamp('2024-02-15 00:00:00+0000', tz='UTC'),
       Timestamp('2024-04-04 00:00:00+0000', tz='UTC'),
       Timestamp('2024-06-20 00:00:00+0000', tz='UTC'),
       Timestamp('2024-07-18 00:00:00+0000', tz='UTC'),
       Timestamp('2024-09-19 00:00:00+0000', tz='UTC'),
       Timestamp('2024-10-24 00:00:00+0000', tz='UTC'),
       Timestamp('2024-11-28 00:00:00+0000', tz='UTC'),
       Timestamp('2024-12-19 00:00:00+0000', tz='UTC'),
       Timestamp('2025-01-20 00:00:00+0000', tz='UTC'),
       Timestamp('2025-04-03 00:00:00+0000', tz='UTC'),
       Timestamp('2025-07-10 00:00:00+0000', tz='UTC'),
       Timestamp('2025-09-18 00:00:00+0000', tz='UTC'),
       Timestamp('2025-10-17 00:00:00+0000', tz='UTC'),
       Timestamp('2025-11-19 00:00:00+0000', tz='UTC'),
       Timestamp('2025-12-22 00:00:00+0000', tz='UTC'),
       Timestamp('2026-01-19 00:00:00+0000', tz='UTC'),
       Timestamp('2026-03-18 00:00:00+0000', tz='UTC'),
       Timestamp('2026-04-01 00:00:00+0000', tz='UTC')], dtype=object)

In [112]:
def give_rank_date(date):
    for d in rank_date:
        if date>d:
            return d
       
matches["date"]=pd.to_datetime(matches["date"],utc=True)
matches["rank_date"]=matches["date"].apply(give_rank_date)
matches

,home_team,away_team,home_team_goals,away_team_goals,home_team_age,away_team_age,date,rank_date
0,Czech Republic,Denmark,3,1,29.363636,26.727273,2026-03-31 18:45:00+00:00,2022-02-10 00:00:00+00:00
1,Hungary,Czech Republic,1,1,27.272727,27.000000,2023-09-10 16:00:00+00:00,2022-02-10 00:00:00+00:00
2,Czech Republic,Saudi Arabia,1,1,26.090909,26.272727,2025-09-08 17:15:00+00:00,2022-02-10 00:00:00+00:00
3,Czech Republic,Turkey,1,2,27.090909,25.818182,2024-06-26 19:00:00+00:00,2022-02-10 00:00:00+00:00
4,Czech Republic,Albania,2,0,27.363636,26.363636,2024-10-11 18:45:00+00:00,2022-02-10 00:00:00+00:00
...,...,...,...,...,...,...,...,...
1833,Canada,Guatemala,1,0,26.000000,26.181818,2026-01-18 03:30:00+00:00,2022-02-10 00:00:00+00:00
1834,Canada,Guatemala,5,6,25.727273,27.090909,2025-06-29 20:00:00+00:00,2022-02-10 00:00:00+00:00
1835,Guatemala,Canada,0,0,27.909091,28.727273,2023-07-02 01:30:00+00:00,2022-02-10 00:00:00+00:00
1836,Japan,Canada,4,1,26.545455,26.909091,2023-10-13 10:35:00+00:00,2022-02-10 00:00:00+00:00
1837,Venezuela,Canada,3,4,28.000000,27.090909,2024-07-06 01:00:00+00:00,2022-02-10 00:00:00+00:00

In [113]:
spcial_teams={"IR Iran":"Iran","Turkey":"Turkiye","Korea Republic":"South Korea","Côte d'Ivoire":"Ivory Coast","Congo DR":"DR Congo","Cabo Verde":"Cape Verde","Curacao":"Curaçao","USA":"United States","Czech Republic":"Czechia"}

spcial = {v: k for k, v in spcial_teams.items()}

In [114]:
rank["country_full"]=rank["country_full"].replace(spcial)

In [115]:
rank

,rank,country_full,total_points,previous_points,rank_change,confederation,rank_date
0,111.0,New Zealand,1161.66,1165.81,1,OFC,2022-02-10 00:00:00+00:00
1,29.0,Korea Republic,1522.85,1507.24,-4,AFC,2022-02-10 00:00:00+00:00
2,30.0,Austria,1511.56,1511.56,-1,UEFA,2022-02-10 00:00:00+00:00
3,31.0,Czech Republic,1510.42,1510.42,-1,UEFA,2022-02-10 00:00:00+00:00
4,33.0,Canada,1497.82,1462.32,-7,CONCACAF,2022-02-10 00:00:00+00:00
...,...,...,...,...,...,...,...
2097,63.0,Jordan,1391.00,1389.00,1,AFC,2026-04-01 00:00:00+00:00
2098,74.0,Ghana,1346.00,1351.00,-2,CAF,2026-04-01 00:00:00+00:00
2099,76.0,Bolivia,1329.00,1331.00,0,CONMEBOL,2026-04-01 00:00:00+00:00
2100,83.0,Haiti,1292.00,1294.00,0,CONCACAF,2026-04-01 00:00:00+00:00
2101,85.0,New Zealand,1282.00,1279.00,0,OFC,2026-04-01 00:00:00+00:00

In [116]:
matches = matches.merge(
    rank[[
        "country_full",
        "rank_date",
        "rank",
        "total_points",
        "rank_change",
        "previous_points",
        "confederation"
    ]],
    left_on=["home_team", "rank_date"],
    right_on=["country_full", "rank_date"],
    how="left"
)

matches = matches.rename(columns={
    "rank": "home_rank",
    "total_points": "home_total_points",
    "rank_change": "home_rank_change",
    "previous_points": "home_previous_points",
    "confederation": "home_conf"
}).drop(columns=["country_full"])
matches = matches.merge(
    rank[[
        "country_full",
        "rank_date",
        "rank",
        "total_points",
        "rank_change",
        "previous_points",
        "confederation"
    ]],
    left_on=["away_team", "rank_date"],
    right_on=["country_full", "rank_date"],
    how="left"
)

matches = matches.rename(columns={
    "rank": "away_rank",
    "total_points": "away_total_points",
    "rank_change": "away_rank_change",
    "previous_points": "away_previous_points",
    "confederation": "away_conf"
}).drop(columns=["country_full"])

In [117]:
matches

,home_team,away_team,home_team_goals,away_team_goals,home_team_age,away_team_age,date,rank_date,home_rank,home_total_points,home_rank_change,home_previous_points,home_conf,away_rank,away_total_points,away_rank_change,away_previous_points,away_conf
0,Czech Republic,Denmark,3,1,29.363636,26.727273,2026-03-31 18:45:00+00:00,2022-02-10 00:00:00+00:00,31.0,1510.42,-1.0,1510.42,UEFA,NaN,NaN,NaN,NaN,NaN
1,Hungary,Czech Republic,1,1,27.272727,27.000000,2023-09-10 16:00:00+00:00,2022-02-10 00:00:00+00:00,NaN,NaN,NaN,NaN,NaN,31.0,1510.42,-1.0,1510.42,UEFA
2,Czech Republic,Saudi Arabia,1,1,26.090909,26.272727,2025-09-08 17:15:00+00:00,2022-02-10 00:00:00+00:00,31.0,1510.42,-1.0,1510.42,UEFA,53.0,1433.95,2.0,1434.71,AFC
3,Czech Republic,Turkey,1,2,27.090909,25.818182,2024-06-26 19:00:00+00:00,2022-02-10 00:00:00+00:00,31.0,1510.42,-1.0,1510.42,UEFA,39.0,1472.72,2.0,1472.72,UEFA
4,Czech Republic,Albania,2,0,27.363636,26.363636,2024-10-11 18:45:00+00:00,2022-02-10 00:00:00+00:00,31.0,1510.42,-1.0,1510.42,UEFA,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1833,Canada,Guatemala,1,0,26.000000,26.181818,2026-01-18 03:30:00+00:00,2022-02-10 00:00:00+00:00,33.0,1497.82,-7.0,1462.32,CONCACAF,NaN,NaN,NaN,NaN,NaN
1834,Canada,Guatemala,5,6,25.727273,27.090909,2025-06-29 20:00:00+00:00,2022-02-10 00:00:00+00:00,33.0,1497.82,-7.0,1462.32,CONCACAF,NaN,NaN,NaN,NaN,NaN
1835,Guatemala,Canada,0,0,27.909091,28.727273,2023-07-02 01:30:00+00:00,2022-02-10 00:00:00+00:00,NaN,NaN,NaN,NaN,NaN,33.0,1497.82,-7.0,1462.32,CONCACAF
1836,Japan,Canada,4,1,26.545455,26.909091,2023-10-13 10:35:00+00:00,2022-02-10 00:00:00+00:00,23.0,1549.82,-3.0,1531.53,AFC,33.0,1497.82,-7.0,1462.32,CONCACAF
1837,Venezuela,Canada,3,4,28.000000,27.090909,2024-07-06 01:00:00+00:00,2022-02-10 00:00:00+00:00,NaN,NaN,NaN,NaN,NaN,33.0,1497.82,-7.0,1462.32,CONCACAF