In [50]:
import pandas as pd 
import numpy as np

In [51]:
matches=pd.read_csv("../team_data/mathces.csv")
matches

,home_team,away_team,home_team_goals,away_team_goals,home_team_age,away_team_age,date
0,Czech Republic,Denmark,3,1,29.363636,26.727273,2026-03-31T18:45:00Z
1,Hungary,Czech Republic,1,1,27.272727,27.000000,2023-09-10T16:00:00Z
2,Czech Republic,Saudi Arabia,1,1,26.090909,26.272727,2025-09-08T17:15:00Z
3,Czech Republic,Turkey,1,2,27.090909,25.818182,2024-06-26T19:00:00Z
4,Czech Republic,Albania,2,0,27.363636,26.363636,2024-10-11T18:45:00Z
...,...,...,...,...,...,...,...
1833,Canada,Guatemala,1,0,26.000000,26.181818,2026-01-18T03:30:00Z
1834,Canada,Guatemala,5,6,25.727273,27.090909,2025-06-29T20:00:00Z
1835,Guatemala,Canada,0,0,27.909091,28.727273,2023-07-02T01:30:00Z
1836,Japan,Canada,4,1,26.545455,26.909091,2023-10-13T10:35:00Z
1837,Venezuela,Canada,3,4,28.000000,27.090909,2024-07-06T01:00:00Z

In [52]:
matches.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1838 entries, 0 to 1837
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   home_team        1838 non-null   object
 1   away_team        1838 non-null   object
 2   home_team_goals  1838 non-null   int64
 3   away_team_goals  1838 non-null   int64
 4   home_team_age    1838 non-null   float64
 5   away_team_age    1838 non-null   float64
 6   date             1838 non-null   object
dtypes: float64(2), int64(2), object(3)
memory usage: 100.6+ KB

In [53]:
rank=pd.read_csv("../team_data/fifa_ranking-2024-06-20.csv")
rank.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 70322 entries, 0 to 70321
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   rank             70313 non-null  float64
 1   country_full     70322 non-null  object
 2   country_abrv     70322 non-null  object
 3   total_points     70322 non-null  float64
 4   previous_points  70322 non-null  float64
 5   rank_change      70322 non-null  int64
 6   confederation    67472 non-null  object
 7   rank_date        70322 non-null  object
dtypes: float64(3), int64(1), object(4)
memory usage: 4.3+ MB

In [54]:
rank["rank_date"] = pd.to_datetime(rank["rank_date"], utc=True)

In [55]:
rank=rank[rank["rank_date"].dt.year>=2022]
rank

,rank,country_full,country_abrv,total_points,previous_points,rank_change,confederation,rank_date
64104,128.0,Antigua and Barbuda,ATG,1131.07,1131.07,1,CONCACAF,2022-02-10 00:00:00+00:00
64105,136.0,Rwanda,RWA,1097.16,1095.34,1,CAF,2022-02-10 00:00:00+00:00
64106,135.0,Latvia,LVA,1100.03,1100.03,1,UEFA,2022-02-10 00:00:00+00:00
64107,127.0,Angola,ANG,1131.72,1131.72,1,CAF,2022-02-10 00:00:00+00:00
64108,134.0,Turkmenistan,TKM,1117.60,1117.60,1,AFC,2022-02-10 00:00:00+00:00
...,...,...,...,...,...,...,...,...
70317,195.0,Cayman Islands,CAY,855.00,852.00,0,NaN,2026-04-01 00:00:00+00:00
70318,197.0,Djibouti,DJI,854.00,847.00,-1,NaN,2026-04-01 00:00:00+00:00
70319,198.0,Somalia,SOM,839.00,829.00,2,NaN,2026-04-01 00:00:00+00:00
70320,199.0,Tonga,TGA,836.00,836.00,-2,NaN,2026-04-01 00:00:00+00:00
70321,200.0,Timor-Leste,TLS,826.00,836.00,-2,NaN,2026-04-01 00:00:00+00:00

In [56]:
world_cup_2026_teams = [
    # Hosts
    "Canada", "Mexico", "USA",

    # AFC (Asia)
    "Australia", "IR Iran", "Japan", "Jordan", "Korea Republic",
    "Qatar", "Saudi Arabia", "Uzbekistan",

    # CAF (Africa)
    "Algeria", "Cabo Verde", "Côte d'Ivoire", "Egypt", "Ghana",
    "Morocco", "Senegal", "South Africa", "Tunisia",

    # CONCACAF (North & Central America, Caribbean)
    "Curacao", "Haiti", "Panama",

    # CONMEBOL (South America)
    "Argentina", "Brazil", "Colombia", "Ecuador", "Paraguay", "Uruguay",

    # OFC (Oceania)
    "New Zealand",

    # UEFA (Europe)
    "Austria", "Belgium", "Bosnia and Herzegovina", "Croatia", "Czechia",
    "England", "France", "Germany", "Netherlands", "Norway",
    "Portugal", "Scotland", "Spain", "Sweden", "Switzerland", "Turkey",

    # Play-Off Tournament winners
    "Bolivia", "Congo DR", "Iraq"
]
print(len(world_cup_2026_teams))
rank

49

,rank,country_full,country_abrv,total_points,previous_points,rank_change,confederation,rank_date
64104,128.0,Antigua and Barbuda,ATG,1131.07,1131.07,1,CONCACAF,2022-02-10 00:00:00+00:00
64105,136.0,Rwanda,RWA,1097.16,1095.34,1,CAF,2022-02-10 00:00:00+00:00
64106,135.0,Latvia,LVA,1100.03,1100.03,1,UEFA,2022-02-10 00:00:00+00:00
64107,127.0,Angola,ANG,1131.72,1131.72,1,CAF,2022-02-10 00:00:00+00:00
64108,134.0,Turkmenistan,TKM,1117.60,1117.60,1,AFC,2022-02-10 00:00:00+00:00
...,...,...,...,...,...,...,...,...
70317,195.0,Cayman Islands,CAY,855.00,852.00,0,NaN,2026-04-01 00:00:00+00:00
70318,197.0,Djibouti,DJI,854.00,847.00,-1,NaN,2026-04-01 00:00:00+00:00
70319,198.0,Somalia,SOM,839.00,829.00,2,NaN,2026-04-01 00:00:00+00:00
70320,199.0,Tonga,TGA,836.00,836.00,-2,NaN,2026-04-01 00:00:00+00:00
70321,200.0,Timor-Leste,TLS,826.00,836.00,-2,NaN,2026-04-01 00:00:00+00:00

In [57]:
rank["confederation"]=rank.groupby("country_full")["confederation"].transform("first")
rank

,rank,country_full,country_abrv,total_points,previous_points,rank_change,confederation,rank_date
64104,128.0,Antigua and Barbuda,ATG,1131.07,1131.07,1,CONCACAF,2022-02-10 00:00:00+00:00
64105,136.0,Rwanda,RWA,1097.16,1095.34,1,CAF,2022-02-10 00:00:00+00:00
64106,135.0,Latvia,LVA,1100.03,1100.03,1,UEFA,2022-02-10 00:00:00+00:00
64107,127.0,Angola,ANG,1131.72,1131.72,1,CAF,2022-02-10 00:00:00+00:00
64108,134.0,Turkmenistan,TKM,1117.60,1117.60,1,AFC,2022-02-10 00:00:00+00:00
...,...,...,...,...,...,...,...,...
70317,195.0,Cayman Islands,CAY,855.00,852.00,0,CONCACAF,2026-04-01 00:00:00+00:00
70318,197.0,Djibouti,DJI,854.00,847.00,-1,CAF,2026-04-01 00:00:00+00:00
70319,198.0,Somalia,SOM,839.00,829.00,2,CAF,2026-04-01 00:00:00+00:00
70320,199.0,Tonga,TGA,836.00,836.00,-2,OFC,2026-04-01 00:00:00+00:00
70321,200.0,Timor-Leste,TLS,826.00,836.00,-2,AFC,2026-04-01 00:00:00+00:00

In [58]:
rank=rank.reset_index()
rank=rank.drop(columns=["country_abrv","index"])
rank

,rank,country_full,total_points,previous_points,rank_change,confederation,rank_date
0,128.0,Antigua and Barbuda,1131.07,1131.07,1,CONCACAF,2022-02-10 00:00:00+00:00
1,136.0,Rwanda,1097.16,1095.34,1,CAF,2022-02-10 00:00:00+00:00
2,135.0,Latvia,1100.03,1100.03,1,UEFA,2022-02-10 00:00:00+00:00
3,127.0,Angola,1131.72,1131.72,1,CAF,2022-02-10 00:00:00+00:00
4,134.0,Turkmenistan,1117.60,1117.60,1,AFC,2022-02-10 00:00:00+00:00
...,...,...,...,...,...,...,...
6213,195.0,Cayman Islands,855.00,852.00,0,CONCACAF,2026-04-01 00:00:00+00:00
6214,197.0,Djibouti,854.00,847.00,-1,CAF,2026-04-01 00:00:00+00:00
6215,198.0,Somalia,839.00,829.00,2,CAF,2026-04-01 00:00:00+00:00
6216,199.0,Tonga,836.00,836.00,-2,OFC,2026-04-01 00:00:00+00:00
6217,200.0,Timor-Leste,826.00,836.00,-2,AFC,2026-04-01 00:00:00+00:00

In [59]:
rank_date=np.unique(rank["rank_date"])
rank_date

array([Timestamp('2022-02-10 00:00:00+0000', tz='UTC'),
       Timestamp('2022-03-31 00:00:00+0000', tz='UTC'),
       Timestamp('2022-06-23 00:00:00+0000', tz='UTC'),
       Timestamp('2022-08-25 00:00:00+0000', tz='UTC'),
       Timestamp('2022-10-06 00:00:00+0000', tz='UTC'),
       Timestamp('2022-12-22 00:00:00+0000', tz='UTC'),
       Timestamp('2023-04-06 00:00:00+0000', tz='UTC'),
       Timestamp('2023-06-29 00:00:00+0000', tz='UTC'),
       Timestamp('2023-07-20 00:00:00+0000', tz='UTC'),
       Timestamp('2023-09-21 00:00:00+0000', tz='UTC'),
       Timestamp('2023-10-26 00:00:00+0000', tz='UTC'),
       Timestamp('2023-11-30 00:00:00+0000', tz='UTC'),
       Timestamp('2023-12-21 00:00:00+0000', tz='UTC'),
       Timestamp('2024-02-15 00:00:00+0000', tz='UTC'),
       Timestamp('2024-04-04 00:00:00+0000', tz='UTC'),
       Timestamp('2024-06-20 00:00:00+0000', tz='UTC'),
       Timestamp('2024-07-18 00:00:00+0000', tz='UTC'),
       Timestamp('2024-09-19 00:00:00+0000', tz='UTC'),
       Timestamp('2024-10-24 00:00:00+0000', tz='UTC'),
       Timestamp('2024-11-28 00:00:00+0000', tz='UTC'),
       Timestamp('2024-12-19 00:00:00+0000', tz='UTC'),
       Timestamp('2025-01-20 00:00:00+0000', tz='UTC'),
       Timestamp('2025-04-03 00:00:00+0000', tz='UTC'),
       Timestamp('2025-07-10 00:00:00+0000', tz='UTC'),
       Timestamp('2025-09-18 00:00:00+0000', tz='UTC'),
       Timestamp('2025-10-17 00:00:00+0000', tz='UTC'),
       Timestamp('2025-11-19 00:00:00+0000', tz='UTC'),
       Timestamp('2025-12-22 00:00:00+0000', tz='UTC'),
       Timestamp('2026-01-19 00:00:00+0000', tz='UTC'),
       Timestamp('2026-03-18 00:00:00+0000', tz='UTC'),
       Timestamp('2026-04-01 00:00:00+0000', tz='UTC')], dtype=object)

In [60]:
def give_rank_date(date):
    for d in rank_date:
        if date>d:
            return d
       
matches["date"]=pd.to_datetime(matches["date"],utc=True)
matches["rank_date"]=matches["date"].apply(give_rank_date)
matches

,home_team,away_team,home_team_goals,away_team_goals,home_team_age,away_team_age,date,rank_date
0,Czech Republic,Denmark,3,1,29.363636,26.727273,2026-03-31 18:45:00+00:00,2022-02-10 00:00:00+00:00
1,Hungary,Czech Republic,1,1,27.272727,27.000000,2023-09-10 16:00:00+00:00,2022-02-10 00:00:00+00:00
2,Czech Republic,Saudi Arabia,1,1,26.090909,26.272727,2025-09-08 17:15:00+00:00,2022-02-10 00:00:00+00:00
3,Czech Republic,Turkey,1,2,27.090909,25.818182,2024-06-26 19:00:00+00:00,2022-02-10 00:00:00+00:00
4,Czech Republic,Albania,2,0,27.363636,26.363636,2024-10-11 18:45:00+00:00,2022-02-10 00:00:00+00:00
...,...,...,...,...,...,...,...,...
1833,Canada,Guatemala,1,0,26.000000,26.181818,2026-01-18 03:30:00+00:00,2022-02-10 00:00:00+00:00
1834,Canada,Guatemala,5,6,25.727273,27.090909,2025-06-29 20:00:00+00:00,2022-02-10 00:00:00+00:00
1835,Guatemala,Canada,0,0,27.909091,28.727273,2023-07-02 01:30:00+00:00,2022-02-10 00:00:00+00:00
1836,Japan,Canada,4,1,26.545455,26.909091,2023-10-13 10:35:00+00:00,2022-02-10 00:00:00+00:00
1837,Venezuela,Canada,3,4,28.000000,27.090909,2024-07-06 01:00:00+00:00,2022-02-10 00:00:00+00:00

In [61]:
spcial_teams = {
    "IR Iran": "Iran",
    "Turkey": "Turkiye",
    "Korea Republic": "South Korea",
    "Côte d'Ivoire": "Ivory Coast",
    "Congo DR": "DR Congo",
    "Cabo Verde": "Cape Verde",
    "Curacao": "Curaçao",
    "USA": "United States",
    "Czech Republic": "Czechia"
}

rank["country_full"] = rank["country_full"].replace(spcial_teams)
matches["home_team"] = matches["home_team"].replace(spcial_teams)
matches["away_team"] = matches["away_team"].replace(spcial_teams)

In [62]:
rank

,rank,country_full,total_points,previous_points,rank_change,confederation,rank_date
0,128.0,Antigua and Barbuda,1131.07,1131.07,1,CONCACAF,2022-02-10 00:00:00+00:00
1,136.0,Rwanda,1097.16,1095.34,1,CAF,2022-02-10 00:00:00+00:00
2,135.0,Latvia,1100.03,1100.03,1,UEFA,2022-02-10 00:00:00+00:00
3,127.0,Angola,1131.72,1131.72,1,CAF,2022-02-10 00:00:00+00:00
4,134.0,Turkmenistan,1117.60,1117.60,1,AFC,2022-02-10 00:00:00+00:00
...,...,...,...,...,...,...,...
6213,195.0,Cayman Islands,855.00,852.00,0,CONCACAF,2026-04-01 00:00:00+00:00
6214,197.0,Djibouti,854.00,847.00,-1,CAF,2026-04-01 00:00:00+00:00
6215,198.0,Somalia,839.00,829.00,2,CAF,2026-04-01 00:00:00+00:00
6216,199.0,Tonga,836.00,836.00,-2,OFC,2026-04-01 00:00:00+00:00
6217,200.0,Timor-Leste,826.00,836.00,-2,AFC,2026-04-01 00:00:00+00:00

In [63]:
rank["country_full"] = rank["country_full"].str.strip()
matches["home_team"] = matches["home_team"].str.strip()
matches["away_team"] = matches["away_team"].str.strip()

In [64]:
matches = matches.merge(
    rank[[
        "country_full",
        "rank_date",
        "rank",
        "total_points",
        "rank_change",
        "previous_points",
        "confederation"
    ]],
    left_on=["home_team", "rank_date"],
    right_on=["country_full", "rank_date"],
    how="left"
)

matches = matches.rename(columns={
    "rank": "home_rank",
    "total_points": "home_total_points",
    "rank_change": "home_rank_change",
    "previous_points": "home_previous_points",
    "confederation": "home_conf"
}).drop(columns=["country_full"])
matches = matches.merge(
    rank[[
        "country_full",
        "rank_date",
        "rank",
        "total_points",
        "rank_change",
        "previous_points",
        "confederation"
    ]],
    left_on=["away_team", "rank_date"],
    right_on=["country_full", "rank_date"],
    how="left"
)

matches = matches.rename(columns={
    "rank": "away_rank",
    "total_points": "away_total_points",
    "rank_change": "away_rank_change",
    "previous_points": "away_previous_points",
    "confederation": "away_conf"
}).drop(columns=["country_full"])

In [65]:
matches

,home_team,away_team,home_team_goals,away_team_goals,home_team_age,away_team_age,date,rank_date,home_rank,home_total_points,home_rank_change,home_previous_points,home_conf,away_rank,away_total_points,away_rank_change,away_previous_points,away_conf
0,Czechia,Denmark,3,1,29.363636,26.727273,2026-03-31 18:45:00+00:00,2022-02-10 00:00:00+00:00,31.0,1510.42,-1.0,1510.42,UEFA,9.0,1654.54,0.0,1654.54,UEFA
1,Hungary,Czechia,1,1,27.272727,27.000000,2023-09-10 16:00:00+00:00,2022-02-10 00:00:00+00:00,41.0,1465.62,2.0,1465.62,UEFA,31.0,1510.42,-1.0,1510.42,UEFA
2,Czechia,Saudi Arabia,1,1,26.090909,26.272727,2025-09-08 17:15:00+00:00,2022-02-10 00:00:00+00:00,31.0,1510.42,-1.0,1510.42,UEFA,53.0,1433.95,2.0,1434.71,AFC
3,Czechia,Turkiye,1,2,27.090909,25.818182,2024-06-26 19:00:00+00:00,2022-02-10 00:00:00+00:00,31.0,1510.42,-1.0,1510.42,UEFA,39.0,1472.72,2.0,1472.72,UEFA
4,Czechia,Albania,2,0,27.363636,26.363636,2024-10-11 18:45:00+00:00,2022-02-10 00:00:00+00:00,31.0,1510.42,-1.0,1510.42,UEFA,65.0,1374.98,-1.0,1374.98,UEFA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1833,Canada,Guatemala,1,0,26.000000,26.181818,2026-01-18 03:30:00+00:00,2022-02-10 00:00:00+00:00,33.0,1497.82,-7.0,1462.32,CONCACAF,123.0,1138.40,1.0,1138.40,CONCACAF
1834,Canada,Guatemala,5,6,25.727273,27.090909,2025-06-29 20:00:00+00:00,2022-02-10 00:00:00+00:00,33.0,1497.82,-7.0,1462.32,CONCACAF,123.0,1138.40,1.0,1138.40,CONCACAF
1835,Guatemala,Canada,0,0,27.909091,28.727273,2023-07-02 01:30:00+00:00,2022-02-10 00:00:00+00:00,123.0,1138.40,1.0,1138.40,CONCACAF,33.0,1497.82,-7.0,1462.32,CONCACAF
1836,Japan,Canada,4,1,26.545455,26.909091,2023-10-13 10:35:00+00:00,2022-02-10 00:00:00+00:00,23.0,1549.82,-3.0,1531.53,AFC,33.0,1497.82,-7.0,1462.32,CONCACAF
1837,Venezuela,Canada,3,4,28.000000,27.090909,2024-07-06 01:00:00+00:00,2022-02-10 00:00:00+00:00,58.0,1411.45,-1.0,1409.14,CONMEBOL,33.0,1497.82,-7.0,1462.32,CONCACAF

In [66]:
matches.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1838 entries, 0 to 1837
Data columns (total 18 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   home_team             1838 non-null   object
 1   away_team             1838 non-null   object
 2   home_team_goals       1838 non-null   int64
 3   away_team_goals       1838 non-null   int64
 4   home_team_age         1838 non-null   float64
 5   away_team_age         1838 non-null   float64
 6   date                  1838 non-null   datetime64[ns, UTC]
 7   rank_date             1785 non-null   datetime64[ns, UTC]
 8   home_rank             1704 non-null   float64
 9   home_total_points     1704 non-null   float64
 10  home_rank_change      1704 non-null   float64
 11  home_previous_points  1704 non-null   float64
 12  home_conf             1704 non-null   object
 13  away_rank             1687 non-null   float64
 14  away_total_points     1687 non-null   float64
 15  away_rank_change      1687 non-null   float64
 16  away_previous_points  1687 non-null   float64
 17  away_conf             1687 non-null   object
dtypes: datetime64[ns, UTC](2), float64(10), int64(2), object(4)
memory usage: 258.6+ KB

In [67]:
matches=matches.dropna()
matches.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1607 entries, 0 to 1837
Data columns (total 18 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   home_team             1607 non-null   object
 1   away_team             1607 non-null   object
 2   home_team_goals       1607 non-null   int64
 3   away_team_goals       1607 non-null   int64
 4   home_team_age         1607 non-null   float64
 5   away_team_age         1607 non-null   float64
 6   date                  1607 non-null   datetime64[ns, UTC]
 7   rank_date             1607 non-null   datetime64[ns, UTC]
 8   home_rank             1607 non-null   float64
 9   home_total_points     1607 non-null   float64
 10  home_rank_change      1607 non-null   float64
 11  home_previous_points  1607 non-null   float64
 12  home_conf             1607 non-null   object
 13  away_rank             1607 non-null   float64
 14  away_total_points     1607 non-null   float64
 15  away_rank_change      1607 non-null   float64
 16  away_previous_points  1607 non-null   float64
 17  away_conf             1607 non-null   object
dtypes: datetime64[ns, UTC](2), float64(10), int64(2), object(4)
memory usage: 238.5+ KB

In [68]:
matches["hour"]=matches["date"].dt.hour
matches

/tmp/ipykernel_73008/2423581444.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  matches["hour"]=matches["date"].dt.hour

,home_team,away_team,home_team_goals,away_team_goals,home_team_age,away_team_age,date,rank_date,home_rank,home_total_points,home_rank_change,home_previous_points,home_conf,away_rank,away_total_points,away_rank_change,away_previous_points,away_conf,hour
0,Czechia,Denmark,3,1,29.363636,26.727273,2026-03-31 18:45:00+00:00,2022-02-10 00:00:00+00:00,31.0,1510.42,-1.0,1510.42,UEFA,9.0,1654.54,0.0,1654.54,UEFA,18
1,Hungary,Czechia,1,1,27.272727,27.000000,2023-09-10 16:00:00+00:00,2022-02-10 00:00:00+00:00,41.0,1465.62,2.0,1465.62,UEFA,31.0,1510.42,-1.0,1510.42,UEFA,16
2,Czechia,Saudi Arabia,1,1,26.090909,26.272727,2025-09-08 17:15:00+00:00,2022-02-10 00:00:00+00:00,31.0,1510.42,-1.0,1510.42,UEFA,53.0,1433.95,2.0,1434.71,AFC,17
3,Czechia,Turkiye,1,2,27.090909,25.818182,2024-06-26 19:00:00+00:00,2022-02-10 00:00:00+00:00,31.0,1510.42,-1.0,1510.42,UEFA,39.0,1472.72,2.0,1472.72,UEFA,19
4,Czechia,Albania,2,0,27.363636,26.363636,2024-10-11 18:45:00+00:00,2022-02-10 00:00:00+00:00,31.0,1510.42,-1.0,1510.42,UEFA,65.0,1374.98,-1.0,1374.98,UEFA,18
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1833,Canada,Guatemala,1,0,26.000000,26.181818,2026-01-18 03:30:00+00:00,2022-02-10 00:00:00+00:00,33.0,1497.82,-7.0,1462.32,CONCACAF,123.0,1138.40,1.0,1138.40,CONCACAF,3
1834,Canada,Guatemala,5,6,25.727273,27.090909,2025-06-29 20:00:00+00:00,2022-02-10 00:00:00+00:00,33.0,1497.82,-7.0,1462.32,CONCACAF,123.0,1138.40,1.0,1138.40,CONCACAF,20
1835,Guatemala,Canada,0,0,27.909091,28.727273,2023-07-02 01:30:00+00:00,2022-02-10 00:00:00+00:00,123.0,1138.40,1.0,1138.40,CONCACAF,33.0,1497.82,-7.0,1462.32,CONCACAF,1
1836,Japan,Canada,4,1,26.545455,26.909091,2023-10-13 10:35:00+00:00,2022-02-10 00:00:00+00:00,23.0,1549.82,-3.0,1531.53,AFC,33.0,1497.82,-7.0,1462.32,CONCACAF,10
1837,Venezuela,Canada,3,4,28.000000,27.090909,2024-07-06 01:00:00+00:00,2022-02-10 00:00:00+00:00,58.0,1411.45,-1.0,1409.14,CONMEBOL,33.0,1497.82,-7.0,1462.32,CONCACAF,1

In [69]:
matches["rank_diff"]=matches["home_rank"]-matches["away_rank"]
matches["points_diff"]=matches["home_total_points"]-matches["away_total_points"]
matches["age_diff"]=matches["home_team_age"]-matches["away_team_age"]

/tmp/ipykernel_73008/3877619087.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  matches["rank_diff"]=matches["home_rank"]-matches["away_rank"]
/tmp/ipykernel_73008/3877619087.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  matches["points_diff"]=matches["home_total_points"]-matches["away_total_points"]
/tmp/ipykernel_73008/3877619087.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  matches["age_diff"]=matches["home_team_age"]-matches["away_team_age"]

In [70]:
matches_train=matches[matches["date"].dt.year>2023]
matches_test=matches[matches["date"].dt.year<2023]
x_train=matches_train.drop(columns=["date","home_team_goals","rank_date","away_team_goals","home_rank","away_rank","home_team_age","away_team_age"])
y_train=matches_train[["home_team_goals","away_team_goals"]]

In [71]:
from sklearn.preprocessing import LabelEncoder,StandardScaler
from sklearn.pipeline import Pipeline

team_encoder=LabelEncoder()
conf_encoder=LabelEncoder()

team_encoder.fit(pd.concat([matches["home_team"], matches["away_team"]]))
conf_encoder.fit(pd.concat([matches["home_conf"], matches["away_conf"]]))
x_train["home_team"]=team_encoder.transform(x_train["home_team"])
x_train["away_team"]=team_encoder.transform(x_train["away_team"])
x_train["home_conf"]=conf_encoder.transform(x_train["home_conf"])
x_train["away_conf"]=conf_encoder.transform(x_train["away_conf"])

In [72]:
x_train.info()

<class 'pandas.core.frame.DataFrame'>
Index: 937 entries, 0 to 1837
Data columns (total 14 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   home_team             937 non-null    int64
 1   away_team             937 non-null    int64
 2   home_total_points     937 non-null    float64
 3   home_rank_change      937 non-null    float64
 4   home_previous_points  937 non-null    float64
 5   home_conf             937 non-null    int64
 6   away_total_points     937 non-null    float64
 7   away_rank_change      937 non-null    float64
 8   away_previous_points  937 non-null    float64
 9   away_conf             937 non-null    int64
 10  hour                  937 non-null    int32
 11  rank_diff             937 non-null    float64
 12  points_diff           937 non-null    float64
 13  age_diff              937 non-null    float64
dtypes: float64(9), int32(1), int64(4)
memory usage: 106.1 KB

In [73]:
from sklearn.linear_model import LinearRegression

linear_model=Pipeline([("Scaler",StandardScaler()),("Regresso",LinearRegression())])
linear_model.fit(x_train,y_train)

Pipeline(steps=[('Scaler', StandardScaler()), ('Regresso', LinearRegression())])

In [ ]:
x_test=matches_test.drop(columns=["date","home_team_goals","rank_date","away_team_goals","home_rank","away_rank","home_team_age","away_team_age"])
y_test=matches_test[["home_team_goals","away_team_goals"]]
best_acc=0
best_par=0

for j in np.arange(0, 0.5, 0.05):

    correct=0
    total=len(x_test)

    for i in range(total):

        match=x_test.iloc[i]
        y_match=y_test.iloc[i]

        home_team = team_encoder.transform([match["home_team"]])[0]
        away_team = team_encoder.transform([match["away_team"]])[0]
        home_conf = conf_encoder.transform([match["home_conf"]])[0]
        away_conf = conf_encoder.transform([match["away_conf"]])[0]

        a = [[
            home_team,
            away_team,
            match["home_total_points"],
            match["home_rank_change"],
            match["home_previous_points"],
            home_conf,
            match["away_total_points"],
            match["away_rank_change"],
            match["away_previous_points"],
            away_conf,
            match["hour"],
            match["rank_diff"],
            match["points_diff"],
            match["age_diff"]
        ]]

        
        pred = gboost_model.predict(a)

        
        pred = np.where((pred - np.floor(pred)) >= j,np.ceil(pred),np.floor(pred)).astype(int)

       
        if y_match[0] > y_match[1]:
            true = 0   
        elif y_match[0] < y_match[1]:
            true = 2   
        else:
            true = 1   

        
        if pred[0][0] > pred[0][1]:
            pred_label = 0
        elif pred[0][0] < pred[0][1]:
            pred_label = 2
        else:
            pred_label = 1

        if pred_label == true:
            correct += 1

    acc = correct / total

    if acc > best_acc:
        best_acc = acc
        best_par = j

print("Best threshold:", best_par)
print("Best accuracy:", best_acc)

/tmp/ipykernel_73008/2047386350.py:26: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/2047386350.py:28: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/2047386350.py:26: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/2047386350.py:26: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/2047386350.py:26: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/2047386350.py:26: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/2047386350.py:26: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/2047386350.py:26: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/2047386350.py:26: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/2047386350.py:28: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/2047386350.py:26: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/2047386350.py:28: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/2047386350.py:26: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/2047386350.py:28: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/2047386350.py:26: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/2047386350.py:28: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/2047386350.py:26: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/2047386350.py:26: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/2047386350.py:28: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/2047386350.py:26: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/2047386350.py:26: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/2047386350.py:26: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/2047386350.py:28: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/2047386350.py:26: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/2047386350.py:28: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/2047386350.py:26: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/2047386350.py:28: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/2047386350.py:26: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/2047386350.py:26: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/2047386350.py:26: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/2047386350.py:28: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/2047386350.py:26: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/2047386350.py:26: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/2047386350.py:28: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/2047386350.py:26: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/2047386350.py:28: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/2047386350.py:26: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/2047386350.py:26: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/2047386350.py:26: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/2047386350.py:26: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/2047386350.py:28: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/2047386350.py:26: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/2047386350.py:26: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/2047386350.py:26: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/2047386350.py:28: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/2047386350.py:26: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`

In [77]:
from xgboost import XGBRegressor

print(dir(XGBRegressor()))

['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__setstate__', '__sizeof__', '__sklearn_clone__', '__sklearn_is_fitted__', '__sklearn_tags__', '__str__', '__subclasshook__', '__weakref__', '_build_request_for_signature', '_can_use_inplace_predict', '_configure_fit', '_create_dmatrix', '_doc_link_module', '_doc_link_template', '_doc_link_url_param_generator', '_estimator_type', '_get_default_requests', '_get_doc_link', '_get_iteration_range', '_get_metadata_request', '_get_param_names', '_get_params_html', '_get_type', '_html_repr', '_load_model_attributes', '_more_tags', '_repr_html_', '_repr_html_inner', '_repr_mimebundle_', '_set_evaluation_result', '_update_sklearn_tags_from_dict', '_validate_params', '_wrapper_params', 'apply', 'base_score', 'best_iteration', 'best_score', 'booster', 'callbacks', 'coef_', 'colsample_bylevel', 'colsample_bynode', 'colsample_bytree', 'device', 'early_stopping_rounds', 'enable_categorical', 'eval_metric', 'evals_result', 'feature_importances_', 'feature_names_in_', 'feature_types', 'feature_weights', 'fit', 'gamma', 'get_booster', 'get_metadata_routing', 'get_num_boosting_rounds', 'get_params', 'get_xgb_params', 'grow_policy', 'importance_type', 'interaction_constraints', 'intercept_', 'learning_rate', 'load_model', 'max_bin', 'max_cat_threshold', 'max_cat_to_onehot', 'max_delta_step', 'max_depth', 'max_leaves', 'min_child_weight', 'missing', 'monotone_constraints', 'multi_strategy', 'n_estimators', 'n_features_in_', 'n_jobs', 'num_parallel_tree', 'objective', 'predict', 'random_state', 'reg_alpha', 'reg_lambda', 'sampling_method', 'save_model', 'scale_pos_weight', 'score', 'set_fit_request', 'set_params', 'set_predict_request', 'set_score_request', 'subsample', 'tree_method', 'validate_parameters', 'verbosity']

In [78]:
gboost_model=XGBRegressor(learning_rate=0.05,max_depth=3,n_estimators=300,subsample=0.8,colsample_bytree=0.8)
gboost_model.fit(x_train,y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=0.8, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=0.05, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=3,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=300,
             n_jobs=None, num_parallel_tree=None, ...)

In [ ]:
best_acc=0
best_par=0

for j in np.arange(0, 0.5, 0.05):

    correct=0
    total=len(x_test)

    for i in range(total):

        match=x_test.iloc[i]
        y_match=y_test.iloc[i]

        home_team = team_encoder.transform([match["home_team"]])[0]
        away_team = team_encoder.transform([match["away_team"]])[0]
        home_conf = conf_encoder.transform([match["home_conf"]])[0]
        away_conf = conf_encoder.transform([match["away_conf"]])[0]

        a = [[
            home_team,
            away_team,
            match["home_total_points"],
            match["home_rank_change"],
            match["home_previous_points"],
            home_conf,
            match["away_total_points"],
            match["away_rank_change"],
            match["away_previous_points"],
            away_conf,
            match["hour"],
            match["rank_diff"],
            match["points_diff"],
            match["age_diff"]
        ]]

        
        pred = gboost_model.predict(a)

        
        pred = np.where((pred - np.floor(pred)) >= j,np.ceil(pred),np.floor(pred)).astype(int)

       
        if y_match[0] > y_match[1]:
            true = 0   
        elif y_match[0] < y_match[1]:
            true = 2   
        else:
            true = 1   

        
        if pred[0][0] > pred[0][1]:
            pred_label = 0
        elif pred[0][0] < pred[0][1]:
            pred_label = 2
        else:
            pred_label = 1

        if pred_label == true:
            correct += 1

    acc = correct / total

    if acc > best_acc:
        best_acc = acc
        best_par = j

print("Best threshold:", best_par)
print("Best accuracy:", best_acc)

/tmp/ipykernel_73008/309198985.py:37: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0] > y_match[1]:
/tmp/ipykernel_73008/309198985.py:39: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0] < y_match[1]:
/tmp/ipykernel_73008/309198985.py:37: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0] > y_match[1]:
/tmp/ipykernel_73008/309198985.py:37: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0] > y_match[1]:
/tmp/ipykernel_73008/309198985.py:37: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0] > y_match[1]:
/tmp/ipykernel_73008/309198985.py:37: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0] > y_match[1]:
/tmp/ipykernel_73008/309198985.py:37: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0] > y_match[1]:
/tmp/ipykernel_73008/309198985.py:37: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0] > y_match[1]:
/tmp/ipykernel_73008/309198985.py:37: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0] > y_match[1]:
/tmp/ipykernel_73008/309198985.py:39: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0] < y_match[1]:
/tmp/ipykernel_73008/309198985.py:37: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0] > y_match[1]:
/tmp/ipykernel_73008/309198985.py:39: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0] < y_match[1]:
/tmp/ipykernel_73008/309198985.py:37: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0] > y_match[1]:
/tmp/ipykernel_73008/309198985.py:39: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0] < y_match[1]:
/tmp/ipykernel_73008/309198985.py:37: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0] > y_match[1]:
/tmp/ipykernel_73008/309198985.py:39: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0] < y_match[1]:
/tmp/ipykernel_73008/309198985.py:37: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0] > y_match[1]:
/tmp/ipykernel_73008/309198985.py:37: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0] > y_match[1]:
/tmp/ipykernel_73008/309198985.py:39: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0] < y_match[1]:
/tmp/ipykernel_73008/309198985.py:37: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0] > y_match[1]:
/tmp/ipykernel_73008/309198985.py:37: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0] > y_match[1]:
/tmp/ipykernel_73008/309198985.py:37: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0] > y_match[1]:
/tmp/ipykernel_73008/309198985.py:39: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0] < y_match[1]:
/tmp/ipykernel_73008/309198985.py:37: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0] > y_match[1]:
/tmp/ipykernel_73008/309198985.py:39: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0] < y_match[1]:
/tmp/ipykernel_73008/309198985.py:37: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0] > y_match[1]:
/tmp/ipykernel_73008/309198985.py:39: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0] < y_match[1]:
/tmp/ipykernel_73008/309198985.py:37: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0] > y_match[1]:
/tmp/ipykernel_73008/309198985.py:37: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0] > y_match[1]:
/tmp/ipykernel_73008/309198985.py:37: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0] > y_match[1]:
/tmp/ipykernel_73008/309198985.py:39: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0] < y_match[1]:
/tmp/ipykernel_73008/309198985.py:37: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0] > y_match[1]:
/tmp/ipykernel_73008/309198985.py:37: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0] > y_match[1]:
/tmp/ipykernel_73008/309198985.py:39: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0] < y_match[1]:
/tmp/ipykernel_73008/309198985.py:37: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0] > y_match[1]:
/tmp/ipykernel_73008/309198985.py:39: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0] < y_match[1]:
/tmp/ipykernel_73008/309198985.py:37: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0] > y_match[1]:
/tmp/ipykernel_73008/309198985.py:37: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0] > y_match[1]:
/tmp/ipykernel_73008/309198985.py:37: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0] > y_match[1]:
/tmp/ipykernel_73008/309198985.py:37: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0] > y_match[1]:
/tmp/ipykernel_73008/309198985.py:39: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0] < y_match[1]:
/tmp/ipykernel_73008/309198985.py:37: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0] > y_match[1]:
/tmp/ipykernel_73008/309198985.py:37: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0] > y_match[1]:
/tmp/ipykernel_73008/309198985.py:37: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0] > y_match[1]:
/tmp/ipykernel_73008/309198985.py:39: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0] < y_match[1]:
/tmp/ipykernel_73008/309198985.py:37: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0] > y_match[1]:
/tmp/ipykernel_73008/309198985.py:37: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0] > y_match[1]:
/tmp/ipykernel_73008/309198985.py:39: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0] < y_match[1]:
/tmp/ipykernel_73008/309198985.py:37: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0] > y_match[1]:
/tmp/ipykernel_73008/309198985.py:37: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0] > y_match[1]:
/tmp/ipykernel_73008/309198985.py:39: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0] < y_match[1]:
/tmp/ipykernel_73008/309198985.py:37: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0] > y_match[1]:
/tmp/ipykernel_73008/309198985.py:39: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0] < y_match[1]:
/tmp/ipykernel_73008/309198985.py:37: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0] > y_match[1]:
/tmp/ipykernel_73008/309198985.py:37: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0] > y_match[1]:
/tmp/ipykernel_73008/309198985.py:39: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0] < y_match[1]:
/tmp/ipykernel_73008/309198985.py:37: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0] > y_match[1]:
/tmp/ipykernel_73008/309198985.py:37: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0] > y_match[1]:
/tmp/ipykernel_73008/309198985.py:39: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0] < y_match[1]:
/tmp/ipykernel_73008/309198985.py:37: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0] > y_match[1]:
/tmp/ipykernel_73008/309198985.py:39: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0] < y_match[1]:
/tmp/ipykernel_73008/309198985.py:37: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0] > y_match[1]:
/tmp/ipykernel_73008/309198985.py:39: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0] < y_match[1]:
/tmp/ipykernel_73008/309198985.py:37: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0] > y_match[1]:
/tmp/ipykernel_73008/309198985.py:37: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0] > y_match[1]:
/tmp/ipykernel_73008/309198985.py:37: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0] > y_match[1]:

Accuracy: 0.4882154882154882

/tmp/ipykernel_73008/309198985.py:37: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0] > y_match[1]:
/tmp/ipykernel_73008/309198985.py:39: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0] < y_match[1]:
/tmp/ipykernel_73008/309198985.py:37: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0] > y_match[1]:
/tmp/ipykernel_73008/309198985.py:37: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0] > y_match[1]:
/tmp/ipykernel_73008/309198985.py:37: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0] > y_match[1]:
/tmp/ipykernel_73008/309198985.py:37: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0] > y_match[1]:
/tmp/ipykernel_73008/309198985.py:37: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0] > y_match[1]:
/tmp/ipykernel_73008/309198985.py:39: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0] < y_match[1]:
/tmp/ipykernel_73008/309198985.py:37: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0] > y_match[1]:
/tmp/ipykernel_73008/309198985.py:37: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0] > y_match[1]:
/tmp/ipykernel_73008/309198985.py:37: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0] > y_match[1]:
/tmp/ipykernel_73008/309198985.py:39: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0] < y_match[1]:
/tmp/ipykernel_73008/309198985.py:37: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0] > y_match[1]:
/tmp/ipykernel_73008/309198985.py:37: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0] > y_match[1]:
/tmp/ipykernel_73008/309198985.py:39: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0] < y_match[1]:
/tmp/ipykernel_73008/309198985.py:37: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0] > y_match[1]:
/tmp/ipykernel_73008/309198985.py:37: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0] > y_match[1]:
/tmp/ipykernel_73008/309198985.py:37: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0] > y_match[1]:
/tmp/ipykernel_73008/309198985.py:37: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0] > y_match[1]:
/tmp/ipykernel_73008/309198985.py:37: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0] > y_match[1]:

In [80]:
print(best_par)

0.1

In [81]:
print(len(matches[matches["home_team_goals"]>matches["away_team_goals"]]))
print(len(matches[matches["home_team_goals"]<matches["away_team_goals"]]))
print(len(matches[matches["home_team_goals"]==matches["away_team_goals"]]))

883
393
331

In [86]:
away=0
home=0
equal=0
home_test=0
equal_test=0
away_test=0
best_diff=0
best_par=0
for i in range(len(x_test)):
     
    match=x_test.iloc[i]
    y_match=y_test.iloc[i]

    print("the match is: ",match,y_test.iloc[i])    
    home_team =team_encoder.transform([match["home_team"]])[0]
    away_team=team_encoder.transform([match["away_team"]])[0]
    home_conf=conf_encoder.transform([match["home_conf"]])[0]
    away_conf=conf_encoder.transform([match["away_conf"]])[0]
    if y_match[0]>y_match[1]:
        home_test+=1
    elif y_match[0]<y_match[1]:
        away_test+=1 
    else :
        equal_test+=1


    
    a = [[
        home_team,
        away_team,
        match["home_total_points"],
        match["home_rank_change"],
        match["home_previous_points"],
        home_conf,
        match["away_total_points"],
        match["away_rank_change"],
        match["away_previous_points"],
        away_conf,
        match["hour"],
        match["rank_diff"],
        match["points_diff"],
        match["age_diff"]
    ]]

    
    pred=gboost_model.predict(a)
    pred=np.where((pred - np.floor(pred)) >= 0.1,np.ceil(pred),np.floor(pred)).astype(int)
    print("model prediction:", pred)
    if pred[0][0]>pred[0][1]:
        home+=1
    elif pred[0][0]==pred[0][1]:
        equal+=1    
    else:
        away+=1

the match is:  home_team                Czechia
away_team                  Spain
home_total_points        1510.42
home_rank_change            -1.0
home_previous_points     1510.42
home_conf                   UEFA
away_total_points        1704.75
away_rank_change             0.0
away_previous_points     1704.75
away_conf                   UEFA
hour                          18
rank_diff                   24.0
points_diff              -194.33
age_diff                0.806818
Name: 17, dtype: object home_team_goals    2
away_team_goals    2
Name: 17, dtype: int64
model prediction: [[2 2]]
the match is:  home_team                 Sweden
away_team                Czechia
home_total_points        1588.26
home_rank_change            -1.0
home_previous_points     1588.26
home_conf                   UEFA
away_total_points        1510.42
away_rank_change            -1.0
away_previous_points     1510.42
away_conf                   UEFA
hour                          19
rank_diff                  -14.0
points_diff                77.84
age_diff                2.636364
Name: 18, dtype: object home_team_goals    1
away_team_goals    0
Name: 18, dtype: int64
model prediction: [[2 1]]
the match is:  home_team                   Czechia
away_team               Switzerland
home_total_points           1510.42
home_rank_change               -1.0
home_previous_points        1510.42
home_conf                      UEFA
away_total_points           1642.83
away_rank_change                1.0
away_previous_points        1642.83
away_conf                      UEFA
hour                             18
rank_diff                      17.0
points_diff                 -132.41
age_diff                  -1.545455
Name: 32, dtype: object home_team_goals    2
away_team_goals    1
Name: 32, dtype: int64
model prediction: [[2 2]]
the match is:  home_team                Uruguay
away_team                   Peru
home_total_points        1614.05
home_rank_change            -1.0
home_previous_points     1596.66
home_conf               CONMEBOL
away_total_points        1563.45
away_rank_change             0.0
away_previous_points     1551.15
away_conf               CONMEBOL
hour                          23
rank_diff                   -6.0
points_diff                 50.6
age_diff               -3.727273
Name: 49, dtype: object home_team_goals    1
away_team_goals    0
Name: 49, dtype: int64
model prediction: [[1 2]]
the match is:  home_team                  Ghana
away_team                Uruguay
home_total_points        1381.45
home_rank_change             9.0
home_previous_points     1428.97
home_conf                    CAF
away_total_points        1614.05
away_rank_change            -1.0
away_previous_points     1596.66
away_conf               CONMEBOL
hour                          15
rank_diff                   45.0
points_diff               -232.6
age_diff               -0.545455
Name: 51, dtype: object home_team_goals    2
away_team_goals    0
Name: 51, dtype: int64
model prediction: [[1 2]]
the match is:  home_team                  Chile
away_team                Uruguay
home_total_points        1543.16
home_rank_change             2.0
home_previous_points     1543.42
home_conf               CONMEBOL
away_total_points        1614.05
away_rank_change            -1.0
away_previous_points     1596.66
away_conf               CONMEBOL
hour                          23
rank_diff                   10.0
points_diff               -70.89
age_diff                2.090909
Name: 54, dtype: object home_team_goals    2
away_team_goals    0
Name: 54, dtype: int64
model prediction: [[1 1]]
the match is:  home_team                Uruguay
away_team                 Panama
home_total_points        1614.05
home_rank_change            -1.0
home_previous_points     1596.66
home_conf               CONMEBOL
away_total_points        1375.56
away_rank_change             0.0
away_previous_points     1379.34
away_conf               CONCACAF
hour                          20
rank_diff                  -47.0
points_diff               238.49
age_diff                2.181818
Name: 56, dtype: object home_team_goals    5
away_team_goals    0
Name: 56, dtype: int64
model prediction: [[2 1]]
the match is:  home_team                   Uruguay
away_team               South Korea
home_total_points           1614.05
home_rank_change               -1.0
home_previous_points        1596.66
home_conf                  CONMEBOL
away_total_points           1522.85
away_rank_change               -4.0
away_previous_points        1507.24
away_conf                       AFC
hour                             13
rank_diff                     -13.0
points_diff                    91.2
age_diff                       -1.0
Name: 58, dtype: object home_team_goals    0
away_team_goals    0
Name: 58, dtype: int64
model prediction: [[2 2]]
the match is:  home_team               Portugal
away_team                Uruguay
home_total_points        1660.25
home_rank_change             0.0
home_previous_points     1660.25
home_conf                   UEFA
away_total_points        1614.05
away_rank_change            -1.0
away_previous_points     1596.66
away_conf               CONMEBOL
hour                          19
rank_diff                   -8.0
points_diff                 46.2
age_diff               -0.909091
Name: 59, dtype: object home_team_goals    0
away_team_goals    2
Name: 59, dtype: int64
model prediction: [[3 2]]
the match is:  home_team                Belgium
away_team                Morocco
home_total_points        1828.45
home_rank_change             0.0
home_previous_points     1828.45
home_conf                   UEFA
away_total_points        1547.42
away_rank_change            -4.0
away_previous_points     1529.93
away_conf                    CAF
hour                          13
rank_diff                  -23.0
points_diff               281.03
age_diff                5.722222
Name: 78, dtype: object home_team_goals    0
away_team_goals    2
Name: 78, dtype: int64
model prediction: [[2 1]]
the match is:  home_team                 Canada
away_team                Morocco
home_total_points        1497.82
home_rank_change            -7.0
home_previous_points     1462.32
home_conf               CONCACAF
away_total_points        1547.42
away_rank_change            -4.0
away_previous_points     1529.93
away_conf                    CAF
hour                          15
rank_diff                    9.0
points_diff                -49.6
age_diff                1.181818
Name: 85, dtype: object home_team_goals    1
away_team_goals    2
Name: 85, dtype: int64
model prediction: [[1 3]]
the match is:  home_team                Morocco
away_team                  Spain
home_total_points        1547.42
home_rank_change            -4.0
home_previous_points     1529.93
home_conf                    CAF
away_total_points        1704.75
away_rank_change             0.0
away_previous_points     1704.75
away_conf                   UEFA
hour                          15
rank_diff                   17.0
points_diff              -157.33
age_diff                1.090909
Name: 92, dtype: object home_team_goals    3
away_team_goals    0
Name: 92, dtype: int64

/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:

model prediction: [[2 2]]
the match is:  home_team                Morocco
away_team                Croatia
home_total_points        1547.42
home_rank_change            -4.0
home_previous_points     1529.93
home_conf                    CAF
away_total_points        1620.74
away_rank_change             0.0
away_previous_points     1620.74
away_conf                   UEFA
hour                          10
rank_diff                    9.0
points_diff               -73.32
age_diff               -1.818182
Name: 102, dtype: object home_team_goals    0
away_team_goals    0
Name: 102, dtype: int64
model prediction: [[2 2]]
the match is:  home_team                    Brazil
away_team               Switzerland
home_total_points           1823.42
home_rank_change                0.0
home_previous_points        1826.35
home_conf                  CONMEBOL
away_total_points           1642.83
away_rank_change                1.0
away_previous_points        1642.83
away_conf                      UEFA
hour                             16
rank_diff                     -12.0
points_diff                  180.59
age_diff                   0.727273
Name: 142, dtype: object home_team_goals    1
away_team_goals    0
Name: 142, dtype: int64
model prediction: [[3 2]]
the match is:  home_team               Switzerland
away_team                  Cameroon
home_total_points           1642.83
home_rank_change                1.0
home_previous_points        1642.83
home_conf                      UEFA
away_total_points           1480.82
away_rank_change              -12.0
away_previous_points        1437.35
away_conf                       CAF
hour                             10
rank_diff                     -24.0
points_diff                  162.01
age_diff                   0.818182
Name: 144, dtype: object home_team_goals    1
away_team_goals    0
Name: 144, dtype: int64
model prediction: [[3 1]]
the match is:  home_team                    Serbia
away_team               Switzerland
home_total_points           1547.38
home_rank_change                2.0
home_previous_points        1547.38
home_conf                      UEFA
away_total_points           1642.83
away_rank_change                1.0
away_previous_points        1642.83
away_conf                      UEFA
hour                             19
rank_diff                      11.0
points_diff                  -95.45
age_diff                  -2.555556
Name: 151, dtype: object home_team_goals    2
away_team_goals    3
Name: 151, dtype: int64
model prediction: [[2 2]]
the match is:  home_team               Belgium
away_team                 Egypt
home_total_points       1828.45
home_rank_change            0.0
home_previous_points    1828.45
home_conf                  UEFA
away_total_points       1497.05
away_rank_change          -11.0
away_previous_points    1451.77
away_conf                   CAF
hour                         15
rank_diff                 -33.0
points_diff               331.4
age_diff                   -1.0
Name: 173, dtype: object home_team_goals    1
away_team_goals    2
Name: 173, dtype: int64
model prediction: [[1 1]]
the match is:  home_team                  Wales
away_team                Belgium
home_total_points        1578.01
home_rank_change             1.0
home_previous_points     1578.01
home_conf                   UEFA
away_total_points        1828.45
away_rank_change             0.0
away_previous_points     1828.45
away_conf                   UEFA
hour                          18
rank_diff                   19.0
points_diff              -250.44
age_diff               -1.636364
Name: 176, dtype: object home_team_goals    1
away_team_goals    1
Name: 176, dtype: int64
model prediction: [[2 3]]
the match is:  home_team                Belgium
away_team                  Wales
home_total_points        1828.45
home_rank_change             0.0
home_previous_points     1828.45
home_conf                   UEFA
away_total_points        1578.01
away_rank_change             1.0
away_previous_points     1578.01
away_conf                   UEFA
hour                          18
rank_diff                  -19.0
points_diff               250.44
age_diff                4.454545
Name: 177, dtype: object home_team_goals    2
away_team_goals    1
Name: 177, dtype: int64
model prediction: [[4 1]]
the match is:  home_team                    Belgium
away_team               Burkina Faso
home_total_points            1828.45
home_rank_change                 0.0
home_previous_points         1828.45
home_conf                       UEFA
away_total_points            1418.58
away_rank_change                -4.0
away_previous_points         1397.64
away_conf                        CAF
hour                              18
rank_diff                      -55.0
points_diff                   409.87
age_diff                   -0.363636
Name: 178, dtype: object home_team_goals    3
away_team_goals    0
Name: 178, dtype: int64
model prediction: [[2 1]]
the match is:  home_team                Croatia
away_team                Belgium
home_total_points        1620.74
home_rank_change             0.0
home_previous_points     1620.74
home_conf                   UEFA
away_total_points        1828.45
away_rank_change             0.0
away_previous_points     1828.45
away_conf                   UEFA
hour                          15
rank_diff                   14.0
points_diff              -207.71
age_diff               -1.818182
Name: 181, dtype: object home_team_goals    0
away_team_goals    0
Name: 181, dtype: int64
model prediction: [[2 2]]
the match is:  home_team                Belgium
away_team                 Poland
home_total_points        1828.45
home_rank_change             0.0
home_previous_points     1828.45
home_conf                   UEFA
away_total_points        1530.62
away_rank_change             1.0
away_previous_points     1530.62
away_conf                   UEFA
hour                          18
rank_diff                  -27.0
points_diff               297.83
age_diff                3.636364
Name: 182, dtype: object home_team_goals    6
away_team_goals    1
Name: 182, dtype: int64
model prediction: [[2 1]]
the match is:  home_team                 Poland
away_team                Belgium
home_total_points        1530.62
home_rank_change             1.0
home_previous_points     1530.62
home_conf                   UEFA
away_total_points        1828.45
away_rank_change             0.0
away_previous_points     1828.45
away_conf                   UEFA
hour                          18
rank_diff                   27.0
points_diff              -297.83
age_diff               -3.909091
Name: 183, dtype: object home_team_goals    0
away_team_goals    1
Name: 183, dtype: int64
model prediction: [[2 2]]
the match is:  home_team                England
away_team                Senegal
home_total_points        1755.52
home_rank_change             1.0
home_previous_points     1755.52
home_conf                   UEFA
away_total_points        1587.78
away_rank_change            -2.0
away_previous_points     1561.68
away_conf                    CAF
hour                          19
rank_diff                  -13.0
points_diff               167.74
age_diff               -0.181818
Name: 196, dtype: object home_team_goals    0
away_team_goals    3
Name: 196, dtype: int64
model prediction: [[2 1]]
the match is:  home_team                Senegal
away_team               Eswatini
home_total_points        1587.78
home_rank_change            -2.0
home_previous_points     1561.68
home_conf                    CAF
away_total_points        1054.14
away_rank_change             1.0
away_previous_points     1054.14
away_conf                    CAF
hour                          12
rank_diff                 -129.0
points_diff               533.64
age_diff                    -6.0
Name: 203, dtype: object home_team_goals    10
away_team_goals     9
Name: 203, dtype: int64

/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:

model prediction: [[4 1]]
the match is:  home_team                Senegal
away_team                  Benin
home_total_points        1587.78
home_rank_change            -2.0
home_previous_points     1561.68
home_conf                    CAF
away_total_points        1282.53
away_rank_change             0.0
away_previous_points     1282.53
away_conf                    CAF
hour                          19
rank_diff                  -65.0
points_diff               305.25
age_diff               -0.272727
Name: 210, dtype: object home_team_goals    3
away_team_goals    1
Name: 210, dtype: int64
model prediction: [[2 1]]
the match is:  home_team                 Rwanda
away_team                Senegal
home_total_points        1097.16
home_rank_change             1.0
home_previous_points     1095.34
home_conf                    CAF
away_total_points        1587.78
away_rank_change            -2.0
away_previous_points     1561.68
away_conf                    CAF
hour                          19
rank_diff                  118.0
points_diff              -490.62
age_diff               -1.090909
Name: 216, dtype: object home_team_goals    1
away_team_goals    0
Name: 216, dtype: int64
model prediction: [[1 1]]
the match is:  home_team                 Zambia
away_team                Senegal
home_total_points        1264.64
home_rank_change             0.0
home_previous_points     1264.64
home_conf                    CAF
away_total_points        1587.78
away_rank_change            -2.0
away_previous_points     1561.68
away_conf                    CAF
hour                          17
rank_diff                   70.0
points_diff              -323.14
age_diff                2.454545
Name: 217, dtype: object home_team_goals    3
away_team_goals    4
Name: 217, dtype: int64
model prediction: [[1 2]]
the match is:  home_team                Bolivia
away_team                Senegal
home_total_points        1308.12
home_rank_change            -1.0
home_previous_points     1324.21
home_conf               CONMEBOL
away_total_points        1587.78
away_rank_change            -2.0
away_previous_points     1561.68
away_conf                    CAF
hour                          17
rank_diff                   58.0
points_diff              -279.66
age_diff                0.909091
Name: 224, dtype: object home_team_goals    2
away_team_goals    0
Name: 224, dtype: int64
model prediction: [[2 2]]
the match is:  home_team               Mozambique
away_team                  Senegal
home_total_points           1151.0
home_rank_change              -1.0
home_previous_points        1151.0
home_conf                      CAF
away_total_points          1587.78
away_rank_change              -2.0
away_previous_points       1561.68
away_conf                      CAF
hour                            13
rank_diff                     99.0
points_diff                -436.78
age_diff                  3.090909
Name: 238, dtype: object home_team_goals    4
away_team_goals    2
Name: 238, dtype: int64
model prediction: [[1 1]]
the match is:  home_team                Algeria
away_team                Senegal
home_total_points        1460.93
home_rank_change            14.0
home_previous_points     1516.51
home_conf                    CAF
away_total_points        1587.78
away_rank_change            -2.0
away_previous_points     1561.68
away_conf                    CAF
hour                          17
rank_diff                   25.0
points_diff              -126.85
age_diff                4.454545
Name: 248, dtype: object home_team_goals    2
away_team_goals    2
Name: 248, dtype: int64
model prediction: [[1 1]]
the match is:  home_team                   Japan
away_team               Hong Kong
home_total_points         1549.82
home_rank_change             -3.0
home_previous_points      1531.53
home_conf                     AFC
away_total_points         1053.39
away_rank_change              1.0
away_previous_points      1053.39
away_conf                     AFC
hour                           10
rank_diff                  -125.0
points_diff                496.43
age_diff                -2.454545
Name: 252, dtype: object home_team_goals    6
away_team_goals    0
Name: 252, dtype: int64
model prediction: [[5 1]]
the match is:  home_team                    Japan
away_team               Costa Rica
home_total_points          1549.82
home_rank_change              -3.0
home_previous_points       1531.53
home_conf                      AFC
away_total_points          1464.06
away_rank_change              -7.0
away_previous_points       1437.43
away_conf                 CONCACAF
hour                            10
rank_diff                    -19.0
points_diff                  85.76
age_diff                      -2.0
Name: 253, dtype: object home_team_goals    0
away_team_goals    1
Name: 253, dtype: int64
model prediction: [[3 1]]
the match is:  home_team                  Japan
away_team                  Ghana
home_total_points        1549.82
home_rank_change            -3.0
home_previous_points     1531.53
home_conf                    AFC
away_total_points        1381.45
away_rank_change             9.0
away_previous_points     1428.97
away_conf                    CAF
hour                           9
rank_diff                  -38.0
points_diff               168.37
age_diff                0.727273
Name: 265, dtype: object home_team_goals    4
away_team_goals    1
Name: 265, dtype: int64
model prediction: [[3 1]]
the match is:  home_team                  Japan
away_team                Tunisia
home_total_points        1549.82
home_rank_change            -3.0
home_previous_points     1531.53
home_conf                    AFC
away_total_points        1489.92
away_rank_change             6.0
away_previous_points     1512.72
away_conf                    CAF
hour                           9
rank_diff                  -13.0
points_diff                 59.9
age_diff                1.818182
Name: 274, dtype: object home_team_goals    0
away_team_goals    3
Name: 274, dtype: int64
model prediction: [[2 2]]
the match is:  home_team                  Japan
away_team                Vietnam
home_total_points        1549.82
home_rank_change            -3.0
home_previous_points     1531.53
home_conf                    AFC
away_total_points        1218.55
away_rank_change             0.0
away_previous_points     1212.54
away_conf                    AFC
hour                          10
rank_diff                  -75.0
points_diff               331.27
age_diff                2.363636
Name: 278, dtype: object home_team_goals    1
away_team_goals    1
Name: 278, dtype: int64
model prediction: [[3 2]]
the match is:  home_team                  Japan
away_team                  Spain
home_total_points        1549.82
home_rank_change            -3.0
home_previous_points     1531.53
home_conf                    AFC
away_total_points        1704.75
away_rank_change             0.0
away_previous_points     1704.75
away_conf                   UEFA
hour                          19
rank_diff                   16.0
points_diff              -154.93
age_diff                3.363636
Name: 281, dtype: object home_team_goals    2
away_team_goals    1
Name: 281, dtype: int64
model prediction: [[2 2]]
the match is:  home_team                  Japan
away_team                Croatia
home_total_points        1549.82
home_rank_change            -3.0
home_previous_points     1531.53
home_conf                    AFC
away_total_points        1620.74
away_rank_change             0.0
away_previous_points     1620.74
away_conf                   UEFA
hour                          15
rank_diff                    8.0
points_diff               -70.92
age_diff               -0.545455
Name: 289, dtype: object home_team_goals    1
away_team_goals    3
Name: 289, dtype: int64
model prediction: [[2 2]]
the match is:  home_team                    Iran
away_team               Nicaragua
home_total_points         1572.89
home_rank_change              0.0
home_previous_points      1557.58
home_conf                     AFC
away_total_points         1062.21
away_rank_change              1.0
away_previous_points      1062.21
away_conf                CONCACAF
hour                           16
rank_diff                  -123.0
points_diff                510.68
age_diff                 1.909091
Name: 295, dtype: object home_team_goals    1
away_team_goals    0
Name: 295, dtype: int64
model prediction: [[4 1]]
the match is:  home_team                England
away_team                   Iran
home_total_points        1755.52
home_rank_change             1.0
home_previous_points     1755.52
home_conf                   UEFA
away_total_points        1572.89
away_rank_change             0.0
away_previous_points     1557.58
away_conf                    AFC
hour                          13
rank_diff                  -16.0
points_diff               182.63
age_diff               -2.818182
Name: 297, dtype: object home_team_goals    2
away_team_goals    6
Name: 297, dtype: int64
model prediction: [[2 1]]
the match is:  home_team                England
away_team                   Iran
home_total_points        1755.52
home_rank_change             1.0
home_previous_points     1755.52
home_conf                   UEFA
away_total_points        1572.89
away_rank_change             0.0
away_previous_points     1557.58
away_conf                    AFC
hour                          13
rank_diff                  -16.0
points_diff               182.63
age_diff               -2.818182
Name: 298, dtype: object home_team_goals    2
away_team_goals    6
Name: 298, dtype: int64
model prediction: [[2 1]]
the match is:  home_team               South Korea
away_team                      Iran
home_total_points           1522.85
home_rank_change               -4.0
home_previous_points        1507.24
home_conf                       AFC
away_total_points           1572.89
away_rank_change                0.0
away_previous_points        1557.58
away_conf                       AFC
hour                             11
rank_diff                       8.0
points_diff                  -50.04
age_diff                   1.090909
Name: 306, dtype: object home_team_goals    0
away_team_goals    2
Name: 306, dtype: int64
model prediction: [[2 2]]
the match is:  home_team                   Iran
away_team                Uruguay
home_total_points        1572.89
home_rank_change             0.0
home_previous_points     1557.58
home_conf                    AFC
away_total_points        1614.05
away_rank_change            -1.0
away_previous_points     1596.66
away_conf               CONMEBOL
hour                          16
rank_diff                    5.0
points_diff               -41.16
age_diff                1.727273
Name: 307, dtype: object home_team_goals    1
away_team_goals    0
Name: 307, dtype: int64
model prediction: [[2 2]]
the match is:  home_team                  Wales
away_team                   Iran
home_total_points        1578.01
home_rank_change             1.0
home_previous_points     1578.01
home_conf                   UEFA
away_total_points        1572.89
away_rank_change             0.0
away_previous_points     1557.58
away_conf                    AFC
hour                          10
rank_diff                   -1.0
points_diff                 5.12
age_diff               -1.181818
Name: 308, dtype: object home_team_goals    2
away_team_goals    0
Name: 308, dtype: int64
model prediction: [[2 2]]
the match is:  home_team                  Wales
away_team                   Iran
home_total_points        1578.01
home_rank_change             1.0
home_previous_points     1578.01
home_conf                   UEFA
away_total_points        1572.89
away_rank_change             0.0
away_previous_points     1557.58
away_conf                    AFC
hour                          10
rank_diff                   -1.0
points_diff                 5.12
age_diff               -1.181818
Name: 309, dtype: object home_team_goals    2
away_team_goals    0
Name: 309, dtype: int64
model prediction: [[2 2]]
the match is:  home_team                   Iran
away_team                Lebanon
home_total_points        1572.89
home_rank_change             0.0
home_previous_points     1557.58
home_conf                    AFC
away_total_points        1228.97
away_rank_change             0.0
away_previous_points      1233.0
away_conf                    AFC
hour                          11
rank_diff                  -74.0
points_diff               343.92
age_diff               -2.818182
Name: 316, dtype: object home_team_goals    2
away_team_goals    0
Name: 316, dtype: int64
model prediction: [[3 1]]
the match is:  home_team                   Iran
away_team                Senegal
home_total_points        1572.89
home_rank_change             0.0
home_previous_points     1557.58
home_conf                    AFC
away_total_points        1587.78
away_rank_change            -2.0
away_previous_points     1561.68
away_conf                    CAF
hour                          14
rank_diff                    3.0
points_diff               -14.89
age_diff                1.454545
Name: 324, dtype: object home_team_goals    1
away_team_goals    1
Name: 324, dtype: int64

/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:

model prediction: [[2 2]]
the match is:  home_team                   Iran
away_team                Algeria
home_total_points        1572.89
home_rank_change             0.0
home_previous_points     1557.58
home_conf                    AFC
away_total_points        1460.93
away_rank_change            14.0
away_previous_points     1516.51
away_conf                    CAF
hour                          18
rank_diff                  -22.0
points_diff               111.96
age_diff                2.636364
Name: 338, dtype: object home_team_goals    1
away_team_goals    2
Name: 338, dtype: int64
model prediction: [[3 2]]
the match is:  home_team                  Egypt
away_team                Liberia
home_total_points        1497.05
home_rank_change           -11.0
home_previous_points     1451.77
home_conf                    CAF
away_total_points        1058.28
away_rank_change             1.0
away_previous_points     1058.28
away_conf                    CAF
hour                          18
rank_diff                 -111.0
points_diff               438.77
age_diff                2.181818
Name: 347, dtype: object home_team_goals    3
away_team_goals    0
Name: 347, dtype: int64
model prediction: [[3 1]]
the match is:  home_team                 Egypt
away_team                 Niger
home_total_points       1497.05
home_rank_change          -11.0
home_previous_points    1451.77
home_conf                   CAF
away_total_points       1158.39
away_rank_change            1.0
away_previous_points    1158.39
away_conf                   CAF
hour                         18
rank_diff                 -80.0
points_diff              338.66
age_diff                    2.0
Name: 351, dtype: object home_team_goals    3
away_team_goals    0
Name: 351, dtype: int64
model prediction: [[2 1]]
the match is:  home_team               Ethiopia
away_team                  Egypt
home_total_points        1081.24
home_rank_change             1.0
home_previous_points     1087.89
home_conf                    CAF
away_total_points        1497.05
away_rank_change           -11.0
away_previous_points     1451.77
away_conf                    CAF
hour                          16
rank_diff                  104.0
points_diff              -415.81
age_diff               -2.818182
Name: 355, dtype: object home_team_goals    2
away_team_goals    0
Name: 355, dtype: int64
model prediction: [[1 2]]
the match is:  home_team                  Egypt
away_team                 Guinea
home_total_points        1497.05
home_rank_change           -11.0
home_previous_points     1451.77
home_conf                    CAF
away_total_points        1292.58
away_rank_change             0.0
away_previous_points     1298.32
away_conf                    CAF
hour                          19
rank_diff                  -47.0
points_diff               204.47
age_diff                3.454545
Name: 357, dtype: object home_team_goals    1
away_team_goals    0
Name: 357, dtype: int64
model prediction: [[3 1]]
the match is:  home_team               South Korea
away_team                     Egypt
home_total_points           1522.85
home_rank_change               -4.0
home_previous_points        1507.24
home_conf                       AFC
away_total_points           1497.05
away_rank_change              -11.0
away_previous_points        1451.77
away_conf                       CAF
hour                             11
rank_diff                      -5.0
points_diff                    25.8
age_diff                   1.363636
Name: 361, dtype: object home_team_goals    4
away_team_goals    1
Name: 361, dtype: int64
model prediction: [[1 2]]
the match is:  home_team                  Egypt
away_team                Senegal
home_total_points        1497.05
home_rank_change           -11.0
home_previous_points     1451.77
home_conf                    CAF
away_total_points        1587.78
away_rank_change            -2.0
away_previous_points     1561.68
away_conf                    CAF
hour                          19
rank_diff                   16.0
points_diff               -90.73
age_diff               -1.454545
Name: 385, dtype: object home_team_goals    1
away_team_goals    0
Name: 385, dtype: int64
model prediction: [[2 2]]
the match is:  home_team                Senegal
away_team                  Egypt
home_total_points        1587.78
home_rank_change            -2.0
home_previous_points     1561.68
home_conf                    CAF
away_total_points        1497.05
away_rank_change           -11.0
away_previous_points     1451.77
away_conf                    CAF
hour                          17
rank_diff                  -16.0
points_diff                90.73
age_diff                0.545455
Name: 386, dtype: object home_team_goals    3
away_team_goals    1
Name: 386, dtype: int64
model prediction: [[2 1]]
the match is:  home_team                Austria
away_team                Denmark
home_total_points        1511.56
home_rank_change            -1.0
home_previous_points     1511.56
home_conf                   UEFA
away_total_points        1654.54
away_rank_change             0.0
away_previous_points     1654.54
away_conf                   UEFA
hour                          20
rank_diff                   21.0
points_diff              -142.98
age_diff               -2.272727
Name: 397, dtype: object home_team_goals    1
away_team_goals    2
Name: 397, dtype: int64
model prediction: [[2 1]]
the match is:  home_team                Denmark
away_team                Austria
home_total_points        1654.54
home_rank_change             0.0
home_previous_points     1654.54
home_conf                   UEFA
away_total_points        1511.56
away_rank_change            -1.0
away_previous_points     1511.56
away_conf                   UEFA
hour                          18
rank_diff                  -21.0
points_diff               142.98
age_diff               -0.181818
Name: 398, dtype: object home_team_goals    0
away_team_goals    2
Name: 398, dtype: int64
model prediction: [[2 1]]
the match is:  home_team                Austria
away_team                  Italy
home_total_points        1511.56
home_rank_change            -1.0
home_previous_points     1511.56
home_conf                   UEFA
away_total_points        1740.77
away_rank_change             0.0
away_previous_points     1740.77
away_conf                   UEFA
hour                          19
rank_diff                   24.0
points_diff              -229.21
age_diff               -1.545455
Name: 400, dtype: object home_team_goals    2
away_team_goals    0
Name: 400, dtype: int64
model prediction: [[2 1]]
the match is:  home_team                Andorra
away_team                Austria
home_total_points        1030.28
home_rank_change             0.0
home_previous_points     1030.28
home_conf                   UEFA
away_total_points        1511.56
away_rank_change            -1.0
away_previous_points     1511.56
away_conf                   UEFA
hour                          17
rank_diff                  125.0
points_diff              -481.28
age_diff               -0.272727
Name: 410, dtype: object home_team_goals    1
away_team_goals    0
Name: 410, dtype: int64
model prediction: [[2 1]]
the match is:  home_team                  Wales
away_team                Austria
home_total_points        1578.01
home_rank_change             1.0
home_previous_points     1578.01
home_conf                   UEFA
away_total_points        1511.56
away_rank_change            -1.0
away_previous_points     1511.56
away_conf                   UEFA
hour                          19
rank_diff                  -10.0
points_diff                66.45
age_diff               -0.181818
Name: 411, dtype: object home_team_goals    1
away_team_goals    2
Name: 411, dtype: int64
model prediction: [[2 2]]
the match is:  home_team                Croatia
away_team                Austria
home_total_points        1620.74
home_rank_change             0.0
home_previous_points     1620.74
home_conf                   UEFA
away_total_points        1511.56
away_rank_change            -1.0
away_previous_points     1511.56
away_conf                   UEFA
hour                          18
rank_diff                  -15.0
points_diff               109.18
age_diff               -1.727273
Name: 414, dtype: object home_team_goals    3
away_team_goals    0
Name: 414, dtype: int64
model prediction: [[2 1]]
the match is:  home_team                Austria
away_team                Croatia
home_total_points        1511.56
home_rank_change            -1.0
home_previous_points     1511.56
home_conf                   UEFA
away_total_points        1620.74
away_rank_change             0.0
away_previous_points     1620.74
away_conf                   UEFA
hour                          18
rank_diff                   15.0
points_diff              -109.18
age_diff               -1.090909
Name: 415, dtype: object home_team_goals    1
away_team_goals    3
Name: 415, dtype: int64
model prediction: [[2 2]]
the match is:  home_team               Costa Rica
away_team                  Germany
home_total_points          1464.06
home_rank_change              -7.0
home_previous_points       1437.43
home_conf                 CONCACAF
away_total_points          1648.33
away_rank_change              -1.0
away_previous_points       1648.33
away_conf                     UEFA
hour                            19
rank_diff                     31.0
points_diff                -184.27
age_diff                  2.727273
Name: 425, dtype: object home_team_goals    2
away_team_goals    4
Name: 425, dtype: int64
model prediction: [[2 2]]
the match is:  home_team                Hungary
away_team                Germany
home_total_points        1465.62
home_rank_change             2.0
home_previous_points     1465.62
home_conf                   UEFA
away_total_points        1648.33
away_rank_change            -1.0
away_previous_points     1648.33
away_conf                   UEFA
hour                          18
rank_diff                   30.0
points_diff              -182.71
age_diff                1.727273
Name: 431, dtype: object home_team_goals    1
away_team_goals    1
Name: 431, dtype: int64

/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:

model prediction: [[2 2]]
the match is:  home_team                Germany
away_team                Hungary
home_total_points        1648.33
home_rank_change            -1.0
home_previous_points     1648.33
home_conf                   UEFA
away_total_points        1465.62
away_rank_change             2.0
away_previous_points     1465.62
away_conf                   UEFA
hour                          18
rank_diff                  -30.0
points_diff               182.71
age_diff                1.090909
Name: 432, dtype: object home_team_goals    0
away_team_goals    1
Name: 432, dtype: int64
model prediction: [[3 1]]
the match is:  home_team                Germany
away_team                England
home_total_points        1648.33
home_rank_change            -1.0
home_previous_points     1648.33
home_conf                   UEFA
away_total_points        1755.52
away_rank_change             1.0
away_previous_points     1755.52
away_conf                   UEFA
hour                          18
rank_diff                    6.0
points_diff              -107.19
age_diff                0.181818
Name: 434, dtype: object home_team_goals    1
away_team_goals    1
Name: 434, dtype: int64
model prediction: [[2 2]]
the match is:  home_team                England
away_team                Germany
home_total_points        1755.52
home_rank_change             1.0
home_previous_points     1755.52
home_conf                   UEFA
away_total_points        1648.33
away_rank_change            -1.0
away_previous_points     1648.33
away_conf                   UEFA
hour                          18
rank_diff                   -6.0
points_diff               107.19
age_diff               -0.090909
Name: 435, dtype: object home_team_goals    3
away_team_goals    3
Name: 435, dtype: int64
model prediction: [[2 2]]
the match is:  home_team               Netherlands
away_team                   Germany
home_total_points           1653.73
home_rank_change                0.0
home_previous_points        1653.73
home_conf                      UEFA
away_total_points           1648.33
away_rank_change               -1.0
away_previous_points        1648.33
away_conf                      UEFA
hour                             18
rank_diff                      -1.0
points_diff                     5.4
age_diff                  -0.181818
Name: 440, dtype: object home_team_goals    1
away_team_goals    1
Name: 440, dtype: int64
model prediction: [[2 2]]
the match is:  home_team                  Italy
away_team                Germany
home_total_points        1740.77
home_rank_change             0.0
home_previous_points     1740.77
home_conf                   UEFA
away_total_points        1648.33
away_rank_change            -1.0
away_previous_points     1648.33
away_conf                   UEFA
hour                          18
rank_diff                   -5.0
points_diff                92.44
age_diff               -1.636364
Name: 443, dtype: object home_team_goals    1
away_team_goals    1
Name: 443, dtype: int64
model prediction: [[3 2]]
the match is:  home_team               Germany
away_team                 Italy
home_total_points       1648.33
home_rank_change           -1.0
home_previous_points    1648.33
home_conf                  UEFA
away_total_points       1740.77
away_rank_change            0.0
away_previous_points    1740.77
away_conf                  UEFA
hour                         18
rank_diff                   5.0
points_diff              -92.44
age_diff                    4.0
Name: 444, dtype: object home_team_goals    5
away_team_goals    2
Name: 444, dtype: int64
model prediction: [[3 2]]
the match is:  home_team                   Oman
away_team                Germany
home_total_points         1301.0
home_rank_change             0.0
home_previous_points     1306.01
home_conf                    AFC
away_total_points        1648.33
away_rank_change            -1.0
away_previous_points     1648.33
away_conf                   UEFA
hour                          17
rank_diff                   68.0
points_diff              -347.33
age_diff               -0.272727
Name: 453, dtype: object home_team_goals    0
away_team_goals    1
Name: 453, dtype: int64
model prediction: [[2 2]]
the match is:  home_team                  Spain
away_team                Germany
home_total_points        1704.75
home_rank_change             0.0
home_previous_points     1704.75
home_conf                   UEFA
away_total_points        1648.33
away_rank_change            -1.0
away_previous_points     1648.33
away_conf                   UEFA
hour                          19
rank_diff                   -4.0
points_diff                56.42
age_diff               -1.909091
Name: 455, dtype: object home_team_goals    1
away_team_goals    1
Name: 455, dtype: int64
model prediction: [[3 2]]
the match is:  home_team                Germany
away_team                  Japan
home_total_points        1648.33
home_rank_change            -1.0
home_previous_points     1648.33
home_conf                   UEFA
away_total_points        1549.82
away_rank_change            -3.0
away_previous_points     1531.53
away_conf                    AFC
hour                          13
rank_diff                  -12.0
points_diff                98.51
age_diff               -1.272727
Name: 458, dtype: object home_team_goals    1
away_team_goals    2
Name: 458, dtype: int64
model prediction: [[2 1]]
the match is:  home_team                Germany
away_team                 Israel
home_total_points        1648.33
home_rank_change            -1.0
home_previous_points     1648.33
home_conf                   UEFA
away_total_points         1306.7
away_rank_change            -1.0
away_previous_points      1306.7
away_conf                   UEFA
hour                          19
rank_diff                  -66.0
points_diff               341.63
age_diff               -1.727273
Name: 464, dtype: object home_team_goals    2
away_team_goals    0
Name: 464, dtype: int64
model prediction: [[3 1]]
the match is:  home_team                Turkiye
away_team                  Italy
home_total_points        1472.72
home_rank_change             2.0
home_previous_points     1472.72
home_conf                   UEFA
away_total_points        1740.77
away_rank_change             0.0
away_previous_points     1740.77
away_conf                   UEFA
hour                          18
rank_diff                   33.0
points_diff              -268.05
age_diff               -2.636364
Name: 512, dtype: object home_team_goals    2
away_team_goals    3
Name: 512, dtype: int64
model prediction: [[2 2]]
the match is:  home_team               Luxembourg
away_team                  Turkiye
home_total_points          1236.45
home_rank_change               0.0
home_previous_points       1236.45
home_conf                     UEFA
away_total_points          1472.72
away_rank_change               2.0
away_previous_points       1472.72
away_conf                     UEFA
hour                            18
rank_diff                     54.0
points_diff                -236.27
age_diff                  1.090909
Name: 517, dtype: object home_team_goals    0
away_team_goals    2
Name: 517, dtype: int64
model prediction: [[2 2]]
the match is:  home_team                  Turkiye
away_team               Luxembourg
home_total_points          1472.72
home_rank_change               2.0
home_previous_points       1472.72
home_conf                     UEFA
away_total_points          1236.45
away_rank_change               0.0
away_previous_points       1236.45
away_conf                     UEFA
hour                            18
rank_diff                    -54.0
points_diff                 236.27
age_diff                 -2.272727
Name: 518, dtype: object home_team_goals    3
away_team_goals    3
Name: 518, dtype: int64
model prediction: [[3 1]]
the match is:  home_team               Portugal
away_team                Turkiye
home_total_points        1660.25
home_rank_change             0.0
home_previous_points     1660.25
home_conf                   UEFA
away_total_points        1472.72
away_rank_change             2.0
away_previous_points     1472.72
away_conf                   UEFA
hour                          19
rank_diff                  -31.0
points_diff               187.53
age_diff                     4.0
Name: 520, dtype: object home_team_goals    3
away_team_goals    1
Name: 520, dtype: int64
model prediction: [[3 1]]
the match is:  home_team               Lithuania
away_team                 Turkiye
home_total_points         1091.77
home_rank_change              1.0
home_previous_points      1091.77
home_conf                    UEFA
away_total_points         1472.72
away_rank_change              2.0
away_previous_points      1472.72
away_conf                    UEFA
hour                           18
rank_diff                    98.0
points_diff               -380.95
age_diff                 3.727273
Name: 521, dtype: object home_team_goals    0
away_team_goals    6
Name: 521, dtype: int64
model prediction: [[2 2]]
the match is:  home_team                 Turkiye
away_team               Lithuania
home_total_points         1472.72
home_rank_change              2.0
home_previous_points      1472.72
home_conf                    UEFA
away_total_points         1091.77
away_rank_change              1.0
away_previous_points      1091.77
away_conf                    UEFA
hour                           18
rank_diff                   -98.0
points_diff                380.95
age_diff                -1.181818
Name: 522, dtype: object home_team_goals    2
away_team_goals    0
Name: 522, dtype: int64
model prediction: [[3 1]]
the match is:  home_team                   Peru
away_team               Paraguay
home_total_points        1563.45
home_rank_change             0.0
home_previous_points     1551.15
home_conf               CONMEBOL
away_total_points        1440.53
away_rank_change             7.0
away_previous_points     1454.52
away_conf               CONMEBOL
hour                          23
rank_diff                  -28.0
points_diff               122.92
age_diff                2.545455
Name: 552, dtype: object home_team_goals    2
away_team_goals    0
Name: 552, dtype: int64
model prediction: [[1 1]]
the match is:  home_team                   Peru
away_team               Paraguay
home_total_points        1563.45
home_rank_change             0.0
home_previous_points     1551.15
home_conf               CONMEBOL
away_total_points        1440.53
away_rank_change             7.0
away_previous_points     1454.52
away_conf               CONMEBOL
hour                           1
rank_diff                  -28.0
points_diff               122.92
age_diff                0.272727
Name: 553, dtype: object home_team_goals    1
away_team_goals    0
Name: 553, dtype: int64
model prediction: [[2 1]]
the match is:  home_team               Paraguay
away_team                Ecuador
home_total_points        1440.53
home_rank_change             7.0
home_previous_points     1454.52
home_conf               CONMEBOL
away_total_points        1458.63
away_rank_change            -2.0
away_previous_points     1448.27
away_conf               CONMEBOL
hour                          23
rank_diff                    6.0
points_diff                -18.1
age_diff                0.454545
Name: 566, dtype: object home_team_goals    3
away_team_goals    1
Name: 566, dtype: int64

/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:

model prediction: [[1 1]]
the match is:  home_team                 Mexico
away_team               Paraguay
home_total_points         1647.9
home_rank_change            -2.0
home_previous_points      1638.3
home_conf               CONCACAF
away_total_points        1440.53
away_rank_change             7.0
away_previous_points     1454.52
away_conf               CONMEBOL
hour                           1
rank_diff                  -38.0
points_diff               207.37
age_diff               -3.909091
Name: 568, dtype: object home_team_goals    0
away_team_goals    1
Name: 568, dtype: int64
model prediction: [[2 1]]
the match is:  home_team                  Japan
away_team               Paraguay
home_total_points        1549.82
home_rank_change            -3.0
home_previous_points     1531.53
home_conf                    AFC
away_total_points        1440.53
away_rank_change             7.0
away_previous_points     1454.52
away_conf               CONMEBOL
hour                          10
rank_diff                  -27.0
points_diff               109.29
age_diff                1.272727
Name: 572, dtype: object home_team_goals    4
away_team_goals    1
Name: 572, dtype: int64
model prediction: [[2 1]]
the match is:  home_team               Colombia
away_team               Paraguay
home_total_points        1585.89
home_rank_change             3.0
home_previous_points     1607.15
home_conf               CONMEBOL
away_total_points        1440.53
away_rank_change             7.0
away_previous_points     1454.52
away_conf               CONMEBOL
hour                           1
rank_diff                  -31.0
points_diff               145.36
age_diff               -0.363636
Name: 579, dtype: object home_team_goals    2
away_team_goals    0
Name: 579, dtype: int64
model prediction: [[2 1]]
the match is:  home_team                 Norway
away_team               Slovenia
home_total_points        1455.43
home_rank_change             4.0
home_previous_points     1455.43
home_conf                   UEFA
away_total_points        1375.42
away_rank_change            -1.0
away_previous_points     1375.42
away_conf                   UEFA
hour                          18
rank_diff                  -19.0
points_diff                80.01
age_diff               -0.636364
Name: 590, dtype: object home_team_goals    0
away_team_goals    0
Name: 590, dtype: int64
model prediction: [[2 1]]
the match is:  home_team               Slovenia
away_team                 Norway
home_total_points        1375.42
home_rank_change            -1.0
home_previous_points     1375.42
home_conf                   UEFA
away_total_points        1455.43
away_rank_change             4.0
away_previous_points     1455.43
away_conf                   UEFA
hour                          16
rank_diff                   19.0
points_diff               -80.01
age_diff                1.363636
Name: 591, dtype: object home_team_goals    1
away_team_goals    2
Name: 591, dtype: int64
model prediction: [[2 2]]
the match is:  home_team                 Norway
away_team               Slovakia
home_total_points        1455.43
home_rank_change             4.0
home_previous_points     1455.43
home_conf                   UEFA
away_total_points        1455.36
away_rank_change             4.0
away_previous_points     1455.36
away_conf                   UEFA
hour                          17
rank_diff                   -1.0
points_diff                 0.07
age_diff               -0.909091
Name: 593, dtype: object home_team_goals    2
away_team_goals    0
Name: 593, dtype: int64
model prediction: [[2 1]]
the match is:  home_team                 Norway
away_team                Finland
home_total_points        1455.43
home_rank_change             4.0
home_previous_points     1455.43
home_conf                   UEFA
away_total_points        1411.77
away_rank_change            -1.0
away_previous_points     1411.77
away_conf                   UEFA
hour                          13
rank_diff                  -12.0
points_diff                43.66
age_diff                0.727273
Name: 597, dtype: object home_team_goals    1
away_team_goals    1
Name: 597, dtype: int64
model prediction: [[2 1]]
the match is:  home_team                 Serbia
away_team                 Norway
home_total_points        1547.38
home_rank_change             2.0
home_previous_points     1547.38
home_conf                   UEFA
away_total_points        1455.43
away_rank_change             4.0
away_previous_points     1455.43
away_conf                   UEFA
hour                          18
rank_diff                  -20.0
points_diff                91.95
age_diff                1.272727
Name: 608, dtype: object home_team_goals    1
away_team_goals    0
Name: 608, dtype: int64
model prediction: [[2 1]]
the match is:  home_team                 Norway
away_team                 Serbia
home_total_points        1455.43
home_rank_change             4.0
home_previous_points     1455.43
home_conf                   UEFA
away_total_points        1547.38
away_rank_change             2.0
away_previous_points     1547.38
away_conf                   UEFA
hour                          18
rank_diff                   20.0
points_diff               -91.95
age_diff               -0.636364
Name: 609, dtype: object home_team_goals    0
away_team_goals    2
Name: 609, dtype: int64
model prediction: [[2 1]]
the match is:  home_team                 Norway
away_team                Armenia
home_total_points        1455.43
home_rank_change             4.0
home_previous_points     1455.43
home_conf                   UEFA
away_total_points        1242.24
away_rank_change             0.0
away_previous_points     1242.24
away_conf                   UEFA
hour                          17
rank_diff                  -47.0
points_diff               213.19
age_diff               -1.454545
Name: 612, dtype: object home_team_goals    9
away_team_goals    0
Name: 612, dtype: int64
model prediction: [[3 1]]
the match is:  home_team                Costa Rica
away_team               New Zealand
home_total_points           1464.06
home_rank_change               -7.0
home_previous_points        1437.43
home_conf                  CONCACAF
away_total_points           1161.66
away_rank_change                1.0
away_previous_points        1165.81
away_conf                       OFC
hour                             18
rank_diff                     -69.0
points_diff                   302.4
age_diff                   3.363636
Name: 614, dtype: object home_team_goals    0
away_team_goals    1
Name: 614, dtype: int64
model prediction: [[2 1]]
the match is:  home_team               New Zealand
away_team                    Tahiti
home_total_points           1161.66
home_rank_change                1.0
home_previous_points        1165.81
home_conf                       OFC
away_total_points           1014.27
away_rank_change                0.0
away_previous_points        1014.27
away_conf                       OFC
hour                             17
rank_diff                     -48.0
points_diff                  147.39
age_diff                  -2.545455
Name: 617, dtype: object home_team_goals    1
away_team_goals    0
Name: 617, dtype: int64
model prediction: [[4 1]]
the match is:  home_team               New Zealand
away_team                      Fiji
home_total_points           1161.66
home_rank_change                1.0
home_previous_points        1165.81
home_conf                       OFC
away_total_points            996.27
away_rank_change                1.0
away_previous_points         996.27
away_conf                       OFC
hour                             17
rank_diff                     -51.0
points_diff                  165.39
age_diff                  -0.090909
Name: 619, dtype: object home_team_goals    4
away_team_goals    0
Name: 619, dtype: int64
model prediction: [[6 1]]
the match is:  home_team                      Peru
away_team               New Zealand
home_total_points           1563.45
home_rank_change                0.0
home_previous_points        1551.15
home_conf                  CONMEBOL
away_total_points           1161.66
away_rank_change                1.0
away_previous_points        1165.81
away_conf                       OFC
hour                             15
rank_diff                     -89.0
points_diff                  401.79
age_diff                   4.181818
Name: 620, dtype: object home_team_goals    0
away_team_goals    1
Name: 620, dtype: int64

/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:

model prediction: [[3 1]]
the match is:  home_team                 New Zealand
away_team               New Caledonia
home_total_points             1161.66
home_rank_change                  1.0
home_previous_points          1165.81
home_conf                         OFC
away_total_points             1035.12
away_rank_change                  0.0
away_previous_points          1035.12
away_conf                         OFC
hour                               17
rank_diff                       -42.0
points_diff                    126.54
age_diff                    -3.818182
Name: 627, dtype: object home_team_goals    7
away_team_goals    1
Name: 627, dtype: int64
model prediction: [[4 1]]
the match is:  home_team                      Oman
away_team               New Zealand
home_total_points            1301.0
home_rank_change                0.0
home_previous_points        1306.01
home_conf                       AFC
away_total_points           1161.66
away_rank_change                1.0
away_previous_points        1165.81
away_conf                       OFC
hour                             18
rank_diff                     -32.0
points_diff                  139.34
age_diff                   0.454545
Name: 630, dtype: object home_team_goals    0
away_team_goals    0
Name: 630, dtype: int64
model prediction: [[3 1]]
the match is:  home_team               Solomon Islands
away_team                   New Zealand
home_total_points               1072.78
home_rank_change                    1.0
home_previous_points            1072.78
home_conf                           OFC
away_total_points               1161.66
away_rank_change                    1.0
away_previous_points            1165.81
away_conf                           OFC
hour                                 17
rank_diff                          31.0
points_diff                      -88.88
age_diff                       0.909091
Name: 633, dtype: object home_team_goals    5
away_team_goals    0
Name: 633, dtype: int64
model prediction: [[4 1]]
the match is:  home_team                   England
away_team               Ivory Coast
home_total_points           1755.52
home_rank_change                1.0
home_previous_points        1755.52
home_conf                      UEFA
away_total_points           1439.62
away_rank_change               -5.0
away_previous_points        1417.86
away_conf                       CAF
hour                             18
rank_diff                     -46.0
points_diff                   315.9
age_diff                  -3.454545
Name: 651, dtype: object home_team_goals    3
away_team_goals    0
Name: 651, dtype: int64
model prediction: [[2 1]]
the match is:  home_team               Ivory Coast
away_team                   Burundi
home_total_points           1439.62
home_rank_change               -5.0
home_previous_points        1417.86
home_conf                       CAF
away_total_points           1075.82
away_rank_change                1.0
away_previous_points        1075.82
away_conf                       CAF
hour                             16
rank_diff                     -90.0
points_diff                   363.8
age_diff                   2.272727
Name: 654, dtype: object home_team_goals    4
away_team_goals    0
Name: 654, dtype: int64
model prediction: [[2 1]]
the match is:  home_team                    France
away_team               Ivory Coast
home_total_points           1786.15
home_rank_change                0.0
home_previous_points        1786.15
home_conf                      UEFA
away_total_points           1439.62
away_rank_change               -5.0
away_previous_points        1417.86
away_conf                       CAF
hour                             20
rank_diff                     -48.0
points_diff                  346.53
age_diff                  -0.909091
Name: 658, dtype: object home_team_goals    2
away_team_goals    1
Name: 658, dtype: int64
model prediction: [[1 1]]
the match is:  home_team               Ivory Coast
away_team                      Togo
home_total_points           1439.62
home_rank_change               -5.0
home_previous_points        1417.86
home_conf                       CAF
away_total_points           1133.24
away_rank_change                2.0
away_previous_points        1133.24
away_conf                       CAF
hour                             16
rank_diff                     -75.0
points_diff                  306.38
age_diff                   0.909091
Name: 660, dtype: object home_team_goals    2
away_team_goals    1
Name: 660, dtype: int64
model prediction: [[3 1]]
the match is:  home_team               Ivory Coast
away_team                    Guinea
home_total_points           1439.62
home_rank_change               -5.0
home_previous_points        1417.86
home_conf                       CAF
away_total_points           1292.58
away_rank_change                0.0
away_previous_points        1298.32
away_conf                       CAF
hour                             18
rank_diff                     -30.0
points_diff                  147.04
age_diff                   0.181818
Name: 661, dtype: object home_team_goals    3
away_team_goals    1
Name: 661, dtype: int64
model prediction: [[3 2]]
the match is:  home_team               Ivory Coast
away_team                    Zambia
home_total_points           1439.62
home_rank_change               -5.0
home_previous_points        1417.86
home_conf                       CAF
away_total_points           1264.64
away_rank_change                0.0
away_previous_points        1264.64
away_conf                       CAF
hour                             19
rank_diff                     -37.0
points_diff                  174.98
age_diff                   3.818182
Name: 672, dtype: object home_team_goals    3
away_team_goals    1
Name: 672, dtype: int64
model prediction: [[3 1]]
the match is:  home_team               Burkina Faso
away_team                Ivory Coast
home_total_points            1418.58
home_rank_change                -4.0
home_previous_points         1397.64
home_conf                        CAF
away_total_points            1439.62
away_rank_change                -5.0
away_previous_points         1417.86
away_conf                        CAF
hour                              16
rank_diff                        5.0
points_diff                   -21.04
age_diff                   -4.818182
Name: 687, dtype: object home_team_goals    2
away_team_goals    1
Name: 687, dtype: int64
model prediction: [[1 1]]
the match is:  home_team                   Lesotho
away_team               Ivory Coast
home_total_points           1057.62
home_rank_change                1.0
home_previous_points        1057.62
home_conf                       CAF
away_total_points           1439.62
away_rank_change               -5.0
away_previous_points        1417.86
away_conf                       CAF
hour                             17
rank_diff                      95.0
points_diff                  -382.0
age_diff                  -1.363636
Name: 689, dtype: object home_team_goals    0
away_team_goals    0
Name: 689, dtype: int64
model prediction: [[1 2]]
the match is:  home_team                     France
away_team               South Africa
home_total_points            1786.15
home_rank_change                 0.0
home_previous_points         1786.15
home_conf                       UEFA
away_total_points            1358.24
away_rank_change                 0.0
away_previous_points         1358.24
away_conf                        CAF
hour                              19
rank_diff                      -65.0
points_diff                   427.91
age_diff                    0.555556
Name: 705, dtype: object home_team_goals    5
away_team_goals    0
Name: 705, dtype: int64
model prediction: [[2 1]]
the match is:  home_team               South Africa
away_team                     Guinea
home_total_points            1358.24
home_rank_change                 0.0
home_previous_points         1358.24
home_conf                        CAF
away_total_points            1292.58
away_rank_change                 0.0
away_previous_points         1298.32
away_conf                        CAF
hour                              17
rank_diff                      -13.0
points_diff                    65.66
age_diff                    1.090909
Name: 709, dtype: object home_team_goals    0
away_team_goals    0
Name: 709, dtype: int64
model prediction: [[2 1]]
the match is:  home_team                    Morocco
away_team               South Africa
home_total_points            1547.42
home_rank_change                -4.0
home_previous_points         1529.93
home_conf                        CAF
away_total_points            1358.24
away_rank_change                 0.0
away_previous_points         1358.24
away_conf                        CAF
hour                              19
rank_diff                      -44.0
points_diff                   189.18
age_diff                   -0.454545
Name: 721, dtype: object home_team_goals    2
away_team_goals    1
Name: 721, dtype: int64
model prediction: [[3 1]]
the match is:  home_team               Australia
away_team                 Denmark
home_total_points         1486.86
home_rank_change              2.0
home_previous_points      1484.88
home_conf                     AFC
away_total_points         1654.54
away_rank_change              0.0
away_previous_points      1654.54
away_conf                    UEFA
hour                           15
rank_diff                    28.0
points_diff               -167.68
age_diff                 1.727273
Name: 730, dtype: object home_team_goals    1
away_team_goals    0
Name: 730, dtype: int64

/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:

model prediction: [[2 2]]
the match is:  home_team               Australia
away_team                    Peru
home_total_points         1486.86
home_rank_change              2.0
home_previous_points      1484.88
home_conf                     AFC
away_total_points         1563.45
away_rank_change              0.0
away_previous_points      1551.15
away_conf                CONMEBOL
hour                           18
rank_diff                    15.0
points_diff                -76.59
age_diff                -1.636364
Name: 731, dtype: object home_team_goals    5
away_team_goals    4
Name: 731, dtype: int64
model prediction: [[2 1]]
the match is:  home_team               Australia
away_team                  Jordan
home_total_points         1486.86
home_rank_change              2.0
home_previous_points      1484.88
home_conf                     AFC
away_total_points         1259.84
away_rank_change              0.0
away_previous_points      1255.69
away_conf                     AFC
hour                           18
rank_diff                   -53.0
points_diff                227.02
age_diff                 0.454545
Name: 733, dtype: object home_team_goals    2
away_team_goals    1
Name: 733, dtype: int64
model prediction: [[2 1]]
the match is:  home_team               Saudi Arabia
away_team                  Australia
home_total_points            1433.95
home_rank_change                 2.0
home_previous_points         1434.71
home_conf                        AFC
away_total_points            1486.86
away_rank_change                 2.0
away_previous_points         1484.88
away_conf                        AFC
hour                              18
rank_diff                       16.0
points_diff                   -52.91
age_diff                    0.363636
Name: 740, dtype: object home_team_goals    1
away_team_goals    0
Name: 740, dtype: int64
model prediction: [[1 2]]
the match is:  home_team                 Australia
away_team               New Zealand
home_total_points           1486.86
home_rank_change                2.0
home_previous_points        1484.88
home_conf                       AFC
away_total_points           1161.66
away_rank_change                1.0
away_previous_points        1165.81
away_conf                       OFC
hour                             10
rank_diff                     -74.0
points_diff                   325.2
age_diff                   3.636364
Name: 744, dtype: object home_team_goals    1
away_team_goals    0
Name: 744, dtype: int64

/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:

model prediction: [[2 1]]
the match is:  home_team               New Zealand
away_team                 Australia
home_total_points           1161.66
home_rank_change                1.0
home_previous_points        1165.81
home_conf                       OFC
away_total_points           1486.86
away_rank_change                2.0
away_previous_points        1484.88
away_conf                       AFC
hour                              3
rank_diff                      74.0
points_diff                  -325.2
age_diff                  -0.909091
Name: 745, dtype: object home_team_goals    0
away_team_goals    2
Name: 745, dtype: int64
model prediction: [[2 2]]
the match is:  home_team                  France
away_team               Australia
home_total_points         1786.15
home_rank_change              0.0
home_previous_points      1786.15
home_conf                    UEFA
away_total_points         1486.86
away_rank_change              2.0
away_previous_points      1484.88
away_conf                     AFC
hour                           19
rank_diff                   -34.0
points_diff                299.29
age_diff                     -1.0
Name: 751, dtype: object home_team_goals    4
away_team_goals    1
Name: 751, dtype: int64
model prediction: [[2 1]]
the match is:  home_team                 Tunisia
away_team               Australia
home_total_points         1489.92
home_rank_change              6.0
home_previous_points      1512.72
home_conf                     CAF
away_total_points         1486.86
away_rank_change              2.0
away_previous_points      1484.88
away_conf                     AFC
hour                           10
rank_diff                    -1.0
points_diff                  3.06
age_diff                -0.727273
Name: 757, dtype: object home_team_goals    0
away_team_goals    1
Name: 757, dtype: int64
model prediction: [[1 2]]
the match is:  home_team               Argentina
away_team               Australia
home_total_points         1766.99
home_rank_change             -1.0
home_previous_points      1750.51
home_conf                CONMEBOL
away_total_points         1486.86
away_rank_change              2.0
away_previous_points      1484.88
away_conf                     AFC
hour                           19
rank_diff                   -33.0
points_diff                280.13
age_diff                -0.181818
Name: 765, dtype: object home_team_goals    2
away_team_goals    1
Name: 765, dtype: int64
model prediction: [[3 1]]
the match is:  home_team               Australia
away_team                   Japan
home_total_points         1486.86
home_rank_change              2.0
home_previous_points      1484.88
home_conf                     AFC
away_total_points         1549.82
away_rank_change             -3.0
away_previous_points      1531.53
away_conf                     AFC
hour                            9
rank_diff                    14.0
points_diff                -62.96
age_diff                -1.909091
Name: 771, dtype: object home_team_goals    0
away_team_goals    2
Name: 771, dtype: int64
model prediction: [[1 2]]
the match is:  home_team               Saudi Arabia
away_team                    Ecuador
home_total_points            1433.95
home_rank_change                 2.0
home_previous_points         1434.71
home_conf                        AFC
away_total_points            1458.63
away_rank_change                -2.0
away_previous_points         1448.27
away_conf                   CONMEBOL
hour                              18
rank_diff                        9.0
points_diff                   -24.68
age_diff                    2.090909
Name: 782, dtype: object home_team_goals    0
away_team_goals    0
Name: 782, dtype: int64
model prediction: [[1 2]]
the match is:  home_team               Netherlands
away_team                   Ecuador
home_total_points           1653.73
home_rank_change                0.0
home_previous_points        1653.73
home_conf                      UEFA
away_total_points           1458.63
away_rank_change               -2.0
away_previous_points        1448.27
away_conf                  CONMEBOL
hour                             16
rank_diff                     -34.0
points_diff                   195.1
age_diff                   1.272727
Name: 785, dtype: object home_team_goals    1
away_team_goals    1
Name: 785, dtype: int64
model prediction: [[3 1]]
the match is:  home_team                  Ecuador
away_team               Cape Verde
home_total_points          1458.63
home_rank_change              -2.0
home_previous_points       1448.27
home_conf                 CONMEBOL
away_total_points          1336.88
away_rank_change               0.0
away_previous_points       1339.48
away_conf                      CAF
hour                            23
rank_diff                    -29.0
points_diff                 121.75
age_diff                 -1.363636
Name: 793, dtype: object home_team_goals    1
away_team_goals    0
Name: 793, dtype: int64

/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:

model prediction: [[2 2]]
the match is:  home_team                Ecuador
away_team                Nigeria
home_total_points        1458.63
home_rank_change            -2.0
home_previous_points     1448.27
home_conf               CONMEBOL
away_total_points        1509.91
away_rank_change            -4.0
away_previous_points     1478.78
away_conf                    CAF
hour                           0
rank_diff                   12.0
points_diff               -51.28
age_diff                     0.0
Name: 798, dtype: object home_team_goals    1
away_team_goals    0
Name: 798, dtype: int64
model prediction: [[1 2]]
the match is:  home_team                 Ecuador
away_team               Argentina
home_total_points         1458.63
home_rank_change             -2.0
home_previous_points      1448.27
home_conf                CONMEBOL
away_total_points         1766.99
away_rank_change             -1.0
away_previous_points      1750.51
away_conf                CONMEBOL
hour                           23
rank_diff                    40.0
points_diff               -308.36
age_diff                -2.181818
Name: 803, dtype: object home_team_goals    1
away_team_goals    1
Name: 803, dtype: int64
model prediction: [[1 0]]
the match is:  home_team                Ecuador
away_team                   Iraq
home_total_points        1458.63
home_rank_change            -2.0
home_previous_points     1448.27
home_conf               CONMEBOL
away_total_points        1325.44
away_rank_change            -1.0
away_previous_points     1333.03
away_conf                    AFC
hour                          17
rank_diff                  -30.0
points_diff               133.19
age_diff                2.545455
Name: 804, dtype: object home_team_goals    0
away_team_goals    0
Name: 804, dtype: int64
model prediction: [[2 1]]
the match is:  home_team                Ecuador
away_team                  Japan
home_total_points        1458.63
home_rank_change            -2.0
home_previous_points     1448.27
home_conf               CONMEBOL
away_total_points        1549.82
away_rank_change            -3.0
away_previous_points     1531.53
away_conf                    AFC
hour                          11
rank_diff                   21.0
points_diff               -91.19
age_diff               -2.181818
Name: 806, dtype: object home_team_goals    0
away_team_goals    0
Name: 806, dtype: int64
model prediction: [[1 2]]
the match is:  home_team                Ecuador
away_team                Senegal
home_total_points        1458.63
home_rank_change            -2.0
home_previous_points     1448.27
home_conf               CONMEBOL
away_total_points        1587.78
away_rank_change            -2.0
away_previous_points     1561.68
away_conf                    CAF
hour                          15
rank_diff                   26.0
points_diff              -129.15
age_diff               -1.272727
Name: 807, dtype: object home_team_goals    1
away_team_goals    2
Name: 807, dtype: int64
model prediction: [[1 2]]
the match is:  home_team               Cameroon
away_team                Algeria
home_total_points        1480.82
home_rank_change           -12.0
home_previous_points     1437.35
home_conf                    CAF
away_total_points        1460.93
away_rank_change            14.0
away_previous_points     1516.51
away_conf                    CAF
hour                          17
rank_diff                   -5.0
points_diff                19.89
age_diff               -2.454545
Name: 834, dtype: object home_team_goals    1
away_team_goals    0
Name: 834, dtype: int64
model prediction: [[3 1]]
the match is:  home_team                Algeria
away_team               Cameroon
home_total_points        1460.93
home_rank_change            14.0
home_previous_points     1516.51
home_conf                    CAF
away_total_points        1480.82
away_rank_change           -12.0
away_previous_points     1437.35
away_conf                    CAF
hour                          19
rank_diff                    5.0
points_diff               -19.89
age_diff                1.090909
Name: 835, dtype: object home_team_goals    1
away_team_goals    2
Name: 835, dtype: int64

/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:

model prediction: [[2 1]]
the match is:  home_team               Cameroon
away_team                Algeria
home_total_points        1480.82
home_rank_change           -12.0
home_previous_points     1437.35
home_conf                    CAF
away_total_points        1460.93
away_rank_change            14.0
away_previous_points     1516.51
away_conf                    CAF
hour                          17
rank_diff                   -5.0
points_diff                19.89
age_diff               -2.454545
Name: 836, dtype: object home_team_goals    1
away_team_goals    0
Name: 836, dtype: int64
model prediction: [[3 1]]
the match is:  home_team                Algeria
away_team               Cameroon
home_total_points        1460.93
home_rank_change            14.0
home_previous_points     1516.51
home_conf                    CAF
away_total_points        1480.82
away_rank_change           -12.0
away_previous_points     1437.35
away_conf                    CAF
hour                          19
rank_diff                    5.0
points_diff               -19.89
age_diff                1.090909
Name: 837, dtype: object home_team_goals    1
away_team_goals    2
Name: 837, dtype: int64
model prediction: [[2 1]]
the match is:  home_team               Tanzania
away_team                Algeria
home_total_points        1118.76
home_rank_change             1.0
home_previous_points     1118.76
home_conf                    CAF
away_total_points        1460.93
away_rank_change            14.0
away_previous_points     1516.51
away_conf                    CAF
hour                          16
rank_diff                   89.0
points_diff              -342.17
age_diff               -4.363636
Name: 853, dtype: object home_team_goals    2
away_team_goals    0
Name: 853, dtype: int64
model prediction: [[3 2]]
the match is:  home_team               Tanzania
away_team                Algeria
home_total_points        1118.76
home_rank_change             1.0
home_previous_points     1118.76
home_conf                    CAF
away_total_points        1460.93
away_rank_change            14.0
away_previous_points     1516.51
away_conf                    CAF
hour                          16
rank_diff                   89.0
points_diff              -342.17
age_diff               -4.363636
Name: 854, dtype: object home_team_goals    2
away_team_goals    0
Name: 854, dtype: int64
model prediction: [[3 2]]
the match is:  home_team                Algeria
away_team                 Uganda
home_total_points        1460.93
home_rank_change            14.0
home_previous_points     1516.51
home_conf                    CAF
away_total_points        1279.18
away_rank_change             2.0
away_previous_points     1285.28
away_conf                    CAF
hour                          19
rank_diff                  -41.0
points_diff               181.75
age_diff                1.909091
Name: 866, dtype: object home_team_goals    2
away_team_goals    0
Name: 866, dtype: int64
model prediction: [[2 1]]
the match is:  home_team                Algeria
away_team                 Uganda
home_total_points        1460.93
home_rank_change            14.0
home_previous_points     1516.51
home_conf                    CAF
away_total_points        1279.18
away_rank_change             2.0
away_previous_points     1285.28
away_conf                    CAF
hour                          19
rank_diff                  -41.0
points_diff               181.75
age_diff                1.909091
Name: 867, dtype: object home_team_goals    2
away_team_goals    0
Name: 867, dtype: int64
model prediction: [[2 1]]
the match is:  home_team               Saudi Arabia
away_team                    Albania
home_total_points            1433.95
home_rank_change                 2.0
home_previous_points         1434.71
home_conf                        AFC
away_total_points            1374.98
away_rank_change                -1.0
away_previous_points         1374.98
away_conf                       UEFA
hour                              14
rank_diff                      -12.0
points_diff                    58.97
age_diff                    1.818182
Name: 881, dtype: object home_team_goals    1
away_team_goals    1
Name: 881, dtype: int64

/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:

model prediction: [[2 2]]
the match is:  home_team                     Panama
away_team               Saudi Arabia
home_total_points            1375.56
home_rank_change                 0.0
home_previous_points         1379.34
home_conf                   CONCACAF
away_total_points            1433.95
away_rank_change                 2.0
away_previous_points         1434.71
away_conf                        AFC
hour                              12
rank_diff                       10.0
points_diff                   -58.39
age_diff                   -0.818182
Name: 889, dtype: object home_team_goals    1
away_team_goals    1
Name: 889, dtype: int64
model prediction: [[2 1]]
the match is:  home_team               Saudi Arabia
away_team                   Honduras
home_total_points            1433.95
home_rank_change                 2.0
home_previous_points         1434.71
home_conf                        AFC
away_total_points            1303.96
away_rank_change                 2.0
away_previous_points         1332.16
away_conf                   CONCACAF
hour                              14
rank_diff                      -25.0
points_diff                   129.99
age_diff                   -0.272727
Name: 890, dtype: object home_team_goals    0
away_team_goals    0
Name: 890, dtype: int64
model prediction: [[2 2]]
the match is:  home_team                  Saudi Arabia
away_team               North Macedonia
home_total_points               1433.95
home_rank_change                    2.0
home_previous_points            1434.71
home_conf                           AFC
away_total_points               1367.23
away_rank_change                    0.0
away_previous_points            1367.23
away_conf                          UEFA
hour                                 14
rank_diff                         -14.0
points_diff                       66.72
age_diff                      -0.818182
Name: 892, dtype: object home_team_goals    1
away_team_goals    0
Name: 892, dtype: int64
model prediction: [[2 1]]
the match is:  home_team                    Iceland
away_team               Saudi Arabia
home_total_points            1382.81
home_rank_change                -2.0
home_previous_points         1385.21
home_conf                       UEFA
away_total_points            1433.95
away_rank_change                 2.0
away_previous_points         1434.71
away_conf                        AFC
hour                              12
rank_diff                        7.0
points_diff                   -51.14
age_diff                   -2.636364
Name: 900, dtype: object home_team_goals    1
away_team_goals    0
Name: 900, dtype: int64
model prediction: [[1 1]]
the match is:  home_team                  Argentina
away_team               Saudi Arabia
home_total_points            1766.99
home_rank_change                -1.0
home_previous_points         1750.51
home_conf                   CONMEBOL
away_total_points            1433.95
away_rank_change                 2.0
away_previous_points         1434.71
away_conf                        AFC
hour                              10
rank_diff                      -49.0
points_diff                   333.04
age_diff                    1.363636
Name: 903, dtype: object home_team_goals    2
away_team_goals    1
Name: 903, dtype: int64
model prediction: [[2 1]]
the match is:  home_team               Saudi Arabia
away_team                    Croatia
home_total_points            1433.95
home_rank_change                 2.0
home_previous_points         1434.71
home_conf                        AFC
away_total_points            1620.74
away_rank_change                 0.0
away_previous_points         1620.74
away_conf                       UEFA
hour                              12
rank_diff                       38.0
points_diff                  -186.79
age_diff                    2.090909
Name: 906, dtype: object home_team_goals    0
away_team_goals    1
Name: 906, dtype: int64
model prediction: [[2 2]]
the match is:  home_team                     Poland
away_team               Saudi Arabia
home_total_points            1530.62
home_rank_change                 1.0
home_previous_points         1530.62
home_conf                       UEFA
away_total_points            1433.95
away_rank_change                 2.0
away_previous_points         1434.71
away_conf                        AFC
hour                              13
rank_diff                      -25.0
points_diff                    96.67
age_diff                         1.0
Name: 907, dtype: object home_team_goals    0
away_team_goals    2
Name: 907, dtype: int64

/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:

model prediction: [[2 1]]
the match is:  home_team               Saudi Arabia
away_team                  Venezuela
home_total_points            1433.95
home_rank_change                 2.0
home_previous_points         1434.71
home_conf                        AFC
away_total_points            1411.45
away_rank_change                -1.0
away_previous_points         1409.14
away_conf                   CONMEBOL
hour                              17
rank_diff                       -5.0
points_diff                     22.5
age_diff                   -0.363636
Name: 909, dtype: object home_team_goals    0
away_team_goals    1
Name: 909, dtype: int64
model prediction: [[2 2]]
the match is:  home_team               Saudi Arabia
away_team                   Colombia
home_total_points            1433.95
home_rank_change                 2.0
home_previous_points         1434.71
home_conf                        AFC
away_total_points            1585.89
away_rank_change                 3.0
away_previous_points         1607.15
away_conf                   CONMEBOL
hour                              17
rank_diff                       34.0
points_diff                  -151.94
age_diff                         1.0
Name: 910, dtype: object home_team_goals    0
away_team_goals    1
Name: 910, dtype: int64
model prediction: [[2 2]]
the match is:  home_team                Austria
away_team               Scotland
home_total_points        1511.56
home_rank_change            -1.0
home_previous_points     1511.56
home_conf                   UEFA
away_total_points        1471.82
away_rank_change             2.0
away_previous_points     1471.82
away_conf                   UEFA
hour                          18
rank_diff                  -10.0
points_diff                39.74
age_diff                0.909091
Name: 918, dtype: object home_team_goals    2
away_team_goals    2
Name: 918, dtype: int64
model prediction: [[2 2]]
the match is:  home_team                Turkiye
away_team               Scotland
home_total_points        1472.72
home_rank_change             2.0
home_previous_points     1472.72
home_conf                   UEFA
away_total_points        1471.82
away_rank_change             2.0
away_previous_points     1471.82
away_conf                   UEFA
hour                          17
rank_diff                   -1.0
points_diff                  0.9
age_diff               -3.090909
Name: 923, dtype: object home_team_goals    2
away_team_goals    1
Name: 923, dtype: int64
model prediction: [[1 2]]
the match is:  home_team               Scotland
away_team                 Poland
home_total_points        1471.82
home_rank_change             2.0
home_previous_points     1471.82
home_conf                   UEFA
away_total_points        1530.62
away_rank_change             1.0
away_previous_points     1530.62
away_conf                   UEFA
hour                          19
rank_diff                   12.0
points_diff                -58.8
age_diff                    -1.0
Name: 952, dtype: object home_team_goals    1
away_team_goals    1
Name: 952, dtype: int64
model prediction: [[2 2]]
the match is:  home_team               Scotland
away_team                Ukraine
home_total_points        1471.82
home_rank_change             2.0
home_previous_points     1471.82
home_conf                   UEFA
away_total_points        1535.08
away_rank_change             2.0
away_previous_points     1535.08
away_conf                   UEFA
hour                          18
rank_diff                   13.0
points_diff               -63.26
age_diff                0.636364
Name: 953, dtype: object home_team_goals    1
away_team_goals    3
Name: 953, dtype: int64
model prediction: [[2 2]]
the match is:  home_team               Scotland
away_team                Ukraine
home_total_points        1471.82
home_rank_change             2.0
home_previous_points     1471.82
home_conf                   UEFA
away_total_points        1535.08
away_rank_change             2.0
away_previous_points     1535.08
away_conf                   UEFA
hour                          18
rank_diff                   13.0
points_diff               -63.26
age_diff                1.272727
Name: 954, dtype: object home_team_goals    3
away_team_goals    0
Name: 954, dtype: int64

/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:

model prediction: [[2 2]]
the match is:  home_team                Ukraine
away_team               Scotland
home_total_points        1535.08
home_rank_change             2.0
home_previous_points     1535.08
home_conf                   UEFA
away_total_points        1471.82
away_rank_change             2.0
away_previous_points     1471.82
away_conf                   UEFA
hour                          18
rank_diff                  -13.0
points_diff                63.26
age_diff               -2.090909
Name: 955, dtype: object home_team_goals    0
away_team_goals    0
Name: 955, dtype: int64
model prediction: [[2 2]]
the match is:  home_team               Scotland
away_team                Armenia
home_total_points        1471.82
home_rank_change             2.0
home_previous_points     1471.82
home_conf                   UEFA
away_total_points        1242.24
away_rank_change             0.0
away_previous_points     1242.24
away_conf                   UEFA
hour                          18
rank_diff                  -52.0
points_diff               229.58
age_diff               -2.454545
Name: 957, dtype: object home_team_goals    2
away_team_goals    0
Name: 957, dtype: int64
model prediction: [[3 1]]
the match is:  home_team                Armenia
away_team               Scotland
home_total_points        1242.24
home_rank_change             0.0
home_previous_points     1242.24
home_conf                   UEFA
away_total_points        1471.82
away_rank_change             2.0
away_previous_points     1471.82
away_conf                   UEFA
hour                          16
rank_diff                   52.0
points_diff              -229.58
age_diff                2.818182
Name: 958, dtype: object home_team_goals    1
away_team_goals    4
Name: 958, dtype: int64
model prediction: [[2 2]]
the match is:  home_team               Austria
away_team                France
home_total_points       1511.56
home_rank_change           -1.0
home_previous_points    1511.56
home_conf                  UEFA
away_total_points       1786.15
away_rank_change            0.0
away_previous_points    1786.15
away_conf                  UEFA
hour                         18
rank_diff                  27.0
points_diff             -274.59
age_diff                    1.0
Name: 962, dtype: object home_team_goals    1
away_team_goals    1
Name: 962, dtype: int64
model prediction: [[2 1]]
the match is:  home_team                 France
away_team                Austria
home_total_points        1786.15
home_rank_change             0.0
home_previous_points     1786.15
home_conf                   UEFA
away_total_points        1511.56
away_rank_change            -1.0
away_previous_points     1511.56
away_conf                   UEFA
hour                          18
rank_diff                  -27.0
points_diff               274.59
age_diff               -1.272727
Name: 963, dtype: object home_team_goals    2
away_team_goals    0
Name: 963, dtype: int64
model prediction: [[2 1]]
the match is:  home_team                France
away_team               Denmark
home_total_points       1786.15
home_rank_change            0.0
home_previous_points    1786.15
home_conf                  UEFA
away_total_points       1654.54
away_rank_change            0.0
away_previous_points    1654.54
away_conf                  UEFA
hour                         16
rank_diff                  -6.0
points_diff              131.61
age_diff                    1.0
Name: 964, dtype: object home_team_goals    2
away_team_goals    1
Name: 964, dtype: int64
model prediction: [[3 2]]
the match is:  home_team                 France
away_team                Denmark
home_total_points        1786.15
home_rank_change             0.0
home_previous_points     1786.15
home_conf                   UEFA
away_total_points        1654.54
away_rank_change             0.0
away_previous_points     1654.54
away_conf                   UEFA
hour                          18
rank_diff                   -6.0
points_diff               131.61
age_diff               -0.090909
Name: 965, dtype: object home_team_goals    1
away_team_goals    2
Name: 965, dtype: int64
model prediction: [[2 2]]
the match is:  home_team                Denmark
away_team                 France
home_total_points        1654.54
home_rank_change             0.0
home_previous_points     1654.54
home_conf                   UEFA
away_total_points        1786.15
away_rank_change             0.0
away_previous_points     1786.15
away_conf                   UEFA
hour                          18
rank_diff                    6.0
points_diff              -131.61
age_diff                1.363636
Name: 966, dtype: object home_team_goals    0
away_team_goals    2
Name: 966, dtype: int64

/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:

model prediction: [[2 2]]
the match is:  home_team                England
away_team                 France
home_total_points        1755.52
home_rank_change             1.0
home_previous_points     1755.52
home_conf                   UEFA
away_total_points        1786.15
away_rank_change             0.0
away_previous_points     1786.15
away_conf                   UEFA
hour                          19
rank_diff                    2.0
points_diff               -30.63
age_diff               -1.181818
Name: 967, dtype: object home_team_goals    2
away_team_goals    1
Name: 967, dtype: int64
model prediction: [[2 2]]
the match is:  home_team                 France
away_team                Morocco
home_total_points        1786.15
home_rank_change             0.0
home_previous_points     1786.15
home_conf                   UEFA
away_total_points        1547.42
away_rank_change            -4.0
away_previous_points     1529.93
away_conf                    CAF
hour                          19
rank_diff                  -21.0
points_diff               238.73
age_diff                0.181818
Name: 974, dtype: object home_team_goals    2
away_team_goals    0
Name: 974, dtype: int64
model prediction: [[2 2]]
the match is:  home_team               Argentina
away_team                  France
home_total_points         1766.99
home_rank_change             -1.0
home_previous_points      1750.51
home_conf                CONMEBOL
away_total_points         1786.15
away_rank_change              0.0
away_previous_points      1786.15
away_conf                    UEFA
hour                           15
rank_diff                     1.0
points_diff                -19.16
age_diff                 0.272727
Name: 977, dtype: object home_team_goals    2
away_team_goals    4
Name: 977, dtype: int64
model prediction: [[2 1]]
the match is:  home_team               Croatia
away_team                France
home_total_points       1620.74
home_rank_change            0.0
home_previous_points    1620.74
home_conf                  UEFA
away_total_points       1786.15
away_rank_change            0.0
away_previous_points    1786.15
away_conf                  UEFA
hour                         18
rank_diff                  12.0
points_diff             -165.41
age_diff                    3.0
Name: 982, dtype: object home_team_goals    1
away_team_goals    1
Name: 982, dtype: int64
model prediction: [[2 2]]
the match is:  home_team                 France
away_team                Croatia
home_total_points        1786.15
home_rank_change             0.0
home_previous_points     1786.15
home_conf                   UEFA
away_total_points        1620.74
away_rank_change             0.0
away_previous_points     1620.74
away_conf                   UEFA
hour                          18
rank_diff                  -12.0
points_diff               165.41
age_diff               -1.090909
Name: 983, dtype: object home_team_goals    0
away_team_goals    1
Name: 983, dtype: int64
model prediction: [[3 2]]
the match is:  home_team                 France
away_team                 Poland
home_total_points        1786.15
home_rank_change             0.0
home_previous_points     1786.15
home_conf                   UEFA
away_total_points        1530.62
away_rank_change             1.0
away_previous_points     1530.62
away_conf                   UEFA
hour                          15
rank_diff                  -25.0
points_diff               255.53
age_diff               -0.363636
Name: 987, dtype: object home_team_goals    3
away_team_goals    1
Name: 987, dtype: int64
model prediction: [[2 1]]
the match is:  home_team               Indonesia
away_team                 Curaçao
home_total_points         1001.61
home_rank_change             -4.0
home_previous_points       992.31
home_conf                     AFC
away_total_points         1298.39
away_rank_change              0.0
away_previous_points      1298.39
away_conf                CONCACAF
hour                           13
rank_diff                    80.0
points_diff               -296.78
age_diff                     -2.0
Name: 1001, dtype: object home_team_goals    3
away_team_goals    2
Name: 1001, dtype: int64

/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:

model prediction: [[2 1]]
the match is:  home_team               Indonesia
away_team                 Curaçao
home_total_points         1001.61
home_rank_change             -4.0
home_previous_points       992.31
home_conf                     AFC
away_total_points         1298.39
away_rank_change              0.0
away_previous_points      1298.39
away_conf                CONCACAF
hour                           13
rank_diff                    80.0
points_diff               -296.78
age_diff                -4.181818
Name: 1002, dtype: object home_team_goals    2
away_team_goals    1
Name: 1002, dtype: int64
model prediction: [[2 1]]
the match is:  home_team                Curaçao
away_team               Honduras
home_total_points        1298.39
home_rank_change             0.0
home_previous_points     1298.39
home_conf               CONCACAF
away_total_points        1303.96
away_rank_change             2.0
away_previous_points     1332.16
away_conf               CONCACAF
hour                           0
rank_diff                    2.0
points_diff                -5.57
age_diff                3.636364
Name: 1005, dtype: object home_team_goals    0
away_team_goals    1
Name: 1005, dtype: int64
model prediction: [[2 1]]
the match is:  home_team               Honduras
away_team                Curaçao
home_total_points        1303.96
home_rank_change             2.0
home_previous_points     1332.16
home_conf               CONCACAF
away_total_points        1298.39
away_rank_change             0.0
away_previous_points     1298.39
away_conf               CONCACAF
hour                           2
rank_diff                   -2.0
points_diff                 5.57
age_diff               -3.181818
Name: 1006, dtype: object home_team_goals    1
away_team_goals    2
Name: 1006, dtype: int64
model prediction: [[2 1]]
the match is:  home_team                Curaçao
away_team                  Aruba
home_total_points        1298.39
home_rank_change             0.0
home_previous_points     1298.39
home_conf               CONCACAF
away_total_points         859.97
away_rank_change             0.0
away_previous_points      859.97
away_conf               CONCACAF
hour                           1
rank_diff                 -120.0
points_diff               438.42
age_diff               -0.393939
Name: 1019, dtype: object home_team_goals    5
away_team_goals    3
Name: 1019, dtype: int64
model prediction: [[5 1]]
the match is:  home_team                Curaçao
away_team               Suriname
home_total_points        1298.39
home_rank_change             0.0
home_previous_points     1298.39
home_conf               CONCACAF
away_total_points        1077.57
away_rank_change             1.0
away_previous_points     1077.57
away_conf               CONCACAF
hour                           1
rank_diff                  -60.0
points_diff               220.82
age_diff                1.636364
Name: 1022, dtype: object home_team_goals    6
away_team_goals    5
Name: 1022, dtype: int64
model prediction: [[2 1]]
the match is:  home_team                Hungary
away_team                England
home_total_points        1465.62
home_rank_change             2.0
home_previous_points     1465.62
home_conf                   UEFA
away_total_points        1755.52
away_rank_change             1.0
away_previous_points     1755.52
away_conf                   UEFA
hour                          16
rank_diff                   36.0
points_diff               -289.9
age_diff                1.909091
Name: 1025, dtype: object home_team_goals    0
away_team_goals    1
Name: 1025, dtype: int64
model prediction: [[2 1]]
the match is:  home_team                England
away_team                Hungary
home_total_points        1755.52
home_rank_change             1.0
home_previous_points     1755.52
home_conf                   UEFA
away_total_points        1465.62
away_rank_change             2.0
away_previous_points     1465.62
away_conf                   UEFA
hour                          18
rank_diff                  -36.0
points_diff                289.9
age_diff               -2.727273
Name: 1026, dtype: object home_team_goals    0
away_team_goals    4
Name: 1026, dtype: int64
model prediction: [[2 1]]
the match is:  home_team                England
away_team                  Italy
home_total_points        1755.52
home_rank_change             1.0
home_previous_points     1755.52
home_conf                   UEFA
away_total_points        1740.77
away_rank_change             0.0
away_previous_points     1740.77
away_conf                   UEFA
hour                          18
rank_diff                   -1.0
points_diff                14.75
age_diff                0.818182
Name: 1031, dtype: object home_team_goals    0
away_team_goals    0
Name: 1031, dtype: int64
model prediction: [[2 2]]
the match is:  home_team                 Italy
away_team               England
home_total_points       1740.77
home_rank_change            0.0
home_previous_points    1740.77
home_conf                  UEFA
away_total_points       1755.52
away_rank_change            1.0
away_previous_points    1755.52
away_conf                  UEFA
hour                         18
rank_diff                   1.0
points_diff              -14.75
age_diff                    2.0
Name: 1032, dtype: object home_team_goals    0
away_team_goals    1
Name: 1032, dtype: int64

/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:

model prediction: [[3 2]]
the match is:  home_team                  Wales
away_team                England
home_total_points        1578.01
home_rank_change             1.0
home_previous_points     1578.01
home_conf                   UEFA
away_total_points        1755.52
away_rank_change             1.0
away_previous_points     1755.52
away_conf                   UEFA
hour                          19
rank_diff                   15.0
points_diff              -177.51
age_diff                0.818182
Name: 1044, dtype: object home_team_goals    3
away_team_goals    0
Name: 1044, dtype: int64
model prediction: [[3 2]]
the match is:  home_team                   England
away_team               Switzerland
home_total_points           1755.52
home_rank_change                1.0
home_previous_points        1755.52
home_conf                      UEFA
away_total_points           1642.83
away_rank_change                1.0
away_previous_points        1642.83
away_conf                      UEFA
hour                             17
rank_diff                      -9.0
points_diff                  112.69
age_diff                  -3.090909
Name: 1053, dtype: object home_team_goals    2
away_team_goals    1
Name: 1053, dtype: int64
model prediction: [[2 2]]
the match is:  home_team                 Guyana
away_team                  Haiti
home_total_points         958.87
home_rank_change            -1.0
home_previous_points      958.87
home_conf               CONCACAF
away_total_points        1268.05
away_rank_change             0.0
away_previous_points     1268.05
away_conf               CONCACAF
hour                          20
rank_diff                   88.0
points_diff              -309.18
age_diff                0.727273
Name: 1070, dtype: object home_team_goals    2
away_team_goals    6
Name: 1070, dtype: int64
model prediction: [[2 4]]
the match is:  home_team                  Haiti
away_team                 Guyana
home_total_points        1268.05
home_rank_change             0.0
home_previous_points     1268.05
home_conf               CONCACAF
away_total_points         958.87
away_rank_change            -1.0
away_previous_points      958.87
away_conf               CONCACAF
hour                          22
rank_diff                  -88.0
points_diff               309.18
age_diff               -0.272727
Name: 1071, dtype: object home_team_goals    6
away_team_goals    0
Name: 1071, dtype: int64

/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:

model prediction: [[4 2]]
the match is:  home_team                    Haiti
away_team               Montserrat
home_total_points          1268.05
home_rank_change               0.0
home_previous_points       1268.05
home_conf                 CONCACAF
away_total_points           950.71
away_rank_change               0.0
away_previous_points        950.71
away_conf                 CONCACAF
hour                            21
rank_diff                    -91.0
points_diff                 317.34
age_diff                      -3.0
Name: 1079, dtype: object home_team_goals    3
away_team_goals    2
Name: 1079, dtype: int64
model prediction: [[5 1]]
the match is:  home_team                Bermuda
away_team                  Haiti
home_total_points         982.43
home_rank_change             0.0
home_previous_points      982.43
home_conf               CONCACAF
away_total_points        1268.05
away_rank_change             0.0
away_previous_points     1268.05
away_conf               CONCACAF
hour                          21
rank_diff                   79.0
points_diff              -285.62
age_diff               -0.181818
Name: 1081, dtype: object home_team_goals    0
away_team_goals    0
Name: 1081, dtype: int64
model prediction: [[2 4]]
the match is:  home_team               Guatemala
away_team                   Haiti
home_total_points          1138.4
home_rank_change              1.0
home_previous_points       1138.4
home_conf                CONCACAF
away_total_points         1268.05
away_rank_change              0.0
away_previous_points      1268.05
away_conf                CONCACAF
hour                           20
rank_diff                    36.0
points_diff               -129.65
age_diff                 2.363636
Name: 1086, dtype: object home_team_goals    2
away_team_goals    1
Name: 1086, dtype: int64
model prediction: [[2 2]]
the match is:  home_team                  Costa Rica
away_team               United States
home_total_points             1464.06
home_rank_change                 -7.0
home_previous_points          1437.43
home_conf                    CONCACAF
away_total_points             1643.34
away_rank_change                  2.0
away_previous_points          1648.51
away_conf                    CONCACAF
hour                                1
rank_diff                        29.0
points_diff                   -179.28
age_diff                    -0.636364
Name: 1095, dtype: object home_team_goals    2
away_team_goals    0
Name: 1095, dtype: int64
model prediction: [[2 2]]
the match is:  home_team                     England
away_team               United States
home_total_points             1755.52
home_rank_change                  1.0
home_previous_points          1755.52
home_conf                        UEFA
away_total_points             1643.34
away_rank_change                  2.0
away_previous_points          1648.51
away_conf                    CONCACAF
hour                               19
rank_diff                        -8.0
points_diff                    112.18
age_diff                          1.0
Name: 1097, dtype: object home_team_goals    0
away_team_goals    0
Name: 1097, dtype: int64
model prediction: [[3 2]]
the match is:  home_team                Saudi Arabia
away_team               United States
home_total_points             1433.95
home_rank_change                  2.0
home_previous_points          1434.71
home_conf                         AFC
away_total_points             1643.34
away_rank_change                  2.0
away_previous_points          1648.51
away_conf                    CONCACAF
hour                               18
rank_diff                        40.0
points_diff                   -209.39
age_diff                     1.272727
Name: 1104, dtype: object home_team_goals    0
away_team_goals    0
Name: 1104, dtype: int64
model prediction: [[1 2]]
the match is:  home_team                 Netherlands
away_team               United States
home_total_points             1653.73
home_rank_change                  0.0
home_previous_points          1653.73
home_conf                        UEFA
away_total_points             1643.34
away_rank_change                  2.0
away_previous_points          1648.51
away_conf                    CONCACAF
hour                               15
rank_diff                        -3.0
points_diff                     10.39
age_diff                     2.454545
Name: 1108, dtype: object home_team_goals    3
away_team_goals    1
Name: 1108, dtype: int64
model prediction: [[2 2]]
the match is:  home_team               United States
away_team                      Panama
home_total_points             1643.34
home_rank_change                  2.0
home_previous_points          1648.51
home_conf                    CONCACAF
away_total_points             1375.56
away_rank_change                  0.0
away_previous_points          1379.34
away_conf                    CONCACAF
hour                               23
rank_diff                       -50.0
points_diff                    267.78
age_diff                    -4.181818
Name: 1114, dtype: object home_team_goals    5
away_team_goals    1
Name: 1114, dtype: int64

/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:

model prediction: [[2 2]]
the match is:  home_team                        Iran
away_team               United States
home_total_points             1572.89
home_rank_change                  0.0
home_previous_points          1557.58
home_conf                         AFC
away_total_points             1643.34
away_rank_change                  2.0
away_previous_points          1648.51
away_conf                    CONCACAF
hour                               19
rank_diff                         8.0
points_diff                    -70.45
age_diff                     4.272727
Name: 1116, dtype: object home_team_goals    0
away_team_goals    1
Name: 1116, dtype: int64
model prediction: [[2 2]]
the match is:  home_team               United States
away_team                     Grenada
home_total_points             1643.34
home_rank_change                  2.0
home_previous_points          1648.51
home_conf                    CONCACAF
away_total_points              974.03
away_rank_change                  1.0
away_previous_points           974.03
away_conf                    CONCACAF
hour                                2
rank_diff                      -156.0
points_diff                    669.31
age_diff                     0.272727
Name: 1119, dtype: object home_team_goals    5
away_team_goals    0
Name: 1119, dtype: int64
model prediction: [[4 1]]
the match is:  home_team               United States
away_team                     Morocco
home_total_points             1643.34
home_rank_change                  2.0
home_previous_points          1648.51
home_conf                    CONCACAF
away_total_points             1547.42
away_rank_change                 -4.0
away_previous_points          1529.93
away_conf                         CAF
hour                               23
rank_diff                       -11.0
points_diff                     95.92
age_diff                    -3.363636
Name: 1120, dtype: object home_team_goals    3
away_team_goals    0
Name: 1120, dtype: int64
model prediction: [[1 2]]
the match is:  home_team               United States
away_team                     Uruguay
home_total_points             1643.34
home_rank_change                  2.0
home_previous_points          1648.51
home_conf                    CONCACAF
away_total_points             1614.05
away_rank_change                 -1.0
away_previous_points          1596.66
away_conf                    CONMEBOL
hour                               21
rank_diff                        -3.0
points_diff                     29.29
age_diff                    -3.363636
Name: 1124, dtype: object home_team_goals    0
away_team_goals    0
Name: 1124, dtype: int64
model prediction: [[1 3]]
the match is:  home_team               United States
away_team                       Wales
home_total_points             1643.34
home_rank_change                  2.0
home_previous_points          1648.51
home_conf                    CONCACAF
away_total_points             1578.01
away_rank_change                  1.0
away_previous_points          1578.01
away_conf                        UEFA
hour                               19
rank_diff                        -7.0
points_diff                     65.33
age_diff                    -2.272727
Name: 1125, dtype: object home_team_goals    1
away_team_goals    1
Name: 1125, dtype: int64
model prediction: [[2 2]]
the match is:  home_team                 El Salvador
away_team               United States
home_total_points             1346.04
home_rank_change                  0.0
home_previous_points          1349.47
home_conf                    CONCACAF
away_total_points             1643.34
away_rank_change                  2.0
away_previous_points          1648.51
away_conf                    CONCACAF
hour                                2
rank_diff                        57.0
points_diff                    -297.3
age_diff                          3.0
Name: 1129, dtype: object home_team_goals    1
away_team_goals    1
Name: 1129, dtype: int64
model prediction: [[1 1]]
the match is:  home_team                       Japan
away_team               United States
home_total_points             1549.82
home_rank_change                 -3.0
home_previous_points          1531.53
home_conf                         AFC
away_total_points             1643.34
away_rank_change                  2.0
away_previous_points          1648.51
away_conf                    CONCACAF
hour                               12
rank_diff                        10.0
points_diff                    -93.52
age_diff                     3.454545
Name: 1133, dtype: object home_team_goals    2
away_team_goals    0
Name: 1133, dtype: int64
model prediction: [[2 2]]
the match is:  home_team                   Panama
away_team               Costa Rica
home_total_points          1375.56
home_rank_change               0.0
home_previous_points       1379.34
home_conf                 CONCACAF
away_total_points          1464.06
away_rank_change              -7.0
away_previous_points       1437.43
away_conf                 CONCACAF
hour                            23
rank_diff                     21.0
points_diff                  -88.5
age_diff                  2.545455
Name: 1145, dtype: object home_team_goals    2
away_team_goals    0
Name: 1145, dtype: int64
model prediction: [[2 2]]
the match is:  home_team                 Panama
away_team               Honduras
home_total_points        1375.56
home_rank_change             0.0
home_previous_points     1379.34
home_conf               CONCACAF
away_total_points        1303.96
away_rank_change             2.0
away_previous_points     1332.16
away_conf               CONCACAF
hour                           1
rank_diff                  -15.0
points_diff                 71.6
age_diff                     1.0
Name: 1157, dtype: object home_team_goals    1
away_team_goals    1
Name: 1157, dtype: int64
model prediction: [[2 1]]
the match is:  home_team               Cameroon
away_team                 Panama
home_total_points        1480.82
home_rank_change           -12.0
home_previous_points     1437.35
home_conf                    CAF
away_total_points        1375.56
away_rank_change             0.0
away_previous_points     1379.34
away_conf               CONCACAF
hour                          10
rank_diff                  -25.0
points_diff               105.26
age_diff                0.818182
Name: 1163, dtype: object home_team_goals    1
away_team_goals    1
Name: 1163, dtype: int64
model prediction: [[3 1]]
the match is:  home_team               Venezuela
away_team                  Panama
home_total_points         1411.45
home_rank_change             -1.0
home_previous_points      1409.14
home_conf                CONMEBOL
away_total_points         1375.56
away_rank_change              0.0
away_previous_points      1379.34
away_conf                CONCACAF
hour                           17
rank_diff                    -5.0
points_diff                 35.89
age_diff                      0.0
Name: 1177, dtype: object home_team_goals    2
away_team_goals    2
Name: 1177, dtype: int64
model prediction: [[2 1]]
the match is:  home_team               Indonesia
away_team                  Jordan
home_total_points         1001.61
home_rank_change             -4.0
home_previous_points       992.31
home_conf                     AFC
away_total_points         1259.84
away_rank_change              0.0
away_previous_points      1255.69
away_conf                     AFC
hour                           19
rank_diff                    70.0
points_diff               -258.23
age_diff                -3.454545
Name: 1190, dtype: object home_team_goals    1
away_team_goals    0
Name: 1190, dtype: int64
model prediction: [[2 1]]
the match is:  home_team                 Jordan
away_team                   Oman
home_total_points        1259.84
home_rank_change             0.0
home_previous_points     1255.69
home_conf                    AFC
away_total_points         1301.0
away_rank_change             0.0
away_previous_points     1306.01
away_conf                    AFC
hour                          18
rank_diff                   11.0
points_diff               -41.16
age_diff               -0.545455
Name: 1197, dtype: object home_team_goals    1
away_team_goals    0
Name: 1197, dtype: int64
model prediction: [[2 1]]
the match is:  home_team                  India
away_team                 Jordan
home_total_points        1182.75
home_rank_change             0.0
home_previous_points     1182.75
home_conf                    AFC
away_total_points        1259.84
away_rank_change             0.0
away_previous_points     1255.69
away_conf                    AFC
hour                          16
rank_diff                   14.0
points_diff               -77.09
age_diff               -0.636364
Name: 1201, dtype: object home_team_goals    2
away_team_goals    0
Name: 1201, dtype: int64

/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:

model prediction: [[2 1]]
the match is:  home_team                 Jordan
away_team                  Syria
home_total_points        1259.84
home_rank_change             0.0
home_previous_points     1255.69
home_conf                    AFC
away_total_points        1251.22
away_rank_change             5.0
away_previous_points     1268.54
away_conf                    AFC
hour                          18
rank_diff                   -1.0
points_diff                 8.62
age_diff                5.363636
Name: 1203, dtype: object home_team_goals    2
away_team_goals    0
Name: 1203, dtype: int64
model prediction: [[2 1]]
the match is:  home_team                 Kuwait
away_team                 Jordan
home_total_points        1065.56
home_rank_change             1.0
home_previous_points     1064.02
home_conf                    AFC
away_total_points        1259.84
away_rank_change             0.0
away_previous_points     1255.69
away_conf                    AFC
hour                          16
rank_diff                   53.0
points_diff              -194.28
age_diff                0.818182
Name: 1207, dtype: object home_team_goals    3
away_team_goals    0
Name: 1207, dtype: int64
model prediction: [[2 1]]
the match is:  home_team                 Jordan
away_team                  Nepal
home_total_points        1259.84
home_rank_change             0.0
home_previous_points     1255.69
home_conf                    AFC
away_total_points         982.22
away_rank_change            -2.0
away_previous_points      972.45
away_conf                    AFC
hour                          19
rank_diff                  -77.0
points_diff               277.62
age_diff                3.727273
Name: 1208, dtype: object home_team_goals    2
away_team_goals    0
Name: 1208, dtype: int64
model prediction: [[4 1]]
the match is:  home_team               Denmark
away_team               Croatia
home_total_points       1654.54
home_rank_change            0.0
home_previous_points    1654.54
home_conf                  UEFA
away_total_points       1620.74
away_rank_change            0.0
away_previous_points    1620.74
away_conf                  UEFA
hour                         18
rank_diff                  -6.0
points_diff                33.8
age_diff                    1.0
Name: 1215, dtype: object home_team_goals    1
away_team_goals    0
Name: 1215, dtype: int64
model prediction: [[2 2]]
the match is:  home_team                Croatia
away_team                Denmark
home_total_points        1620.74
home_rank_change             0.0
home_previous_points     1620.74
home_conf                   UEFA
away_total_points        1654.54
away_rank_change             0.0
away_previous_points     1654.54
away_conf                   UEFA
hour                          18
rank_diff                    6.0
points_diff                -33.8
age_diff               -1.363636
Name: 1216, dtype: object home_team_goals    2
away_team_goals    1
Name: 1216, dtype: int64
model prediction: [[2 2]]
the match is:  home_team                Croatia
away_team                 Canada
home_total_points        1620.74
home_rank_change             0.0
home_previous_points     1620.74
home_conf                   UEFA
away_total_points        1497.82
away_rank_change            -7.0
away_previous_points     1462.32
away_conf               CONCACAF
hour                          16
rank_diff                  -18.0
points_diff               122.92
age_diff                1.272727
Name: 1219, dtype: object home_team_goals    4
away_team_goals    1
Name: 1219, dtype: int64
model prediction: [[2 1]]
the match is:  home_team                Croatia
away_team               Slovenia
home_total_points        1620.74
home_rank_change             0.0
home_previous_points     1620.74
home_conf                   UEFA
away_total_points        1375.42
away_rank_change            -1.0
away_previous_points     1375.42
away_conf                   UEFA
hour                          14
rank_diff                  -49.0
points_diff               245.32
age_diff                1.181818
Name: 1220, dtype: object home_team_goals    1
away_team_goals    1
Name: 1220, dtype: int64
model prediction: [[3 1]]
the match is:  home_team                Croatia
away_team               Bulgaria
home_total_points        1620.74
home_rank_change             0.0
home_previous_points     1620.74
home_conf                   UEFA
away_total_points        1345.47
away_rank_change             0.0
away_previous_points     1345.47
away_conf                   UEFA
hour                          14
rank_diff                  -56.0
points_diff               275.27
age_diff                2.272727
Name: 1230, dtype: object home_team_goals    2
away_team_goals    1
Name: 1230, dtype: int64
model prediction: [[3 1]]
the match is:  home_team               Colombia
away_team                Bolivia
home_total_points        1585.89
home_rank_change             3.0
home_previous_points     1607.15
home_conf               CONMEBOL
away_total_points        1308.12
away_rank_change            -1.0
away_previous_points     1324.21
away_conf               CONMEBOL
hour                          23
rank_diff                  -57.0
points_diff               277.77
age_diff                4.545455
Name: 1251, dtype: object home_team_goals    3
away_team_goals    0
Name: 1251, dtype: int64
model prediction: [[3 1]]
the match is:  home_team                 Mexico
away_team               Colombia
home_total_points         1647.9
home_rank_change            -2.0
home_previous_points      1638.3
home_conf               CONCACAF
away_total_points        1585.89
away_rank_change             3.0
away_previous_points     1607.15
away_conf               CONMEBOL
hour                           2
rank_diff                   -7.0
points_diff                62.01
age_diff               -0.545455
Name: 1254, dtype: object home_team_goals    3
away_team_goals    2
Name: 1254, dtype: int64
model prediction: [[2 2]]
the match is:  home_team                Colombia
away_team               Guatemala
home_total_points         1585.89
home_rank_change              3.0
home_previous_points      1607.15
home_conf                CONMEBOL
away_total_points          1138.4
away_rank_change              1.0
away_previous_points       1138.4
away_conf                CONCACAF
hour                           23
rank_diff                  -104.0
points_diff                447.49
age_diff                 1.636364
Name: 1255, dtype: object home_team_goals    4
away_team_goals    1
Name: 1255, dtype: int64

/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:

model prediction: [[3 1]]
the match is:  home_team               Venezuela
away_team                Colombia
home_total_points         1411.45
home_rank_change             -1.0
home_previous_points      1409.14
home_conf                CONMEBOL
away_total_points         1585.89
away_rank_change              3.0
away_previous_points      1607.15
away_conf                CONMEBOL
hour                           23
rank_diff                    39.0
points_diff               -174.44
age_diff                -0.545455
Name: 1260, dtype: object home_team_goals    1
away_team_goals    0
Name: 1260, dtype: int64
model prediction: [[3 2]]
the match is:  home_team                   Iraq
away_team                 Zambia
home_total_points        1325.44
home_rank_change            -1.0
home_previous_points     1333.03
home_conf                    AFC
away_total_points        1264.64
away_rank_change             0.0
away_previous_points     1264.64
away_conf                    CAF
hour                          17
rank_diff                  -14.0
points_diff                 60.8
age_diff                2.909091
Name: 1281, dtype: object home_team_goals    3
away_team_goals    1
Name: 1281, dtype: int64
model prediction: [[3 1]]
the match is:  home_team                   Iraq
away_team                   Oman
home_total_points        1325.44
home_rank_change            -1.0
home_previous_points     1333.03
home_conf                    AFC
away_total_points         1301.0
away_rank_change             0.0
away_previous_points     1306.01
away_conf                    AFC
hour                          15
rank_diff                   -5.0
points_diff                24.44
age_diff               -1.636364
Name: 1287, dtype: object home_team_goals    3
away_team_goals    4
Name: 1287, dtype: int64
model prediction: [[2 1]]
the match is:  home_team                 Mexico
away_team                   Iraq
home_total_points         1647.9
home_rank_change            -2.0
home_previous_points      1638.3
home_conf               CONCACAF
away_total_points        1325.44
away_rank_change            -1.0
away_previous_points     1333.03
away_conf                    AFC
hour                          20
rank_diff                  -62.0
points_diff               322.46
age_diff                3.363636
Name: 1289, dtype: object home_team_goals    0
away_team_goals    4
Name: 1289, dtype: int64
model prediction: [[3 1]]
the match is:  home_team                  Syria
away_team                   Iraq
home_total_points        1251.22
home_rank_change             5.0
home_previous_points     1268.54
home_conf                    AFC
away_total_points        1325.44
away_rank_change            -1.0
away_previous_points     1333.03
away_conf                    AFC
hour                          13
rank_diff                   17.0
points_diff               -74.22
age_diff                0.727273
Name: 1292, dtype: object home_team_goals    1
away_team_goals    1
Name: 1292, dtype: int64
model prediction: [[2 1]]
the match is:  home_team                   Iraq
away_team                 Kuwait
home_total_points        1325.44
home_rank_change            -1.0
home_previous_points     1333.03
home_conf                    AFC
away_total_points        1065.56
away_rank_change             1.0
away_previous_points     1064.02
away_conf                    AFC
hour                          12
rank_diff                  -69.0
points_diff               259.88
age_diff               -0.636364
Name: 1295, dtype: object home_team_goals    1
away_team_goals    0
Name: 1295, dtype: int64
model prediction: [[2 1]]
the match is:  home_team               Portugal
away_team                  Ghana
home_total_points        1660.25
home_rank_change             0.0
home_previous_points     1660.25
home_conf                   UEFA
away_total_points        1381.45
away_rank_change             9.0
away_previous_points     1428.97
away_conf                    CAF
hour                          16
rank_diff                  -53.0
points_diff                278.8
age_diff                1.363636
Name: 1306, dtype: object home_team_goals    3
away_team_goals    2
Name: 1306, dtype: int64
model prediction: [[3 1]]
the match is:  home_team                      Portugal
away_team               North Macedonia
home_total_points               1660.25
home_rank_change                    0.0
home_previous_points            1660.25
home_conf                          UEFA
away_total_points               1367.23
away_rank_change                    0.0
away_previous_points            1367.23
away_conf                          UEFA
hour                                 18
rank_diff                         -59.0
points_diff                      293.02
age_diff                       1.636364
Name: 1313, dtype: object home_team_goals    2
away_team_goals    0
Name: 1313, dtype: int64
model prediction: [[3 1]]
the match is:  home_team               South Korea
away_team                  Portugal
home_total_points           1522.85
home_rank_change               -4.0
home_previous_points        1507.24
home_conf                       AFC
away_total_points           1660.25
away_rank_change                0.0
away_previous_points        1660.25
away_conf                      UEFA
hour                             15
rank_diff                      21.0
points_diff                  -137.4
age_diff                   1.636364
Name: 1314, dtype: object home_team_goals    1
away_team_goals    2
Name: 1314, dtype: int64
model prediction: [[2 3]]
the match is:  home_team                Morocco
away_team               Portugal
home_total_points        1547.42
home_rank_change            -4.0
home_previous_points     1529.93
home_conf                    CAF
away_total_points        1660.25
away_rank_change             0.0
away_previous_points     1660.25
away_conf                   UEFA
hour                          15
rank_diff                   16.0
points_diff              -112.83
age_diff                0.909091
Name: 1318, dtype: object home_team_goals    0
away_team_goals    1
Name: 1318, dtype: int64
model prediction: [[2 2]]
the match is:  home_team               Portugal
away_team                Nigeria
home_total_points        1660.25
home_rank_change             0.0
home_previous_points     1660.25
home_conf                   UEFA
away_total_points        1509.91
away_rank_change            -4.0
away_previous_points     1478.78
away_conf                    CAF
hour                          18
rank_diff                  -24.0
points_diff               150.34
age_diff                0.272727
Name: 1322, dtype: object home_team_goals    4
away_team_goals    0
Name: 1322, dtype: int64
model prediction: [[3 2]]
the match is:  home_team                  Portugal
away_team               Switzerland
home_total_points           1660.25
home_rank_change                0.0
home_previous_points        1660.25
home_conf                      UEFA
away_total_points           1642.83
away_rank_change                1.0
away_previous_points        1642.83
away_conf                      UEFA
hour                             19
rank_diff                      -6.0
points_diff                   17.42
age_diff                  -1.545455
Name: 1329, dtype: object home_team_goals    6
away_team_goals    1
Name: 1329, dtype: int64
model prediction: [[3 3]]
the match is:  home_team                  Portugal
away_team               Switzerland
home_total_points           1660.25
home_rank_change                0.0
home_previous_points        1660.25
home_conf                      UEFA
away_total_points           1642.83
away_rank_change                1.0
away_previous_points        1642.83
away_conf                      UEFA
hour                             18
rank_diff                      -6.0
points_diff                   17.42
age_diff                   0.727273
Name: 1330, dtype: object home_team_goals    4
away_team_goals    0
Name: 1330, dtype: int64
model prediction: [[3 2]]
the match is:  home_team               Switzerland
away_team                  Portugal
home_total_points           1642.83
home_rank_change                1.0
home_previous_points        1642.83
home_conf                      UEFA
away_total_points           1660.25
away_rank_change                0.0
away_previous_points        1660.25
away_conf                      UEFA
hour                             18
rank_diff                       6.0
points_diff                  -17.42
age_diff                   0.636364
Name: 1331, dtype: object home_team_goals    0
away_team_goals    1
Name: 1331, dtype: int64
model prediction: [[2 2]]
the match is:  home_team                 Jamaica
away_team               Argentina
home_total_points         1378.62
home_rank_change              5.0
home_previous_points      1412.13
home_conf                CONCACAF
away_total_points         1766.99
away_rank_change             -1.0
away_previous_points      1750.51
away_conf                CONMEBOL
hour                            0
rank_diff                    58.0
points_diff               -388.37
age_diff                 1.454545
Name: 1374, dtype: object home_team_goals    3
away_team_goals    0
Name: 1374, dtype: int64
model prediction: [[2 2]]
the match is:  home_team                   Italy
away_team               Argentina
home_total_points         1740.77
home_rank_change              0.0
home_previous_points      1740.77
home_conf                    UEFA
away_total_points         1766.99
away_rank_change             -1.0
away_previous_points      1750.51
away_conf                CONMEBOL
hour                           18
rank_diff                     2.0
points_diff                -26.22
age_diff                -0.454545
Name: 1375, dtype: object home_team_goals    3
away_team_goals    0
Name: 1375, dtype: int64
model prediction: [[2 1]]
the match is:  home_team               Argentina
away_team                Honduras
home_total_points         1766.99
home_rank_change             -1.0
home_previous_points      1750.51
home_conf                CONMEBOL
away_total_points         1303.96
away_rank_change              2.0
away_previous_points      1332.16
away_conf                CONCACAF
hour                            0
rank_diff                   -74.0
points_diff                463.03
age_diff                 0.909091
Name: 1382, dtype: object home_team_goals    3
away_team_goals    0
Name: 1382, dtype: int64
model prediction: [[3 1]]
the match is:  home_team               Argentina
away_team                 Estonia
home_total_points         1766.99
home_rank_change             -1.0
home_previous_points      1750.51
home_conf                CONMEBOL
away_total_points          1176.5
away_rank_change             -1.0
away_previous_points       1176.5
away_conf                    UEFA
hour                           18
rank_diff                  -102.0
points_diff                590.49
age_diff                 2.454545
Name: 1383, dtype: object home_team_goals    5
away_team_goals    0
Name: 1383, dtype: int64
model prediction: [[4 1]]
the match is:  home_team               Argentina
away_team                  Mexico
home_total_points         1766.99
home_rank_change             -1.0
home_previous_points      1750.51
home_conf                CONMEBOL
away_total_points          1647.9
away_rank_change             -2.0
away_previous_points       1638.3
away_conf                CONCACAF
hour                           19
rank_diff                    -8.0
points_diff                119.09
age_diff                -0.545455
Name: 1388, dtype: object home_team_goals    2
away_team_goals    0
Name: 1388, dtype: int64
model prediction: [[2 2]]
the match is:  home_team               Argentina
away_team                 Croatia
home_total_points         1766.99
home_rank_change             -1.0
home_previous_points      1750.51
home_conf                CONMEBOL
away_total_points         1620.74
away_rank_change              0.0
away_previous_points      1620.74
away_conf                    UEFA
hour                           19
rank_diff                   -11.0
points_diff                146.25
age_diff                -1.545455
Name: 1392, dtype: object home_team_goals    3
away_team_goals    0
Name: 1392, dtype: int64
model prediction: [[3 2]]
the match is:  home_team                  Poland
away_team               Argentina
home_total_points         1530.62
home_rank_change              1.0
home_previous_points      1530.62
home_conf                    UEFA
away_total_points         1766.99
away_rank_change             -1.0
away_previous_points      1750.51
away_conf                CONMEBOL
hour                           19
rank_diff                    24.0
points_diff               -236.37
age_diff                 0.545455
Name: 1393, dtype: object home_team_goals    2
away_team_goals    0
Name: 1393, dtype: int64

/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:

model prediction: [[2 1]]
the match is:  home_team               Argentina
away_team               Venezuela
home_total_points         1766.99
home_rank_change             -1.0
home_previous_points      1750.51
home_conf                CONMEBOL
away_total_points         1411.45
away_rank_change             -1.0
away_previous_points      1409.14
away_conf                CONMEBOL
hour                           23
rank_diff                   -54.0
points_diff                355.54
age_diff                 2.636364
Name: 1397, dtype: object home_team_goals    3
away_team_goals    0
Name: 1397, dtype: int64
model prediction: [[3 0]]
the match is:  home_team               Netherlands
away_team                     Qatar
home_total_points           1653.73
home_rank_change                0.0
home_previous_points        1653.73
home_conf                      UEFA
away_total_points           1437.91
away_rank_change                4.0
away_previous_points        1437.91
away_conf                       AFC
hour                             15
rank_diff                     -42.0
points_diff                  215.82
age_diff                  -1.181818
Name: 1412, dtype: object home_team_goals    2
away_team_goals    0
Name: 1412, dtype: int64
model prediction: [[2 1]]
the match is:  home_team                 Canada
away_team                  Qatar
home_total_points        1497.82
home_rank_change            -7.0
home_previous_points     1462.32
home_conf               CONCACAF
away_total_points        1437.91
away_rank_change             4.0
away_previous_points     1437.91
away_conf                    AFC
hour                          17
rank_diff                  -19.0
points_diff                59.91
age_diff               -0.181818
Name: 1413, dtype: object home_team_goals    2
away_team_goals    0
Name: 1413, dtype: int64
model prediction: [[2 2]]
the match is:  home_team                  Qatar
away_team               Slovenia
home_total_points        1437.91
home_rank_change             4.0
home_previous_points     1437.91
home_conf                    AFC
away_total_points        1375.42
away_rank_change            -1.0
away_previous_points     1375.42
away_conf                   UEFA
hour                          17
rank_diff                  -12.0
points_diff                62.49
age_diff                1.454545
Name: 1416, dtype: object home_team_goals    0
away_team_goals    0
Name: 1416, dtype: int64
model prediction: [[2 1]]
the match is:  home_team                  Qatar
away_team                  Chile
home_total_points        1437.91
home_rank_change             4.0
home_previous_points     1437.91
home_conf                    AFC
away_total_points        1543.16
away_rank_change             2.0
away_previous_points     1543.42
away_conf               CONMEBOL
hour                          17
rank_diff                   26.0
points_diff              -105.25
age_diff               -0.545455
Name: 1417, dtype: object home_team_goals    2
away_team_goals    2
Name: 1417, dtype: int64
model prediction: [[2 2]]
the match is:  home_team                  Qatar
away_team                Ecuador
home_total_points        1437.91
home_rank_change             4.0
home_previous_points     1437.91
home_conf                    AFC
away_total_points        1458.63
away_rank_change            -2.0
away_previous_points     1448.27
away_conf               CONMEBOL
hour                          16
rank_diff                    8.0
points_diff               -20.72
age_diff                3.454545
Name: 1433, dtype: object home_team_goals    0
away_team_goals    2
Name: 1433, dtype: int64
model prediction: [[1 1]]
the match is:  home_team                  Qatar
away_team               Bulgaria
home_total_points        1437.91
home_rank_change             4.0
home_previous_points     1437.91
home_conf                    AFC
away_total_points        1345.47
away_rank_change             0.0
away_previous_points     1345.47
away_conf                   UEFA
hour                          17
rank_diff                  -19.0
points_diff                92.44
age_diff               -0.818182
Name: 1439, dtype: object home_team_goals    2
away_team_goals    1
Name: 1439, dtype: int64
model prediction: [[3 1]]
the match is:  home_team                   Qatar
away_team               Guatemala
home_total_points         1437.91
home_rank_change              4.0
home_previous_points      1437.91
home_conf                     AFC
away_total_points          1138.4
away_rank_change              1.0
away_previous_points       1138.4
away_conf                CONCACAF
hour                           16
rank_diff                   -71.0
points_diff                299.51
age_diff                -7.545455
Name: 1440, dtype: object home_team_goals    2
away_team_goals    0
Name: 1440, dtype: int64
model prediction: [[2 1]]
the match is:  home_team                  Qatar
away_team                Senegal
home_total_points        1437.91
home_rank_change             4.0
home_previous_points     1437.91
home_conf                    AFC
away_total_points        1587.78
away_rank_change            -2.0
away_previous_points     1561.68
away_conf                    CAF
hour                          13
rank_diff                   34.0
points_diff              -149.87
age_diff                0.818182
Name: 1442, dtype: object home_team_goals    1
away_team_goals    3
Name: 1442, dtype: int64
model prediction: [[1 2]]
the match is:  home_team               Netherlands
away_team                   Denmark
home_total_points           1653.73
home_rank_change                0.0
home_previous_points        1653.73
home_conf                      UEFA
away_total_points           1654.54
away_rank_change                0.0
away_previous_points        1654.54
away_conf                      UEFA
hour                             19
rank_diff                       1.0
points_diff                   -0.81
age_diff                   0.363636
Name: 1459, dtype: object home_team_goals    4
away_team_goals    2
Name: 1459, dtype: int64
model prediction: [[2 2]]
the match is:  home_team                   Belgium
away_team               Netherlands
home_total_points           1828.45
home_rank_change                0.0
home_previous_points        1828.45
home_conf                      UEFA
away_total_points           1653.73
away_rank_change                0.0
away_previous_points        1653.73
away_conf                      UEFA
hour                             18
rank_diff                      -9.0
points_diff                  174.72
age_diff                   3.454545
Name: 1460, dtype: object home_team_goals    1
away_team_goals    4
Name: 1460, dtype: int64
model prediction: [[2 2]]
the match is:  home_team               Netherlands
away_team                   Belgium
home_total_points           1653.73
home_rank_change                0.0
home_previous_points        1653.73
home_conf                      UEFA
away_total_points           1828.45
away_rank_change                0.0
away_previous_points        1828.45
away_conf                      UEFA
hour                             18
rank_diff                       9.0
points_diff                 -174.72
age_diff                        0.0
Name: 1461, dtype: object home_team_goals    1
away_team_goals    0
Name: 1461, dtype: int64
model prediction: [[2 2]]
the match is:  home_team                     Wales
away_team               Netherlands
home_total_points           1578.01
home_rank_change                1.0
home_previous_points        1578.01
home_conf                      UEFA
away_total_points           1653.73
away_rank_change                0.0
away_previous_points        1653.73
away_conf                      UEFA
hour                             18
rank_diff                      10.0
points_diff                  -75.72
age_diff                  -0.454545
Name: 1479, dtype: object home_team_goals    1
away_team_goals    2
Name: 1479, dtype: int64
model prediction: [[2 2]]
the match is:  home_team               Netherlands
away_team                     Wales
home_total_points           1653.73
home_rank_change                0.0
home_previous_points        1653.73
home_conf                      UEFA
away_total_points           1578.01
away_rank_change                1.0
away_previous_points        1578.01
away_conf                      UEFA
hour                             18
rank_diff                     -10.0
points_diff                   75.72
age_diff                   0.181818
Name: 1480, dtype: object home_team_goals    3
away_team_goals    2
Name: 1480, dtype: int64
model prediction: [[3 2]]
the match is:  home_team               Netherlands
away_team                 Argentina
home_total_points           1653.73
home_rank_change                0.0
home_previous_points        1653.73
home_conf                      UEFA
away_total_points           1766.99
away_rank_change               -1.0
away_previous_points        1750.51
away_conf                  CONMEBOL
hour                             19
rank_diff                       6.0
points_diff                 -113.26
age_diff                        0.0
Name: 1483, dtype: object home_team_goals    3
away_team_goals    4
Name: 1483, dtype: int64
model prediction: [[2 2]]
the match is:  home_team                   Senegal
away_team               Netherlands
home_total_points           1587.78
home_rank_change               -2.0
home_previous_points        1561.68
home_conf                       CAF
away_total_points           1653.73
away_rank_change                0.0
away_previous_points        1653.73
away_conf                      UEFA
hour                             16
rank_diff                       8.0
points_diff                  -65.95
age_diff                   1.181818
Name: 1489, dtype: object home_team_goals    0
away_team_goals    2
Name: 1489, dtype: int64
model prediction: [[2 2]]
the match is:  home_team               Netherlands
away_team                    Poland
home_total_points           1653.73
home_rank_change                0.0
home_previous_points        1653.73
home_conf                      UEFA
away_total_points           1530.62
away_rank_change                1.0
away_previous_points        1530.62
away_conf                      UEFA
hour                             18
rank_diff                     -18.0
points_diff                  123.11
age_diff                   0.454545
Name: 1493, dtype: object home_team_goals    2
away_team_goals    2
Name: 1493, dtype: int64
model prediction: [[3 1]]
the match is:  home_team                    Poland
away_team               Netherlands
home_total_points           1530.62
home_rank_change                1.0
home_previous_points        1530.62
home_conf                      UEFA
away_total_points           1653.73
away_rank_change                0.0
away_previous_points        1653.73
away_conf                      UEFA
hour                             18
rank_diff                      18.0
points_diff                 -123.11
age_diff                   0.363636
Name: 1494, dtype: object home_team_goals    0
away_team_goals    2
Name: 1494, dtype: int64
model prediction: [[2 2]]
the match is:  home_team                    Spain
away_team               Costa Rica
home_total_points          1704.75
home_rank_change               0.0
home_previous_points       1704.75
home_conf                     UEFA
away_total_points          1464.06
away_rank_change              -7.0
away_previous_points       1437.43
away_conf                 CONCACAF
hour                            16
rank_diff                    -35.0
points_diff                 240.69
age_diff                 -2.454545
Name: 1549, dtype: object home_team_goals    7
away_team_goals    0
Name: 1549, dtype: int64
model prediction: [[3 1]]
the match is:  home_team                 Jordan
away_team                  Spain
home_total_points        1259.84
home_rank_change             0.0
home_previous_points     1255.69
home_conf                    AFC
away_total_points        1704.75
away_rank_change             0.0
away_previous_points     1704.75
away_conf                   UEFA
hour                          16
rank_diff                   83.0
points_diff              -444.91
age_diff                0.363636
Name: 1553, dtype: object home_team_goals    3
away_team_goals    1
Name: 1553, dtype: int64

/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:

model prediction: [[3 2]]
the match is:  home_team                  Spain
away_team                Albania
home_total_points        1704.75
home_rank_change             0.0
home_previous_points     1704.75
home_conf                   UEFA
away_total_points        1374.98
away_rank_change            -1.0
away_previous_points     1374.98
away_conf                   UEFA
hour                          18
rank_diff                  -58.0
points_diff               329.77
age_diff               -2.181818
Name: 1555, dtype: object home_team_goals    2
away_team_goals    1
Name: 1555, dtype: int64
model prediction: [[3 0]]
the match is:  home_team                  Spain
away_team               Portugal
home_total_points        1704.75
home_rank_change             0.0
home_previous_points     1704.75
home_conf                   UEFA
away_total_points        1660.25
away_rank_change             0.0
away_previous_points     1660.25
away_conf                   UEFA
hour                          18
rank_diff                   -1.0
points_diff                 44.5
age_diff               -1.363636
Name: 1562, dtype: object home_team_goals    1
away_team_goals    1
Name: 1562, dtype: int64
model prediction: [[3 2]]
the match is:  home_team               Portugal
away_team                  Spain
home_total_points        1660.25
home_rank_change             0.0
home_previous_points     1660.25
home_conf                   UEFA
away_total_points        1704.75
away_rank_change             0.0
away_previous_points     1704.75
away_conf                   UEFA
hour                          18
rank_diff                    1.0
points_diff                -44.5
age_diff                0.818182
Name: 1563, dtype: object home_team_goals    1
away_team_goals    0
Name: 1563, dtype: int64
model prediction: [[3 3]]
the match is:  home_team                  Spain
away_team                Iceland
home_total_points        1704.75
home_rank_change             0.0
home_previous_points     1704.75
home_conf                   UEFA
away_total_points        1382.81
away_rank_change            -2.0
away_previous_points     1385.21
away_conf                   UEFA
hour                          18
rank_diff                  -53.0
points_diff               321.94
age_diff                0.454545
Name: 1569, dtype: object home_team_goals    5
away_team_goals    0
Name: 1569, dtype: int64
model prediction: [[4 1]]
the match is:  home_team               Switzerland
away_team                     Spain
home_total_points           1642.83
home_rank_change                1.0
home_previous_points        1642.83
home_conf                      UEFA
away_total_points           1704.75
away_rank_change                0.0
away_previous_points        1704.75
away_conf                      UEFA
hour                             18
rank_diff                       7.0
points_diff                  -61.92
age_diff                   0.909091
Name: 1579, dtype: object home_team_goals    1
away_team_goals    0
Name: 1579, dtype: int64
model prediction: [[2 3]]
the match is:  home_team                     Spain
away_team               Switzerland
home_total_points           1704.75
home_rank_change                0.0
home_previous_points        1704.75
home_conf                      UEFA
away_total_points           1642.83
away_rank_change                1.0
away_previous_points        1642.83
away_conf                      UEFA
hour                             18
rank_diff                      -7.0
points_diff                   61.92
age_diff                  -2.181818
Name: 1580, dtype: object home_team_goals    1
away_team_goals    2
Name: 1580, dtype: int64
model prediction: [[3 2]]
the match is:  home_team               DR Congo
away_team                  Gabon
home_total_points        1369.53
home_rank_change             2.0
home_previous_points     1375.64
home_conf                    CAF
away_total_points        1290.65
away_rank_change            -7.0
away_previous_points      1262.0
away_conf                    CAF
hour                          20
rank_diff                  -16.0
points_diff                78.88
age_diff                0.454545
Name: 1588, dtype: object home_team_goals    0
away_team_goals    1
Name: 1588, dtype: int64
model prediction: [[2 2]]
the match is:  home_team                  Sudan
away_team               DR Congo
home_total_points        1118.31
home_rank_change             8.0
home_previous_points     1131.74
home_conf                    CAF
away_total_points        1369.53
away_rank_change             2.0
away_previous_points     1375.64
away_conf                    CAF
hour                          19
rank_diff                   67.0
points_diff              -251.22
age_diff                0.545455
Name: 1608, dtype: object home_team_goals    1
away_team_goals    2
Name: 1608, dtype: int64
model prediction: [[2 1]]
the match is:  home_team                   DR Congo
away_team               Burkina Faso
home_total_points            1369.53
home_rank_change                 2.0
home_previous_points         1375.64
home_conf                        CAF
away_total_points            1418.58
away_rank_change                -4.0
away_previous_points         1397.64
away_conf                        CAF
hour                              16
rank_diff                       10.0
points_diff                   -49.05
age_diff                    2.363636
Name: 1616, dtype: object home_team_goals    0
away_team_goals    1
Name: 1616, dtype: int64
model prediction: [[1 2]]
the match is:  home_team                Denmark
away_team                Tunisia
home_total_points        1654.54
home_rank_change             0.0
home_previous_points     1654.54
home_conf                   UEFA
away_total_points        1489.92
away_rank_change             6.0
away_previous_points     1512.72
away_conf                    CAF
hour                          13
rank_diff                  -27.0
points_diff               164.62
age_diff                0.909091
Name: 1644, dtype: object home_team_goals    0
away_team_goals    0
Name: 1644, dtype: int64
model prediction: [[2 1]]
the match is:  home_team                Tunisia
away_team                 France
home_total_points        1489.92
home_rank_change             6.0
home_previous_points     1512.72
home_conf                    CAF
away_total_points        1786.15
away_rank_change             0.0
away_previous_points     1786.15
away_conf                   UEFA
hour                          15
rank_diff                   33.0
points_diff              -296.23
age_diff                1.090909
Name: 1655, dtype: object home_team_goals    1
away_team_goals    0
Name: 1655, dtype: int64
model prediction: [[2 3]]
the match is:  home_team                  Chile
away_team                Tunisia
home_total_points        1543.16
home_rank_change             2.0
home_previous_points     1543.42
home_conf               CONMEBOL
away_total_points        1489.92
away_rank_change             6.0
away_previous_points     1512.72
away_conf                    CAF
hour                           6
rank_diff                  -10.0
points_diff                53.24
age_diff                0.545455
Name: 1656, dtype: object home_team_goals    0
away_team_goals    2
Name: 1656, dtype: int64
model prediction: [[2 2]]
the match is:  home_team                Tunisia
away_team                Comoros
home_total_points        1489.92
home_rank_change             6.0
home_previous_points     1512.72
home_conf                    CAF
away_total_points         1126.2
away_rank_change            -1.0
away_previous_points     1117.65
away_conf                    CAF
hour                          14
rank_diff                  -95.0
points_diff               363.72
age_diff                0.636364
Name: 1659, dtype: object home_team_goals    1
away_team_goals    0
Name: 1659, dtype: int64
model prediction: [[2 1]]
the match is:  home_team                   Iran
away_team                Tunisia
home_total_points        1572.89
home_rank_change             0.0
home_previous_points     1557.58
home_conf                    AFC
away_total_points        1489.92
away_rank_change             6.0
away_previous_points     1512.72
away_conf                    CAF
hour                          13
rank_diff                  -15.0
points_diff                82.97
age_diff                2.363636
Name: 1660, dtype: object home_team_goals    0
away_team_goals    2
Name: 1660, dtype: int64
model prediction: [[2 2]]
the match is:  home_team               Botswana
away_team                Tunisia
home_total_points        1051.59
home_rank_change             1.0
home_previous_points     1051.59
home_conf                    CAF
away_total_points        1489.92
away_rank_change             6.0
away_previous_points     1512.72
away_conf                    CAF
hour                          13
rank_diff                  113.0
points_diff              -438.33
age_diff               -1.818182
Name: 1666, dtype: object home_team_goals    0
away_team_goals    0
Name: 1666, dtype: int64
model prediction: [[2 2]]
the match is:  home_team                   Mali
away_team                Tunisia
home_total_points        1446.49
home_rank_change            -5.0
home_previous_points     1427.98
home_conf                    CAF
away_total_points        1489.92
away_rank_change             6.0
away_previous_points     1512.72
away_conf                    CAF
hour                          17
rank_diff                   12.0
points_diff               -43.43
age_diff               -1.454545
Name: 1673, dtype: object home_team_goals    0
away_team_goals    1
Name: 1673, dtype: int64
model prediction: [[2 2]]
the match is:  home_team                Tunisia
away_team                   Mali
home_total_points        1489.92
home_rank_change             6.0
home_previous_points     1512.72
home_conf                    CAF
away_total_points        1446.49
away_rank_change            -5.0
away_previous_points     1427.98
away_conf                    CAF
hour                          19
rank_diff                  -12.0
points_diff                43.43
age_diff                0.545455
Name: 1674, dtype: object home_team_goals    0
away_team_goals    0
Name: 1674, dtype: int64

/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:

model prediction: [[1 2]]
the match is:  home_team               Nicaragua
away_team                   Ghana
home_total_points         1062.21
home_rank_change              1.0
home_previous_points      1062.21
home_conf                CONCACAF
away_total_points         1381.45
away_rank_change              9.0
away_previous_points      1428.97
away_conf                     CAF
hour                           18
rank_diff                    83.0
points_diff               -319.24
age_diff                 3.636364
Name: 1699, dtype: object home_team_goals    1
away_team_goals    0
Name: 1699, dtype: int64
model prediction: [[2 1]]
the match is:  home_team                    Ghana
away_team               Madagascar
home_total_points          1381.45
home_rank_change               9.0
home_previous_points       1428.97
home_conf                      CAF
away_total_points          1205.61
away_rank_change               1.0
away_previous_points       1205.61
away_conf                      CAF
hour                            19
rank_diff                    -41.0
points_diff                 175.84
age_diff                 -2.363636
Name: 1706, dtype: object home_team_goals    3
away_team_goals    0
Name: 1706, dtype: int64
model prediction: [[2 1]]
the match is:  home_team                  Chile
away_team                  Ghana
home_total_points        1543.16
home_rank_change             2.0
home_previous_points     1543.42
home_conf               CONMEBOL
away_total_points        1381.45
away_rank_change             9.0
away_previous_points     1428.97
away_conf                    CAF
hour                           6
rank_diff                  -35.0
points_diff               161.71
age_diff                0.727273
Name: 1711, dtype: object home_team_goals    3
away_team_goals    1
Name: 1711, dtype: int64
model prediction: [[2 2]]
the match is:  home_team                  Ghana
away_team                  Benin
home_total_points        1381.45
home_rank_change             9.0
home_previous_points     1428.97
home_conf                    CAF
away_total_points        1282.53
away_rank_change             0.0
away_previous_points     1282.53
away_conf                    CAF
hour                          16
rank_diff                  -22.0
points_diff                98.92
age_diff               -1.363636
Name: 1715, dtype: object home_team_goals    3
away_team_goals    0
Name: 1715, dtype: int64
model prediction: [[2 1]]
the match is:  home_team                 Brazil
away_team                  Ghana
home_total_points        1823.42
home_rank_change             0.0
home_previous_points     1826.35
home_conf               CONMEBOL
away_total_points        1381.45
away_rank_change             9.0
away_previous_points     1428.97
away_conf                    CAF
hour                          18
rank_diff                  -59.0
points_diff               441.97
age_diff                1.181818
Name: 1716, dtype: object home_team_goals    0
away_team_goals    3
Name: 1716, dtype: int64
model prediction: [[3 1]]
the match is:  home_team                  Ghana
away_team                Nigeria
home_total_points        1381.45
home_rank_change             9.0
home_previous_points     1428.97
home_conf                    CAF
away_total_points        1509.91
away_rank_change            -4.0
away_previous_points     1478.78
away_conf                    CAF
hour                          19
rank_diff                   29.0
points_diff              -128.46
age_diff               -0.454545
Name: 1729, dtype: object home_team_goals    0
away_team_goals    0
Name: 1729, dtype: int64
model prediction: [[1 2]]
the match is:  home_team                Nigeria
away_team                  Ghana
home_total_points        1509.91
home_rank_change            -4.0
home_previous_points     1478.78
home_conf                    CAF
away_total_points        1381.45
away_rank_change             9.0
away_previous_points     1428.97
away_conf                    CAF
hour                          17
rank_diff                  -29.0
points_diff               128.46
age_diff                0.181818
Name: 1730, dtype: object home_team_goals    1
away_team_goals    1
Name: 1730, dtype: int64
model prediction: [[2 2]]
the match is:  home_team                     Ghana
away_team               Switzerland
home_total_points           1381.45
home_rank_change                9.0
home_previous_points        1428.97
home_conf                       CAF
away_total_points           1642.83
away_rank_change                1.0
away_previous_points        1642.83
away_conf                      UEFA
hour                             10
rank_diff                      47.0
points_diff                 -261.38
age_diff                  -2.181818
Name: 1731, dtype: object home_team_goals    2
away_team_goals    0
Name: 1731, dtype: int64
model prediction: [[1 2]]
the match is:  home_team               Slovenia
away_team                 Sweden
home_total_points        1375.42
home_rank_change            -1.0
home_previous_points     1375.42
home_conf                   UEFA
away_total_points        1588.26
away_rank_change            -1.0
away_previous_points     1588.26
away_conf                   UEFA
hour                          18
rank_diff                   47.0
points_diff              -212.84
age_diff                0.181818
Name: 1751, dtype: object home_team_goals    0
away_team_goals    2
Name: 1751, dtype: int64
model prediction: [[2 2]]
the match is:  home_team                 Sweden
away_team               Slovenia
home_total_points        1588.26
home_rank_change            -1.0
home_previous_points     1588.26
home_conf                   UEFA
away_total_points        1375.42
away_rank_change            -1.0
away_previous_points     1375.42
away_conf                   UEFA
hour                          18
rank_diff                  -47.0
points_diff               212.84
age_diff                1.636364
Name: 1752, dtype: object home_team_goals    1
away_team_goals    1
Name: 1752, dtype: int64
model prediction: [[3 1]]
the match is:  home_team                 Sweden
away_team                 Norway
home_total_points        1588.26
home_rank_change            -1.0
home_previous_points     1588.26
home_conf                   UEFA
away_total_points        1455.43
away_rank_change             4.0
away_previous_points     1455.43
away_conf                   UEFA
hour                          18
rank_diff                  -28.0
points_diff               132.83
age_diff                0.909091
Name: 1764, dtype: object home_team_goals    1
away_team_goals    2
Name: 1764, dtype: int64
model prediction: [[2 2]]
the match is:  home_team                 Norway
away_team                 Sweden
home_total_points        1455.43
home_rank_change             4.0
home_previous_points     1455.43
home_conf                   UEFA
away_total_points        1588.26
away_rank_change            -1.0
away_previous_points     1588.26
away_conf                   UEFA
hour                          16
rank_diff                   28.0
points_diff              -132.83
age_diff                0.181818
Name: 1765, dtype: object home_team_goals    3
away_team_goals    2
Name: 1765, dtype: int64
model prediction: [[2 2]]
the match is:  home_team                 Sweden
away_team                 Mexico
home_total_points        1588.26
home_rank_change            -1.0
home_previous_points     1588.26
home_conf                   UEFA
away_total_points         1647.9
away_rank_change            -2.0
away_previous_points      1638.3
away_conf               CONCACAF
hour                          19
rank_diff                    5.0
points_diff               -59.64
age_diff               -2.363636
Name: 1766, dtype: object home_team_goals    2
away_team_goals    1
Name: 1766, dtype: int64
model prediction: [[1 2]]
the match is:  home_team                 Poland
away_team                 Sweden
home_total_points        1530.62
home_rank_change             1.0
home_previous_points     1530.62
home_conf                   UEFA
away_total_points        1588.26
away_rank_change            -1.0
away_previous_points     1588.26
away_conf                   UEFA
hour                          18
rank_diff                   11.0
points_diff               -57.64
age_diff                0.090909
Name: 1769, dtype: object home_team_goals    2
away_team_goals    0
Name: 1769, dtype: int64
model prediction: [[2 2]]
the match is:  home_team                 Sweden
away_team                Algeria
home_total_points        1588.26
home_rank_change            -1.0
home_previous_points     1588.26
home_conf                   UEFA
away_total_points        1460.93
away_rank_change            14.0
away_previous_points     1516.51
away_conf                    CAF
hour                          19
rank_diff                  -26.0
points_diff               127.33
age_diff               -1.909091
Name: 1772, dtype: object home_team_goals    2
away_team_goals    0
Name: 1772, dtype: int64
model prediction: [[3 2]]
the match is:  home_team                 Sweden
away_team                 Serbia
home_total_points        1588.26
home_rank_change            -1.0
home_previous_points     1588.26
home_conf                   UEFA
away_total_points        1547.38
away_rank_change             2.0
away_previous_points     1547.38
away_conf                   UEFA
hour                          18
rank_diff                   -8.0
points_diff                40.88
age_diff               -1.363636
Name: 1774, dtype: object home_team_goals    0
away_team_goals    1
Name: 1774, dtype: int64

/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:

model prediction: [[2 2]]
the match is:  home_team                 Serbia
away_team                 Sweden
home_total_points        1547.38
home_rank_change             2.0
home_previous_points     1547.38
home_conf                   UEFA
away_total_points        1588.26
away_rank_change            -1.0
away_previous_points     1588.26
away_conf                   UEFA
hour                          18
rank_diff                    8.0
points_diff               -40.88
age_diff                0.363636
Name: 1775, dtype: object home_team_goals    4
away_team_goals    1
Name: 1775, dtype: int64
model prediction: [[2 2]]
the match is:  home_team               Uzbekistan
away_team                 Maldives
home_total_points          1277.02
home_rank_change               1.0
home_previous_points       1274.58
home_conf                      AFC
away_total_points          1021.58
away_rank_change               0.0
away_previous_points       1021.58
away_conf                      AFC
hour                            15
rank_diff                    -72.0
points_diff                 255.44
age_diff                      -2.0
Name: 1776, dtype: object home_team_goals    4
away_team_goals    0
Name: 1776, dtype: int64
model prediction: [[3 1]]
the match is:  home_team               Uzbekistan
away_team               Costa Rica
home_total_points          1277.02
home_rank_change               1.0
home_previous_points       1274.58
home_conf                      AFC
away_total_points          1464.06
away_rank_change              -7.0
away_previous_points       1437.43
away_conf                 CONCACAF
hour                             6
rank_diff                     43.0
points_diff                -187.04
age_diff                 -0.272727
Name: 1779, dtype: object home_team_goals    1
away_team_goals    2
Name: 1779, dtype: int64
model prediction: [[3 1]]
the match is:  home_team               Uzbekistan
away_team                 Thailand
home_total_points          1277.02
home_rank_change               1.0
home_previous_points       1274.58
home_conf                      AFC
away_total_points          1160.14
away_rank_change              -3.0
away_previous_points       1156.16
away_conf                      AFC
hour                            15
rank_diff                    -27.0
points_diff                 116.88
age_diff                 -2.090909
Name: 1782, dtype: object home_team_goals    2
away_team_goals    0
Name: 1782, dtype: int64
model prediction: [[2 1]]
the match is:  home_team               Uzbekistan
away_team                   Russia
home_total_points          1277.02
home_rank_change               1.0
home_previous_points       1274.58
home_conf                      AFC
away_total_points          1493.42
away_rank_change               1.0
away_previous_points       1493.42
away_conf                     UEFA
hour                            12
rank_diff                     50.0
points_diff                 -216.4
age_diff                       1.0
Name: 1783, dtype: object home_team_goals    0
away_team_goals    0
Name: 1783, dtype: int64
model prediction: [[2 2]]
the match is:  home_team               Uzbekistan
away_team                Sri Lanka
home_total_points          1277.02
home_rank_change               1.0
home_previous_points       1274.58
home_conf                      AFC
away_total_points           842.93
away_rank_change               0.0
away_previous_points        842.93
away_conf                      AFC
hour                            15
rank_diff                   -119.0
points_diff                 434.09
age_diff                       1.0
Name: 1784, dtype: object home_team_goals    3
away_team_goals    0
Name: 1784, dtype: int64
model prediction: [[5 1]]
the match is:  home_team                 Cameroon
away_team               Uzbekistan
home_total_points          1480.82
home_rank_change             -12.0
home_previous_points       1437.35
home_conf                      CAF
away_total_points          1277.02
away_rank_change               1.0
away_previous_points       1274.58
away_conf                      AFC
hour                             6
rank_diff                    -47.0
points_diff                  203.8
age_diff                  1.181818
Name: 1788, dtype: object home_team_goals    2
away_team_goals    0
Name: 1788, dtype: int64
model prediction: [[3 1]]
the match is:  home_team               Uzbekistan
away_team               Kazakhstan
home_total_points          1277.02
home_rank_change               1.0
home_previous_points       1274.58
home_conf                      AFC
away_total_points          1140.71
away_rank_change               1.0
away_previous_points       1140.71
away_conf                     UEFA
hour                            13
rank_diff                    -35.0
points_diff                 136.31
age_diff                 -2.818182
Name: 1809, dtype: object home_team_goals    2
away_team_goals    0
Name: 1809, dtype: int64
model prediction: [[3 1]]
the match is:  home_team               Uzbekistan
away_team                   Uganda
home_total_points          1277.02
home_rank_change               1.0
home_previous_points       1274.58
home_conf                      AFC
away_total_points          1279.18
away_rank_change               2.0
away_previous_points       1285.28
away_conf                      CAF
hour                            14
rank_diff                      1.0
points_diff                  -2.16
age_diff                  0.909091
Name: 1811, dtype: object home_team_goals    4
away_team_goals    2
Name: 1811, dtype: int64
model prediction: [[2 1]]
the match is:  home_team                Belgium
away_team                 Canada
home_total_points        1828.45
home_rank_change             0.0
home_previous_points     1828.45
home_conf                   UEFA
away_total_points        1497.82
away_rank_change            -7.0
away_previous_points     1462.32
away_conf               CONCACAF
hour                          19
rank_diff                  -32.0
points_diff               330.63
age_diff                3.766667
Name: 1812, dtype: object home_team_goals    1
away_team_goals    0
Name: 1812, dtype: int64
model prediction: [[2 1]]

/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/1992541822.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:

In [84]:
away=0
home=0
equal=0
home_test=0
equal_test=0
away_test=0
best_diff=0
best_par=0
for i in range(len(x_test)):
     
    match=x_test.iloc[i]
    y_match=y_test.iloc[i]

    print("the match is: ",match,y_test.iloc[i])    
    home_team =team_encoder.transform([match["home_team"]])[0]
    away_team=team_encoder.transform([match["away_team"]])[0]
    home_conf=conf_encoder.transform([match["home_conf"]])[0]
    away_conf=conf_encoder.transform([match["away_conf"]])[0]
    if y_match[0]>y_match[1]:
        home_test+=1
    elif y_match[0]<y_match[1]:
        away_test+=1 
    else :
        equal_test+=1


    
    a = [[
        home_team,
        away_team,
        match["home_total_points"],
        match["home_rank_change"],
        match["home_previous_points"],
        home_conf,
        match["away_total_points"],
        match["away_rank_change"],
        match["away_previous_points"],
        away_conf,
        match["hour"],
        match["rank_diff"],
        match["points_diff"],
        match["age_diff"]
    ]]

    
    pred=linear_model.predict(a)
    pred=np.where((pred - np.floor(pred)) >= 0.2,np.ceil(pred),np.floor(pred)).astype(int)
    print("model prediction:", pred)
    if pred[0][0]>pred[0][1]:
        home+=1
    elif pred[0][0]==pred[0][1]:
        equal+=1    
    else:
        away+=1

the match is:  home_team                Czechia
away_team                  Spain
home_total_points        1510.42
home_rank_change            -1.0
home_previous_points     1510.42
home_conf                   UEFA
away_total_points        1704.75
away_rank_change             0.0
away_previous_points     1704.75
away_conf                   UEFA
hour                          18
rank_diff                   24.0
points_diff              -194.33
age_diff                0.806818
Name: 17, dtype: object home_team_goals    2
away_team_goals    2
Name: 17, dtype: int64
model prediction: [[2 2]]
the match is:  home_team                 Sweden
away_team                Czechia
home_total_points        1588.26
home_rank_change            -1.0
home_previous_points     1588.26
home_conf                   UEFA
away_total_points        1510.42
away_rank_change            -1.0
away_previous_points     1510.42
away_conf                   UEFA
hour                          19
rank_diff                  -14.0
points_diff                77.84
age_diff                2.636364
Name: 18, dtype: object home_team_goals    1
away_team_goals    0
Name: 18, dtype: int64
model prediction: [[2 1]]
the match is:  home_team                   Czechia
away_team               Switzerland
home_total_points           1510.42
home_rank_change               -1.0
home_previous_points        1510.42
home_conf                      UEFA
away_total_points           1642.83
away_rank_change                1.0
away_previous_points        1642.83
away_conf                      UEFA
hour                             18
rank_diff                      17.0
points_diff                 -132.41
age_diff                  -1.545455
Name: 32, dtype: object home_team_goals    2
away_team_goals    1
Name: 32, dtype: int64
model prediction: [[2 2]]
the match is:  home_team                Uruguay
away_team                   Peru
home_total_points        1614.05
home_rank_change            -1.0
home_previous_points     1596.66
home_conf               CONMEBOL
away_total_points        1563.45
away_rank_change             0.0
away_previous_points     1551.15
away_conf               CONMEBOL
hour                          23
rank_diff                   -6.0
points_diff                 50.6
age_diff               -3.727273
Name: 49, dtype: object home_team_goals    1
away_team_goals    0
Name: 49, dtype: int64
model prediction: [[2 2]]
the match is:  home_team                  Ghana
away_team                Uruguay
home_total_points        1381.45
home_rank_change             9.0
home_previous_points     1428.97
home_conf                    CAF
away_total_points        1614.05
away_rank_change            -1.0
away_previous_points     1596.66
away_conf               CONMEBOL
hour                          15
rank_diff                   45.0
points_diff               -232.6
age_diff               -0.545455
Name: 51, dtype: object home_team_goals    2
away_team_goals    0
Name: 51, dtype: int64
model prediction: [[1 2]]
the match is:  home_team                  Chile
away_team                Uruguay
home_total_points        1543.16
home_rank_change             2.0
home_previous_points     1543.42
home_conf               CONMEBOL
away_total_points        1614.05
away_rank_change            -1.0
away_previous_points     1596.66
away_conf               CONMEBOL
hour                          23
rank_diff                   10.0
points_diff               -70.89
age_diff                2.090909
Name: 54, dtype: object home_team_goals    2
away_team_goals    0
Name: 54, dtype: int64
model prediction: [[2 2]]
the match is:  home_team                Uruguay
away_team                 Panama
home_total_points        1614.05
home_rank_change            -1.0
home_previous_points     1596.66
home_conf               CONMEBOL
away_total_points        1375.56
away_rank_change             0.0
away_previous_points     1379.34
away_conf               CONCACAF
hour                          20
rank_diff                  -47.0
points_diff               238.49
age_diff                2.181818
Name: 56, dtype: object home_team_goals    5
away_team_goals    0
Name: 56, dtype: int64
model prediction: [[2 1]]
the match is:  home_team                   Uruguay
away_team               South Korea
home_total_points           1614.05
home_rank_change               -1.0
home_previous_points        1596.66
home_conf                  CONMEBOL
away_total_points           1522.85
away_rank_change               -4.0
away_previous_points        1507.24
away_conf                       AFC
hour                             13
rank_diff                     -13.0
points_diff                    91.2
age_diff                       -1.0
Name: 58, dtype: object home_team_goals    0
away_team_goals    0
Name: 58, dtype: int64
model prediction: [[2 1]]
the match is:  home_team               Portugal
away_team                Uruguay
home_total_points        1660.25
home_rank_change             0.0
home_previous_points     1660.25
home_conf                   UEFA
away_total_points        1614.05
away_rank_change            -1.0
away_previous_points     1596.66
away_conf               CONMEBOL
hour                          19
rank_diff                   -8.0
points_diff                 46.2
age_diff               -0.909091
Name: 59, dtype: object home_team_goals    0
away_team_goals    2
Name: 59, dtype: int64
model prediction: [[2 1]]
the match is:  home_team                Belgium
away_team                Morocco
home_total_points        1828.45
home_rank_change             0.0
home_previous_points     1828.45
home_conf                   UEFA
away_total_points        1547.42
away_rank_change            -4.0
away_previous_points     1529.93
away_conf                    CAF
hour                          13
rank_diff                  -23.0
points_diff               281.03
age_diff                5.722222
Name: 78, dtype: object home_team_goals    0
away_team_goals    2
Name: 78, dtype: int64
model prediction: [[2 1]]
the match is:  home_team                 Canada
away_team                Morocco
home_total_points        1497.82
home_rank_change            -7.0
home_previous_points     1462.32
home_conf               CONCACAF
away_total_points        1547.42
away_rank_change            -4.0
away_previous_points     1529.93
away_conf                    CAF
hour                          15
rank_diff                    9.0
points_diff                -49.6
age_diff                1.181818
Name: 85, dtype: object home_team_goals    1
away_team_goals    2
Name: 85, dtype: int64
model prediction: [[2 2]]
the match is:  home_team                Morocco
away_team                  Spain
home_total_points        1547.42
home_rank_change            -4.0
home_previous_points     1529.93
home_conf                    CAF
away_total_points        1704.75
away_rank_change             0.0
away_previous_points     1704.75
away_conf                   UEFA
hour                          15
rank_diff                   17.0
points_diff              -157.33
age_diff                1.090909
Name: 92, dtype: object home_team_goals    3
away_team_goals    0
Name: 92, dtype: int64
model prediction: [[2 2]]
the match is:  home_team                Morocco
away_team                Croatia
home_total_points        1547.42
home_rank_change            -4.0
home_previous_points     1529.93
home_conf                    CAF
away_total_points        1620.74
away_rank_change             0.0
away_previous_points     1620.74
away_conf                   UEFA
hour                          10
rank_diff                    9.0
points_diff               -73.32
age_diff               -1.818182
Name: 102, dtype: object home_team_goals    0
away_team_goals    0
Name: 102, dtype: int64
model prediction: [[2 2]]
the match is:  home_team                    Brazil
away_team               Switzerland
home_total_points           1823.42
home_rank_change                0.0
home_previous_points        1826.35
home_conf                  CONMEBOL
away_total_points           1642.83
away_rank_change                1.0
away_previous_points        1642.83
away_conf                      UEFA
hour                             16
rank_diff                     -12.0
points_diff                  180.59
age_diff                   0.727273
Name: 142, dtype: object home_team_goals    1
away_team_goals    0
Name: 142, dtype: int64
model prediction: [[2 1]]
the match is:  home_team               Switzerland
away_team                  Cameroon
home_total_points           1642.83
home_rank_change                1.0
home_previous_points        1642.83
home_conf                      UEFA
away_total_points           1480.82
away_rank_change              -12.0
away_previous_points        1437.35
away_conf                       CAF
hour                             10
rank_diff                     -24.0
points_diff                  162.01
age_diff                   0.818182
Name: 144, dtype: object home_team_goals    1
away_team_goals    0
Name: 144, dtype: int64
model prediction: [[2 1]]
the match is:  home_team                    Serbia
away_team               Switzerland
home_total_points           1547.38
home_rank_change                2.0
home_previous_points        1547.38
home_conf                      UEFA
away_total_points           1642.83
away_rank_change                1.0
away_previous_points        1642.83
away_conf                      UEFA
hour                             19
rank_diff                      11.0
points_diff                  -95.45
age_diff                  -2.555556
Name: 151, dtype: object home_team_goals    2
away_team_goals    3
Name: 151, dtype: int64
model prediction: [[2 2]]
the match is:  home_team               Belgium
away_team                 Egypt
home_total_points       1828.45
home_rank_change            0.0
home_previous_points    1828.45
home_conf                  UEFA
away_total_points       1497.05
away_rank_change          -11.0
away_previous_points    1451.77
away_conf                   CAF
hour                         15
rank_diff                 -33.0
points_diff               331.4
age_diff                   -1.0
Name: 173, dtype: object home_team_goals    1
away_team_goals    2
Name: 173, dtype: int64
model prediction: [[2 1]]
the match is:  home_team                  Wales
away_team                Belgium
home_total_points        1578.01
home_rank_change             1.0
home_previous_points     1578.01
home_conf                   UEFA
away_total_points        1828.45
away_rank_change             0.0
away_previous_points     1828.45
away_conf                   UEFA
hour                          18
rank_diff                   19.0
points_diff              -250.44
age_diff               -1.636364
Name: 176, dtype: object home_team_goals    1
away_team_goals    1
Name: 176, dtype: int64
model prediction: [[2 2]]
the match is:  home_team                Belgium
away_team                  Wales
home_total_points        1828.45
home_rank_change             0.0
home_previous_points     1828.45
home_conf                   UEFA
away_total_points        1578.01
away_rank_change             1.0
away_previous_points     1578.01
away_conf                   UEFA
hour                          18
rank_diff                  -19.0
points_diff               250.44
age_diff                4.454545
Name: 177, dtype: object home_team_goals    2
away_team_goals    1
Name: 177, dtype: int64
model prediction: [[2 1]]
the match is:  home_team                    Belgium
away_team               Burkina Faso
home_total_points            1828.45
home_rank_change                 0.0
home_previous_points         1828.45
home_conf                       UEFA
away_total_points            1418.58
away_rank_change                -4.0
away_previous_points         1397.64
away_conf                        CAF
hour                              18
rank_diff                      -55.0
points_diff                   409.87
age_diff                   -0.363636
Name: 178, dtype: object home_team_goals    3
away_team_goals    0
Name: 178, dtype: int64
model prediction: [[2 1]]
the match is:  home_team                Croatia
away_team                Belgium
home_total_points        1620.74
home_rank_change             0.0
home_previous_points     1620.74
home_conf                   UEFA
away_total_points        1828.45
away_rank_change             0.0
away_previous_points     1828.45
away_conf                   UEFA
hour                          15
rank_diff                   14.0
points_diff              -207.71
age_diff               -1.818182
Name: 181, dtype: object home_team_goals    0
away_team_goals    0
Name: 181, dtype: int64
model prediction: [[2 2]]
the match is:  home_team                Belgium
away_team                 Poland
home_total_points        1828.45
home_rank_change             0.0
home_previous_points     1828.45
home_conf                   UEFA
away_total_points        1530.62
away_rank_change             1.0
away_previous_points     1530.62
away_conf                   UEFA
hour                          18
rank_diff                  -27.0
points_diff               297.83
age_diff                3.636364
Name: 182, dtype: object home_team_goals    6
away_team_goals    1
Name: 182, dtype: int64
model prediction: [[2 1]]
the match is:  home_team                 Poland
away_team                Belgium
home_total_points        1530.62
home_rank_change             1.0
home_previous_points     1530.62
home_conf                   UEFA
away_total_points        1828.45
away_rank_change             0.0
away_previous_points     1828.45
away_conf                   UEFA
hour                          18
rank_diff                   27.0
points_diff              -297.83
age_diff               -3.909091
Name: 183, dtype: object home_team_goals    0
away_team_goals    1
Name: 183, dtype: int64

/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/3283078934.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/3283078934.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/3283078934.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/3283078934.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/3283078934.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/3283078934.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/3283078934.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/3283078934.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/3283078934.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/3283078934.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/3283078934.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/3283078934.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

model prediction: [[2 2]]
the match is:  home_team                England
away_team                Senegal
home_total_points        1755.52
home_rank_change             1.0
home_previous_points     1755.52
home_conf                   UEFA
away_total_points        1587.78
away_rank_change            -2.0
away_previous_points     1561.68
away_conf                    CAF
hour                          19
rank_diff                  -13.0
points_diff               167.74
age_diff               -0.181818
Name: 196, dtype: object home_team_goals    0
away_team_goals    3
Name: 196, dtype: int64
model prediction: [[1 1]]
the match is:  home_team                Senegal
away_team               Eswatini
home_total_points        1587.78
home_rank_change            -2.0
home_previous_points     1561.68
home_conf                    CAF
away_total_points        1054.14
away_rank_change             1.0
away_previous_points     1054.14
away_conf                    CAF
hour                          12
rank_diff                 -129.0
points_diff               533.64
age_diff                    -6.0
Name: 203, dtype: object home_team_goals    10
away_team_goals     9
Name: 203, dtype: int64
model prediction: [[3 1]]
the match is:  home_team                Senegal
away_team                  Benin
home_total_points        1587.78
home_rank_change            -2.0
home_previous_points     1561.68
home_conf                    CAF
away_total_points        1282.53
away_rank_change             0.0
away_previous_points     1282.53
away_conf                    CAF
hour                          19
rank_diff                  -65.0
points_diff               305.25
age_diff               -0.272727
Name: 210, dtype: object home_team_goals    3
away_team_goals    1
Name: 210, dtype: int64
model prediction: [[3 1]]
the match is:  home_team                 Rwanda
away_team                Senegal
home_total_points        1097.16
home_rank_change             1.0
home_previous_points     1095.34
home_conf                    CAF
away_total_points        1587.78
away_rank_change            -2.0
away_previous_points     1561.68
away_conf                    CAF
hour                          19
rank_diff                  118.0
points_diff              -490.62
age_diff               -1.090909
Name: 216, dtype: object home_team_goals    1
away_team_goals    0
Name: 216, dtype: int64
model prediction: [[1 2]]
the match is:  home_team                 Zambia
away_team                Senegal
home_total_points        1264.64
home_rank_change             0.0
home_previous_points     1264.64
home_conf                    CAF
away_total_points        1587.78
away_rank_change            -2.0
away_previous_points     1561.68
away_conf                    CAF
hour                          17
rank_diff                   70.0
points_diff              -323.14
age_diff                2.454545
Name: 217, dtype: object home_team_goals    3
away_team_goals    4
Name: 217, dtype: int64
model prediction: [[1 2]]
the match is:  home_team                Bolivia
away_team                Senegal
home_total_points        1308.12
home_rank_change            -1.0
home_previous_points     1324.21
home_conf               CONMEBOL
away_total_points        1587.78
away_rank_change            -2.0
away_previous_points     1561.68
away_conf                    CAF
hour                          17
rank_diff                   58.0
points_diff              -279.66
age_diff                0.909091
Name: 224, dtype: object home_team_goals    2
away_team_goals    0
Name: 224, dtype: int64
model prediction: [[1 1]]
the match is:  home_team               Mozambique
away_team                  Senegal
home_total_points           1151.0
home_rank_change              -1.0
home_previous_points        1151.0
home_conf                      CAF
away_total_points          1587.78
away_rank_change              -2.0
away_previous_points       1561.68
away_conf                      CAF
hour                            13
rank_diff                     99.0
points_diff                -436.78
age_diff                  3.090909
Name: 238, dtype: object home_team_goals    4
away_team_goals    2
Name: 238, dtype: int64
model prediction: [[1 2]]
the match is:  home_team                Algeria
away_team                Senegal
home_total_points        1460.93
home_rank_change            14.0
home_previous_points     1516.51
home_conf                    CAF
away_total_points        1587.78
away_rank_change            -2.0
away_previous_points     1561.68
away_conf                    CAF
hour                          17
rank_diff                   25.0
points_diff              -126.85
age_diff                4.454545
Name: 248, dtype: object home_team_goals    2
away_team_goals    2
Name: 248, dtype: int64
model prediction: [[1 1]]
the match is:  home_team                   Japan
away_team               Hong Kong
home_total_points         1549.82
home_rank_change             -3.0
home_previous_points      1531.53
home_conf                     AFC
away_total_points         1053.39
away_rank_change              1.0
away_previous_points      1053.39
away_conf                     AFC
hour                           10
rank_diff                  -125.0
points_diff                496.43
age_diff                -2.454545
Name: 252, dtype: object home_team_goals    6
away_team_goals    0
Name: 252, dtype: int64
model prediction: [[3 1]]
the match is:  home_team                    Japan
away_team               Costa Rica
home_total_points          1549.82
home_rank_change              -3.0
home_previous_points       1531.53
home_conf                      AFC
away_total_points          1464.06
away_rank_change              -7.0
away_previous_points       1437.43
away_conf                 CONCACAF
hour                            10
rank_diff                    -19.0
points_diff                  85.76
age_diff                      -2.0
Name: 253, dtype: object home_team_goals    0
away_team_goals    1
Name: 253, dtype: int64
model prediction: [[2 2]]
the match is:  home_team                  Japan
away_team                  Ghana
home_total_points        1549.82
home_rank_change            -3.0
home_previous_points     1531.53
home_conf                    AFC
away_total_points        1381.45
away_rank_change             9.0
away_previous_points     1428.97
away_conf                    CAF
hour                           9
rank_diff                  -38.0
points_diff               168.37
age_diff                0.727273
Name: 265, dtype: object home_team_goals    4
away_team_goals    1
Name: 265, dtype: int64
model prediction: [[2 1]]
the match is:  home_team                  Japan
away_team                Tunisia
home_total_points        1549.82
home_rank_change            -3.0
home_previous_points     1531.53
home_conf                    AFC
away_total_points        1489.92
away_rank_change             6.0
away_previous_points     1512.72
away_conf                    CAF
hour                           9
rank_diff                  -13.0
points_diff                 59.9
age_diff                1.818182
Name: 274, dtype: object home_team_goals    0
away_team_goals    3
Name: 274, dtype: int64
model prediction: [[2 1]]
the match is:  home_team                  Japan
away_team                Vietnam
home_total_points        1549.82
home_rank_change            -3.0
home_previous_points     1531.53
home_conf                    AFC
away_total_points        1218.55
away_rank_change             0.0
away_previous_points     1212.54
away_conf                    AFC
hour                          10
rank_diff                  -75.0
points_diff               331.27
age_diff                2.363636
Name: 278, dtype: object home_team_goals    1
away_team_goals    1
Name: 278, dtype: int64
model prediction: [[2 1]]
the match is:  home_team                  Japan
away_team                  Spain
home_total_points        1549.82
home_rank_change            -3.0
home_previous_points     1531.53
home_conf                    AFC
away_total_points        1704.75
away_rank_change             0.0
away_previous_points     1704.75
away_conf                   UEFA
hour                          19
rank_diff                   16.0
points_diff              -154.93
age_diff                3.363636
Name: 281, dtype: object home_team_goals    2
away_team_goals    1
Name: 281, dtype: int64
model prediction: [[2 2]]
the match is:  home_team                  Japan
away_team                Croatia
home_total_points        1549.82
home_rank_change            -3.0
home_previous_points     1531.53
home_conf                    AFC
away_total_points        1620.74
away_rank_change             0.0
away_previous_points     1620.74
away_conf                   UEFA
hour                          15
rank_diff                    8.0
points_diff               -70.92
age_diff               -0.545455
Name: 289, dtype: object home_team_goals    1
away_team_goals    3
Name: 289, dtype: int64
model prediction: [[2 2]]
the match is:  home_team                    Iran
away_team               Nicaragua
home_total_points         1572.89
home_rank_change              0.0
home_previous_points      1557.58
home_conf                     AFC
away_total_points         1062.21
away_rank_change              1.0
away_previous_points      1062.21
away_conf                CONCACAF
hour                           16
rank_diff                  -123.0
points_diff                510.68
age_diff                 1.909091
Name: 295, dtype: object home_team_goals    1
away_team_goals    0
Name: 295, dtype: int64

/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/3283078934.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/3283078934.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/3283078934.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/3283078934.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/3283078934.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/3283078934.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/3283078934.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/3283078934.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

model prediction: [[3 1]]
the match is:  home_team                England
away_team                   Iran
home_total_points        1755.52
home_rank_change             1.0
home_previous_points     1755.52
home_conf                   UEFA
away_total_points        1572.89
away_rank_change             0.0
away_previous_points     1557.58
away_conf                    AFC
hour                          13
rank_diff                  -16.0
points_diff               182.63
age_diff               -2.818182
Name: 297, dtype: object home_team_goals    2
away_team_goals    6
Name: 297, dtype: int64
model prediction: [[1 1]]
the match is:  home_team                England
away_team                   Iran
home_total_points        1755.52
home_rank_change             1.0
home_previous_points     1755.52
home_conf                   UEFA
away_total_points        1572.89
away_rank_change             0.0
away_previous_points     1557.58
away_conf                    AFC
hour                          13
rank_diff                  -16.0
points_diff               182.63
age_diff               -2.818182
Name: 298, dtype: object home_team_goals    2
away_team_goals    6
Name: 298, dtype: int64
model prediction: [[1 1]]
the match is:  home_team               South Korea
away_team                      Iran
home_total_points           1522.85
home_rank_change               -4.0
home_previous_points        1507.24
home_conf                       AFC
away_total_points           1572.89
away_rank_change                0.0
away_previous_points        1557.58
away_conf                       AFC
hour                             11
rank_diff                       8.0
points_diff                  -50.04
age_diff                   1.090909
Name: 306, dtype: object home_team_goals    0
away_team_goals    2
Name: 306, dtype: int64
model prediction: [[1 2]]
the match is:  home_team                   Iran
away_team                Uruguay
home_total_points        1572.89
home_rank_change             0.0
home_previous_points     1557.58
home_conf                    AFC
away_total_points        1614.05
away_rank_change            -1.0
away_previous_points     1596.66
away_conf               CONMEBOL
hour                          16
rank_diff                    5.0
points_diff               -41.16
age_diff                1.727273
Name: 307, dtype: object home_team_goals    1
away_team_goals    0
Name: 307, dtype: int64
model prediction: [[2 2]]
the match is:  home_team                  Wales
away_team                   Iran
home_total_points        1578.01
home_rank_change             1.0
home_previous_points     1578.01
home_conf                   UEFA
away_total_points        1572.89
away_rank_change             0.0
away_previous_points     1557.58
away_conf                    AFC
hour                          10
rank_diff                   -1.0
points_diff                 5.12
age_diff               -1.181818
Name: 308, dtype: object home_team_goals    2
away_team_goals    0
Name: 308, dtype: int64
model prediction: [[1 1]]
the match is:  home_team                  Wales
away_team                   Iran
home_total_points        1578.01
home_rank_change             1.0
home_previous_points     1578.01
home_conf                   UEFA
away_total_points        1572.89
away_rank_change             0.0
away_previous_points     1557.58
away_conf                    AFC
hour                          10
rank_diff                   -1.0
points_diff                 5.12
age_diff               -1.181818
Name: 309, dtype: object home_team_goals    2
away_team_goals    0
Name: 309, dtype: int64
model prediction: [[1 1]]
the match is:  home_team                   Iran
away_team                Lebanon
home_total_points        1572.89
home_rank_change             0.0
home_previous_points     1557.58
home_conf                    AFC
away_total_points        1228.97
away_rank_change             0.0
away_previous_points      1233.0
away_conf                    AFC
hour                          11
rank_diff                  -74.0
points_diff               343.92
age_diff               -2.818182
Name: 316, dtype: object home_team_goals    2
away_team_goals    0
Name: 316, dtype: int64
model prediction: [[3 1]]
the match is:  home_team                   Iran
away_team                Senegal
home_total_points        1572.89
home_rank_change             0.0
home_previous_points     1557.58
home_conf                    AFC
away_total_points        1587.78
away_rank_change            -2.0
away_previous_points     1561.68
away_conf                    CAF
hour                          14
rank_diff                    3.0
points_diff               -14.89
age_diff                1.454545
Name: 324, dtype: object home_team_goals    1
away_team_goals    1
Name: 324, dtype: int64
model prediction: [[1 2]]
the match is:  home_team                   Iran
away_team                Algeria
home_total_points        1572.89
home_rank_change             0.0
home_previous_points     1557.58
home_conf                    AFC
away_total_points        1460.93
away_rank_change            14.0
away_previous_points     1516.51
away_conf                    CAF
hour                          18
rank_diff                  -22.0
points_diff               111.96
age_diff                2.636364
Name: 338, dtype: object home_team_goals    1
away_team_goals    2
Name: 338, dtype: int64
model prediction: [[2 1]]
the match is:  home_team                  Egypt
away_team                Liberia
home_total_points        1497.05
home_rank_change           -11.0
home_previous_points     1451.77
home_conf                    CAF
away_total_points        1058.28
away_rank_change             1.0
away_previous_points     1058.28
away_conf                    CAF
hour                          18
rank_diff                 -111.0
points_diff               438.77
age_diff                2.181818
Name: 347, dtype: object home_team_goals    3
away_team_goals    0
Name: 347, dtype: int64
model prediction: [[3 1]]
the match is:  home_team                 Egypt
away_team                 Niger
home_total_points       1497.05
home_rank_change          -11.0
home_previous_points    1451.77
home_conf                   CAF
away_total_points       1158.39
away_rank_change            1.0
away_previous_points    1158.39
away_conf                   CAF
hour                         18
rank_diff                 -80.0
points_diff              338.66
age_diff                    2.0
Name: 351, dtype: object home_team_goals    3
away_team_goals    0
Name: 351, dtype: int64
model prediction: [[3 1]]
the match is:  home_team               Ethiopia
away_team                  Egypt
home_total_points        1081.24
home_rank_change             1.0
home_previous_points     1087.89
home_conf                    CAF
away_total_points        1497.05
away_rank_change           -11.0
away_previous_points     1451.77
away_conf                    CAF
hour                          16
rank_diff                  104.0
points_diff              -415.81
age_diff               -2.818182
Name: 355, dtype: object home_team_goals    2
away_team_goals    0
Name: 355, dtype: int64
model prediction: [[1 2]]
the match is:  home_team                  Egypt
away_team                 Guinea
home_total_points        1497.05
home_rank_change           -11.0
home_previous_points     1451.77
home_conf                    CAF
away_total_points        1292.58
away_rank_change             0.0
away_previous_points     1298.32
away_conf                    CAF
hour                          19
rank_diff                  -47.0
points_diff               204.47
age_diff                3.454545
Name: 357, dtype: object home_team_goals    1
away_team_goals    0
Name: 357, dtype: int64
model prediction: [[3 1]]
the match is:  home_team               South Korea
away_team                     Egypt
home_total_points           1522.85
home_rank_change               -4.0
home_previous_points        1507.24
home_conf                       AFC
away_total_points           1497.05
away_rank_change              -11.0
away_previous_points        1451.77
away_conf                       CAF
hour                             11
rank_diff                      -5.0
points_diff                    25.8
age_diff                   1.363636
Name: 361, dtype: object home_team_goals    4
away_team_goals    1
Name: 361, dtype: int64
model prediction: [[1 2]]
the match is:  home_team                  Egypt
away_team                Senegal
home_total_points        1497.05
home_rank_change           -11.0
home_previous_points     1451.77
home_conf                    CAF
away_total_points        1587.78
away_rank_change            -2.0
away_previous_points     1561.68
away_conf                    CAF
hour                          19
rank_diff                   16.0
points_diff               -90.73
age_diff               -1.454545
Name: 385, dtype: object home_team_goals    1
away_team_goals    0
Name: 385, dtype: int64
model prediction: [[1 2]]
the match is:  home_team                Senegal
away_team                  Egypt
home_total_points        1587.78
home_rank_change            -2.0
home_previous_points     1561.68
home_conf                    CAF
away_total_points        1497.05
away_rank_change           -11.0
away_previous_points     1451.77
away_conf                    CAF
hour                          17
rank_diff                  -16.0
points_diff                90.73
age_diff                0.545455
Name: 386, dtype: object home_team_goals    3
away_team_goals    1
Name: 386, dtype: int64
model prediction: [[2 2]]
the match is:  home_team                Austria
away_team                Denmark
home_total_points        1511.56
home_rank_change            -1.0
home_previous_points     1511.56
home_conf                   UEFA
away_total_points        1654.54
away_rank_change             0.0
away_previous_points     1654.54
away_conf                   UEFA
hour                          20
rank_diff                   21.0
points_diff              -142.98
age_diff               -2.272727
Name: 397, dtype: object home_team_goals    1
away_team_goals    2
Name: 397, dtype: int64
model prediction: [[2 2]]
the match is:  home_team                Denmark
away_team                Austria
home_total_points        1654.54
home_rank_change             0.0
home_previous_points     1654.54
home_conf                   UEFA
away_total_points        1511.56
away_rank_change            -1.0
away_previous_points     1511.56
away_conf                   UEFA
hour                          18
rank_diff                  -21.0
points_diff               142.98
age_diff               -0.181818
Name: 398, dtype: object home_team_goals    0
away_team_goals    2
Name: 398, dtype: int64
model prediction: [[3 1]]
the match is:  home_team                Austria
away_team                  Italy
home_total_points        1511.56
home_rank_change            -1.0
home_previous_points     1511.56
home_conf                   UEFA
away_total_points        1740.77
away_rank_change             0.0
away_previous_points     1740.77
away_conf                   UEFA
hour                          19
rank_diff                   24.0
points_diff              -229.21
age_diff               -1.545455
Name: 400, dtype: object home_team_goals    2
away_team_goals    0
Name: 400, dtype: int64

/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/3283078934.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/3283078934.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/3283078934.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/3283078934.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/3283078934.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/3283078934.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/3283078934.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/3283078934.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

model prediction: [[2 2]]
the match is:  home_team                Andorra
away_team                Austria
home_total_points        1030.28
home_rank_change             0.0
home_previous_points     1030.28
home_conf                   UEFA
away_total_points        1511.56
away_rank_change            -1.0
away_previous_points     1511.56
away_conf                   UEFA
hour                          17
rank_diff                  125.0
points_diff              -481.28
age_diff               -0.272727
Name: 410, dtype: object home_team_goals    1
away_team_goals    0
Name: 410, dtype: int64
model prediction: [[2 2]]
the match is:  home_team                  Wales
away_team                Austria
home_total_points        1578.01
home_rank_change             1.0
home_previous_points     1578.01
home_conf                   UEFA
away_total_points        1511.56
away_rank_change            -1.0
away_previous_points     1511.56
away_conf                   UEFA
hour                          19
rank_diff                  -10.0
points_diff                66.45
age_diff               -0.181818
Name: 411, dtype: object home_team_goals    1
away_team_goals    2
Name: 411, dtype: int64
model prediction: [[3 1]]
the match is:  home_team                Croatia
away_team                Austria
home_total_points        1620.74
home_rank_change             0.0
home_previous_points     1620.74
home_conf                   UEFA
away_total_points        1511.56
away_rank_change            -1.0
away_previous_points     1511.56
away_conf                   UEFA
hour                          18
rank_diff                  -15.0
points_diff               109.18
age_diff               -1.727273
Name: 414, dtype: object home_team_goals    3
away_team_goals    0
Name: 414, dtype: int64
model prediction: [[3 1]]
the match is:  home_team                Austria
away_team                Croatia
home_total_points        1511.56
home_rank_change            -1.0
home_previous_points     1511.56
home_conf                   UEFA
away_total_points        1620.74
away_rank_change             0.0
away_previous_points     1620.74
away_conf                   UEFA
hour                          18
rank_diff                   15.0
points_diff              -109.18
age_diff               -1.090909
Name: 415, dtype: object home_team_goals    1
away_team_goals    3
Name: 415, dtype: int64
model prediction: [[2 2]]
the match is:  home_team               Costa Rica
away_team                  Germany
home_total_points          1464.06
home_rank_change              -7.0
home_previous_points       1437.43
home_conf                 CONCACAF
away_total_points          1648.33
away_rank_change              -1.0
away_previous_points       1648.33
away_conf                     UEFA
hour                            19
rank_diff                     31.0
points_diff                -184.27
age_diff                  2.727273
Name: 425, dtype: object home_team_goals    2
away_team_goals    4
Name: 425, dtype: int64
model prediction: [[2 2]]
the match is:  home_team                Hungary
away_team                Germany
home_total_points        1465.62
home_rank_change             2.0
home_previous_points     1465.62
home_conf                   UEFA
away_total_points        1648.33
away_rank_change            -1.0
away_previous_points     1648.33
away_conf                   UEFA
hour                          18
rank_diff                   30.0
points_diff              -182.71
age_diff                1.727273
Name: 431, dtype: object home_team_goals    1
away_team_goals    1
Name: 431, dtype: int64
model prediction: [[2 2]]
the match is:  home_team                Germany
away_team                Hungary
home_total_points        1648.33
home_rank_change            -1.0
home_previous_points     1648.33
home_conf                   UEFA
away_total_points        1465.62
away_rank_change             2.0
away_previous_points     1465.62
away_conf                   UEFA
hour                          18
rank_diff                  -30.0
points_diff               182.71
age_diff                1.090909
Name: 432, dtype: object home_team_goals    0
away_team_goals    1
Name: 432, dtype: int64
model prediction: [[3 1]]
the match is:  home_team                Germany
away_team                England
home_total_points        1648.33
home_rank_change            -1.0
home_previous_points     1648.33
home_conf                   UEFA
away_total_points        1755.52
away_rank_change             1.0
away_previous_points     1755.52
away_conf                   UEFA
hour                          18
rank_diff                    6.0
points_diff              -107.19
age_diff                0.181818
Name: 434, dtype: object home_team_goals    1
away_team_goals    1
Name: 434, dtype: int64
model prediction: [[2 2]]
the match is:  home_team                England
away_team                Germany
home_total_points        1755.52
home_rank_change             1.0
home_previous_points     1755.52
home_conf                   UEFA
away_total_points        1648.33
away_rank_change            -1.0
away_previous_points     1648.33
away_conf                   UEFA
hour                          18
rank_diff                   -6.0
points_diff               107.19
age_diff               -0.090909
Name: 435, dtype: object home_team_goals    3
away_team_goals    3
Name: 435, dtype: int64
model prediction: [[2 1]]
the match is:  home_team               Netherlands
away_team                   Germany
home_total_points           1653.73
home_rank_change                0.0
home_previous_points        1653.73
home_conf                      UEFA
away_total_points           1648.33
away_rank_change               -1.0
away_previous_points        1648.33
away_conf                      UEFA
hour                             18
rank_diff                      -1.0
points_diff                     5.4
age_diff                  -0.181818
Name: 440, dtype: object home_team_goals    1
away_team_goals    1
Name: 440, dtype: int64
model prediction: [[2 2]]
the match is:  home_team                  Italy
away_team                Germany
home_total_points        1740.77
home_rank_change             0.0
home_previous_points     1740.77
home_conf                   UEFA
away_total_points        1648.33
away_rank_change            -1.0
away_previous_points     1648.33
away_conf                   UEFA
hour                          18
rank_diff                   -5.0
points_diff                92.44
age_diff               -1.636364
Name: 443, dtype: object home_team_goals    1
away_team_goals    1
Name: 443, dtype: int64
model prediction: [[2 2]]
the match is:  home_team               Germany
away_team                 Italy
home_total_points       1648.33
home_rank_change           -1.0
home_previous_points    1648.33
home_conf                  UEFA
away_total_points       1740.77
away_rank_change            0.0
away_previous_points    1740.77
away_conf                  UEFA
hour                         18
rank_diff                   5.0
points_diff              -92.44
age_diff                    4.0
Name: 444, dtype: object home_team_goals    5
away_team_goals    2
Name: 444, dtype: int64
model prediction: [[2 2]]
the match is:  home_team                   Oman
away_team                Germany
home_total_points         1301.0
home_rank_change             0.0
home_previous_points     1306.01
home_conf                    AFC
away_total_points        1648.33
away_rank_change            -1.0
away_previous_points     1648.33
away_conf                   UEFA
hour                          17
rank_diff                   68.0
points_diff              -347.33
age_diff               -0.272727
Name: 453, dtype: object home_team_goals    0
away_team_goals    1
Name: 453, dtype: int64
model prediction: [[2 2]]
the match is:  home_team                  Spain
away_team                Germany
home_total_points        1704.75
home_rank_change             0.0
home_previous_points     1704.75
home_conf                   UEFA
away_total_points        1648.33
away_rank_change            -1.0
away_previous_points     1648.33
away_conf                   UEFA
hour                          19
rank_diff                   -4.0
points_diff                56.42
age_diff               -1.909091
Name: 455, dtype: object home_team_goals    1
away_team_goals    1
Name: 455, dtype: int64
model prediction: [[2 2]]
the match is:

/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/3283078934.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/3283078934.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/3283078934.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/3283078934.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/3283078934.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/3283078934.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/3283078934.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/3283078934.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/3283078934.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

home_team                Germany
away_team                  Japan
home_total_points        1648.33
home_rank_change            -1.0
home_previous_points     1648.33
home_conf                   UEFA
away_total_points        1549.82
away_rank_change            -3.0
away_previous_points     1531.53
away_conf                    AFC
hour                          13
rank_diff                  -12.0
points_diff                98.51
age_diff               -1.272727
Name: 458, dtype: object home_team_goals    1
away_team_goals    2
Name: 458, dtype: int64
model prediction: [[2 1]]
the match is:  home_team                Germany
away_team                 Israel
home_total_points        1648.33
home_rank_change            -1.0
home_previous_points     1648.33
home_conf                   UEFA
away_total_points         1306.7
away_rank_change            -1.0
away_previous_points      1306.7
away_conf                   UEFA
hour                          19
rank_diff                  -66.0
points_diff               341.63
age_diff               -1.727273
Name: 464, dtype: object home_team_goals    2
away_team_goals    0
Name: 464, dtype: int64
model prediction: [[3 1]]
the match is:  home_team                Turkiye
away_team                  Italy
home_total_points        1472.72
home_rank_change             2.0
home_previous_points     1472.72
home_conf                   UEFA
away_total_points        1740.77
away_rank_change             0.0
away_previous_points     1740.77
away_conf                   UEFA
hour                          18
rank_diff                   33.0
points_diff              -268.05
age_diff               -2.636364
Name: 512, dtype: object home_team_goals    2
away_team_goals    3
Name: 512, dtype: int64
model prediction: [[2 2]]
the match is:  home_team               Luxembourg
away_team                  Turkiye
home_total_points          1236.45
home_rank_change               0.0
home_previous_points       1236.45
home_conf                     UEFA
away_total_points          1472.72
away_rank_change               2.0
away_previous_points       1472.72
away_conf                     UEFA
hour                            18
rank_diff                     54.0
points_diff                -236.27
age_diff                  1.090909
Name: 517, dtype: object home_team_goals    0
away_team_goals    2
Name: 517, dtype: int64
model prediction: [[2 2]]
the match is:  home_team                  Turkiye
away_team               Luxembourg
home_total_points          1472.72
home_rank_change               2.0
home_previous_points       1472.72
home_conf                     UEFA
away_total_points          1236.45
away_rank_change               0.0
away_previous_points       1236.45
away_conf                     UEFA
hour                            18
rank_diff                    -54.0
points_diff                 236.27
age_diff                 -2.272727
Name: 518, dtype: object home_team_goals    3
away_team_goals    3
Name: 518, dtype: int64
model prediction: [[3 1]]
the match is:  home_team               Portugal
away_team                Turkiye
home_total_points        1660.25
home_rank_change             0.0
home_previous_points     1660.25
home_conf                   UEFA
away_total_points        1472.72
away_rank_change             2.0
away_previous_points     1472.72
away_conf                   UEFA
hour                          19
rank_diff                  -31.0
points_diff               187.53
age_diff                     4.0
Name: 520, dtype: object home_team_goals    3
away_team_goals    1
Name: 520, dtype: int64
model prediction: [[2 1]]
the match is:  home_team               Lithuania
away_team                 Turkiye
home_total_points         1091.77
home_rank_change              1.0
home_previous_points      1091.77
home_conf                    UEFA
away_total_points         1472.72
away_rank_change              2.0
away_previous_points      1472.72
away_conf                    UEFA
hour                           18
rank_diff                    98.0
points_diff               -380.95
age_diff                 3.727273
Name: 521, dtype: object home_team_goals    0
away_team_goals    6
Name: 521, dtype: int64
model prediction: [[2 2]]
the match is:  home_team                 Turkiye
away_team               Lithuania
home_total_points         1472.72
home_rank_change              2.0
home_previous_points      1472.72
home_conf                    UEFA
away_total_points         1091.77
away_rank_change              1.0
away_previous_points      1091.77
away_conf                    UEFA
hour                           18
rank_diff                   -98.0
points_diff                380.95
age_diff                -1.181818
Name: 522, dtype: object home_team_goals    2
away_team_goals    0
Name: 522, dtype: int64
model prediction: [[4 1]]
the match is:  home_team                   Peru
away_team               Paraguay
home_total_points        1563.45
home_rank_change             0.0
home_previous_points     1551.15
home_conf               CONMEBOL
away_total_points        1440.53
away_rank_change             7.0
away_previous_points     1454.52
away_conf               CONMEBOL
hour                          23
rank_diff                  -28.0
points_diff               122.92
age_diff                2.545455
Name: 552, dtype: object home_team_goals    2
away_team_goals    0
Name: 552, dtype: int64
model prediction: [[2 1]]
the match is:  home_team                   Peru
away_team               Paraguay
home_total_points        1563.45
home_rank_change             0.0
home_previous_points     1551.15
home_conf               CONMEBOL
away_total_points        1440.53
away_rank_change             7.0
away_previous_points     1454.52
away_conf               CONMEBOL
hour                           1
rank_diff                  -28.0
points_diff               122.92
age_diff                0.272727
Name: 553, dtype: object home_team_goals    1
away_team_goals    0
Name: 553, dtype: int64
model prediction: [[2 1]]
the match is:  home_team               Paraguay
away_team                Ecuador
home_total_points        1440.53
home_rank_change             7.0
home_previous_points     1454.52
home_conf               CONMEBOL
away_total_points        1458.63
away_rank_change            -2.0
away_previous_points     1448.27
away_conf               CONMEBOL
hour                          23
rank_diff                    6.0
points_diff                -18.1
age_diff                0.454545
Name: 566, dtype: object home_team_goals    3
away_team_goals    1
Name: 566, dtype: int64
model prediction: [[2 1]]
the match is:  home_team                 Mexico
away_team               Paraguay
home_total_points         1647.9
home_rank_change            -2.0
home_previous_points      1638.3
home_conf               CONCACAF
away_total_points        1440.53
away_rank_change             7.0
away_previous_points     1454.52
away_conf               CONMEBOL
hour                           1
rank_diff                  -38.0
points_diff               207.37
age_diff               -3.909091
Name: 568, dtype: object home_team_goals    0
away_team_goals    1
Name: 568, dtype: int64
model prediction: [[2 1]]
the match is:  home_team                  Japan
away_team               Paraguay
home_total_points        1549.82
home_rank_change            -3.0
home_previous_points     1531.53
home_conf                    AFC
away_total_points        1440.53
away_rank_change             7.0
away_previous_points     1454.52
away_conf               CONMEBOL
hour                          10
rank_diff                  -27.0
points_diff               109.29
age_diff                1.272727
Name: 572, dtype: object home_team_goals    4
away_team_goals    1
Name: 572, dtype: int64
model prediction: [[2 1]]
the match is:  home_team               Colombia
away_team               Paraguay
home_total_points        1585.89
home_rank_change             3.0
home_previous_points     1607.15
home_conf               CONMEBOL
away_total_points        1440.53
away_rank_change             7.0
away_previous_points     1454.52
away_conf               CONMEBOL
hour                           1
rank_diff                  -31.0
points_diff               145.36
age_diff               -0.363636
Name: 579, dtype: object home_team_goals    2
away_team_goals    0
Name: 579, dtype: int64

/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/3283078934.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/3283078934.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/3283078934.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/3283078934.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/3283078934.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

model prediction: [[2 1]]
the match is:  home_team                 Norway
away_team               Slovenia
home_total_points        1455.43
home_rank_change             4.0
home_previous_points     1455.43
home_conf                   UEFA
away_total_points        1375.42
away_rank_change            -1.0
away_previous_points     1375.42
away_conf                   UEFA
hour                          18
rank_diff                  -19.0
points_diff                80.01
age_diff               -0.636364
Name: 590, dtype: object home_team_goals    0
away_team_goals    0
Name: 590, dtype: int64
model prediction: [[3 1]]
the match is:  home_team               Slovenia
away_team                 Norway
home_total_points        1375.42
home_rank_change            -1.0
home_previous_points     1375.42
home_conf                   UEFA
away_total_points        1455.43
away_rank_change             4.0
away_previous_points     1455.43
away_conf                   UEFA
hour                          16
rank_diff                   19.0
points_diff               -80.01
age_diff                1.363636
Name: 591, dtype: object home_team_goals    1
away_team_goals    2
Name: 591, dtype: int64
model prediction: [[2 1]]
the match is:  home_team                 Norway
away_team               Slovakia
home_total_points        1455.43
home_rank_change             4.0
home_previous_points     1455.43
home_conf                   UEFA
away_total_points        1455.36
away_rank_change             4.0
away_previous_points     1455.36
away_conf                   UEFA
hour                          17
rank_diff                   -1.0
points_diff                 0.07
age_diff               -0.909091
Name: 593, dtype: object home_team_goals    2
away_team_goals    0
Name: 593, dtype: int64
model prediction: [[3 1]]
the match is:  home_team                 Norway
away_team                Finland
home_total_points        1455.43
home_rank_change             4.0
home_previous_points     1455.43
home_conf                   UEFA
away_total_points        1411.77
away_rank_change            -1.0
away_previous_points     1411.77
away_conf                   UEFA
hour                          13
rank_diff                  -12.0
points_diff                43.66
age_diff                0.727273
Name: 597, dtype: object home_team_goals    1
away_team_goals    1
Name: 597, dtype: int64
model prediction: [[3 1]]
the match is:  home_team                 Serbia
away_team                 Norway
home_total_points        1547.38
home_rank_change             2.0
home_previous_points     1547.38
home_conf                   UEFA
away_total_points        1455.43
away_rank_change             4.0
away_previous_points     1455.43
away_conf                   UEFA
hour                          18
rank_diff                  -20.0
points_diff                91.95
age_diff                1.272727
Name: 608, dtype: object home_team_goals    1
away_team_goals    0
Name: 608, dtype: int64
model prediction: [[3 1]]
the match is:  home_team                 Norway
away_team                 Serbia
home_total_points        1455.43
home_rank_change             4.0
home_previous_points     1455.43
home_conf                   UEFA
away_total_points        1547.38
away_rank_change             2.0
away_previous_points     1547.38
away_conf                   UEFA
hour                          18
rank_diff                   20.0
points_diff               -91.95
age_diff               -0.636364
Name: 609, dtype: object home_team_goals    0
away_team_goals    2
Name: 609, dtype: int64
model prediction: [[2 1]]
the match is:  home_team                 Norway
away_team                Armenia
home_total_points        1455.43
home_rank_change             4.0
home_previous_points     1455.43
home_conf                   UEFA
away_total_points        1242.24
away_rank_change             0.0
away_previous_points     1242.24
away_conf                   UEFA
hour                          17
rank_diff                  -47.0
points_diff               213.19
age_diff               -1.454545
Name: 612, dtype: object home_team_goals    9
away_team_goals    0
Name: 612, dtype: int64
model prediction: [[3 1]]
the match is:  home_team                Costa Rica
away_team               New Zealand
home_total_points           1464.06
home_rank_change               -7.0
home_previous_points        1437.43
home_conf                  CONCACAF
away_total_points           1161.66
away_rank_change                1.0
away_previous_points        1165.81
away_conf                       OFC
hour                             18
rank_diff                     -69.0
points_diff                   302.4
age_diff                   3.363636
Name: 614, dtype: object home_team_goals    0
away_team_goals    1
Name: 614, dtype: int64
model prediction: [[3 1]]
the match is:  home_team               New Zealand
away_team                    Tahiti
home_total_points           1161.66
home_rank_change                1.0
home_previous_points        1165.81
home_conf                       OFC
away_total_points           1014.27
away_rank_change                0.0
away_previous_points        1014.27
away_conf                       OFC
hour                             17
rank_diff                     -48.0
points_diff                  147.39
age_diff                  -2.545455
Name: 617, dtype: object home_team_goals    1
away_team_goals    0
Name: 617, dtype: int64
model prediction: [[4 1]]
the match is:  home_team               New Zealand
away_team                      Fiji
home_total_points           1161.66
home_rank_change                1.0
home_previous_points        1165.81
home_conf                       OFC
away_total_points            996.27
away_rank_change                1.0
away_previous_points         996.27
away_conf                       OFC
hour                             17
rank_diff                     -51.0
points_diff                  165.39
age_diff                  -0.090909
Name: 619, dtype: object home_team_goals    4
away_team_goals    0
Name: 619, dtype: int64
model prediction: [[4 1]]
the match is:  home_team                      Peru
away_team               New Zealand
home_total_points           1563.45
home_rank_change                0.0
home_previous_points        1551.15
home_conf                  CONMEBOL
away_total_points           1161.66
away_rank_change                1.0
away_previous_points        1165.81
away_conf                       OFC
hour                             15
rank_diff                     -89.0
points_diff                  401.79
age_diff                   4.181818
Name: 620, dtype: object home_team_goals    0
away_team_goals    1
Name: 620, dtype: int64
model prediction: [[3 1]]
the match is:  home_team                 New Zealand
away_team               New Caledonia
home_total_points             1161.66
home_rank_change                  1.0
home_previous_points          1165.81
home_conf                         OFC
away_total_points             1035.12
away_rank_change                  0.0
away_previous_points          1035.12
away_conf                         OFC
hour                               17
rank_diff                       -42.0
points_diff                    126.54
age_diff                    -3.818182
Name: 627, dtype: object home_team_goals    7
away_team_goals    1
Name: 627, dtype: int64
model prediction: [[4 1]]
the match is:  home_team                      Oman
away_team               New Zealand
home_total_points            1301.0
home_rank_change                0.0
home_previous_points        1306.01
home_conf                       AFC
away_total_points           1161.66
away_rank_change                1.0
away_previous_points        1165.81
away_conf                       OFC
hour                             18
rank_diff                     -32.0
points_diff                  139.34
age_diff                   0.454545
Name: 630, dtype: object home_team_goals    0
away_team_goals    0
Name: 630, dtype: int64
model prediction: [[3 1]]
the match is:  home_team               Solomon Islands
away_team                   New Zealand
home_total_points               1072.78
home_rank_change                    1.0
home_previous_points            1072.78
home_conf                           OFC
away_total_points               1161.66
away_rank_change                    1.0
away_previous_points            1165.81
away_conf                           OFC
hour                                 17
rank_diff                          31.0
points_diff                      -88.88
age_diff                       0.909091
Name: 633, dtype: object home_team_goals    5
away_team_goals    0
Name: 633, dtype: int64
model prediction: [[3 1]]
the match is:  home_team                   England
away_team               Ivory Coast
home_total_points           1755.52
home_rank_change                1.0
home_previous_points        1755.52
home_conf                      UEFA
away_total_points           1439.62
away_rank_change               -5.0
away_previous_points        1417.86
away_conf                       CAF
hour                             18
rank_diff                     -46.0
points_diff                   315.9
age_diff                  -3.454545
Name: 651, dtype: object home_team_goals    3
away_team_goals    0
Name: 651, dtype: int64
model prediction: [[2 1]]
the match is:  home_team               Ivory Coast
away_team                   Burundi
home_total_points           1439.62
home_rank_change               -5.0
home_previous_points        1417.86
home_conf                       CAF
away_total_points           1075.82
away_rank_change                1.0
away_previous_points        1075.82
away_conf                       CAF
hour                             16
rank_diff                     -90.0
points_diff                   363.8
age_diff                   2.272727
Name: 654, dtype: object home_team_goals    4
away_team_goals    0
Name: 654, dtype: int64
model prediction: [[3 1]]
the match is:  home_team                    France
away_team               Ivory Coast
home_total_points           1786.15
home_rank_change                0.0
home_previous_points        1786.15
home_conf                      UEFA
away_total_points           1439.62
away_rank_change               -5.0
away_previous_points        1417.86
away_conf                       CAF
hour                             20
rank_diff                     -48.0
points_diff                  346.53
age_diff                  -0.909091
Name: 658, dtype: object home_team_goals    2
away_team_goals    1
Name: 658, dtype: int64
model prediction: [[2 1]]
the match is:  home_team               Ivory Coast
away_team                      Togo
home_total_points           1439.62
home_rank_change               -5.0
home_previous_points        1417.86
home_conf                       CAF
away_total_points           1133.24
away_rank_change                2.0
away_previous_points        1133.24
away_conf                       CAF
hour                             16
rank_diff                     -75.0
points_diff                  306.38
age_diff                   0.909091
Name: 660, dtype: object home_team_goals    2
away_team_goals    1
Name: 660, dtype: int64

/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/3283078934.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/3283078934.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/3283078934.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/3283078934.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/3283078934.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/3283078934.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/3283078934.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

model prediction: [[3 1]]
the match is:  home_team               Ivory Coast
away_team                    Guinea
home_total_points           1439.62
home_rank_change               -5.0
home_previous_points        1417.86
home_conf                       CAF
away_total_points           1292.58
away_rank_change                0.0
away_previous_points        1298.32
away_conf                       CAF
hour                             18
rank_diff                     -30.0
points_diff                  147.04
age_diff                   0.181818
Name: 661, dtype: object home_team_goals    3
away_team_goals    1
Name: 661, dtype: int64
model prediction: [[2 1]]
the match is:  home_team               Ivory Coast
away_team                    Zambia
home_total_points           1439.62
home_rank_change               -5.0
home_previous_points        1417.86
home_conf                       CAF
away_total_points           1264.64
away_rank_change                0.0
away_previous_points        1264.64
away_conf                       CAF
hour                             19
rank_diff                     -37.0
points_diff                  174.98
age_diff                   3.818182
Name: 672, dtype: object home_team_goals    3
away_team_goals    1
Name: 672, dtype: int64
model prediction: [[2 1]]
the match is:  home_team               Burkina Faso
away_team                Ivory Coast
home_total_points            1418.58
home_rank_change                -4.0
home_previous_points         1397.64
home_conf                        CAF
away_total_points            1439.62
away_rank_change                -5.0
away_previous_points         1417.86
away_conf                        CAF
hour                              16
rank_diff                        5.0
points_diff                   -21.04
age_diff                   -4.818182
Name: 687, dtype: object home_team_goals    2
away_team_goals    1
Name: 687, dtype: int64
model prediction: [[2 2]]
the match is:  home_team                   Lesotho
away_team               Ivory Coast
home_total_points           1057.62
home_rank_change                1.0
home_previous_points        1057.62
home_conf                       CAF
away_total_points           1439.62
away_rank_change               -5.0
away_previous_points        1417.86
away_conf                       CAF
hour                             17
rank_diff                      95.0
points_diff                  -382.0
age_diff                  -1.363636
Name: 689, dtype: object home_team_goals    0
away_team_goals    0
Name: 689, dtype: int64
model prediction: [[1 2]]
the match is:  home_team                     France
away_team               South Africa
home_total_points            1786.15
home_rank_change                 0.0
home_previous_points         1786.15
home_conf                       UEFA
away_total_points            1358.24
away_rank_change                 0.0
away_previous_points         1358.24
away_conf                        CAF
hour                              19
rank_diff                      -65.0
points_diff                   427.91
age_diff                    0.555556
Name: 705, dtype: object home_team_goals    5
away_team_goals    0
Name: 705, dtype: int64
model prediction: [[2 1]]
the match is:  home_team               South Africa
away_team                     Guinea
home_total_points            1358.24
home_rank_change                 0.0
home_previous_points         1358.24
home_conf                        CAF
away_total_points            1292.58
away_rank_change                 0.0
away_previous_points         1298.32
away_conf                        CAF
hour                              17
rank_diff                      -13.0
points_diff                    65.66
age_diff                    1.090909
Name: 709, dtype: object home_team_goals    0
away_team_goals    0
Name: 709, dtype: int64
model prediction: [[2 1]]
the match is:  home_team                    Morocco
away_team               South Africa
home_total_points            1547.42
home_rank_change                -4.0
home_previous_points         1529.93
home_conf                        CAF
away_total_points            1358.24
away_rank_change                 0.0
away_previous_points         1358.24
away_conf                        CAF
hour                              19
rank_diff                      -44.0
points_diff                   189.18
age_diff                   -0.454545
Name: 721, dtype: object home_team_goals    2
away_team_goals    1
Name: 721, dtype: int64
model prediction: [[2 1]]
the match is:  home_team               Australia
away_team                 Denmark
home_total_points         1486.86
home_rank_change              2.0
home_previous_points      1484.88
home_conf                     AFC
away_total_points         1654.54
away_rank_change              0.0
away_previous_points      1654.54
away_conf                    UEFA
hour                           15
rank_diff                    28.0
points_diff               -167.68
age_diff                 1.727273
Name: 730, dtype: object home_team_goals    1
away_team_goals    0
Name: 730, dtype: int64
model prediction: [[2 2]]
the match is:  home_team               Australia
away_team                    Peru
home_total_points         1486.86
home_rank_change              2.0
home_previous_points      1484.88
home_conf                     AFC
away_total_points         1563.45
away_rank_change              0.0
away_previous_points      1551.15
away_conf                CONMEBOL
hour                           18
rank_diff                    15.0
points_diff                -76.59
age_diff                -1.636364
Name: 731, dtype: object home_team_goals    5
away_team_goals    4
Name: 731, dtype: int64
model prediction: [[2 2]]
the match is:  home_team               Australia
away_team                  Jordan
home_total_points         1486.86
home_rank_change              2.0
home_previous_points      1484.88
home_conf                     AFC
away_total_points         1259.84
away_rank_change              0.0
away_previous_points      1255.69
away_conf                     AFC
hour                           18
rank_diff                   -53.0
points_diff                227.02
age_diff                 0.454545
Name: 733, dtype: object home_team_goals    2
away_team_goals    1
Name: 733, dtype: int64
model prediction: [[2 1]]
the match is:  home_team               Saudi Arabia
away_team                  Australia
home_total_points            1433.95
home_rank_change                 2.0
home_previous_points         1434.71
home_conf                        AFC
away_total_points            1486.86
away_rank_change                 2.0
away_previous_points         1484.88
away_conf                        AFC
hour                              18
rank_diff                       16.0
points_diff                   -52.91
age_diff                    0.363636
Name: 740, dtype: object home_team_goals    1
away_team_goals    0
Name: 740, dtype: int64
model prediction: [[1 1]]
the match is:  home_team                 Australia
away_team               New Zealand
home_total_points           1486.86
home_rank_change                2.0
home_previous_points        1484.88
home_conf                       AFC
away_total_points           1161.66
away_rank_change                1.0
away_previous_points        1165.81
away_conf                       OFC
hour                             10
rank_diff                     -74.0
points_diff                   325.2
age_diff                   3.636364
Name: 744, dtype: object home_team_goals    1
away_team_goals    0
Name: 744, dtype: int64
model prediction: [[3 1]]
the match is:  home_team               New Zealand
away_team                 Australia
home_total_points           1161.66
home_rank_change                1.0
home_previous_points        1165.81
home_conf                       OFC
away_total_points           1486.86
away_rank_change                2.0
away_previous_points        1484.88
away_conf                       AFC
hour                              3
rank_diff                      74.0
points_diff                  -325.2
age_diff                  -0.909091
Name: 745, dtype: object home_team_goals    0
away_team_goals    2
Name: 745, dtype: int64

/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/3283078934.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/3283078934.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/3283078934.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/3283078934.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/3283078934.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/3283078934.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

model prediction: [[2 1]]
the match is:  home_team                  France
away_team               Australia
home_total_points         1786.15
home_rank_change              0.0
home_previous_points      1786.15
home_conf                    UEFA
away_total_points         1486.86
away_rank_change              2.0
away_previous_points      1484.88
away_conf                     AFC
hour                           19
rank_diff                   -34.0
points_diff                299.29
age_diff                     -1.0
Name: 751, dtype: object home_team_goals    4
away_team_goals    1
Name: 751, dtype: int64
model prediction: [[2 1]]
the match is:  home_team                 Tunisia
away_team               Australia
home_total_points         1489.92
home_rank_change              6.0
home_previous_points      1512.72
home_conf                     CAF
away_total_points         1486.86
away_rank_change              2.0
away_previous_points      1484.88
away_conf                     AFC
hour                           10
rank_diff                    -1.0
points_diff                  3.06
age_diff                -0.727273
Name: 757, dtype: object home_team_goals    0
away_team_goals    1
Name: 757, dtype: int64
model prediction: [[1 1]]
the match is:  home_team               Argentina
away_team               Australia
home_total_points         1766.99
home_rank_change             -1.0
home_previous_points      1750.51
home_conf                CONMEBOL
away_total_points         1486.86
away_rank_change              2.0
away_previous_points      1484.88
away_conf                     AFC
hour                           19
rank_diff                   -33.0
points_diff                280.13
age_diff                -0.181818
Name: 765, dtype: object home_team_goals    2
away_team_goals    1
Name: 765, dtype: int64
model prediction: [[2 1]]
the match is:  home_team               Australia
away_team                   Japan
home_total_points         1486.86
home_rank_change              2.0
home_previous_points      1484.88
home_conf                     AFC
away_total_points         1549.82
away_rank_change             -3.0
away_previous_points      1531.53
away_conf                     AFC
hour                            9
rank_diff                    14.0
points_diff                -62.96
age_diff                -1.909091
Name: 771, dtype: object home_team_goals    0
away_team_goals    2
Name: 771, dtype: int64
model prediction: [[1 1]]
the match is:  home_team               Saudi Arabia
away_team                    Ecuador
home_total_points            1433.95
home_rank_change                 2.0
home_previous_points         1434.71
home_conf                        AFC
away_total_points            1458.63
away_rank_change                -2.0
away_previous_points         1448.27
away_conf                   CONMEBOL
hour                              18
rank_diff                        9.0
points_diff                   -24.68
age_diff                    2.090909
Name: 782, dtype: object home_team_goals    0
away_team_goals    0
Name: 782, dtype: int64
model prediction: [[2 2]]
the match is:  home_team               Netherlands
away_team                   Ecuador
home_total_points           1653.73
home_rank_change                0.0
home_previous_points        1653.73
home_conf                      UEFA
away_total_points           1458.63
away_rank_change               -2.0
away_previous_points        1448.27
away_conf                  CONMEBOL
hour                             16
rank_diff                     -34.0
points_diff                   195.1
age_diff                   1.272727
Name: 785, dtype: object home_team_goals    1
away_team_goals    1
Name: 785, dtype: int64
model prediction: [[2 1]]
the match is:  home_team                  Ecuador
away_team               Cape Verde
home_total_points          1458.63
home_rank_change              -2.0
home_previous_points       1448.27
home_conf                 CONMEBOL
away_total_points          1336.88
away_rank_change               0.0
away_previous_points       1339.48
away_conf                      CAF
hour                            23
rank_diff                    -29.0
points_diff                 121.75
age_diff                 -1.363636
Name: 793, dtype: object home_team_goals    1
away_team_goals    0
Name: 793, dtype: int64
model prediction: [[2 1]]
the match is:  home_team                Ecuador
away_team                Nigeria
home_total_points        1458.63
home_rank_change            -2.0
home_previous_points     1448.27
home_conf               CONMEBOL
away_total_points        1509.91
away_rank_change            -4.0
away_previous_points     1478.78
away_conf                    CAF
hour                           0
rank_diff                   12.0
points_diff               -51.28
age_diff                     0.0
Name: 798, dtype: object home_team_goals    1
away_team_goals    0
Name: 798, dtype: int64
model prediction: [[2 1]]
the match is:  home_team                 Ecuador
away_team               Argentina
home_total_points         1458.63
home_rank_change             -2.0
home_previous_points      1448.27
home_conf                CONMEBOL
away_total_points         1766.99
away_rank_change             -1.0
away_previous_points      1750.51
away_conf                CONMEBOL
hour                           23
rank_diff                    40.0
points_diff               -308.36
age_diff                -2.181818
Name: 803, dtype: object home_team_goals    1
away_team_goals    1
Name: 803, dtype: int64
model prediction: [[2 2]]
the match is:  home_team                Ecuador
away_team                   Iraq
home_total_points        1458.63
home_rank_change            -2.0
home_previous_points     1448.27
home_conf               CONMEBOL
away_total_points        1325.44
away_rank_change            -1.0
away_previous_points     1333.03
away_conf                    AFC
hour                          17
rank_diff                  -30.0
points_diff               133.19
age_diff                2.545455
Name: 804, dtype: object home_team_goals    0
away_team_goals    0
Name: 804, dtype: int64
model prediction: [[2 1]]
the match is:  home_team                Ecuador
away_team                  Japan
home_total_points        1458.63
home_rank_change            -2.0
home_previous_points     1448.27
home_conf               CONMEBOL
away_total_points        1549.82
away_rank_change            -3.0
away_previous_points     1531.53
away_conf                    AFC
hour                          11
rank_diff                   21.0
points_diff               -91.19
age_diff               -2.181818
Name: 806, dtype: object home_team_goals    0
away_team_goals    0
Name: 806, dtype: int64
model prediction: [[1 1]]
the match is:  home_team                Ecuador
away_team                Senegal
home_total_points        1458.63
home_rank_change            -2.0
home_previous_points     1448.27
home_conf               CONMEBOL
away_total_points        1587.78
away_rank_change            -2.0
away_previous_points     1561.68
away_conf                    CAF
hour                          15
rank_diff                   26.0
points_diff              -129.15
age_diff               -1.272727
Name: 807, dtype: object home_team_goals    1
away_team_goals    2
Name: 807, dtype: int64
model prediction: [[1 1]]
the match is:  home_team               Cameroon
away_team                Algeria
home_total_points        1480.82
home_rank_change           -12.0
home_previous_points     1437.35
home_conf                    CAF
away_total_points        1460.93
away_rank_change            14.0
away_previous_points     1516.51
away_conf                    CAF
hour                          17
rank_diff                   -5.0
points_diff                19.89
age_diff               -2.454545
Name: 834, dtype: object home_team_goals    1
away_team_goals    0
Name: 834, dtype: int64
model prediction: [[2 1]]
the match is:  home_team                Algeria
away_team               Cameroon
home_total_points        1460.93
home_rank_change            14.0
home_previous_points     1516.51
home_conf                    CAF
away_total_points        1480.82
away_rank_change           -12.0
away_previous_points     1437.35
away_conf                    CAF
hour                          19
rank_diff                    5.0
points_diff               -19.89
age_diff                1.090909
Name: 835, dtype: object home_team_goals    1
away_team_goals    2
Name: 835, dtype: int64
model prediction: [[1 1]]
the match is:  home_team               Cameroon
away_team                Algeria
home_total_points        1480.82
home_rank_change           -12.0
home_previous_points     1437.35
home_conf                    CAF
away_total_points        1460.93
away_rank_change            14.0
away_previous_points     1516.51
away_conf                    CAF
hour                          17
rank_diff                   -5.0
points_diff                19.89
age_diff               -2.454545
Name: 836, dtype: object home_team_goals    1
away_team_goals    0
Name: 836, dtype: int64
model prediction: [[2 1]]
the match is:  home_team                Algeria
away_team               Cameroon
home_total_points        1460.93
home_rank_change            14.0
home_previous_points     1516.51
home_conf                    CAF
away_total_points        1480.82
away_rank_change           -12.0
away_previous_points     1437.35
away_conf                    CAF
hour                          19
rank_diff                    5.0
points_diff               -19.89
age_diff                1.090909
Name: 837, dtype: object home_team_goals    1
away_team_goals    2
Name: 837, dtype: int64
model prediction: [[1 1]]
the match is:  home_team               Tanzania
away_team                Algeria
home_total_points        1118.76
home_rank_change             1.0
home_previous_points     1118.76
home_conf                    CAF
away_total_points        1460.93
away_rank_change            14.0
away_previous_points     1516.51
away_conf                    CAF
hour                          16
rank_diff                   89.0
points_diff              -342.17
age_diff               -4.363636
Name: 853, dtype: object home_team_goals    2
away_team_goals    0
Name: 853, dtype: int64
model prediction: [[2 2]]
the match is:  home_team               Tanzania
away_team                Algeria
home_total_points        1118.76
home_rank_change             1.0
home_previous_points     1118.76
home_conf                    CAF
away_total_points        1460.93
away_rank_change            14.0
away_previous_points     1516.51
away_conf                    CAF
hour                          16
rank_diff                   89.0
points_diff              -342.17
age_diff               -4.363636
Name: 854, dtype: object home_team_goals    2
away_team_goals    0
Name: 854, dtype: int64

/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/3283078934.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/3283078934.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/3283078934.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/3283078934.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/3283078934.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/3283078934.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/3283078934.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/3283078934.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/3283078934.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/3283078934.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

model prediction: [[2 2]]
the match is:  home_team                Algeria
away_team                 Uganda
home_total_points        1460.93
home_rank_change            14.0
home_previous_points     1516.51
home_conf                    CAF
away_total_points        1279.18
away_rank_change             2.0
away_previous_points     1285.28
away_conf                    CAF
hour                          19
rank_diff                  -41.0
points_diff               181.75
age_diff                1.909091
Name: 866, dtype: object home_team_goals    2
away_team_goals    0
Name: 866, dtype: int64
model prediction: [[2 1]]
the match is:  home_team                Algeria
away_team                 Uganda
home_total_points        1460.93
home_rank_change            14.0
home_previous_points     1516.51
home_conf                    CAF
away_total_points        1279.18
away_rank_change             2.0
away_previous_points     1285.28
away_conf                    CAF
hour                          19
rank_diff                  -41.0
points_diff               181.75
age_diff                1.909091
Name: 867, dtype: object home_team_goals    2
away_team_goals    0
Name: 867, dtype: int64
model prediction: [[2 1]]
the match is:  home_team               Saudi Arabia
away_team                    Albania
home_total_points            1433.95
home_rank_change                 2.0
home_previous_points         1434.71
home_conf                        AFC
away_total_points            1374.98
away_rank_change                -1.0
away_previous_points         1374.98
away_conf                       UEFA
hour                              14
rank_diff                      -12.0
points_diff                    58.97
age_diff                    1.818182
Name: 881, dtype: object home_team_goals    1
away_team_goals    1
Name: 881, dtype: int64
model prediction: [[3 2]]
the match is:  home_team                     Panama
away_team               Saudi Arabia
home_total_points            1375.56
home_rank_change                 0.0
home_previous_points         1379.34
home_conf                   CONCACAF
away_total_points            1433.95
away_rank_change                 2.0
away_previous_points         1434.71
away_conf                        AFC
hour                              12
rank_diff                       10.0
points_diff                   -58.39
age_diff                   -0.818182
Name: 889, dtype: object home_team_goals    1
away_team_goals    1
Name: 889, dtype: int64
model prediction: [[2 1]]
the match is:  home_team               Saudi Arabia
away_team                   Honduras
home_total_points            1433.95
home_rank_change                 2.0
home_previous_points         1434.71
home_conf                        AFC
away_total_points            1303.96
away_rank_change                 2.0
away_previous_points         1332.16
away_conf                   CONCACAF
hour                              14
rank_diff                      -25.0
points_diff                   129.99
age_diff                   -0.272727
Name: 890, dtype: object home_team_goals    0
away_team_goals    0
Name: 890, dtype: int64
model prediction: [[2 1]]
the match is:  home_team                  Saudi Arabia
away_team               North Macedonia
home_total_points               1433.95
home_rank_change                    2.0
home_previous_points            1434.71
home_conf                           AFC
away_total_points               1367.23
away_rank_change                    0.0
away_previous_points            1367.23
away_conf                          UEFA
hour                                 14
rank_diff                         -14.0
points_diff                       66.72
age_diff                      -0.818182
Name: 892, dtype: object home_team_goals    1
away_team_goals    0
Name: 892, dtype: int64
model prediction: [[2 2]]
the match is:  home_team                    Iceland
away_team               Saudi Arabia
home_total_points            1382.81
home_rank_change                -2.0
home_previous_points         1385.21
home_conf                       UEFA
away_total_points            1433.95
away_rank_change                 2.0
away_previous_points         1434.71
away_conf                        AFC
hour                              12
rank_diff                        7.0
points_diff                   -51.14
age_diff                   -2.636364
Name: 900, dtype: object home_team_goals    1
away_team_goals    0
Name: 900, dtype: int64
model prediction: [[2 1]]
the match is:  home_team                  Argentina
away_team               Saudi Arabia
home_total_points            1766.99
home_rank_change                -1.0
home_previous_points         1750.51
home_conf                   CONMEBOL
away_total_points            1433.95
away_rank_change                 2.0
away_previous_points         1434.71
away_conf                        AFC
hour                              10
rank_diff                      -49.0
points_diff                   333.04
age_diff                    1.363636
Name: 903, dtype: object home_team_goals    2
away_team_goals    1
Name: 903, dtype: int64
model prediction: [[2 1]]
the match is:  home_team               Saudi Arabia
away_team                    Croatia
home_total_points            1433.95
home_rank_change                 2.0
home_previous_points         1434.71
home_conf                        AFC
away_total_points            1620.74
away_rank_change                 0.0
away_previous_points         1620.74
away_conf                       UEFA
hour                              12
rank_diff                       38.0
points_diff                  -186.79
age_diff                    2.090909
Name: 906, dtype: object home_team_goals    0
away_team_goals    1
Name: 906, dtype: int64
model prediction: [[2 2]]
the match is:  home_team                     Poland
away_team               Saudi Arabia
home_total_points            1530.62
home_rank_change                 1.0
home_previous_points         1530.62
home_conf                       UEFA
away_total_points            1433.95
away_rank_change                 2.0
away_previous_points         1434.71
away_conf                        AFC
hour                              13
rank_diff                      -25.0
points_diff                    96.67
age_diff                         1.0
Name: 907, dtype: object home_team_goals    0
away_team_goals    2
Name: 907, dtype: int64
model prediction: [[2 1]]
the match is:  home_team               Saudi Arabia
away_team                  Venezuela
home_total_points            1433.95
home_rank_change                 2.0
home_previous_points         1434.71
home_conf                        AFC
away_total_points            1411.45
away_rank_change                -1.0
away_previous_points         1409.14
away_conf                   CONMEBOL
hour                              17
rank_diff                       -5.0
points_diff                     22.5
age_diff                   -0.363636
Name: 909, dtype: object home_team_goals    0
away_team_goals    1
Name: 909, dtype: int64
model prediction: [[2 2]]
the match is:  home_team               Saudi Arabia
away_team                   Colombia
home_total_points            1433.95
home_rank_change                 2.0
home_previous_points         1434.71
home_conf                        AFC
away_total_points            1585.89
away_rank_change                 3.0
away_previous_points         1607.15
away_conf                   CONMEBOL
hour                              17
rank_diff                       34.0
points_diff                  -151.94
age_diff                         1.0
Name: 910, dtype: object home_team_goals    0
away_team_goals    1
Name: 910, dtype: int64
model prediction: [[2 2]]
the match is:  home_team                Austria
away_team               Scotland
home_total_points        1511.56
home_rank_change            -1.0
home_previous_points     1511.56
home_conf                   UEFA
away_total_points        1471.82
away_rank_change             2.0
away_previous_points     1471.82
away_conf                   UEFA
hour                          18
rank_diff                  -10.0
points_diff                39.74
age_diff                0.909091
Name: 918, dtype: object home_team_goals    2
away_team_goals    2
Name: 918, dtype: int64
model prediction: [[2 1]]
the match is:  home_team                Turkiye
away_team               Scotland
home_total_points        1472.72
home_rank_change             2.0
home_previous_points     1472.72
home_conf                   UEFA
away_total_points        1471.82
away_rank_change             2.0
away_previous_points     1471.82
away_conf                   UEFA
hour                          17
rank_diff                   -1.0
points_diff                  0.9
age_diff               -3.090909
Name: 923, dtype: object home_team_goals    2
away_team_goals    1
Name: 923, dtype: int64
model prediction: [[2 1]]
the match is:  home_team               Scotland
away_team                 Poland
home_total_points        1471.82
home_rank_change             2.0
home_previous_points     1471.82
home_conf                   UEFA
away_total_points        1530.62
away_rank_change             1.0
away_previous_points     1530.62
away_conf                   UEFA
hour                          19
rank_diff                   12.0
points_diff                -58.8
age_diff                    -1.0
Name: 952, dtype: object home_team_goals    1
away_team_goals    1
Name: 952, dtype: int64
model prediction: [[2 2]]
the match is:  home_team               Scotland
away_team                Ukraine
home_total_points        1471.82
home_rank_change             2.0
home_previous_points     1471.82
home_conf                   UEFA
away_total_points        1535.08
away_rank_change             2.0
away_previous_points     1535.08
away_conf                   UEFA
hour                          18
rank_diff                   13.0
points_diff               -63.26
age_diff                0.636364
Name: 953, dtype: object home_team_goals    1
away_team_goals    3
Name: 953, dtype: int64
model prediction: [[2 2]]
the match is:  home_team               Scotland
away_team                Ukraine
home_total_points        1471.82
home_rank_change             2.0
home_previous_points     1471.82
home_conf                   UEFA
away_total_points        1535.08
away_rank_change             2.0
away_previous_points     1535.08
away_conf                   UEFA
hour                          18
rank_diff                   13.0
points_diff               -63.26
age_diff                1.272727
Name: 954, dtype: object home_team_goals    3
away_team_goals    0
Name: 954, dtype: int64
model prediction: [[2 2]]
the match is:  home_team                Ukraine
away_team               Scotland
home_total_points        1535.08
home_rank_change             2.0
home_previous_points     1535.08
home_conf                   UEFA
away_total_points        1471.82
away_rank_change             2.0
away_previous_points     1471.82
away_conf                   UEFA
hour                          18
rank_diff                  -13.0
points_diff                63.26
age_diff               -2.090909
Name: 955, dtype: object home_team_goals    0
away_team_goals    0
Name: 955, dtype: int64
model prediction: [[2 1]]
the match is:  home_team               Scotland
away_team                Armenia
home_total_points        1471.82
home_rank_change             2.0
home_previous_points     1471.82
home_conf                   UEFA
away_total_points        1242.24
away_rank_change             0.0
away_previous_points     1242.24
away_conf                   UEFA
hour                          18
rank_diff                  -52.0
points_diff               229.58
age_diff               -2.454545
Name: 957, dtype: object

/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/3283078934.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/3283078934.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/3283078934.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/3283078934.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/3283078934.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/3283078934.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/3283078934.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/3283078934.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/3283078934.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/3283078934.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

home_team_goals    2
away_team_goals    0
Name: 957, dtype: int64
model prediction: [[3 1]]
the match is:  home_team                Armenia
away_team               Scotland
home_total_points        1242.24
home_rank_change             0.0
home_previous_points     1242.24
home_conf                   UEFA
away_total_points        1471.82
away_rank_change             2.0
away_previous_points     1471.82
away_conf                   UEFA
hour                          16
rank_diff                   52.0
points_diff              -229.58
age_diff                2.818182
Name: 958, dtype: object home_team_goals    1
away_team_goals    4
Name: 958, dtype: int64
model prediction: [[2 1]]
the match is:  home_team               Austria
away_team                France
home_total_points       1511.56
home_rank_change           -1.0
home_previous_points    1511.56
home_conf                  UEFA
away_total_points       1786.15
away_rank_change            0.0
away_previous_points    1786.15
away_conf                  UEFA
hour                         18
rank_diff                  27.0
points_diff             -274.59
age_diff                    1.0
Name: 962, dtype: object home_team_goals    1
away_team_goals    1
Name: 962, dtype: int64
model prediction: [[2 2]]
the match is:  home_team                 France
away_team                Austria
home_total_points        1786.15
home_rank_change             0.0
home_previous_points     1786.15
home_conf                   UEFA
away_total_points        1511.56
away_rank_change            -1.0
away_previous_points     1511.56
away_conf                   UEFA
hour                          18
rank_diff                  -27.0
points_diff               274.59
age_diff               -1.272727
Name: 963, dtype: object home_team_goals    2
away_team_goals    0
Name: 963, dtype: int64
model prediction: [[2 1]]
the match is:  home_team                France
away_team               Denmark
home_total_points       1786.15
home_rank_change            0.0
home_previous_points    1786.15
home_conf                  UEFA
away_total_points       1654.54
away_rank_change            0.0
away_previous_points    1654.54
away_conf                  UEFA
hour                         16
rank_diff                  -6.0
points_diff              131.61
age_diff                    1.0
Name: 964, dtype: object home_team_goals    2
away_team_goals    1
Name: 964, dtype: int64
model prediction: [[2 1]]
the match is:  home_team                 France
away_team                Denmark
home_total_points        1786.15
home_rank_change             0.0
home_previous_points     1786.15
home_conf                   UEFA
away_total_points        1654.54
away_rank_change             0.0
away_previous_points     1654.54
away_conf                   UEFA
hour                          18
rank_diff                   -6.0
points_diff               131.61
age_diff               -0.090909
Name: 965, dtype: object home_team_goals    1
away_team_goals    2
Name: 965, dtype: int64
model prediction: [[2 1]]
the match is:  home_team                Denmark
away_team                 France
home_total_points        1654.54
home_rank_change             0.0
home_previous_points     1654.54
home_conf                   UEFA
away_total_points        1786.15
away_rank_change             0.0
away_previous_points     1786.15
away_conf                   UEFA
hour                          18
rank_diff                    6.0
points_diff              -131.61
age_diff                1.363636
Name: 966, dtype: object home_team_goals    0
away_team_goals    2
Name: 966, dtype: int64
model prediction: [[2 2]]
the match is:  home_team                England
away_team                 France
home_total_points        1755.52
home_rank_change             1.0
home_previous_points     1755.52
home_conf                   UEFA
away_total_points        1786.15
away_rank_change             0.0
away_previous_points     1786.15
away_conf                   UEFA
hour                          19
rank_diff                    2.0
points_diff               -30.63
age_diff               -1.181818
Name: 967, dtype: object home_team_goals    2
away_team_goals    1
Name: 967, dtype: int64
model prediction: [[2 2]]
the match is:  home_team                 France
away_team                Morocco
home_total_points        1786.15
home_rank_change             0.0
home_previous_points     1786.15
home_conf                   UEFA
away_total_points        1547.42
away_rank_change            -4.0
away_previous_points     1529.93
away_conf                    CAF
hour                          19
rank_diff                  -21.0
points_diff               238.73
age_diff                0.181818
Name: 974, dtype: object home_team_goals    2
away_team_goals    0
Name: 974, dtype: int64
model prediction: [[2 1]]
the match is:  home_team               Argentina
away_team                  France
home_total_points         1766.99
home_rank_change             -1.0
home_previous_points      1750.51
home_conf                CONMEBOL
away_total_points         1786.15
away_rank_change              0.0
away_previous_points      1786.15
away_conf                    UEFA
hour                           15
rank_diff                     1.0
points_diff                -19.16
age_diff                 0.272727
Name: 977, dtype: object home_team_goals    2
away_team_goals    4
Name: 977, dtype: int64
model prediction: [[2 2]]
the match is:  home_team               Croatia
away_team                France
home_total_points       1620.74
home_rank_change            0.0
home_previous_points    1620.74
home_conf                  UEFA
away_total_points       1786.15
away_rank_change            0.0
away_previous_points    1786.15
away_conf                  UEFA
hour                         18
rank_diff                  12.0
points_diff             -165.41
age_diff                    3.0
Name: 982, dtype: object home_team_goals    1
away_team_goals    1
Name: 982, dtype: int64
model prediction: [[2 2]]
the match is:  home_team                 France
away_team                Croatia
home_total_points        1786.15
home_rank_change             0.0
home_previous_points     1786.15
home_conf                   UEFA
away_total_points        1620.74
away_rank_change             0.0
away_previous_points     1620.74
away_conf                   UEFA
hour                          18
rank_diff                  -12.0
points_diff               165.41
age_diff               -1.090909
Name: 983, dtype: object home_team_goals    0
away_team_goals    1
Name: 983, dtype: int64
model prediction: [[2 1]]
the match is:  home_team                 France
away_team                 Poland
home_total_points        1786.15
home_rank_change             0.0
home_previous_points     1786.15
home_conf                   UEFA
away_total_points        1530.62
away_rank_change             1.0
away_previous_points     1530.62
away_conf                   UEFA
hour                          15
rank_diff                  -25.0
points_diff               255.53
age_diff               -0.363636
Name: 987, dtype: object home_team_goals    3
away_team_goals    1
Name: 987, dtype: int64
model prediction: [[2 1]]
the match is:  home_team               Indonesia
away_team                 Curaçao
home_total_points         1001.61
home_rank_change             -4.0
home_previous_points       992.31
home_conf                     AFC
away_total_points         1298.39
away_rank_change              0.0
away_previous_points      1298.39
away_conf                CONCACAF
hour                           13
rank_diff                    80.0
points_diff               -296.78
age_diff                     -2.0
Name: 1001, dtype: object home_team_goals    3
away_team_goals    2
Name: 1001, dtype: int64
model prediction: [[2 2]]
the match is:  home_team               Indonesia
away_team                 Curaçao
home_total_points         1001.61
home_rank_change             -4.0
home_previous_points       992.31
home_conf                     AFC
away_total_points         1298.39
away_rank_change              0.0
away_previous_points      1298.39
away_conf                CONCACAF
hour                           13
rank_diff                    80.0
points_diff               -296.78
age_diff                -4.181818
Name: 1002, dtype: object home_team_goals    2
away_team_goals    1
Name: 1002, dtype: int64
model prediction: [[2 2]]
the match is:  home_team                Curaçao
away_team               Honduras
home_total_points        1298.39
home_rank_change             0.0
home_previous_points     1298.39
home_conf               CONCACAF
away_total_points        1303.96
away_rank_change             2.0
away_previous_points     1332.16
away_conf               CONCACAF
hour                           0
rank_diff                    2.0
points_diff                -5.57
age_diff                3.636364
Name: 1005, dtype: object home_team_goals    0
away_team_goals    1
Name: 1005, dtype: int64
model prediction: [[3 1]]
the match is:  home_team               Honduras
away_team                Curaçao
home_total_points        1303.96
home_rank_change             2.0
home_previous_points     1332.16
home_conf               CONCACAF
away_total_points        1298.39
away_rank_change             0.0
away_previous_points     1298.39
away_conf               CONCACAF
hour                           2
rank_diff                   -2.0
points_diff                 5.57
age_diff               -3.181818
Name: 1006, dtype: object home_team_goals    1
away_team_goals    2
Name: 1006, dtype: int64
model prediction: [[2 1]]
the match is:  home_team                Curaçao
away_team                  Aruba
home_total_points        1298.39
home_rank_change             0.0
home_previous_points     1298.39
home_conf               CONCACAF
away_total_points         859.97
away_rank_change             0.0
away_previous_points      859.97
away_conf               CONCACAF
hour                           1
rank_diff                 -120.0
points_diff               438.42
age_diff               -0.393939
Name: 1019, dtype: object home_team_goals    5
away_team_goals    3
Name: 1019, dtype: int64
model prediction: [[4 0]]
the match is:  home_team                Curaçao
away_team               Suriname
home_total_points        1298.39
home_rank_change             0.0
home_previous_points     1298.39
home_conf               CONCACAF
away_total_points        1077.57
away_rank_change             1.0
away_previous_points     1077.57
away_conf               CONCACAF
hour                           1
rank_diff                  -60.0
points_diff               220.82
age_diff                1.636364
Name: 1022, dtype: object home_team_goals    6
away_team_goals    5
Name: 1022, dtype: int64
model prediction: [[3 1]]
the match is:  home_team                Hungary
away_team                England
home_total_points        1465.62
home_rank_change             2.0
home_previous_points     1465.62
home_conf                   UEFA
away_total_points        1755.52
away_rank_change             1.0
away_previous_points     1755.52
away_conf                   UEFA
hour                          16
rank_diff                   36.0
points_diff               -289.9
age_diff                1.909091
Name: 1025, dtype: object home_team_goals    0
away_team_goals    1
Name: 1025, dtype: int64

/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/3283078934.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/3283078934.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/3283078934.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/3283078934.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/3283078934.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/3283078934.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/3283078934.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/3283078934.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:

model prediction: [[2 2]]
the match is:  home_team                England
away_team                Hungary
home_total_points        1755.52
home_rank_change             1.0
home_previous_points     1755.52
home_conf                   UEFA
away_total_points        1465.62
away_rank_change             2.0
away_previous_points     1465.62
away_conf                   UEFA
hour                          18
rank_diff                  -36.0
points_diff                289.9
age_diff               -2.727273
Name: 1026, dtype: object home_team_goals    0
away_team_goals    4
Name: 1026, dtype: int64
model prediction: [[3 1]]
the match is:  home_team                England
away_team                  Italy
home_total_points        1755.52
home_rank_change             1.0
home_previous_points     1755.52
home_conf                   UEFA
away_total_points        1740.77
away_rank_change             0.0
away_previous_points     1740.77
away_conf                   UEFA
hour                          18
rank_diff                   -1.0
points_diff                14.75
age_diff                0.818182
Name: 1031, dtype: object home_team_goals    0
away_team_goals    0
Name: 1031, dtype: int64
model prediction: [[2 2]]
the match is:  home_team                 Italy
away_team               England
home_total_points       1740.77
home_rank_change            0.0
home_previous_points    1740.77
home_conf                  UEFA
away_total_points       1755.52
away_rank_change            1.0
away_previous_points    1755.52
away_conf                  UEFA
hour                         18
rank_diff                   1.0
points_diff              -14.75
age_diff                    2.0
Name: 1032, dtype: object home_team_goals    0
away_team_goals    1
Name: 1032, dtype: int64
model prediction: [[2 2]]
the match is:  home_team                  Wales
away_team                England
home_total_points        1578.01
home_rank_change             1.0
home_previous_points     1578.01
home_conf                   UEFA
away_total_points        1755.52
away_rank_change             1.0
away_previous_points     1755.52
away_conf                   UEFA
hour                          19
rank_diff                   15.0
points_diff              -177.51
age_diff                0.818182
Name: 1044, dtype: object home_team_goals    3
away_team_goals    0
Name: 1044, dtype: int64
model prediction: [[2 2]]
the match is:  home_team                   England
away_team               Switzerland
home_total_points           1755.52
home_rank_change                1.0
home_previous_points        1755.52
home_conf                      UEFA
away_total_points           1642.83
away_rank_change                1.0
away_previous_points        1642.83
away_conf                      UEFA
hour                             17
rank_diff                      -9.0
points_diff                  112.69
age_diff                  -3.090909
Name: 1053, dtype: object home_team_goals    2
away_team_goals    1
Name: 1053, dtype: int64
model prediction: [[2 1]]
the match is:  home_team                 Guyana
away_team                  Haiti
home_total_points         958.87
home_rank_change            -1.0
home_previous_points      958.87
home_conf               CONCACAF
away_total_points        1268.05
away_rank_change             0.0
away_previous_points     1268.05
away_conf               CONCACAF
hour                          20
rank_diff                   88.0
points_diff              -309.18
age_diff                0.727273
Name: 1070, dtype: object home_team_goals    2
away_team_goals    6
Name: 1070, dtype: int64
model prediction: [[2 2]]
the match is:  home_team                  Haiti
away_team                 Guyana
home_total_points        1268.05
home_rank_change             0.0
home_previous_points     1268.05
home_conf               CONCACAF
away_total_points         958.87
away_rank_change            -1.0
away_previous_points      958.87
away_conf               CONCACAF
hour                          22
rank_diff                  -88.0
points_diff               309.18
age_diff               -0.272727
Name: 1071, dtype: object home_team_goals    6
away_team_goals    0
Name: 1071, dtype: int64
model prediction: [[4 1]]
the match is:  home_team                    Haiti
away_team               Montserrat
home_total_points          1268.05
home_rank_change               0.0
home_previous_points       1268.05
home_conf                 CONCACAF
away_total_points           950.71
away_rank_change               0.0
away_previous_points        950.71
away_conf                 CONCACAF
hour                            21
rank_diff                    -91.0
points_diff                 317.34
age_diff                      -3.0
Name: 1079, dtype: object home_team_goals    3
away_team_goals    2
Name: 1079, dtype: int64
model prediction: [[3 1]]
the match is:  home_team                Bermuda
away_team                  Haiti
home_total_points         982.43
home_rank_change             0.0
home_previous_points      982.43
home_conf               CONCACAF
away_total_points        1268.05
away_rank_change             0.0
away_previous_points     1268.05
away_conf               CONCACAF
hour                          21
rank_diff                   79.0
points_diff              -285.62
age_diff               -0.181818
Name: 1081, dtype: object home_team_goals    0
away_team_goals    0
Name: 1081, dtype: int64
model prediction: [[2 1]]
the match is:  home_team               Guatemala
away_team                   Haiti
home_total_points          1138.4
home_rank_change              1.0
home_previous_points       1138.4
home_conf                CONCACAF
away_total_points         1268.05
away_rank_change              0.0
away_previous_points      1268.05
away_conf                CONCACAF
hour                           20
rank_diff                    36.0
points_diff               -129.65
age_diff                 2.363636
Name: 1086, dtype: object home_team_goals    2
away_team_goals    1
Name: 1086, dtype: int64
model prediction: [[2 1]]
the match is:  home_team                  Costa Rica
away_team               United States
home_total_points             1464.06
home_rank_change                 -7.0
home_previous_points          1437.43
home_conf                    CONCACAF
away_total_points             1643.34
away_rank_change                  2.0
away_previous_points          1648.51
away_conf                    CONCACAF
hour                                1
rank_diff                        29.0
points_diff                   -179.28
age_diff                    -0.636364
Name: 1095, dtype: object home_team_goals    2
away_team_goals    0
Name: 1095, dtype: int64
model prediction: [[2 2]]
the match is:  home_team                     England
away_team               United States
home_total_points             1755.52
home_rank_change                  1.0
home_previous_points          1755.52
home_conf                        UEFA
away_total_points             1643.34
away_rank_change                  2.0
away_previous_points          1648.51
away_conf                    CONCACAF
hour                               19
rank_diff                        -8.0
points_diff                    112.18
age_diff                          1.0
Name: 1097, dtype: object home_team_goals    0
away_team_goals    0
Name: 1097, dtype: int64
model prediction: [[2 1]]
the match is:  home_team                Saudi Arabia
away_team               United States
home_total_points             1433.95
home_rank_change                  2.0
home_previous_points          1434.71
home_conf                         AFC
away_total_points             1643.34
away_rank_change                  2.0
away_previous_points          1648.51
away_conf                    CONCACAF
hour                               18
rank_diff                        40.0
points_diff                   -209.39
age_diff                     1.272727
Name: 1104, dtype: object home_team_goals    0
away_team_goals    0
Name: 1104, dtype: int64
model prediction: [[1 2]]
the match is:  home_team                 Netherlands
away_team               United States
home_total_points             1653.73
home_rank_change                  0.0
home_previous_points          1653.73
home_conf                        UEFA
away_total_points             1643.34
away_rank_change                  2.0
away_previous_points          1648.51
away_conf                    CONCACAF
hour                               15
rank_diff                        -3.0
points_diff                     10.39
age_diff                     2.454545
Name: 1108, dtype: object home_team_goals    3
away_team_goals    1
Name: 1108, dtype: int64
model prediction: [[2 1]]
the match is:  home_team               United States
away_team                      Panama
home_total_points             1643.34
home_rank_change                  2.0
home_previous_points          1648.51
home_conf                    CONCACAF
away_total_points             1375.56
away_rank_change                  0.0
away_previous_points          1379.34
away_conf                    CONCACAF
hour                               23
rank_diff                       -50.0
points_diff                    267.78
age_diff                    -4.181818
Name: 1114, dtype: object home_team_goals    5
away_team_goals    1
Name: 1114, dtype: int64
model prediction: [[2 1]]
the match is:  home_team                        Iran
away_team               United States
home_total_points             1572.89
home_rank_change                  0.0
home_previous_points          1557.58
home_conf                         AFC
away_total_points             1643.34
away_rank_change                  2.0
away_previous_points          1648.51
away_conf                    CONCACAF
hour                               19
rank_diff                         8.0
points_diff                    -70.45
age_diff                     4.272727
Name: 1116, dtype: object home_team_goals    0
away_team_goals    1
Name: 1116, dtype: int64
model prediction: [[1 2]]
the match is:

/tmp/ipykernel_73008/3283078934.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/3283078934.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/3283078934.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/3283078934.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/3283078934.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/3283078934.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/3283078934.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/3283078934.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

home_team               United States
away_team                     Grenada
home_total_points             1643.34
home_rank_change                  2.0
home_previous_points          1648.51
home_conf                    CONCACAF
away_total_points              974.03
away_rank_change                  1.0
away_previous_points           974.03
away_conf                    CONCACAF
hour                                2
rank_diff                      -156.0
points_diff                    669.31
age_diff                     0.272727
Name: 1119, dtype: object home_team_goals    5
away_team_goals    0
Name: 1119, dtype: int64
model prediction: [[4 0]]
the match is:  home_team               United States
away_team                     Morocco
home_total_points             1643.34
home_rank_change                  2.0
home_previous_points          1648.51
home_conf                    CONCACAF
away_total_points             1547.42
away_rank_change                 -4.0
away_previous_points          1529.93
away_conf                         CAF
hour                               23
rank_diff                       -11.0
points_diff                     95.92
age_diff                    -3.363636
Name: 1120, dtype: object home_team_goals    3
away_team_goals    0
Name: 1120, dtype: int64
model prediction: [[1 2]]
the match is:  home_team               United States
away_team                     Uruguay
home_total_points             1643.34
home_rank_change                  2.0
home_previous_points          1648.51
home_conf                    CONCACAF
away_total_points             1614.05
away_rank_change                 -1.0
away_previous_points          1596.66
away_conf                    CONMEBOL
hour                               21
rank_diff                        -3.0
points_diff                     29.29
age_diff                    -3.363636
Name: 1124, dtype: object home_team_goals    0
away_team_goals    0
Name: 1124, dtype: int64
model prediction: [[1 2]]
the match is:  home_team               United States
away_team                       Wales
home_total_points             1643.34
home_rank_change                  2.0
home_previous_points          1648.51
home_conf                    CONCACAF
away_total_points             1578.01
away_rank_change                  1.0
away_previous_points          1578.01
away_conf                        UEFA
hour                               19
rank_diff                        -7.0
points_diff                     65.33
age_diff                    -2.272727
Name: 1125, dtype: object home_team_goals    1
away_team_goals    1
Name: 1125, dtype: int64
model prediction: [[2 2]]
the match is:  home_team                 El Salvador
away_team               United States
home_total_points             1346.04
home_rank_change                  0.0
home_previous_points          1349.47
home_conf                    CONCACAF
away_total_points             1643.34
away_rank_change                  2.0
away_previous_points          1648.51
away_conf                    CONCACAF
hour                                2
rank_diff                        57.0
points_diff                    -297.3
age_diff                          3.0
Name: 1129, dtype: object home_team_goals    1
away_team_goals    1
Name: 1129, dtype: int64
model prediction: [[1 2]]
the match is:  home_team                       Japan
away_team               United States
home_total_points             1549.82
home_rank_change                 -3.0
home_previous_points          1531.53
home_conf                         AFC
away_total_points             1643.34
away_rank_change                  2.0
away_previous_points          1648.51
away_conf                    CONCACAF
hour                               12
rank_diff                        10.0
points_diff                    -93.52
age_diff                     3.454545
Name: 1133, dtype: object home_team_goals    2
away_team_goals    0
Name: 1133, dtype: int64
model prediction: [[1 2]]
the match is:  home_team                   Panama
away_team               Costa Rica
home_total_points          1375.56
home_rank_change               0.0
home_previous_points       1379.34
home_conf                 CONCACAF
away_total_points          1464.06
away_rank_change              -7.0
away_previous_points       1437.43
away_conf                 CONCACAF
hour                            23
rank_diff                     21.0
points_diff                  -88.5
age_diff                  2.545455
Name: 1145, dtype: object home_team_goals    2
away_team_goals    0
Name: 1145, dtype: int64
model prediction: [[2 2]]
the match is:  home_team                 Panama
away_team               Honduras
home_total_points        1375.56
home_rank_change             0.0
home_previous_points     1379.34
home_conf               CONCACAF
away_total_points        1303.96
away_rank_change             2.0
away_previous_points     1332.16
away_conf               CONCACAF
hour                           1
rank_diff                  -15.0
points_diff                 71.6
age_diff                     1.0
Name: 1157, dtype: object home_team_goals    1
away_team_goals    1
Name: 1157, dtype: int64
model prediction: [[3 1]]
the match is:  home_team               Cameroon
away_team                 Panama
home_total_points        1480.82
home_rank_change           -12.0
home_previous_points     1437.35
home_conf                    CAF
away_total_points        1375.56
away_rank_change             0.0
away_previous_points     1379.34
away_conf               CONCACAF
hour                          10
rank_diff                  -25.0
points_diff               105.26
age_diff                0.818182
Name: 1163, dtype: object home_team_goals    1
away_team_goals    1
Name: 1163, dtype: int64
model prediction: [[2 1]]
the match is:  home_team               Venezuela
away_team                  Panama
home_total_points         1411.45
home_rank_change             -1.0
home_previous_points      1409.14
home_conf                CONMEBOL
away_total_points         1375.56
away_rank_change              0.0
away_previous_points      1379.34
away_conf                CONCACAF
hour                           17
rank_diff                    -5.0
points_diff                 35.89
age_diff                      0.0
Name: 1177, dtype: object home_team_goals    2
away_team_goals    2
Name: 1177, dtype: int64
model prediction: [[2 1]]
the match is:  home_team               Indonesia
away_team                  Jordan
home_total_points         1001.61
home_rank_change             -4.0
home_previous_points       992.31
home_conf                     AFC
away_total_points         1259.84
away_rank_change              0.0
away_previous_points      1255.69
away_conf                     AFC
hour                           19
rank_diff                    70.0
points_diff               -258.23
age_diff                -3.454545
Name: 1190, dtype: object home_team_goals    1
away_team_goals    0
Name: 1190, dtype: int64
model prediction: [[2 2]]
the match is:  home_team                 Jordan
away_team                   Oman
home_total_points        1259.84
home_rank_change             0.0
home_previous_points     1255.69
home_conf                    AFC
away_total_points         1301.0
away_rank_change             0.0
away_previous_points     1306.01
away_conf                    AFC
hour                          18
rank_diff                   11.0
points_diff               -41.16
age_diff               -0.545455
Name: 1197, dtype: object home_team_goals    1
away_team_goals    0
Name: 1197, dtype: int64
model prediction: [[2 1]]
the match is:  home_team                  India
away_team                 Jordan
home_total_points        1182.75
home_rank_change             0.0
home_previous_points     1182.75
home_conf                    AFC
away_total_points        1259.84
away_rank_change             0.0
away_previous_points     1255.69
away_conf                    AFC
hour                          16
rank_diff                   14.0
points_diff               -77.09
age_diff               -0.636364
Name: 1201, dtype: object home_team_goals    2
away_team_goals    0
Name: 1201, dtype: int64
model prediction: [[2 1]]
the match is:  home_team                 Jordan
away_team                  Syria
home_total_points        1259.84
home_rank_change             0.0
home_previous_points     1255.69
home_conf                    AFC
away_total_points        1251.22
away_rank_change             5.0
away_previous_points     1268.54
away_conf                    AFC
hour                          18
rank_diff                   -1.0
points_diff                 8.62
age_diff                5.363636
Name: 1203, dtype: object home_team_goals    2
away_team_goals    0
Name: 1203, dtype: int64
model prediction: [[2 1]]
the match is:  home_team                 Kuwait
away_team                 Jordan
home_total_points        1065.56
home_rank_change             1.0
home_previous_points     1064.02
home_conf                    AFC
away_total_points        1259.84
away_rank_change             0.0
away_previous_points     1255.69
away_conf                    AFC
hour                          16
rank_diff                   53.0
points_diff              -194.28
age_diff                0.818182
Name: 1207, dtype: object home_team_goals    3
away_team_goals    0
Name: 1207, dtype: int64
model prediction: [[2 1]]
the match is:  home_team                 Jordan
away_team                  Nepal
home_total_points        1259.84
home_rank_change             0.0
home_previous_points     1255.69
home_conf                    AFC
away_total_points         982.22
away_rank_change            -2.0
away_previous_points      972.45
away_conf                    AFC
hour                          19
rank_diff                  -77.0
points_diff               277.62
age_diff                3.727273
Name: 1208, dtype: object home_team_goals    2
away_team_goals    0
Name: 1208, dtype: int64
model prediction: [[3 1]]
the match is:  home_team               Denmark
away_team               Croatia
home_total_points       1654.54
home_rank_change            0.0
home_previous_points    1654.54
home_conf                  UEFA
away_total_points       1620.74
away_rank_change            0.0
away_previous_points    1620.74
away_conf                  UEFA
hour                         18
rank_diff                  -6.0
points_diff                33.8
age_diff                    1.0
Name: 1215, dtype: object home_team_goals    1
away_team_goals    0
Name: 1215, dtype: int64
model prediction: [[2 1]]
the match is:  home_team                Croatia
away_team                Denmark
home_total_points        1620.74
home_rank_change             0.0
home_previous_points     1620.74
home_conf                   UEFA
away_total_points        1654.54
away_rank_change             0.0
away_previous_points     1654.54
away_conf                   UEFA
hour                          18
rank_diff                    6.0
points_diff                -33.8
age_diff               -1.363636
Name: 1216, dtype: object home_team_goals    2
away_team_goals    1
Name: 1216, dtype: int64
model prediction: [[2 2]]
the match is:  home_team                Croatia
away_team                 Canada
home_total_points        1620.74
home_rank_change             0.0
home_previous_points     1620.74
home_conf                   UEFA
away_total_points        1497.82
away_rank_change            -7.0
away_previous_points     1462.32
away_conf               CONCACAF
hour                          16
rank_diff                  -18.0
points_diff               122.92
age_diff                1.272727
Name: 1219, dtype: object home_team_goals    4
away_team_goals    1
Name: 1219, dtype: int64
model prediction: [[2 1]]
the match is:  home_team                Croatia
away_team               Slovenia
home_total_points        1620.74
home_rank_change             0.0
home_previous_points     1620.74
home_conf                   UEFA
away_total_points        1375.42
away_rank_change            -1.0
away_previous_points     1375.42
away_conf                   UEFA
hour                          14
rank_diff                  -49.0
points_diff               245.32
age_diff                1.181818
Name: 1220, dtype: object home_team_goals    1
away_team_goals    1
Name: 1220, dtype: int64

/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/3283078934.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/3283078934.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/3283078934.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/3283078934.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/3283078934.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/3283078934.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/3283078934.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

model prediction: [[3 1]]
the match is:  home_team                Croatia
away_team               Bulgaria
home_total_points        1620.74
home_rank_change             0.0
home_previous_points     1620.74
home_conf                   UEFA
away_total_points        1345.47
away_rank_change             0.0
away_previous_points     1345.47
away_conf                   UEFA
hour                          14
rank_diff                  -56.0
points_diff               275.27
age_diff                2.272727
Name: 1230, dtype: object home_team_goals    2
away_team_goals    1
Name: 1230, dtype: int64
model prediction: [[3 1]]
the match is:  home_team               Colombia
away_team                Bolivia
home_total_points        1585.89
home_rank_change             3.0
home_previous_points     1607.15
home_conf               CONMEBOL
away_total_points        1308.12
away_rank_change            -1.0
away_previous_points     1324.21
away_conf               CONMEBOL
hour                          23
rank_diff                  -57.0
points_diff               277.77
age_diff                4.545455
Name: 1251, dtype: object home_team_goals    3
away_team_goals    0
Name: 1251, dtype: int64
model prediction: [[3 1]]
the match is:  home_team                 Mexico
away_team               Colombia
home_total_points         1647.9
home_rank_change            -2.0
home_previous_points      1638.3
home_conf               CONCACAF
away_total_points        1585.89
away_rank_change             3.0
away_previous_points     1607.15
away_conf               CONMEBOL
hour                           2
rank_diff                   -7.0
points_diff                62.01
age_diff               -0.545455
Name: 1254, dtype: object home_team_goals    3
away_team_goals    2
Name: 1254, dtype: int64
model prediction: [[2 1]]
the match is:  home_team                Colombia
away_team               Guatemala
home_total_points         1585.89
home_rank_change              3.0
home_previous_points      1607.15
home_conf                CONMEBOL
away_total_points          1138.4
away_rank_change              1.0
away_previous_points       1138.4
away_conf                CONCACAF
hour                           23
rank_diff                  -104.0
points_diff                447.49
age_diff                 1.636364
Name: 1255, dtype: object home_team_goals    4
away_team_goals    1
Name: 1255, dtype: int64
model prediction: [[3 1]]
the match is:  home_team               Venezuela
away_team                Colombia
home_total_points         1411.45
home_rank_change             -1.0
home_previous_points      1409.14
home_conf                CONMEBOL
away_total_points         1585.89
away_rank_change              3.0
away_previous_points      1607.15
away_conf                CONMEBOL
hour                           23
rank_diff                    39.0
points_diff               -174.44
age_diff                -0.545455
Name: 1260, dtype: object home_team_goals    1
away_team_goals    0
Name: 1260, dtype: int64
model prediction: [[2 2]]
the match is:  home_team                   Iraq
away_team                 Zambia
home_total_points        1325.44
home_rank_change            -1.0
home_previous_points     1333.03
home_conf                    AFC
away_total_points        1264.64
away_rank_change             0.0
away_previous_points     1264.64
away_conf                    CAF
hour                          17
rank_diff                  -14.0
points_diff                 60.8
age_diff                2.909091
Name: 1281, dtype: object home_team_goals    3
away_team_goals    1
Name: 1281, dtype: int64
model prediction: [[2 1]]
the match is:  home_team                   Iraq
away_team                   Oman
home_total_points        1325.44
home_rank_change            -1.0
home_previous_points     1333.03
home_conf                    AFC
away_total_points         1301.0
away_rank_change             0.0
away_previous_points     1306.01
away_conf                    AFC
hour                          15
rank_diff                   -5.0
points_diff                24.44
age_diff               -1.636364
Name: 1287, dtype: object home_team_goals    3
away_team_goals    4
Name: 1287, dtype: int64
model prediction: [[2 1]]
the match is:  home_team                 Mexico
away_team                   Iraq
home_total_points         1647.9
home_rank_change            -2.0
home_previous_points      1638.3
home_conf               CONCACAF
away_total_points        1325.44
away_rank_change            -1.0
away_previous_points     1333.03
away_conf                    AFC
hour                          20
rank_diff                  -62.0
points_diff               322.46
age_diff                3.363636
Name: 1289, dtype: object home_team_goals    0
away_team_goals    4
Name: 1289, dtype: int64
model prediction: [[2 1]]
the match is:  home_team                  Syria
away_team                   Iraq
home_total_points        1251.22
home_rank_change             5.0
home_previous_points     1268.54
home_conf                    AFC
away_total_points        1325.44
away_rank_change            -1.0
away_previous_points     1333.03
away_conf                    AFC
hour                          13
rank_diff                   17.0
points_diff               -74.22
age_diff                0.727273
Name: 1292, dtype: object home_team_goals    1
away_team_goals    1
Name: 1292, dtype: int64
model prediction: [[2 1]]
the match is:  home_team                   Iraq
away_team                 Kuwait
home_total_points        1325.44
home_rank_change            -1.0
home_previous_points     1333.03
home_conf                    AFC
away_total_points        1065.56
away_rank_change             1.0
away_previous_points     1064.02
away_conf                    AFC
hour                          12
rank_diff                  -69.0
points_diff               259.88
age_diff               -0.636364
Name: 1295, dtype: object home_team_goals    1
away_team_goals    0
Name: 1295, dtype: int64
model prediction: [[3 1]]
the match is:  home_team               Portugal
away_team                  Ghana
home_total_points        1660.25
home_rank_change             0.0
home_previous_points     1660.25
home_conf                   UEFA
away_total_points        1381.45
away_rank_change             9.0
away_previous_points     1428.97
away_conf                    CAF
hour                          16
rank_diff                  -53.0
points_diff                278.8
age_diff                1.363636
Name: 1306, dtype: object home_team_goals    3
away_team_goals    2
Name: 1306, dtype: int64
model prediction: [[3 1]]
the match is:  home_team                      Portugal
away_team               North Macedonia
home_total_points               1660.25
home_rank_change                    0.0
home_previous_points            1660.25
home_conf                          UEFA
away_total_points               1367.23
away_rank_change                    0.0
away_previous_points            1367.23
away_conf                          UEFA
hour                                 18
rank_diff                         -59.0
points_diff                      293.02
age_diff                       1.636364
Name: 1313, dtype: object home_team_goals    2
away_team_goals    0
Name: 1313, dtype: int64
model prediction: [[3 1]]
the match is:  home_team               South Korea
away_team                  Portugal
home_total_points           1522.85
home_rank_change               -4.0
home_previous_points        1507.24
home_conf                       AFC
away_total_points           1660.25
away_rank_change                0.0
away_previous_points        1660.25
away_conf                      UEFA
hour                             15
rank_diff                      21.0
points_diff                  -137.4
age_diff                   1.636364
Name: 1314, dtype: object home_team_goals    1
away_team_goals    2
Name: 1314, dtype: int64
model prediction: [[2 2]]
the match is:  home_team                Morocco
away_team               Portugal
home_total_points        1547.42
home_rank_change            -4.0
home_previous_points     1529.93
home_conf                    CAF
away_total_points        1660.25
away_rank_change             0.0
away_previous_points     1660.25
away_conf                   UEFA
hour                          15
rank_diff                   16.0
points_diff              -112.83
age_diff                0.909091
Name: 1318, dtype: object home_team_goals    0
away_team_goals    1
Name: 1318, dtype: int64
model prediction: [[2 2]]
the match is:  home_team               Portugal
away_team                Nigeria
home_total_points        1660.25
home_rank_change             0.0
home_previous_points     1660.25
home_conf                   UEFA
away_total_points        1509.91
away_rank_change            -4.0
away_previous_points     1478.78
away_conf                    CAF
hour                          18
rank_diff                  -24.0
points_diff               150.34
age_diff                0.272727
Name: 1322, dtype: object home_team_goals    4
away_team_goals    0
Name: 1322, dtype: int64
model prediction: [[2 1]]
the match is:  home_team                  Portugal
away_team               Switzerland
home_total_points           1660.25
home_rank_change                0.0
home_previous_points        1660.25
home_conf                      UEFA
away_total_points           1642.83
away_rank_change                1.0
away_previous_points        1642.83
away_conf                      UEFA
hour                             19
rank_diff                      -6.0
points_diff                   17.42
age_diff                  -1.545455
Name: 1329, dtype: object home_team_goals    6
away_team_goals    1
Name: 1329, dtype: int64
model prediction: [[2 2]]
the match is:  home_team                  Portugal
away_team               Switzerland
home_total_points           1660.25
home_rank_change                0.0
home_previous_points        1660.25
home_conf                      UEFA
away_total_points           1642.83
away_rank_change                1.0
away_previous_points        1642.83
away_conf                      UEFA
hour                             18
rank_diff                      -6.0
points_diff                   17.42
age_diff                   0.727273
Name: 1330, dtype: object home_team_goals    4
away_team_goals    0
Name: 1330, dtype: int64
model prediction: [[2 2]]
the match is:  home_team               Switzerland
away_team                  Portugal
home_total_points           1642.83
home_rank_change                1.0
home_previous_points        1642.83
home_conf                      UEFA
away_total_points           1660.25
away_rank_change                0.0
away_previous_points        1660.25
away_conf                      UEFA
hour                             18
rank_diff                       6.0
points_diff                  -17.42
age_diff                   0.636364
Name: 1331, dtype: object home_team_goals    0
away_team_goals    1
Name: 1331, dtype: int64
model prediction: [[2 2]]
the match is:  home_team                 Jamaica
away_team               Argentina
home_total_points         1378.62
home_rank_change              5.0
home_previous_points      1412.13
home_conf                CONCACAF
away_total_points         1766.99
away_rank_change             -1.0
away_previous_points      1750.51
away_conf                CONMEBOL
hour                            0
rank_diff                    58.0
points_diff               -388.37
age_diff                 1.454545
Name: 1374, dtype: object home_team_goals    3
away_team_goals    0
Name: 1374, dtype: int64
model prediction: [[1 2]]
the match is:  home_team                   Italy
away_team               Argentina
home_total_points         1740.77
home_rank_change              0.0
home_previous_points      1740.77
home_conf                    UEFA
away_total_points         1766.99
away_rank_change             -1.0
away_previous_points      1750.51
away_conf                CONMEBOL
hour                           18
rank_diff                     2.0
points_diff                -26.22
age_diff                -0.454545
Name: 1375, dtype: object home_team_goals    3
away_team_goals    0
Name: 1375, dtype: int64
model prediction: [[2 1]]
the match is:  home_team               Argentina
away_team                Honduras
home_total_points         1766.99
home_rank_change             -1.0
home_previous_points      1750.51
home_conf                CONMEBOL
away_total_points         1303.96
away_rank_change              2.0
away_previous_points      1332.16
away_conf                CONCACAF
hour                            0
rank_diff                   -74.0
points_diff                463.03
age_diff                 0.909091
Name: 1382, dtype: object home_team_goals    3
away_team_goals    0
Name: 1382, dtype: int64
model prediction: [[3 1]]
the match is:  home_team               Argentina
away_team                 Estonia
home_total_points         1766.99
home_rank_change             -1.0
home_previous_points      1750.51
home_conf                CONMEBOL
away_total_points          1176.5
away_rank_change             -1.0
away_previous_points       1176.5
away_conf                    UEFA
hour                           18
rank_diff                  -102.0
points_diff                590.49
age_diff                 2.454545
Name: 1383, dtype: object home_team_goals    5
away_team_goals    0
Name: 1383, dtype: int64
model prediction: [[3 1]]
the match is:  home_team               Argentina
away_team                  Mexico
home_total_points         1766.99
home_rank_change             -1.0
home_previous_points      1750.51
home_conf                CONMEBOL
away_total_points          1647.9
away_rank_change             -2.0
away_previous_points       1638.3
away_conf                CONCACAF
hour                           19
rank_diff                    -8.0
points_diff                119.09
age_diff                -0.545455
Name: 1388, dtype: object home_team_goals    2
away_team_goals    0
Name: 1388, dtype: int64

/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/3283078934.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/3283078934.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/3283078934.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/3283078934.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/3283078934.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/3283078934.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

model prediction: [[2 1]]
the match is:  home_team               Argentina
away_team                 Croatia
home_total_points         1766.99
home_rank_change             -1.0
home_previous_points      1750.51
home_conf                CONMEBOL
away_total_points         1620.74
away_rank_change              0.0
away_previous_points      1620.74
away_conf                    UEFA
hour                           19
rank_diff                   -11.0
points_diff                146.25
age_diff                -1.545455
Name: 1392, dtype: object home_team_goals    3
away_team_goals    0
Name: 1392, dtype: int64
model prediction: [[2 2]]
the match is:  home_team                  Poland
away_team               Argentina
home_total_points         1530.62
home_rank_change              1.0
home_previous_points      1530.62
home_conf                    UEFA
away_total_points         1766.99
away_rank_change             -1.0
away_previous_points      1750.51
away_conf                CONMEBOL
hour                           19
rank_diff                    24.0
points_diff               -236.37
age_diff                 0.545455
Name: 1393, dtype: object home_team_goals    2
away_team_goals    0
Name: 1393, dtype: int64
model prediction: [[2 2]]
the match is:  home_team               Argentina
away_team               Venezuela
home_total_points         1766.99
home_rank_change             -1.0
home_previous_points      1750.51
home_conf                CONMEBOL
away_total_points         1411.45
away_rank_change             -1.0
away_previous_points      1409.14
away_conf                CONMEBOL
hour                           23
rank_diff                   -54.0
points_diff                355.54
age_diff                 2.636364
Name: 1397, dtype: object home_team_goals    3
away_team_goals    0
Name: 1397, dtype: int64
model prediction: [[2 1]]
the match is:  home_team               Netherlands
away_team                     Qatar
home_total_points           1653.73
home_rank_change                0.0
home_previous_points        1653.73
home_conf                      UEFA
away_total_points           1437.91
away_rank_change                4.0
away_previous_points        1437.91
away_conf                       AFC
hour                             15
rank_diff                     -42.0
points_diff                  215.82
age_diff                  -1.181818
Name: 1412, dtype: object home_team_goals    2
away_team_goals    0
Name: 1412, dtype: int64
model prediction: [[2 1]]
the match is:  home_team                 Canada
away_team                  Qatar
home_total_points        1497.82
home_rank_change            -7.0
home_previous_points     1462.32
home_conf               CONCACAF
away_total_points        1437.91
away_rank_change             4.0
away_previous_points     1437.91
away_conf                    AFC
hour                          17
rank_diff                  -19.0
points_diff                59.91
age_diff               -0.181818
Name: 1413, dtype: object home_team_goals    2
away_team_goals    0
Name: 1413, dtype: int64
model prediction: [[2 1]]
the match is:  home_team                  Qatar
away_team               Slovenia
home_total_points        1437.91
home_rank_change             4.0
home_previous_points     1437.91
home_conf                    AFC
away_total_points        1375.42
away_rank_change            -1.0
away_previous_points     1375.42
away_conf                   UEFA
hour                          17
rank_diff                  -12.0
points_diff                62.49
age_diff                1.454545
Name: 1416, dtype: object home_team_goals    0
away_team_goals    0
Name: 1416, dtype: int64
model prediction: [[2 2]]
the match is:  home_team                  Qatar
away_team                  Chile
home_total_points        1437.91
home_rank_change             4.0
home_previous_points     1437.91
home_conf                    AFC
away_total_points        1543.16
away_rank_change             2.0
away_previous_points     1543.42
away_conf               CONMEBOL
hour                          17
rank_diff                   26.0
points_diff              -105.25
age_diff               -0.545455
Name: 1417, dtype: object home_team_goals    2
away_team_goals    2
Name: 1417, dtype: int64
model prediction: [[2 2]]
the match is:  home_team                  Qatar
away_team                Ecuador
home_total_points        1437.91
home_rank_change             4.0
home_previous_points     1437.91
home_conf                    AFC
away_total_points        1458.63
away_rank_change            -2.0
away_previous_points     1448.27
away_conf               CONMEBOL
hour                          16
rank_diff                    8.0
points_diff               -20.72
age_diff                3.454545
Name: 1433, dtype: object home_team_goals    0
away_team_goals    2
Name: 1433, dtype: int64
model prediction: [[2 2]]
the match is:  home_team                  Qatar
away_team               Bulgaria
home_total_points        1437.91
home_rank_change             4.0
home_previous_points     1437.91
home_conf                    AFC
away_total_points        1345.47
away_rank_change             0.0
away_previous_points     1345.47
away_conf                   UEFA
hour                          17
rank_diff                  -19.0
points_diff                92.44
age_diff               -0.818182
Name: 1439, dtype: object home_team_goals    2
away_team_goals    1
Name: 1439, dtype: int64
model prediction: [[3 2]]
the match is:  home_team                   Qatar
away_team               Guatemala
home_total_points         1437.91
home_rank_change              4.0
home_previous_points      1437.91
home_conf                     AFC
away_total_points          1138.4
away_rank_change              1.0
away_previous_points       1138.4
away_conf                CONCACAF
hour                           16
rank_diff                   -71.0
points_diff                299.51
age_diff                -7.545455
Name: 1440, dtype: object home_team_goals    2
away_team_goals    0
Name: 1440, dtype: int64
model prediction: [[3 1]]
the match is:  home_team                  Qatar
away_team                Senegal
home_total_points        1437.91
home_rank_change             4.0
home_previous_points     1437.91
home_conf                    AFC
away_total_points        1587.78
away_rank_change            -2.0
away_previous_points     1561.68
away_conf                    CAF
hour                          13
rank_diff                   34.0
points_diff              -149.87
age_diff                0.818182
Name: 1442, dtype: object home_team_goals    1
away_team_goals    3
Name: 1442, dtype: int64
model prediction: [[1 2]]
the match is:  home_team               Netherlands
away_team                   Denmark
home_total_points           1653.73
home_rank_change                0.0
home_previous_points        1653.73
home_conf                      UEFA
away_total_points           1654.54
away_rank_change                0.0
away_previous_points        1654.54
away_conf                      UEFA
hour                             19
rank_diff                       1.0
points_diff                   -0.81
age_diff                   0.363636
Name: 1459, dtype: object home_team_goals    4
away_team_goals    2
Name: 1459, dtype: int64
model prediction: [[2 2]]
the match is:  home_team                   Belgium
away_team               Netherlands
home_total_points           1828.45
home_rank_change                0.0
home_previous_points        1828.45
home_conf                      UEFA
away_total_points           1653.73
away_rank_change                0.0
away_previous_points        1653.73
away_conf                      UEFA
hour                             18
rank_diff                      -9.0
points_diff                  174.72
age_diff                   3.454545
Name: 1460, dtype: object home_team_goals    1
away_team_goals    4
Name: 1460, dtype: int64
model prediction: [[2 1]]
the match is:  home_team               Netherlands
away_team                   Belgium
home_total_points           1653.73
home_rank_change                0.0
home_previous_points        1653.73
home_conf                      UEFA
away_total_points           1828.45
away_rank_change                0.0
away_previous_points        1828.45
away_conf                      UEFA
hour                             18
rank_diff                       9.0
points_diff                 -174.72
age_diff                        0.0
Name: 1461, dtype: object home_team_goals    1
away_team_goals    0
Name: 1461, dtype: int64
model prediction: [[2 2]]
the match is:  home_team                     Wales
away_team               Netherlands
home_total_points           1578.01
home_rank_change                1.0
home_previous_points        1578.01
home_conf                      UEFA
away_total_points           1653.73
away_rank_change                0.0
away_previous_points        1653.73
away_conf                      UEFA
hour                             18
rank_diff                      10.0
points_diff                  -75.72
age_diff                  -0.454545
Name: 1479, dtype: object home_team_goals    1
away_team_goals    2
Name: 1479, dtype: int64
model prediction: [[2 2]]
the match is:  home_team               Netherlands
away_team                     Wales
home_total_points           1653.73
home_rank_change                0.0
home_previous_points        1653.73
home_conf                      UEFA
away_total_points           1578.01
away_rank_change                1.0
away_previous_points        1578.01
away_conf                      UEFA
hour                             18
rank_diff                     -10.0
points_diff                   75.72
age_diff                   0.181818
Name: 1480, dtype: object

/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/3283078934.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/3283078934.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/3283078934.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/3283078934.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/3283078934.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/3283078934.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

home_team_goals    3
away_team_goals    2
Name: 1480, dtype: int64
model prediction: [[2 1]]
the match is:  home_team               Netherlands
away_team                 Argentina
home_total_points           1653.73
home_rank_change                0.0
home_previous_points        1653.73
home_conf                      UEFA
away_total_points           1766.99
away_rank_change               -1.0
away_previous_points        1750.51
away_conf                  CONMEBOL
hour                             19
rank_diff                       6.0
points_diff                 -113.26
age_diff                        0.0
Name: 1483, dtype: object home_team_goals    3
away_team_goals    4
Name: 1483, dtype: int64
model prediction: [[2 2]]
the match is:  home_team                   Senegal
away_team               Netherlands
home_total_points           1587.78
home_rank_change               -2.0
home_previous_points        1561.68
home_conf                       CAF
away_total_points           1653.73
away_rank_change                0.0
away_previous_points        1653.73
away_conf                      UEFA
hour                             16
rank_diff                       8.0
points_diff                  -65.95
age_diff                   1.181818
Name: 1489, dtype: object home_team_goals    0
away_team_goals    2
Name: 1489, dtype: int64
model prediction: [[2 2]]
the match is:  home_team               Netherlands
away_team                    Poland
home_total_points           1653.73
home_rank_change                0.0
home_previous_points        1653.73
home_conf                      UEFA
away_total_points           1530.62
away_rank_change                1.0
away_previous_points        1530.62
away_conf                      UEFA
hour                             18
rank_diff                     -18.0
points_diff                  123.11
age_diff                   0.454545
Name: 1493, dtype: object home_team_goals    2
away_team_goals    2
Name: 1493, dtype: int64
model prediction: [[2 1]]
the match is:  home_team                    Poland
away_team               Netherlands
home_total_points           1530.62
home_rank_change                1.0
home_previous_points        1530.62
home_conf                      UEFA
away_total_points           1653.73
away_rank_change                0.0
away_previous_points        1653.73
away_conf                      UEFA
hour                             18
rank_diff                      18.0
points_diff                 -123.11
age_diff                   0.363636
Name: 1494, dtype: object home_team_goals    0
away_team_goals    2
Name: 1494, dtype: int64
model prediction: [[2 2]]
the match is:  home_team                    Spain
away_team               Costa Rica
home_total_points          1704.75
home_rank_change               0.0
home_previous_points       1704.75
home_conf                     UEFA
away_total_points          1464.06
away_rank_change              -7.0
away_previous_points       1437.43
away_conf                 CONCACAF
hour                            16
rank_diff                    -35.0
points_diff                 240.69
age_diff                 -2.454545
Name: 1549, dtype: object home_team_goals    7
away_team_goals    0
Name: 1549, dtype: int64
model prediction: [[2 1]]
the match is:  home_team                 Jordan
away_team                  Spain
home_total_points        1259.84
home_rank_change             0.0
home_previous_points     1255.69
home_conf                    AFC
away_total_points        1704.75
away_rank_change             0.0
away_previous_points     1704.75
away_conf                   UEFA
hour                          16
rank_diff                   83.0
points_diff              -444.91
age_diff                0.363636
Name: 1553, dtype: object home_team_goals    3
away_team_goals    1
Name: 1553, dtype: int64
model prediction: [[1 2]]
the match is:  home_team                  Spain
away_team                Albania
home_total_points        1704.75
home_rank_change             0.0
home_previous_points     1704.75
home_conf                   UEFA
away_total_points        1374.98
away_rank_change            -1.0
away_previous_points     1374.98
away_conf                   UEFA
hour                          18
rank_diff                  -58.0
points_diff               329.77
age_diff               -2.181818
Name: 1555, dtype: object home_team_goals    2
away_team_goals    1
Name: 1555, dtype: int64
model prediction: [[3 1]]
the match is:  home_team                  Spain
away_team               Portugal
home_total_points        1704.75
home_rank_change             0.0
home_previous_points     1704.75
home_conf                   UEFA
away_total_points        1660.25
away_rank_change             0.0
away_previous_points     1660.25
away_conf                   UEFA
hour                          18
rank_diff                   -1.0
points_diff                 44.5
age_diff               -1.363636
Name: 1562, dtype: object home_team_goals    1
away_team_goals    1
Name: 1562, dtype: int64
model prediction: [[2 2]]
the match is:  home_team               Portugal
away_team                  Spain
home_total_points        1660.25
home_rank_change             0.0
home_previous_points     1660.25
home_conf                   UEFA
away_total_points        1704.75
away_rank_change             0.0
away_previous_points     1704.75
away_conf                   UEFA
hour                          18
rank_diff                    1.0
points_diff                -44.5
age_diff                0.818182
Name: 1563, dtype: object home_team_goals    1
away_team_goals    0
Name: 1563, dtype: int64
model prediction: [[2 2]]
the match is:  home_team                  Spain
away_team                Iceland
home_total_points        1704.75
home_rank_change             0.0
home_previous_points     1704.75
home_conf                   UEFA
away_total_points        1382.81
away_rank_change            -2.0
away_previous_points     1385.21
away_conf                   UEFA
hour                          18
rank_diff                  -53.0
points_diff               321.94
age_diff                0.454545
Name: 1569, dtype: object home_team_goals    5
away_team_goals    0
Name: 1569, dtype: int64
model prediction: [[3 1]]
the match is:  home_team               Switzerland
away_team                     Spain
home_total_points           1642.83
home_rank_change                1.0
home_previous_points        1642.83
home_conf                      UEFA
away_total_points           1704.75
away_rank_change                0.0
away_previous_points        1704.75
away_conf                      UEFA
hour                             18
rank_diff                       7.0
points_diff                  -61.92
age_diff                   0.909091
Name: 1579, dtype: object home_team_goals    1
away_team_goals    0
Name: 1579, dtype: int64
model prediction: [[2 2]]
the match is:  home_team                     Spain
away_team               Switzerland
home_total_points           1704.75
home_rank_change                0.0
home_previous_points        1704.75
home_conf                      UEFA
away_total_points           1642.83
away_rank_change                1.0
away_previous_points        1642.83
away_conf                      UEFA
hour                             18
rank_diff                      -7.0
points_diff                   61.92
age_diff                  -2.181818
Name: 1580, dtype: object home_team_goals    1
away_team_goals    2
Name: 1580, dtype: int64
model prediction: [[2 2]]
the match is:  home_team               DR Congo
away_team                  Gabon
home_total_points        1369.53
home_rank_change             2.0
home_previous_points     1375.64
home_conf                    CAF
away_total_points        1290.65
away_rank_change            -7.0
away_previous_points      1262.0
away_conf                    CAF
hour                          20
rank_diff                  -16.0
points_diff                78.88
age_diff                0.454545
Name: 1588, dtype: object home_team_goals    0
away_team_goals    1
Name: 1588, dtype: int64
model prediction: [[2 1]]
the match is:  home_team                  Sudan
away_team               DR Congo
home_total_points        1118.31
home_rank_change             8.0
home_previous_points     1131.74
home_conf                    CAF
away_total_points        1369.53
away_rank_change             2.0
away_previous_points     1375.64
away_conf                    CAF
hour                          19
rank_diff                   67.0
points_diff              -251.22
age_diff                0.545455
Name: 1608, dtype: object home_team_goals    1
away_team_goals    2
Name: 1608, dtype: int64
model prediction: [[2 1]]
the match is:  home_team                   DR Congo
away_team               Burkina Faso
home_total_points            1369.53
home_rank_change                 2.0
home_previous_points         1375.64
home_conf                        CAF
away_total_points            1418.58
away_rank_change                -4.0
away_previous_points         1397.64
away_conf                        CAF
hour                              16
rank_diff                       10.0
points_diff                   -49.05
age_diff                    2.363636
Name: 1616, dtype: object home_team_goals    0
away_team_goals    1
Name: 1616, dtype: int64
model prediction: [[2 1]]
the match is:  home_team                Denmark
away_team                Tunisia
home_total_points        1654.54
home_rank_change             0.0
home_previous_points     1654.54
home_conf                   UEFA
away_total_points        1489.92
away_rank_change             6.0
away_previous_points     1512.72
away_conf                    CAF
hour                          13
rank_diff                  -27.0
points_diff               164.62
age_diff                0.909091
Name: 1644, dtype: object home_team_goals    0
away_team_goals    0
Name: 1644, dtype: int64

/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/3283078934.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/3283078934.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/3283078934.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/3283078934.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/3283078934.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/3283078934.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/3283078934.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/3283078934.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/3283078934.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/3283078934.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/3283078934.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

model prediction: [[2 1]]
the match is:  home_team                Tunisia
away_team                 France
home_total_points        1489.92
home_rank_change             6.0
home_previous_points     1512.72
home_conf                    CAF
away_total_points        1786.15
away_rank_change             0.0
away_previous_points     1786.15
away_conf                   UEFA
hour                          15
rank_diff                   33.0
points_diff              -296.23
age_diff                1.090909
Name: 1655, dtype: object home_team_goals    1
away_team_goals    0
Name: 1655, dtype: int64
model prediction: [[1 2]]
the match is:  home_team                  Chile
away_team                Tunisia
home_total_points        1543.16
home_rank_change             2.0
home_previous_points     1543.42
home_conf               CONMEBOL
away_total_points        1489.92
away_rank_change             6.0
away_previous_points     1512.72
away_conf                    CAF
hour                           6
rank_diff                  -10.0
points_diff                53.24
age_diff                0.545455
Name: 1656, dtype: object home_team_goals    0
away_team_goals    2
Name: 1656, dtype: int64
model prediction: [[2 1]]
the match is:  home_team                Tunisia
away_team                Comoros
home_total_points        1489.92
home_rank_change             6.0
home_previous_points     1512.72
home_conf                    CAF
away_total_points         1126.2
away_rank_change            -1.0
away_previous_points     1117.65
away_conf                    CAF
hour                          14
rank_diff                  -95.0
points_diff               363.72
age_diff                0.636364
Name: 1659, dtype: object home_team_goals    1
away_team_goals    0
Name: 1659, dtype: int64
model prediction: [[3 1]]
the match is:  home_team                   Iran
away_team                Tunisia
home_total_points        1572.89
home_rank_change             0.0
home_previous_points     1557.58
home_conf                    AFC
away_total_points        1489.92
away_rank_change             6.0
away_previous_points     1512.72
away_conf                    CAF
hour                          13
rank_diff                  -15.0
points_diff                82.97
age_diff                2.363636
Name: 1660, dtype: object home_team_goals    0
away_team_goals    2
Name: 1660, dtype: int64
model prediction: [[2 1]]
the match is:  home_team               Botswana
away_team                Tunisia
home_total_points        1051.59
home_rank_change             1.0
home_previous_points     1051.59
home_conf                    CAF
away_total_points        1489.92
away_rank_change             6.0
away_previous_points     1512.72
away_conf                    CAF
hour                          13
rank_diff                  113.0
points_diff              -438.33
age_diff               -1.818182
Name: 1666, dtype: object home_team_goals    0
away_team_goals    0
Name: 1666, dtype: int64
model prediction: [[1 2]]
the match is:  home_team                   Mali
away_team                Tunisia
home_total_points        1446.49
home_rank_change            -5.0
home_previous_points     1427.98
home_conf                    CAF
away_total_points        1489.92
away_rank_change             6.0
away_previous_points     1512.72
away_conf                    CAF
hour                          17
rank_diff                   12.0
points_diff               -43.43
age_diff               -1.454545
Name: 1673, dtype: object home_team_goals    0
away_team_goals    1
Name: 1673, dtype: int64
model prediction: [[2 2]]
the match is:  home_team                Tunisia
away_team                   Mali
home_total_points        1489.92
home_rank_change             6.0
home_previous_points     1512.72
home_conf                    CAF
away_total_points        1446.49
away_rank_change            -5.0
away_previous_points     1427.98
away_conf                    CAF
hour                          19
rank_diff                  -12.0
points_diff                43.43
age_diff                0.545455
Name: 1674, dtype: object home_team_goals    0
away_team_goals    0
Name: 1674, dtype: int64
model prediction: [[2 1]]
the match is:  home_team               Nicaragua
away_team                   Ghana
home_total_points         1062.21
home_rank_change              1.0
home_previous_points      1062.21
home_conf                CONCACAF
away_total_points         1381.45
away_rank_change              9.0
away_previous_points      1428.97
away_conf                     CAF
hour                           18
rank_diff                    83.0
points_diff               -319.24
age_diff                 3.636364
Name: 1699, dtype: object home_team_goals    1
away_team_goals    0
Name: 1699, dtype: int64
model prediction: [[2 2]]
the match is:  home_team                    Ghana
away_team               Madagascar
home_total_points          1381.45
home_rank_change               9.0
home_previous_points       1428.97
home_conf                      CAF
away_total_points          1205.61
away_rank_change               1.0
away_previous_points       1205.61
away_conf                      CAF
hour                            19
rank_diff                    -41.0
points_diff                 175.84
age_diff                 -2.363636
Name: 1706, dtype: object home_team_goals    3
away_team_goals    0
Name: 1706, dtype: int64
model prediction: [[2 1]]
the match is:  home_team                  Chile
away_team                  Ghana
home_total_points        1543.16
home_rank_change             2.0
home_previous_points     1543.42
home_conf               CONMEBOL
away_total_points        1381.45
away_rank_change             9.0
away_previous_points     1428.97
away_conf                    CAF
hour                           6
rank_diff                  -35.0
points_diff               161.71
age_diff                0.727273
Name: 1711, dtype: object home_team_goals    3
away_team_goals    1
Name: 1711, dtype: int64
model prediction: [[3 1]]
the match is:  home_team                  Ghana
away_team                  Benin
home_total_points        1381.45
home_rank_change             9.0
home_previous_points     1428.97
home_conf                    CAF
away_total_points        1282.53
away_rank_change             0.0
away_previous_points     1282.53
away_conf                    CAF
hour                          16
rank_diff                  -22.0
points_diff                98.92
age_diff               -1.363636
Name: 1715, dtype: object home_team_goals    3
away_team_goals    0
Name: 1715, dtype: int64
model prediction: [[2 1]]
the match is:  home_team                 Brazil
away_team                  Ghana
home_total_points        1823.42
home_rank_change             0.0
home_previous_points     1826.35
home_conf               CONMEBOL
away_total_points        1381.45
away_rank_change             9.0
away_previous_points     1428.97
away_conf                    CAF
hour                          18
rank_diff                  -59.0
points_diff               441.97
age_diff                1.181818
Name: 1716, dtype: object home_team_goals    0
away_team_goals    3
Name: 1716, dtype: int64
model prediction: [[2 1]]
the match is:  home_team                  Ghana
away_team                Nigeria
home_total_points        1381.45
home_rank_change             9.0
home_previous_points     1428.97
home_conf                    CAF
away_total_points        1509.91
away_rank_change            -4.0
away_previous_points     1478.78
away_conf                    CAF
hour                          19
rank_diff                   29.0
points_diff              -128.46
age_diff               -0.454545
Name: 1729, dtype: object home_team_goals    0
away_team_goals    0
Name: 1729, dtype: int64
model prediction: [[1 1]]
the match is:  home_team                Nigeria
away_team                  Ghana
home_total_points        1509.91
home_rank_change            -4.0
home_previous_points     1478.78
home_conf                    CAF
away_total_points        1381.45
away_rank_change             9.0
away_previous_points     1428.97
away_conf                    CAF
hour                          17
rank_diff                  -29.0
points_diff               128.46
age_diff                0.181818
Name: 1730, dtype: object home_team_goals    1
away_team_goals    1
Name: 1730, dtype: int64
model prediction: [[3 1]]
the match is:  home_team                     Ghana
away_team               Switzerland
home_total_points           1381.45
home_rank_change                9.0
home_previous_points        1428.97
home_conf                       CAF
away_total_points           1642.83
away_rank_change                1.0
away_previous_points        1642.83
away_conf                      UEFA
hour                             10
rank_diff                      47.0
points_diff                 -261.38
age_diff                  -2.181818
Name: 1731, dtype: object home_team_goals    2
away_team_goals    0
Name: 1731, dtype: int64

/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/3283078934.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/3283078934.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/3283078934.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/3283078934.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/3283078934.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/3283078934.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/3283078934.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/3283078934.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

model prediction: [[1 2]]
the match is:  home_team               Slovenia
away_team                 Sweden
home_total_points        1375.42
home_rank_change            -1.0
home_previous_points     1375.42
home_conf                   UEFA
away_total_points        1588.26
away_rank_change            -1.0
away_previous_points     1588.26
away_conf                   UEFA
hour                          18
rank_diff                   47.0
points_diff              -212.84
age_diff                0.181818
Name: 1751, dtype: object home_team_goals    0
away_team_goals    2
Name: 1751, dtype: int64
model prediction: [[2 2]]
the match is:  home_team                 Sweden
away_team               Slovenia
home_total_points        1588.26
home_rank_change            -1.0
home_previous_points     1588.26
home_conf                   UEFA
away_total_points        1375.42
away_rank_change            -1.0
away_previous_points     1375.42
away_conf                   UEFA
hour                          18
rank_diff                  -47.0
points_diff               212.84
age_diff                1.636364
Name: 1752, dtype: object home_team_goals    1
away_team_goals    1
Name: 1752, dtype: int64
model prediction: [[3 1]]
the match is:  home_team                 Sweden
away_team                 Norway
home_total_points        1588.26
home_rank_change            -1.0
home_previous_points     1588.26
home_conf                   UEFA
away_total_points        1455.43
away_rank_change             4.0
away_previous_points     1455.43
away_conf                   UEFA
hour                          18
rank_diff                  -28.0
points_diff               132.83
age_diff                0.909091
Name: 1764, dtype: object home_team_goals    1
away_team_goals    2
Name: 1764, dtype: int64
model prediction: [[2 1]]
the match is:  home_team                 Norway
away_team                 Sweden
home_total_points        1455.43
home_rank_change             4.0
home_previous_points     1455.43
home_conf                   UEFA
away_total_points        1588.26
away_rank_change            -1.0
away_previous_points     1588.26
away_conf                   UEFA
hour                          16
rank_diff                   28.0
points_diff              -132.83
age_diff                0.181818
Name: 1765, dtype: object home_team_goals    3
away_team_goals    2
Name: 1765, dtype: int64
model prediction: [[2 2]]
the match is:  home_team                 Sweden
away_team                 Mexico
home_total_points        1588.26
home_rank_change            -1.0
home_previous_points     1588.26
home_conf                   UEFA
away_total_points         1647.9
away_rank_change            -2.0
away_previous_points      1638.3
away_conf               CONCACAF
hour                          19
rank_diff                    5.0
points_diff               -59.64
age_diff               -2.363636
Name: 1766, dtype: object home_team_goals    2
away_team_goals    1
Name: 1766, dtype: int64
model prediction: [[2 2]]
the match is:  home_team                 Poland
away_team                 Sweden
home_total_points        1530.62
home_rank_change             1.0
home_previous_points     1530.62
home_conf                   UEFA
away_total_points        1588.26
away_rank_change            -1.0
away_previous_points     1588.26
away_conf                   UEFA
hour                          18
rank_diff                   11.0
points_diff               -57.64
age_diff                0.090909
Name: 1769, dtype: object home_team_goals    2
away_team_goals    0
Name: 1769, dtype: int64
model prediction: [[2 2]]
the match is:  home_team                 Sweden
away_team                Algeria
home_total_points        1588.26
home_rank_change            -1.0
home_previous_points     1588.26
home_conf                   UEFA
away_total_points        1460.93
away_rank_change            14.0
away_previous_points     1516.51
away_conf                    CAF
hour                          19
rank_diff                  -26.0
points_diff               127.33
age_diff               -1.909091
Name: 1772, dtype: object home_team_goals    2
away_team_goals    0
Name: 1772, dtype: int64
model prediction: [[2 1]]
the match is:  home_team                 Sweden
away_team                 Serbia
home_total_points        1588.26
home_rank_change            -1.0
home_previous_points     1588.26
home_conf                   UEFA
away_total_points        1547.38
away_rank_change             2.0
away_previous_points     1547.38
away_conf                   UEFA
hour                          18
rank_diff                   -8.0
points_diff                40.88
age_diff               -1.363636
Name: 1774, dtype: object home_team_goals    0
away_team_goals    1
Name: 1774, dtype: int64

/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/3283078934.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/3283078934.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/3283078934.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/3283078934.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/tmp/ipykernel_73008/3283078934.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  elif y_match[0]<y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

model prediction: [[2 1]]
the match is:  home_team                 Serbia
away_team                 Sweden
home_total_points        1547.38
home_rank_change             2.0
home_previous_points     1547.38
home_conf                   UEFA
away_total_points        1588.26
away_rank_change            -1.0
away_previous_points     1588.26
away_conf                   UEFA
hour                          18
rank_diff                    8.0
points_diff               -40.88
age_diff                0.363636
Name: 1775, dtype: object home_team_goals    4
away_team_goals    1
Name: 1775, dtype: int64
model prediction: [[2 2]]
the match is:  home_team               Uzbekistan
away_team                 Maldives
home_total_points          1277.02
home_rank_change               1.0
home_previous_points       1274.58
home_conf                      AFC
away_total_points          1021.58
away_rank_change               0.0
away_previous_points       1021.58
away_conf                      AFC
hour                            15
rank_diff                    -72.0
points_diff                 255.44
age_diff                      -2.0
Name: 1776, dtype: object home_team_goals    4
away_team_goals    0
Name: 1776, dtype: int64
model prediction: [[3 1]]
the match is:  home_team               Uzbekistan
away_team               Costa Rica
home_total_points          1277.02
home_rank_change               1.0
home_previous_points       1274.58
home_conf                      AFC
away_total_points          1464.06
away_rank_change              -7.0
away_previous_points       1437.43
away_conf                 CONCACAF
hour                             6
rank_diff                     43.0
points_diff                -187.04
age_diff                 -0.272727
Name: 1779, dtype: object home_team_goals    1
away_team_goals    2
Name: 1779, dtype: int64
model prediction: [[2 2]]
the match is:  home_team               Uzbekistan
away_team                 Thailand
home_total_points          1277.02
home_rank_change               1.0
home_previous_points       1274.58
home_conf                      AFC
away_total_points          1160.14
away_rank_change              -3.0
away_previous_points       1156.16
away_conf                      AFC
hour                            15
rank_diff                    -27.0
points_diff                 116.88
age_diff                 -2.090909
Name: 1782, dtype: object home_team_goals    2
away_team_goals    0
Name: 1782, dtype: int64
model prediction: [[2 1]]
the match is:  home_team               Uzbekistan
away_team                   Russia
home_total_points          1277.02
home_rank_change               1.0
home_previous_points       1274.58
home_conf                      AFC
away_total_points          1493.42
away_rank_change               1.0
away_previous_points       1493.42
away_conf                     UEFA
hour                            12
rank_diff                     50.0
points_diff                 -216.4
age_diff                       1.0
Name: 1783, dtype: object home_team_goals    0
away_team_goals    0
Name: 1783, dtype: int64
model prediction: [[2 2]]
the match is:  home_team               Uzbekistan
away_team                Sri Lanka
home_total_points          1277.02
home_rank_change               1.0
home_previous_points       1274.58
home_conf                      AFC
away_total_points           842.93
away_rank_change               0.0
away_previous_points        842.93
away_conf                      AFC
hour                            15
rank_diff                   -119.0
points_diff                 434.09
age_diff                       1.0
Name: 1784, dtype: object home_team_goals    3
away_team_goals    0
Name: 1784, dtype: int64
model prediction: [[3 1]]
the match is:  home_team                 Cameroon
away_team               Uzbekistan
home_total_points          1480.82
home_rank_change             -12.0
home_previous_points       1437.35
home_conf                      CAF
away_total_points          1277.02
away_rank_change               1.0
away_previous_points       1274.58
away_conf                      AFC
hour                             6
rank_diff                    -47.0
points_diff                  203.8
age_diff                  1.181818
Name: 1788, dtype: object home_team_goals    2
away_team_goals    0
Name: 1788, dtype: int64
model prediction: [[2 1]]
the match is:  home_team               Uzbekistan
away_team               Kazakhstan
home_total_points          1277.02
home_rank_change               1.0
home_previous_points       1274.58
home_conf                      AFC
away_total_points          1140.71
away_rank_change               1.0
away_previous_points       1140.71
away_conf                     UEFA
hour                            13
rank_diff                    -35.0
points_diff                 136.31
age_diff                 -2.818182
Name: 1809, dtype: object home_team_goals    2
away_team_goals    0
Name: 1809, dtype: int64
model prediction: [[3 1]]
the match is:  home_team               Uzbekistan
away_team                   Uganda
home_total_points          1277.02
home_rank_change               1.0
home_previous_points       1274.58
home_conf                      AFC
away_total_points          1279.18
away_rank_change               2.0
away_previous_points       1285.28
away_conf                      CAF
hour                            14
rank_diff                      1.0
points_diff                  -2.16
age_diff                  0.909091
Name: 1811, dtype: object home_team_goals    4
away_team_goals    2
Name: 1811, dtype: int64
model prediction: [[2 1]]
the match is:  home_team                Belgium
away_team                 Canada
home_total_points        1828.45
home_rank_change             0.0
home_previous_points     1828.45
home_conf                   UEFA
away_total_points        1497.82
away_rank_change            -7.0
away_previous_points     1462.32
away_conf               CONCACAF
hour                          19
rank_diff                  -32.0
points_diff               330.63
age_diff                3.766667
Name: 1812, dtype: object home_team_goals    1
away_team_goals    0
Name: 1812, dtype: int64
model prediction: [[2 1]]

/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/tmp/ipykernel_73008/3283078934.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if y_match[0]>y_match[1]:
/home/yacine10/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

In [85]:
print(home)
print(away)
print(equal)
print(home_test)
print(away_test)
print(equal_test)

168
22
107
163
78
56