In [1]:
import numpy as np
import pandas as pd
import os 
import re

## extract the data

In [2]:
pattern1=r"matches"
matches=pd.DataFrame()
players=pd.DataFrame()
data="../data"
for dirc in os.listdir(data):
    path=os.path.join(data,dirc)
    if os.path.isdir(path):
        print(dirc)
        for file in os.listdir(path):
            match=re.search(pattern1,file)
            if match:
                target_file=os.path.join(path,file)
                matches2=pd.read_csv(target_file)
                if matches.empty:
                    matches=matches2
                else :
                    matches=pd.concat([matches,matches2])
            else :
                target_file=os.path.join(path,file)
                players2=pd.read_csv(target_file)
                if players.empty:
                    players=players2
                else :
                    players=pd.concat([players,players2])   
                 
matches

2006
additional
2018
2010
2002
2014
2022

,timestamp,date_GMT,status,attendance,home_team_name,away_team_name,referee,Game Week,Pre-Match PPG (Home),Pre-Match PPG (Away),...,odds_ft_home_team_win,odds_ft_draw,odds_ft_away_team_win,odds_ft_over15,odds_ft_over25,odds_ft_over35,odds_ft_over45,odds_btts_yes,odds_btts_no,stadium_name
0,1149868800,Jun 09 2006 - 4:00pm,complete,66000.0,Germany,Costa Rica,NaN,1.0,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,Allianz Arena
1,1149879600,Jun 09 2006 - 7:00pm,complete,52000.0,Poland,Ecuador,NaN,1.0,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,VELTINS-Arena
2,1149944400,Jun 10 2006 - 1:00pm,complete,48000.0,England,Paraguay,NaN,1.0,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,Commerzbank-Arena
3,1149955200,Jun 10 2006 - 4:00pm,complete,62959.0,Trinidad and Tobago,Sweden,NaN,1.0,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,Signal-Iduna-Park
4,1149966000,Jun 10 2006 - 7:00pm,complete,49480.0,Argentina,Ivory Coast,NaN,1.0,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,Volksparkstadion
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59,1670698800,Dec 10 2022 - 7:00pm,complete,NaN,England,France,Wilton Pereira Sampaio,NaN,2.50,2.25,...,3.10,3.20,2.38,1.32,2.10,3.40,6.3,1.80,1.95,Al Bayt Stadium (Al Khor)
60,1670958000,Dec 13 2022 - 7:00pm,complete,88966.0,Argentina,Croatia,Daniele Orsato,NaN,2.00,1.40,...,1.80,3.40,5.00,1.52,2.48,4.50,9.0,2.25,1.57,Lusail Iconic Stadium (Lusail)
61,1671044400,Dec 14 2022 - 7:00pm,complete,NaN,France,Morocco,César Arturo Ramos Palazuelos,NaN,2.40,2.20,...,1.57,4.00,6.75,1.40,2.25,1.79,9.5,2.25,1.57,Al Bayt Stadium (Al Khor)
62,1671289200,Dec 17 2022 - 3:00pm,complete,NaN,Croatia,Morocco,Abdulrahman Ibrahim Al Jassim,NaN,1.17,1.83,...,2.43,3.40,3.10,1.26,2.07,2.98,5.7,1.67,2.10,Khalifa International Stadium (Al Rayyan (Ar-R...
63,1671375600,Dec 18 2022 - 3:00pm,complete,88966.0,Argentina,France,Szymon Marciniak,NaN,2.17,2.50,...,2.70,2.95,2.65,1.45,2.35,4.30,7.5,2.00,1.75,Lusail Iconic Stadium (Lusail)

In [3]:
players

,full_name,age,birthday,birthday_GMT,league,season,position,Current Club,minutes_played_overall,minutes_played_home,...,annual_salary_eur_percentile,clean_sheets_percentage_percentile_overall,min_per_card_percentile_overall,cards_per90_percentile_overall,booked_over05_overall,booked_over05_percentage_overall,booked_over05_percentage_percentile_overall,shirt_number,annual_salary_gbp,annual_salary_usd
0,Aaron Lennon,35,5.455548e+08,1987/04/16,FIFA World Cup 2006 Germany,2006,Midfielder,England,102,102,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Abdoulaye Mu00e9u00eftu00e9,41,3.396636e+08,1980/10/06,FIFA World Cup 2006 Germany,2006,Defender,Ivory Coast,180,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Abdul Kader Keu00efta,41,3.659292e+08,1981/08/06,FIFA World Cup 2006 Germany,2006,Midfielder,Ivory Coast,150,73,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Abdulaziz Mohammed Al Khathran,49,1.129500e+08,1973/07/31,FIFA World Cup 2006 Germany,2006,Midfielder,Saudi Arabia,125,125,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Adékambi Olufadé,42,3.160800e+08,1980/01/07,FIFA World Cup 2006 Germany,2006,Forward,Togo,31,31,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
817,Yussuf Poulsen,31,7.716384e+08,1994/06/15,FIFA World Cup 2022 Qatar,2022,Forward,Denmark,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
818,Yuto Nagatomo,39,5.268672e+08,1986/09/12,FIFA World Cup 2022 Qatar,2022,Defender,Japan,213,156,...,46.0,7.0,21.0,21.0,0.0,0.0,21.0,5.0,0.0,0.0
819,Zakaria Aboukhlal,26,9.508320e+08,2000/02/18,FIFA World Cup 2022 Qatar,2022,Forward,Morocco,73,8,...,46.0,92.0,21.0,21.0,0.0,0.0,21.0,14.0,0.0,0.0
820,Zeno Debast,22,1.066954e+09,2003/10/24,FIFA World Cup 2022 Qatar,2022,Midfielder,Belgium,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
821,Łukasz Skorupski,34,6.734016e+08,1991/05/05,FIFA World Cup 2022 Qatar,2022,Goalkeeper,Poland,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## get essenteil info from players data

In [4]:
players["birthday_GMT"]=pd.to_datetime(players["birthday_GMT"],errors="coerce")
players["birthday_GMT"]=players["birthday_GMT"].dt.year
players

,full_name,age,birthday,birthday_GMT,league,season,position,Current Club,minutes_played_overall,minutes_played_home,...,annual_salary_eur_percentile,clean_sheets_percentage_percentile_overall,min_per_card_percentile_overall,cards_per90_percentile_overall,booked_over05_overall,booked_over05_percentage_overall,booked_over05_percentage_percentile_overall,shirt_number,annual_salary_gbp,annual_salary_usd
0,Aaron Lennon,35,5.455548e+08,1987.0,FIFA World Cup 2006 Germany,2006,Midfielder,England,102,102,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Abdoulaye Mu00e9u00eftu00e9,41,3.396636e+08,1980.0,FIFA World Cup 2006 Germany,2006,Defender,Ivory Coast,180,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Abdul Kader Keu00efta,41,3.659292e+08,1981.0,FIFA World Cup 2006 Germany,2006,Midfielder,Ivory Coast,150,73,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Abdulaziz Mohammed Al Khathran,49,1.129500e+08,1973.0,FIFA World Cup 2006 Germany,2006,Midfielder,Saudi Arabia,125,125,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Adékambi Olufadé,42,3.160800e+08,1980.0,FIFA World Cup 2006 Germany,2006,Forward,Togo,31,31,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
817,Yussuf Poulsen,31,7.716384e+08,1994.0,FIFA World Cup 2022 Qatar,2022,Forward,Denmark,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
818,Yuto Nagatomo,39,5.268672e+08,1986.0,FIFA World Cup 2022 Qatar,2022,Defender,Japan,213,156,...,46.0,7.0,21.0,21.0,0.0,0.0,21.0,5.0,0.0,0.0
819,Zakaria Aboukhlal,26,9.508320e+08,2000.0,FIFA World Cup 2022 Qatar,2022,Forward,Morocco,73,8,...,46.0,92.0,21.0,21.0,0.0,0.0,21.0,14.0,0.0,0.0
820,Zeno Debast,22,1.066954e+09,2003.0,FIFA World Cup 2022 Qatar,2022,Midfielder,Belgium,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
821,Łukasz Skorupski,34,6.734016e+08,1991.0,FIFA World Cup 2022 Qatar,2022,Goalkeeper,Poland,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
players

,full_name,age,birthday,birthday_GMT,league,season,position,Current Club,minutes_played_overall,minutes_played_home,...,annual_salary_eur_percentile,clean_sheets_percentage_percentile_overall,min_per_card_percentile_overall,cards_per90_percentile_overall,booked_over05_overall,booked_over05_percentage_overall,booked_over05_percentage_percentile_overall,shirt_number,annual_salary_gbp,annual_salary_usd
0,Aaron Lennon,35,5.455548e+08,1987.0,FIFA World Cup 2006 Germany,2006,Midfielder,England,102,102,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Abdoulaye Mu00e9u00eftu00e9,41,3.396636e+08,1980.0,FIFA World Cup 2006 Germany,2006,Defender,Ivory Coast,180,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Abdul Kader Keu00efta,41,3.659292e+08,1981.0,FIFA World Cup 2006 Germany,2006,Midfielder,Ivory Coast,150,73,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Abdulaziz Mohammed Al Khathran,49,1.129500e+08,1973.0,FIFA World Cup 2006 Germany,2006,Midfielder,Saudi Arabia,125,125,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Adékambi Olufadé,42,3.160800e+08,1980.0,FIFA World Cup 2006 Germany,2006,Forward,Togo,31,31,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
817,Yussuf Poulsen,31,7.716384e+08,1994.0,FIFA World Cup 2022 Qatar,2022,Forward,Denmark,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
818,Yuto Nagatomo,39,5.268672e+08,1986.0,FIFA World Cup 2022 Qatar,2022,Defender,Japan,213,156,...,46.0,7.0,21.0,21.0,0.0,0.0,21.0,5.0,0.0,0.0
819,Zakaria Aboukhlal,26,9.508320e+08,2000.0,FIFA World Cup 2022 Qatar,2022,Forward,Morocco,73,8,...,46.0,92.0,21.0,21.0,0.0,0.0,21.0,14.0,0.0,0.0
820,Zeno Debast,22,1.066954e+09,2003.0,FIFA World Cup 2022 Qatar,2022,Midfielder,Belgium,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
821,Łukasz Skorupski,34,6.734016e+08,1991.0,FIFA World Cup 2022 Qatar,2022,Goalkeeper,Poland,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
players.info()

<class 'pandas.core.frame.DataFrame'>
Index: 65697 entries, 0 to 821
Columns: 271 entries, full_name to annual_salary_usd
dtypes: float64(232), int64(32), object(7)
memory usage: 136.3+ MB

In [7]:
players_summary=pd.DataFrame({
    "Data type":players.dtypes,
    "missing value":players.isna().sum()
    }
)
players_summary

                                            Data type  missing value
full_name                                      object             16
age                                             int64              0
birthday                                      float64            106
birthday_GMT                                  float64            106
league                                         object              0
...                                               ...            ...
booked_over05_percentage_overall              float64          48864
booked_over05_percentage_percentile_overall   float64          48864
shirt_number                                   object          48993
annual_salary_gbp                             float64          48864
annual_salary_usd                             float64          48864

[271 rows x 2 columns]

In [8]:
n=len(players_summary)
for i in range(n):
    print(players_summary.iloc[i])

Data type        object
missing value        16
Name: full_name, dtype: object
Data type        int64
missing value        0
Name: age, dtype: object
Data type        float64
missing value        106
Name: birthday, dtype: object
Data type        float64
missing value        106
Name: birthday_GMT, dtype: object
Data type        object
missing value         0
Name: league, dtype: object
Data type        object
missing value         0
Name: season, dtype: object
Data type        object
missing value         0
Name: position, dtype: object
Data type        object
missing value         0
Name: Current Club, dtype: object
Data type        int64
missing value        0
Name: minutes_played_overall, dtype: object
Data type        int64
missing value        0
Name: minutes_played_home, dtype: object
Data type        int64
missing value        0
Name: minutes_played_away, dtype: object
Data type        object
missing value        58
Name: nationality, dtype: object
Data type        int64
missing value        0
Name: appearances_overall, dtype: object
Data type        int64
missing value        0
Name: appearances_home, dtype: object
Data type        int64
missing value        0
Name: appearances_away, dtype: object
Data type        int64
missing value        0
Name: goals_overall, dtype: object
Data type        int64
missing value        0
Name: goals_home, dtype: object
Data type        int64
missing value        0
Name: goals_away, dtype: object
Data type        int64
missing value        0
Name: assists_overall, dtype: object
Data type        int64
missing value        0
Name: assists_home, dtype: object
Data type        int64
missing value        0
Name: assists_away, dtype: object
Data type        int64
missing value        0
Name: penalty_goals, dtype: object
Data type        int64
missing value        0
Name: penalty_misses, dtype: object
Data type        int64
missing value        0
Name: clean_sheets_overall, dtype: object
Data type        int64
missing value        0
Name: clean_sheets_home, dtype: object
Data type        int64
missing value        0
Name: clean_sheets_away, dtype: object
Data type        int64
missing value        0
Name: conceded_overall, dtype: object
Data type        int64
missing value        0
Name: conceded_home, dtype: object
Data type        int64
missing value        0
Name: conceded_away, dtype: object
Data type        int64
missing value        0
Name: yellow_cards_overall, dtype: object
Data type        int64
missing value        0
Name: red_cards_overall, dtype: object
Data type        float64
missing value          0
Name: goals_involved_per_90_overall, dtype: object
Data type        float64
missing value          0
Name: assists_per_90_overall, dtype: object
Data type        float64
missing value          0
Name: goals_per_90_overall, dtype: object
Data type        float64
missing value          0
Name: goals_per_90_home, dtype: object
Data type        float64
missing value          0
Name: goals_per_90_away, dtype: object
Data type        int64
missing value        0
Name: min_per_goal_overall, dtype: object
Data type        float64
missing value          0
Name: conceded_per_90_overall, dtype: object
Data type        int64
missing value        0
Name: min_per_conceded_overall, dtype: object
Data type        int64
missing value        0
Name: min_per_match, dtype: object
Data type        int64
missing value        0
Name: min_per_card_overall, dtype: object
Data type        int64
missing value        0
Name: min_per_assist_overall, dtype: object
Data type        float64
missing value          0
Name: cards_per_90_overall, dtype: object
Data type        int64
missing value        0
Name: rank_in_league_top_attackers, dtype: object
Data type        int64
missing value        0
Name: rank_in_league_top_midfielders, dtype: object
Data type        int64
missing value        0
Name: rank_in_league_top_defenders, dtype: object
Data type        int64
missing value        0
Name: rank_in_club_top_scorer, dtype: object
Data type        float64
missing value      48864
Name: annual_salary_eur, dtype: object
Data type        float64
missing value      48864
Name: average_rating_overall, dtype: object
Data type        float64
missing value      48864
Name: assists_per_game_overall, dtype: object
Data type        float64
missing value      48864
Name: assists_per90_percentile_overall, dtype: object
Data type        float64
missing value      48864
Name: passes_per_90_overall, dtype: object
Data type        float64
missing value      48864
Name: passes_per_game_overall, dtype: object
Data type        float64
missing value      48864
Name: passes_per90_percentile_overall, dtype: object
Data type        float64
missing value      48864
Name: passes_total_overall, dtype: object
Data type        float64
missing value      48864
Name: passes_completed_per_game_overall, dtype: object
Data type        float64
missing value      48864
Name: passes_completed_total_overall, dtype: object
Data type        float64
missing value      48864
Name: pass_completion_rate_percentile_overall, dtype: object
Data type        float64
missing value      48864
Name: passes_completed_per_90_overall, dtype: object
Data type        float64
missing value      48864
Name: passes_completed_per90_percentile_overall, dtype: object
Data type        float64
missing value      48864
Name: short_passes_per_game_overall, dtype: object
Data type        float64
missing value      48864
Name: long_passes_per_game_overall, dtype: object
Data type        float64
missing value      48864
Name: key_passes_per_game_overall, dtype: object
Data type        float64
missing value      48864
Name: key_passes_total_overall, dtype: object
Data type        float64
missing value      48864
Name: through_passes_per_game_overall, dtype: object
Data type        float64
missing value      48864
Name: crosses_per_game_overall, dtype: object
Data type        float64
missing value      48864
Name: tackles_per_90_overall, dtype: object
Data type        float64
missing value      48864
Name: tackles_per_game_overall, dtype: object
Data type        float64
missing value      48864
Name: tackles_total_overall, dtype: object
Data type        float64
missing value      48864
Name: tackles_successful_per_game_overall, dtype: object
Data type        float64
missing value      48864
Name: dispossesed_per_game_overall, dtype: object
Data type        float64
missing value      48864
Name: possession_regained_per_game_overall, dtype: object
Data type        float64
missing value      48864
Name: pressures_per_game_overall, dtype: object
Data type        float64
missing value      48864
Name: saves_per_game_overall, dtype: object
Data type        float64
missing value      48864
Name: interceptions_per_game_overall, dtype: object
Data type        float64
missing value      48864
Name: dribbles_successful_per_game_overall, dtype: object
Data type        float64
missing value      48864
Name: shots_faced_per_game_overall, dtype: object
Data type        float64
missing value      48864
Name: shots_per_goal_scored_overall, dtype: object
Data type        float64
missing value      48864
Name: shots_per_90_overall, dtype: object
Data type        float64
missing value      48864
Name: shots_off_target_per_game_overall, dtype: object
Data type        float64
missing value      48864
Name: dribbles_per_game_overall, dtype: object
Data type        float64
missing value      48864
Name: distance_travelled_per_game_overall, dtype: object
Data type        float64
missing value      48864
Name: shots_on_target_per_game_overall, dtype: object
Data type        float64
missing value      48864
Name: xg_per_game_overall, dtype: object
Data type        float64
missing value      48864
Name: chances_created_per_game_overall, dtype: object
Data type        float64
missing value      48864
Name: aerial_duels_won_per_game_overall, dtype: object
Data type        float64
missing value      48864
Name: aerial_duels_per_game_overall, dtype: object
Data type        float64
missing value      48864
Name: possession_regained_per_90_overall, dtype: object
Data type        float64
missing value      48864
Name: possession_regained_total_overall, dtype: object
Data type        float64
missing value      48864
Name: possession_regained_per90_percentile_overall, dtype: object
Data type        float64
missing value      65697
Name: additional_info, dtype: object
Data type        float64
missing value      48864
Name: shots_total_overall, dtype: object
Data type        float64
missing value      48864
Name: shots_per_game_overall, dtype: object
Data type        float64
missing value      48864
Name: shots_per90_percentile_overall, dtype: object
Data type        float64
missing value      48864
Name: shots_on_target_total_overall, dtype: object
Data type        float64
missing value      48864
Name: shots_on_target_per_90_overall, dtype: object
Data type        float64
missing value      48864
Name: shots_on_target_per90_percentile_overall, dtype: object
Data type        float64
missing value      48864
Name: shots_off_target_total_overall, dtype: object
Data type        float64
missing value      48864
Name: shots_off_target_per_90_overall, dtype: object
Data type        float64
missing value      48864
Name: shots_off_target_per90_percentile_overall, dtype: object
Data type        float64
missing value      48864
Name: games_subbed_out, dtype: object
Data type        float64
missing value      48864
Name: games_subbed_in, dtype: object
Data type        float64
missing value      48864
Name: games_started, dtype: object
Data type        float64
missing value      48864
Name: tackles_per90_percentile_overall, dtype: object
Data type        float64
missing value      48864
Name: tackles_successful_per_90_overall, dtype: object
Data type        float64
missing value      48864
Name: tackles_successful_per90_percentile_overall, dtype: object
Data type        float64
missing value      48864
Name: tackles_successful_total_overall, dtype: object
Data type        float64
missing value      48864
Name: interceptions_total_overall, dtype: object
Data type        float64
missing value      48864
Name: interceptions_per_90_overall, dtype: object
Data type        float64
missing value      48864
Name: interceptions_per90_percentile_overall, dtype: object
Data type        float64
missing value      48864
Name: crosses_total_overall, dtype: object
Data type        float64
missing value      48864
Name: cross_completion_rate_percentile_overall, dtype: object
Data type        float64
missing value      48864
Name: crosses_per_90_overall, dtype: object
Data type        float64
missing value      48864
Name: crosses_per90_percentile_overall, dtype: object
Data type        float64
missing value      48864
Name: through_passes_total_overall, dtype: object
Data type        float64
missing value      48864
Name: through_passes_per_90_overall, dtype: object
Data type        float64
missing value      48864
Name: through_passes_per90_percentile_overall, dtype: object
Data type        float64
missing value      48864
Name: long_passes_total_overall, dtype: object
Data type        float64
missing value      48864
Name: long_passes_per_90_overall, dtype: object
Data type        float64
missing value      48864
Name: long_passes_per90_percentile_overall, dtype: object
Data type        float64
missing value      48864
Name: short_passes_total_overall, dtype: object
Data type        float64
missing value      48864
Name: short_passes_per_90_overall, dtype: object
Data type        float64
missing value      48864
Name: short_passes_per90_percentile_overall, dtype: object
Data type        float64
missing value      48864
Name: key_passes_per_90_overall, dtype: object
Data type        float64
missing value      48864
Name: key_passes_per90_percentile_overall, dtype: object
Data type        float64
missing value      48864
Name: dribbles_total_overall, dtype: object
Data type        float64
missing value      48864
Name: dribbles_per_90_overall, dtype: object
Data type        float64
missing value      48864
Name: dribbles_per90_percentile_overall, dtype: object
Data type        float64
missing value      48864
Name: dribbles_successful_total_overall, dtype: object
Data type        float64
missing value      48864
Name: dribbles_successful_per_90_overall, dtype: object
Data type        float64
missing value      48864
Name: dribbles_successful_percentage_overall, dtype: object
Data type        float64
missing value      48864
Name: chances_created_total_overall, dtype: object
Data type        float64
missing value      48864
Name: chances_created_per_90_overall, dtype: object
Data type        float64
missing value      48864
Name: chances_created_per90_percentile_overall, dtype: object
Data type        float64
missing value      48864
Name: saves_total_overall, dtype: object
Data type        float64
missing value      48864
Name: save_percentage_percentile_overall, dtype: object
Data type        float64
missing value      48864
Name: saves_per_90_overall, dtype: object
Data type        float64
missing value      48864
Name: saves_per90_percentile_overall, dtype: object
Data type        float64
missing value      48864
Name: shots_faced_total_overall, dtype: object
Data type        float64
missing value      48864
Name: shots_per_goal_conceded_overall, dtype: object
Data type        float64
missing value      48864
Name: conceded_per90_percentile_overall, dtype: object
Data type        float64
missing value      48864
Name: shots_faced_per_90_overall, dtype: object
Data type        float64
missing value      48864
Name: shots_faced_per90_percentile_overall, dtype: object
Data type        float64
missing value      65697
Name: xg_faced_per_90_overall, dtype: object
Data type        float64
missing value      65697
Name: xg_faced_per90_percentile_overall, dtype: object
Data type        float64
missing value      65697
Name: xg_faced_per_game_overall, dtype: object
Data type        float64
missing value      65697
Name: xg_faced_total_overall, dtype: object
Data type        float64
missing value      48864
Name: save_percentage_overall, dtype: object
Data type        float64
missing value      48864
Name: pressures_total_overall, dtype: object
Data type        float64
missing value      48864
Name: pressures_per_90_overall, dtype: object
Data type        float64
missing value      48864
Name: pressures_per90_percentile_overall, dtype: object
Data type        float64
missing value      48864
Name: xg_total_overall, dtype: object
Data type        float64
missing value      48864
Name: market_value, dtype: object
Data type        float64
missing value      48864
Name: market_value_percentile, dtype: object
Data type        float64
missing value      48864
Name: pass_completion_rate_overall, dtype: object
Data type        float64
missing value      48864
Name: shot_accuraccy_percentage_overall, dtype: object
Data type        float64
missing value      48864
Name: shot_accuraccy_percentage_percentile_overall, dtype: object
Data type        float64
missing value      48864
Name: dribbled_past_per90_percentile_overall, dtype: object
Data type        float64
missing value      48864
Name: dribbled_past_per_game_overall, dtype: object
Data type        float64
missing value      48864
Name: dribbled_past_per_90_overall, dtype: object
Data type        float64
missing value      48864
Name: dribbled_past_total_overall, dtype: object
Data type        float64
missing value      48864
Name: dribbles_successful_per90_percentile_overall, dtype: object
Data type        float64
missing value      48864
Name: dribbles_successful_percentage_percentile_overall, dtype: object
Data type        float64
missing value      48864
Name: pen_scored_total_overall, dtype: object
Data type        float64
missing value      48864
Name: pen_missed_total_overall, dtype: object
Data type        float64
missing value      48864
Name: inside_box_saves_total_overall, dtype: object
Data type        float64
missing value      48864
Name: blocks_per_game_overall, dtype: object
Data type        float64
missing value      48864
Name: blocks_per_90_overall, dtype: object
Data type        float64
missing value      48864
Name: blocks_total_overall, dtype: object
Data type        float64
missing value      48864
Name: blocks_per90_percentile_overall, dtype: object
Data type        float64
missing value      48864
Name: ratings_total_overall, dtype: object
Data type        float64
missing value      48864
Name: clearances_per_game_overall, dtype: object
Data type        float64
missing value      48864
Name: clearances_per_90_overall, dtype: object
Data type        float64
missing value      48864
Name: clearances_total_overall, dtype: object
Data type        float64
missing value      48864
Name: pen_committed_total_overall, dtype: object
Data type        float64
missing value      48864
Name: pen_save_percentage_overall, dtype: object
Data type        float64
missing value      48864
Name: pen_committed_per_90_overall, dtype: object
Data type        float64
missing value      48864
Name: pen_committed_per90_percentile_overall, dtype: object
Data type        float64
missing value      48864
Name: pen_committed_per_game_overall, dtype: object
Data type        float64
missing value      48864
Name: pens_saved_total_overall, dtype: object
Data type        float64
missing value      48864
Name: pens_taken_total_overall, dtype: object
Data type        float64
missing value      48864
Name: hit_woodwork_total_overall, dtype: object
Data type        float64
missing value      48864
Name: hit_woodwork_per_game_overall, dtype: object
Data type        float64
missing value      48864
Name: hit_woodwork_per_90_overall, dtype: object
Data type        float64
missing value      48864
Name: punches_total_overall, dtype: object
Data type        float64
missing value      48864
Name: punches_per_game_overall, dtype: object
Data type        float64
missing value      48864
Name: punches_per_90_overall, dtype: object
Data type        float64
missing value      48864
Name: offsides_per_90_overall, dtype: object
Data type        float64
missing value      48864
Name: offsides_per_game_overall, dtype: object
Data type        float64
missing value      48864
Name: offsides_total_overall, dtype: object
Data type        float64
missing value      48864
Name: penalties_won_total_overall, dtype: object
Data type        float64
missing value      48864
Name: shot_conversion_rate_overall, dtype: object
Data type        float64
missing value      48864
Name: shot_conversion_rate_percentile_overall, dtype: object
Data type        float64
missing value      48864
Name: minutes_played_percentile_overall, dtype: object
Data type        float64
missing value      48864
Name: matches_played_percentile_overall, dtype: object
Data type        float64
missing value      48864
Name: min_per_goal_percentile_overall, dtype: object
Data type        float64
missing value      48864
Name: min_per_conceded_percentile_overall, dtype: object
Data type        float64
missing value      48864
Name: xa_total_overall, dtype: object
Data type        float64
missing value      48864
Name: xa_per90_percentile_overall, dtype: object
Data type        float64
missing value      48864
Name: xa_per_game_overall, dtype: object
Data type        float64
missing value      48864
Name: xa_per_90_overall, dtype: object
Data type        float64
missing value      48864
Name: npxg_total_overall, dtype: object
Data type        float64
missing value      48864
Name: npxg_per90_percentile_overall, dtype: object
Data type        float64
missing value      48864
Name: npxg_per_game_overall, dtype: object
Data type        float64
missing value      48864
Name: npxg_per_90_overall, dtype: object
Data type        float64
missing value      48864
Name: fouls_drawn_per90_percentile_overall, dtype: object
Data type        float64
missing value      48864

In [9]:
players["rank_in_league_top_midfielders"]

0     -1
1     -1
2     -1
3     -1
4     -1
      ..
817   -1
818   -1
819   -1
820   -1
821   -1
Name: rank_in_league_top_midfielders, Length: 65697, dtype: int64

In [10]:
players=players[["age","birthday_GMT","season","Current Club"]]
players=players.reset_index()

In [11]:
players=players.drop(columns=["index"])
players

       age  birthday_GMT season  Current Club
0       35        1987.0   2006       England
1       41        1980.0   2006   Ivory Coast
2       41        1981.0   2006   Ivory Coast
3       49        1973.0   2006  Saudi Arabia
4       42        1980.0   2006          Togo
...    ...           ...    ...           ...
65692   31        1994.0   2022       Denmark
65693   39        1986.0   2022         Japan
65694   26        2000.0   2022       Morocco
65695   22        2003.0   2022       Belgium
65696   34        1991.0   2022        Poland

[65697 rows x 4 columns]

In [13]:
print(players.dtypes)

age               int64
birthday_GMT    float64
season           object
Current Club     object
dtype: object

In [14]:
players["season"]=pd.to_numeric(players["season"], errors="coerce")
players["age"]=players.apply(lambda row:(row["season"]-row["birthday_GMT"]),axis=1)
players

        age  birthday_GMT  season  Current Club
0      19.0        1987.0  2006.0       England
1      26.0        1980.0  2006.0   Ivory Coast
2      25.0        1981.0  2006.0   Ivory Coast
3      33.0        1973.0  2006.0  Saudi Arabia
4      26.0        1980.0  2006.0          Togo
...     ...           ...     ...           ...
65692  28.0        1994.0  2022.0       Denmark
65693  36.0        1986.0  2022.0         Japan
65694  22.0        2000.0  2022.0       Morocco
65695  19.0        2003.0  2022.0       Belgium
65696  31.0        1991.0  2022.0        Poland

[65697 rows x 4 columns]

In [15]:
players=players.groupby(["Current Club","season"])["age"].mean()
players=players.reset_index()
players

         Current Club  season        age
0         Afghanistan  2021.0  27.047619
1         Afghanistan  2022.0  28.000000
2         Afghanistan  2024.0  27.000000
3         Afghanistan  2025.0  27.142857
4         Afghanistan  2026.0  28.592593
...               ...     ...        ...
1766         Zimbabwe  2024.0  26.095238
1767         Zimbabwe  2025.0  27.764706
1768         Zimbabwe  2026.0  29.061224
1769  Étoile du Congo  2022.0  25.157895
1770  Étoile du Congo  2026.0  26.942857

[1771 rows x 3 columns]

## get the essentiel info from matches data

In [16]:
matches

,timestamp,date_GMT,status,attendance,home_team_name,away_team_name,referee,Game Week,Pre-Match PPG (Home),Pre-Match PPG (Away),...,odds_ft_home_team_win,odds_ft_draw,odds_ft_away_team_win,odds_ft_over15,odds_ft_over25,odds_ft_over35,odds_ft_over45,odds_btts_yes,odds_btts_no,stadium_name
0,1149868800,Jun 09 2006 - 4:00pm,complete,66000.0,Germany,Costa Rica,NaN,1.0,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,Allianz Arena
1,1149879600,Jun 09 2006 - 7:00pm,complete,52000.0,Poland,Ecuador,NaN,1.0,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,VELTINS-Arena
2,1149944400,Jun 10 2006 - 1:00pm,complete,48000.0,England,Paraguay,NaN,1.0,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,Commerzbank-Arena
3,1149955200,Jun 10 2006 - 4:00pm,complete,62959.0,Trinidad and Tobago,Sweden,NaN,1.0,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,Signal-Iduna-Park
4,1149966000,Jun 10 2006 - 7:00pm,complete,49480.0,Argentina,Ivory Coast,NaN,1.0,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,Volksparkstadion
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59,1670698800,Dec 10 2022 - 7:00pm,complete,NaN,England,France,Wilton Pereira Sampaio,NaN,2.50,2.25,...,3.10,3.20,2.38,1.32,2.10,3.40,6.3,1.80,1.95,Al Bayt Stadium (Al Khor)
60,1670958000,Dec 13 2022 - 7:00pm,complete,88966.0,Argentina,Croatia,Daniele Orsato,NaN,2.00,1.40,...,1.80,3.40,5.00,1.52,2.48,4.50,9.0,2.25,1.57,Lusail Iconic Stadium (Lusail)
61,1671044400,Dec 14 2022 - 7:00pm,complete,NaN,France,Morocco,César Arturo Ramos Palazuelos,NaN,2.40,2.20,...,1.57,4.00,6.75,1.40,2.25,1.79,9.5,2.25,1.57,Al Bayt Stadium (Al Khor)
62,1671289200,Dec 17 2022 - 3:00pm,complete,NaN,Croatia,Morocco,Abdulrahman Ibrahim Al Jassim,NaN,1.17,1.83,...,2.43,3.40,3.10,1.26,2.07,2.98,5.7,1.67,2.10,Khalifa International Stadium (Al Rayyan (Ar-R...
63,1671375600,Dec 18 2022 - 3:00pm,complete,88966.0,Argentina,France,Szymon Marciniak,NaN,2.17,2.50,...,2.70,2.95,2.65,1.45,2.35,4.30,7.5,2.00,1.75,Lusail Iconic Stadium (Lusail)

In [17]:
matches["date_GMT"]=pd.to_datetime(matches["date_GMT"],errors="coerce")
matches["season"]=matches["date_GMT"].dt.year
matches["hour"]=matches["date_GMT"].dt.hour
matches

/tmp/ipykernel_24978/3995122214.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  matches["date_GMT"]=pd.to_datetime(matches["date_GMT"],errors="coerce")

,timestamp,date_GMT,status,attendance,home_team_name,away_team_name,referee,Game Week,Pre-Match PPG (Home),Pre-Match PPG (Away),...,odds_ft_away_team_win,odds_ft_over15,odds_ft_over25,odds_ft_over35,odds_ft_over45,odds_btts_yes,odds_btts_no,stadium_name,season,hour
0,1149868800,2006-06-09 16:00:00,complete,66000.0,Germany,Costa Rica,NaN,1.0,0.00,0.00,...,0.00,0.00,0.00,0.00,0.0,0.00,0.00,Allianz Arena,2006,16
1,1149879600,2006-06-09 19:00:00,complete,52000.0,Poland,Ecuador,NaN,1.0,0.00,0.00,...,0.00,0.00,0.00,0.00,0.0,0.00,0.00,VELTINS-Arena,2006,19
2,1149944400,2006-06-10 13:00:00,complete,48000.0,England,Paraguay,NaN,1.0,0.00,0.00,...,0.00,0.00,0.00,0.00,0.0,0.00,0.00,Commerzbank-Arena,2006,13
3,1149955200,2006-06-10 16:00:00,complete,62959.0,Trinidad and Tobago,Sweden,NaN,1.0,0.00,0.00,...,0.00,0.00,0.00,0.00,0.0,0.00,0.00,Signal-Iduna-Park,2006,16
4,1149966000,2006-06-10 19:00:00,complete,49480.0,Argentina,Ivory Coast,NaN,1.0,0.00,0.00,...,0.00,0.00,0.00,0.00,0.0,0.00,0.00,Volksparkstadion,2006,19
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59,1670698800,2022-12-10 19:00:00,complete,NaN,England,France,Wilton Pereira Sampaio,NaN,2.50,2.25,...,2.38,1.32,2.10,3.40,6.3,1.80,1.95,Al Bayt Stadium (Al Khor),2022,19
60,1670958000,2022-12-13 19:00:00,complete,88966.0,Argentina,Croatia,Daniele Orsato,NaN,2.00,1.40,...,5.00,1.52,2.48,4.50,9.0,2.25,1.57,Lusail Iconic Stadium (Lusail),2022,19
61,1671044400,2022-12-14 19:00:00,complete,NaN,France,Morocco,César Arturo Ramos Palazuelos,NaN,2.40,2.20,...,6.75,1.40,2.25,1.79,9.5,2.25,1.57,Al Bayt Stadium (Al Khor),2022,19
62,1671289200,2022-12-17 15:00:00,complete,NaN,Croatia,Morocco,Abdulrahman Ibrahim Al Jassim,NaN,1.17,1.83,...,3.10,1.26,2.07,2.98,5.7,1.67,2.10,Khalifa International Stadium (Al Rayyan (Ar-R...,2022,15
63,1671375600,2022-12-18 15:00:00,complete,88966.0,Argentina,France,Szymon Marciniak,NaN,2.17,2.50,...,2.65,1.45,2.35,4.30,7.5,2.00,1.75,Lusail Iconic Stadium (Lusail),2022,15

In [18]:
matches_summary=pd.DataFrame({
    "Data type":matches.dtypes,
    "missing value":matches.isna().sum()
    }
)
n=len(matches_summary)
for i in range(n):
    print(matches_summary.iloc[i])

Data type        int64
missing value        0
Name: timestamp, dtype: object
Data type        datetime64[ns]
missing value                 0
Name: date_GMT, dtype: object
Data type        object
missing value         0
Name: status, dtype: object
Data type        float64
missing value       3821
Name: attendance, dtype: object
Data type        object
missing value         0
Name: home_team_name, dtype: object
Data type        object
missing value         0
Name: away_team_name, dtype: object
Data type        object
missing value      4664
Name: referee, dtype: object
Data type        float64
missing value       3839
Name: Game Week, dtype: object
Data type        float64
missing value          0
Name: Pre-Match PPG (Home), dtype: object
Data type        float64
missing value          0
Name: Pre-Match PPG (Away), dtype: object
Data type        float64
missing value          0
Name: home_ppg, dtype: object
Data type        float64
missing value          0
Name: away_ppg, dtype: object
Data type        int64
missing value        0
Name: home_team_goal_count, dtype: object
Data type        int64
missing value        0
Name: away_team_goal_count, dtype: object
Data type        int64
missing value        0
Name: total_goal_count, dtype: object
Data type        int64
missing value        0
Name: total_goals_at_half_time, dtype: object
Data type        int64
missing value        0
Name: home_team_goal_count_half_time, dtype: object
Data type        int64
missing value        0
Name: away_team_goal_count_half_time, dtype: object
Data type        object
missing value      2309
Name: home_team_goal_timings, dtype: object
Data type        object
missing value      2961
Name: away_team_goal_timings, dtype: object
Data type        int64
missing value        0
Name: home_team_corner_count, dtype: object
Data type        int64
missing value        0
Name: away_team_corner_count, dtype: object
Data type        int64
missing value        0
Name: home_team_yellow_cards, dtype: object
Data type        int64
missing value        0
Name: home_team_red_cards, dtype: object
Data type        int64
missing value        0
Name: away_team_yellow_cards, dtype: object
Data type        int64
missing value        0
Name: away_team_red_cards, dtype: object
Data type        int64
missing value        0
Name: home_team_first_half_cards, dtype: object
Data type        int64
missing value        0
Name: home_team_second_half_cards, dtype: object
Data type        int64
missing value        0
Name: away_team_first_half_cards, dtype: object
Data type        int64
missing value        0
Name: away_team_second_half_cards, dtype: object
Data type        int64
missing value        0
Name: home_team_shots, dtype: object
Data type        int64
missing value        0
Name: away_team_shots, dtype: object
Data type        int64
missing value        0
Name: home_team_shots_on_target, dtype: object
Data type        int64
missing value        0
Name: away_team_shots_on_target, dtype: object
Data type        int64
missing value        0
Name: home_team_shots_off_target, dtype: object
Data type        int64
missing value        0
Name: away_team_shots_off_target, dtype: object
Data type        int64
missing value        0
Name: home_team_fouls, dtype: object
Data type        int64
missing value        0
Name: away_team_fouls, dtype: object
Data type        int64
missing value        0
Name: home_team_possession, dtype: object
Data type        int64
missing value        0
Name: away_team_possession, dtype: object
Data type        float64
missing value          0
Name: Home Team Pre-Match xG, dtype: object
Data type        float64
missing value          0
Name: Away Team Pre-Match xG, dtype: object
Data type        float64
missing value          0
Name: team_a_xg, dtype: object
Data type        float64
missing value          0
Name: team_b_xg, dtype: object
Data type        float64
missing value          0
Name: average_goals_per_match_pre_match, dtype: object
Data type        int64
missing value        0
Name: btts_percentage_pre_match, dtype: object
Data type        int64
missing value        0
Name: over_15_percentage_pre_match, dtype: object
Data type        int64
missing value        0
Name: over_25_percentage_pre_match, dtype: object
Data type        int64
missing value        0
Name: over_35_percentage_pre_match, dtype: object
Data type        int64
missing value        0
Name: over_45_percentage_pre_match, dtype: object
Data type        int64
missing value        0
Name: over_15_HT_FHG_percentage_pre_match, dtype: object
Data type        int64
missing value        0
Name: over_05_HT_FHG_percentage_pre_match, dtype: object
Data type        int64
missing value        0
Name: over_15_2HG_percentage_pre_match, dtype: object
Data type        int64
missing value        0
Name: over_05_2HG_percentage_pre_match, dtype: object
Data type        float64
missing value          0
Name: average_corners_per_match_pre_match, dtype: object
Data type        float64
missing value          0
Name: average_cards_per_match_pre_match, dtype: object
Data type        float64
missing value          0
Name: odds_ft_home_team_win, dtype: object
Data type        float64
missing value          0
Name: odds_ft_draw, dtype: object
Data type        float64
missing value          0
Name: odds_ft_away_team_win, dtype: object
Data type        float64
missing value          0
Name: odds_ft_over15, dtype: object
Data type        float64
missing value          0
Name: odds_ft_over25, dtype: object
Data type        float64
missing value          0
Name: odds_ft_over35, dtype: object
Data type        float64
missing value          0
Name: odds_ft_over45, dtype: object
Data type        float64
missing value          0
Name: odds_btts_yes, dtype: object
Data type        float64
missing value          0
Name: odds_btts_no, dtype: object
Data type        object
missing value      1187
Name: stadium_name, dtype: object
Data type        int32
missing value        0
Name: season, dtype: object
Data type        int32
missing value        0
Name: hour, dtype: object

In [19]:
matches=matches[["home_team_name","away_team_name","home_team_goal_count","away_team_goal_count","home_team_goal_count_half_time","away_team_goal_count_half_time","Home Team Pre-Match xG","Away Team Pre-Match xG","hour","season"]]
matches

,home_team_name,away_team_name,home_team_goal_count,away_team_goal_count,home_team_goal_count_half_time,away_team_goal_count_half_time,Home Team Pre-Match xG,Away Team Pre-Match xG,hour,season
0,Germany,Costa Rica,4,2,2,1,0.00,0.00,16,2006
1,Poland,Ecuador,0,2,0,1,0.00,0.00,19,2006
2,England,Paraguay,1,0,1,0,0.00,0.00,13,2006
3,Trinidad and Tobago,Sweden,0,0,0,0,0.00,0.00,16,2006
4,Argentina,Ivory Coast,2,1,2,0,0.00,0.00,19,2006
...,...,...,...,...,...,...,...,...,...,...
59,England,France,1,2,0,1,1.50,1.97,19,2022
60,Argentina,Croatia,3,0,2,0,1.62,1.28,19,2022
61,France,Morocco,2,0,1,0,1.81,0.88,19,2022
62,Croatia,Morocco,2,1,2,1,1.27,0.98,15,2022
63,Argentina,France,3,3,2,0,1.56,1.72,15,2022

In [20]:
players.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1771 entries, 0 to 1770
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Current Club  1771 non-null   object
 1   season        1771 non-null   float64
 2   age           1771 non-null   float64
dtypes: float64(2), object(1)
memory usage: 41.6+ KB

In [21]:
matches.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5926 entries, 0 to 63
Data columns (total 10 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   home_team_name                  5926 non-null   object
 1   away_team_name                  5926 non-null   object
 2   home_team_goal_count            5926 non-null   int64
 3   away_team_goal_count            5926 non-null   int64
 4   home_team_goal_count_half_time  5926 non-null   int64
 5   away_team_goal_count_half_time  5926 non-null   int64
 6   Home Team Pre-Match xG          5926 non-null   float64
 7   Away Team Pre-Match xG          5926 non-null   float64
 8   hour                            5926 non-null   int32
 9   season                          5926 non-null   int32
dtypes: float64(2), int32(2), int64(4), object(2)
memory usage: 463.0+ KB

In [22]:
matches=matches.merge(
    players,
    left_on=["home_team_name","season"],
    right_on=["Current Club","season"],
    how="left"
)
matches.rename(columns={"age": "home_team_age"}, inplace=True)
matches.drop(columns=["Current Club"], inplace=True)
matches=matches.merge(
    players,
    left_on=["away_team_name","season"],
    right_on=["Current Club","season"],
    how="left"
)
matches.rename(columns={"age": "away_team_age"}, inplace=True)
matches.drop(columns=["Current Club"], inplace=True)
matches

,home_team_name,away_team_name,home_team_goal_count,away_team_goal_count,home_team_goal_count_half_time,away_team_goal_count_half_time,Home Team Pre-Match xG,Away Team Pre-Match xG,hour,season,home_team_age,away_team_age
0,Germany,Costa Rica,4,2,2,1,0.00,0.00,16,2006,26.956522,28.086957
1,Poland,Ecuador,0,2,0,1,0.00,0.00,19,2006,27.173913,27.000000
2,England,Paraguay,1,0,1,0,0.00,0.00,13,2006,25.869565,27.173913
3,Trinidad and Tobago,Sweden,0,0,0,0,0.00,0.00,16,2006,29.565217,28.173913
4,Argentina,Ivory Coast,2,1,2,0,0.00,0.00,19,2006,26.565217,25.956522
...,...,...,...,...,...,...,...,...,...,...,...,...
5921,England,France,1,2,0,1,1.50,1.97,19,2022,26.376471,27.452381
5922,Argentina,Croatia,3,0,2,0,1.62,1.28,19,2022,27.491525,27.531915
5923,France,Morocco,2,0,1,0,1.81,0.88,19,2022,27.452381,26.809524
5924,Croatia,Morocco,2,1,2,1,1.27,0.98,15,2022,27.531915,26.809524
5925,Argentina,France,3,3,2,0,1.56,1.72,15,2022,27.491525,27.452381

In [23]:
print(players.loc[(players["Current Club"]=="Germany") & (players["season"]==2006),"age"])

593    26.956522
Name: age, dtype: float64

In [ ]:
matches=matches.drop(columns=["match_number","index"])