In [87]:
import numpy as np
import pandas as pd
import os 
import re

## extract the data

In [88]:
pattern1=r"matches"
matches=pd.DataFrame()
players=pd.DataFrame()
data="../data"
for dirc in os.listdir(data):
    path=os.path.join(data,dirc)
    if os.path.isdir(path):
        print(dirc)
        for file in os.listdir(path):
            match=re.search(pattern1,file)
            if match:
                target_file=os.path.join(path,file)
                matches2=pd.read_csv(target_file)
                if matches.empty:
                    matches=matches2
                else :
                    matches=pd.concat([matches,matches2])
            else :
                target_file=os.path.join(path,file)
                players2=pd.read_csv(target_file)
                if players.empty:
                    players=players2
                else :
                    players=pd.concat([players,players2])   
                 
matches

2006
2018
2010
2002
2014
2022

,timestamp,date_GMT,status,attendance,home_team_name,away_team_name,referee,Game Week,Pre-Match PPG (Home),Pre-Match PPG (Away),...,odds_ft_home_team_win,odds_ft_draw,odds_ft_away_team_win,odds_ft_over15,odds_ft_over25,odds_ft_over35,odds_ft_over45,odds_btts_yes,odds_btts_no,stadium_name
0,1149868800,Jun 09 2006 - 4:00pm,complete,66000.0,Germany,Costa Rica,NaN,1.0,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,Allianz Arena
1,1149879600,Jun 09 2006 - 7:00pm,complete,52000.0,Poland,Ecuador,NaN,1.0,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,VELTINS-Arena
2,1149944400,Jun 10 2006 - 1:00pm,complete,48000.0,England,Paraguay,NaN,1.0,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,Commerzbank-Arena
3,1149955200,Jun 10 2006 - 4:00pm,complete,62959.0,Trinidad and Tobago,Sweden,NaN,1.0,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,Signal-Iduna-Park
4,1149966000,Jun 10 2006 - 7:00pm,complete,49480.0,Argentina,Ivory Coast,NaN,1.0,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,Volksparkstadion
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59,1670698800,Dec 10 2022 - 7:00pm,complete,NaN,England,France,Wilton Pereira Sampaio,NaN,2.50,2.25,...,3.10,3.20,2.38,1.32,2.10,3.40,6.3,1.80,1.95,Al Bayt Stadium (Al Khor)
60,1670958000,Dec 13 2022 - 7:00pm,complete,88966.0,Argentina,Croatia,Daniele Orsato,NaN,2.00,1.40,...,1.80,3.40,5.00,1.52,2.48,4.50,9.0,2.25,1.57,Lusail Iconic Stadium (Lusail)
61,1671044400,Dec 14 2022 - 7:00pm,complete,NaN,France,Morocco,César Arturo Ramos Palazuelos,NaN,2.40,2.20,...,1.57,4.00,6.75,1.40,2.25,1.79,9.5,2.25,1.57,Al Bayt Stadium (Al Khor)
62,1671289200,Dec 17 2022 - 3:00pm,complete,NaN,Croatia,Morocco,Abdulrahman Ibrahim Al Jassim,NaN,1.17,1.83,...,2.43,3.40,3.10,1.26,2.07,2.98,5.7,1.67,2.10,Khalifa International Stadium (Al Rayyan (Ar-R...
63,1671375600,Dec 18 2022 - 3:00pm,complete,88966.0,Argentina,France,Szymon Marciniak,NaN,2.17,2.50,...,2.70,2.95,2.65,1.45,2.35,4.30,7.5,2.00,1.75,Lusail Iconic Stadium (Lusail)

In [89]:
players

,full_name,age,birthday,birthday_GMT,league,season,position,Current Club,minutes_played_overall,minutes_played_home,...,annual_salary_eur_percentile,clean_sheets_percentage_percentile_overall,min_per_card_percentile_overall,cards_per90_percentile_overall,booked_over05_overall,booked_over05_percentage_overall,booked_over05_percentage_percentile_overall,shirt_number,annual_salary_gbp,annual_salary_usd
0,Aaron Lennon,35,545554800,1987/04/16,FIFA World Cup 2006 Germany,2006,Midfielder,England,102,102,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Abdoulaye Mu00e9u00eftu00e9,41,339663600,1980/10/06,FIFA World Cup 2006 Germany,2006,Defender,Ivory Coast,180,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Abdul Kader Keu00efta,41,365929200,1981/08/06,FIFA World Cup 2006 Germany,2006,Midfielder,Ivory Coast,150,73,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Abdulaziz Mohammed Al Khathran,49,112950000,1973/07/31,FIFA World Cup 2006 Germany,2006,Midfielder,Saudi Arabia,125,125,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Adékambi Olufadé,42,316080000,1980/01/07,FIFA World Cup 2006 Germany,2006,Forward,Togo,31,31,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
817,Yussuf Poulsen,31,771638400,1994/06/15,FIFA World Cup 2022 Qatar,2022,Forward,Denmark,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
818,Yuto Nagatomo,39,526867200,1986/09/12,FIFA World Cup 2022 Qatar,2022,Defender,Japan,213,156,...,46.0,7.0,21.0,21.0,0.0,0.0,21.0,5.0,0.0,0.0
819,Zakaria Aboukhlal,26,950832000,2000/02/18,FIFA World Cup 2022 Qatar,2022,Forward,Morocco,73,8,...,46.0,92.0,21.0,21.0,0.0,0.0,21.0,14.0,0.0,0.0
820,Zeno Debast,22,1066953600,2003/10/24,FIFA World Cup 2022 Qatar,2022,Midfielder,Belgium,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
821,Łukasz Skorupski,34,673401600,1991/05/05,FIFA World Cup 2022 Qatar,2022,Goalkeeper,Poland,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## get essenteil info from players data

In [90]:
print(np.unique(players["season"]))

[2002 2006 2010 2014 2018 2022]

In [91]:
def get_birthyear(date):
    i=0
    year=""
    while date[i] != "/" and i<len(date):
        year=year+date[i]
        i+=1
    return int(year)
print(get_birthyear("1991/05/05"))

1991

In [92]:
players["birthday_GMT"]=players["birthday_GMT"].apply(get_birthyear)

In [93]:
players

,full_name,age,birthday,birthday_GMT,league,season,position,Current Club,minutes_played_overall,minutes_played_home,...,annual_salary_eur_percentile,clean_sheets_percentage_percentile_overall,min_per_card_percentile_overall,cards_per90_percentile_overall,booked_over05_overall,booked_over05_percentage_overall,booked_over05_percentage_percentile_overall,shirt_number,annual_salary_gbp,annual_salary_usd
0,Aaron Lennon,35,545554800,1987,FIFA World Cup 2006 Germany,2006,Midfielder,England,102,102,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Abdoulaye Mu00e9u00eftu00e9,41,339663600,1980,FIFA World Cup 2006 Germany,2006,Defender,Ivory Coast,180,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Abdul Kader Keu00efta,41,365929200,1981,FIFA World Cup 2006 Germany,2006,Midfielder,Ivory Coast,150,73,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Abdulaziz Mohammed Al Khathran,49,112950000,1973,FIFA World Cup 2006 Germany,2006,Midfielder,Saudi Arabia,125,125,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Adékambi Olufadé,42,316080000,1980,FIFA World Cup 2006 Germany,2006,Forward,Togo,31,31,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
817,Yussuf Poulsen,31,771638400,1994,FIFA World Cup 2022 Qatar,2022,Forward,Denmark,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
818,Yuto Nagatomo,39,526867200,1986,FIFA World Cup 2022 Qatar,2022,Defender,Japan,213,156,...,46.0,7.0,21.0,21.0,0.0,0.0,21.0,5.0,0.0,0.0
819,Zakaria Aboukhlal,26,950832000,2000,FIFA World Cup 2022 Qatar,2022,Forward,Morocco,73,8,...,46.0,92.0,21.0,21.0,0.0,0.0,21.0,14.0,0.0,0.0
820,Zeno Debast,22,1066953600,2003,FIFA World Cup 2022 Qatar,2022,Midfielder,Belgium,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
821,Łukasz Skorupski,34,673401600,1991,FIFA World Cup 2022 Qatar,2022,Goalkeeper,Poland,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [94]:
players.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4502 entries, 0 to 821
Columns: 271 entries, full_name to annual_salary_usd
dtypes: float64(231), int64(35), object(5)
memory usage: 9.3+ MB

In [95]:
players_summary=pd.DataFrame({
    "Data type":players.dtypes,
    "missing value":players.isna().sum()
    }
)
players_summary

                                            Data type  missing value
full_name                                      object              0
age                                             int64              0
birthday                                        int64              0
birthday_GMT                                    int64              0
league                                         object              0
...                                               ...            ...
booked_over05_percentage_overall              float64           3827
booked_over05_percentage_percentile_overall   float64           3827
shirt_number                                  float64           3827
annual_salary_gbp                             float64           3827
annual_salary_usd                             float64           3827

[271 rows x 2 columns]

In [96]:
n=len(players_summary)
for i in range(n):
    print(players_summary.iloc[i])

Data type        object
missing value         0
Name: full_name, dtype: object
Data type        int64
missing value        0
Name: age, dtype: object
Data type        int64
missing value        0
Name: birthday, dtype: object
Data type        int64
missing value        0
Name: birthday_GMT, dtype: object
Data type        object
missing value         0
Name: league, dtype: object
Data type        int64
missing value        0
Name: season, dtype: object
Data type        object
missing value         0
Name: position, dtype: object
Data type        object
missing value         0
Name: Current Club, dtype: object
Data type        int64
missing value        0
Name: minutes_played_overall, dtype: object
Data type        int64
missing value        0
Name: minutes_played_home, dtype: object
Data type        int64
missing value        0
Name: minutes_played_away, dtype: object
Data type        object
missing value         0
Name: nationality, dtype: object
Data type        int64
missing value        0
Name: appearances_overall, dtype: object
Data type        int64
missing value        0
Name: appearances_home, dtype: object
Data type        int64
missing value        0
Name: appearances_away, dtype: object
Data type        int64
missing value        0
Name: goals_overall, dtype: object
Data type        int64
missing value        0
Name: goals_home, dtype: object
Data type        int64
missing value        0
Name: goals_away, dtype: object
Data type        int64
missing value        0
Name: assists_overall, dtype: object
Data type        int64
missing value        0
Name: assists_home, dtype: object
Data type        int64
missing value        0
Name: assists_away, dtype: object
Data type        int64
missing value        0
Name: penalty_goals, dtype: object
Data type        int64
missing value        0
Name: penalty_misses, dtype: object
Data type        int64
missing value        0
Name: clean_sheets_overall, dtype: object
Data type        int64
missing value        0
Name: clean_sheets_home, dtype: object
Data type        int64
missing value        0
Name: clean_sheets_away, dtype: object
Data type        int64
missing value        0
Name: conceded_overall, dtype: object
Data type        int64
missing value        0
Name: conceded_home, dtype: object
Data type        int64
missing value        0
Name: conceded_away, dtype: object
Data type        int64
missing value        0
Name: yellow_cards_overall, dtype: object
Data type        int64
missing value        0
Name: red_cards_overall, dtype: object
Data type        float64
missing value          0
Name: goals_involved_per_90_overall, dtype: object
Data type        float64
missing value          0
Name: assists_per_90_overall, dtype: object
Data type        float64
missing value          0
Name: goals_per_90_overall, dtype: object
Data type        float64
missing value          0
Name: goals_per_90_home, dtype: object
Data type        float64
missing value          0
Name: goals_per_90_away, dtype: object
Data type        int64
missing value        0
Name: min_per_goal_overall, dtype: object
Data type        float64
missing value          0
Name: conceded_per_90_overall, dtype: object
Data type        int64
missing value        0
Name: min_per_conceded_overall, dtype: object
Data type        int64
missing value        0
Name: min_per_match, dtype: object
Data type        int64
missing value        0
Name: min_per_card_overall, dtype: object
Data type        int64
missing value        0
Name: min_per_assist_overall, dtype: object
Data type        float64
missing value          0
Name: cards_per_90_overall, dtype: object
Data type        int64
missing value        0
Name: rank_in_league_top_attackers, dtype: object
Data type        int64
missing value        0
Name: rank_in_league_top_midfielders, dtype: object
Data type        int64
missing value        0
Name: rank_in_league_top_defenders, dtype: object
Data type        int64
missing value        0
Name: rank_in_club_top_scorer, dtype: object
Data type        float64
missing value       3827
Name: annual_salary_eur, dtype: object
Data type        float64
missing value       3827
Name: average_rating_overall, dtype: object
Data type        float64
missing value       3827
Name: assists_per_game_overall, dtype: object
Data type        float64
missing value       3827
Name: assists_per90_percentile_overall, dtype: object
Data type        float64
missing value       3827
Name: passes_per_90_overall, dtype: object
Data type        float64
missing value       3827
Name: passes_per_game_overall, dtype: object
Data type        float64
missing value       3827
Name: passes_per90_percentile_overall, dtype: object
Data type        float64
missing value       3827
Name: passes_total_overall, dtype: object
Data type        float64
missing value       3827
Name: passes_completed_per_game_overall, dtype: object
Data type        float64
missing value       3827
Name: passes_completed_total_overall, dtype: object
Data type        float64
missing value       3827
Name: pass_completion_rate_percentile_overall, dtype: object
Data type        float64
missing value       3827
Name: passes_completed_per_90_overall, dtype: object
Data type        float64
missing value       3827
Name: passes_completed_per90_percentile_overall, dtype: object
Data type        float64
missing value       3827
Name: short_passes_per_game_overall, dtype: object
Data type        float64
missing value       3827
Name: long_passes_per_game_overall, dtype: object
Data type        float64
missing value       3827
Name: key_passes_per_game_overall, dtype: object
Data type        float64
missing value       3827
Name: key_passes_total_overall, dtype: object
Data type        float64
missing value       3827
Name: through_passes_per_game_overall, dtype: object
Data type        float64
missing value       3827
Name: crosses_per_game_overall, dtype: object
Data type        float64
missing value       3827
Name: tackles_per_90_overall, dtype: object
Data type        float64
missing value       3827
Name: tackles_per_game_overall, dtype: object
Data type        float64
missing value       3827
Name: tackles_total_overall, dtype: object
Data type        float64
missing value       3827
Name: tackles_successful_per_game_overall, dtype: object
Data type        float64
missing value       3827
Name: dispossesed_per_game_overall, dtype: object
Data type        float64
missing value       3827
Name: possession_regained_per_game_overall, dtype: object
Data type        float64
missing value       3827
Name: pressures_per_game_overall, dtype: object
Data type        float64
missing value       3827
Name: saves_per_game_overall, dtype: object
Data type        float64
missing value       3827
Name: interceptions_per_game_overall, dtype: object
Data type        float64
missing value       3827
Name: dribbles_successful_per_game_overall, dtype: object
Data type        float64
missing value       3827
Name: shots_faced_per_game_overall, dtype: object
Data type        float64
missing value       3827
Name: shots_per_goal_scored_overall, dtype: object
Data type        float64
missing value       3827
Name: shots_per_90_overall, dtype: object
Data type        float64
missing value       3827
Name: shots_off_target_per_game_overall, dtype: object
Data type        float64
missing value       3827
Name: dribbles_per_game_overall, dtype: object
Data type        float64
missing value       3827
Name: distance_travelled_per_game_overall, dtype: object
Data type        float64
missing value       3827
Name: shots_on_target_per_game_overall, dtype: object
Data type        float64
missing value       3827
Name: xg_per_game_overall, dtype: object
Data type        float64
missing value       3827
Name: chances_created_per_game_overall, dtype: object
Data type        float64
missing value       3827
Name: aerial_duels_won_per_game_overall, dtype: object
Data type        float64
missing value       3827
Name: aerial_duels_per_game_overall, dtype: object
Data type        float64
missing value       3827
Name: possession_regained_per_90_overall, dtype: object
Data type        float64
missing value       3827
Name: possession_regained_total_overall, dtype: object
Data type        float64
missing value       3827
Name: possession_regained_per90_percentile_overall, dtype: object
Data type        float64
missing value       4502
Name: additional_info, dtype: object
Data type        float64
missing value       3827
Name: shots_total_overall, dtype: object
Data type        float64
missing value       3827
Name: shots_per_game_overall, dtype: object
Data type        float64
missing value       3827
Name: shots_per90_percentile_overall, dtype: object
Data type        float64
missing value       3827
Name: shots_on_target_total_overall, dtype: object
Data type        float64
missing value       3827
Name: shots_on_target_per_90_overall, dtype: object
Data type        float64
missing value       3827
Name: shots_on_target_per90_percentile_overall, dtype: object
Data type        float64
missing value       3827
Name: shots_off_target_total_overall, dtype: object
Data type        float64
missing value       3827
Name: shots_off_target_per_90_overall, dtype: object
Data type        float64
missing value       3827
Name: shots_off_target_per90_percentile_overall, dtype: object
Data type        float64
missing value       3827
Name: games_subbed_out, dtype: object
Data type        float64
missing value       3827
Name: games_subbed_in, dtype: object
Data type        float64
missing value       3827
Name: games_started, dtype: object
Data type        float64
missing value       3827
Name: tackles_per90_percentile_overall, dtype: object
Data type        float64
missing value       3827
Name: tackles_successful_per_90_overall, dtype: object
Data type        float64
missing value       3827
Name: tackles_successful_per90_percentile_overall, dtype: object
Data type        float64
missing value       3827
Name: tackles_successful_total_overall, dtype: object
Data type        float64
missing value       3827
Name: interceptions_total_overall, dtype: object
Data type        float64
missing value       3827
Name: interceptions_per_90_overall, dtype: object
Data type        float64
missing value       3827
Name: interceptions_per90_percentile_overall, dtype: object
Data type        float64
missing value       3827
Name: crosses_total_overall, dtype: object
Data type        float64
missing value       3827
Name: cross_completion_rate_percentile_overall, dtype: object
Data type        float64
missing value       3827
Name: crosses_per_90_overall, dtype: object
Data type        float64
missing value       3827
Name: crosses_per90_percentile_overall, dtype: object
Data type        float64
missing value       3827
Name: through_passes_total_overall, dtype: object
Data type        float64
missing value       3827
Name: through_passes_per_90_overall, dtype: object
Data type        float64
missing value       3827
Name: through_passes_per90_percentile_overall, dtype: object
Data type        float64
missing value       3827
Name: long_passes_total_overall, dtype: object
Data type        float64
missing value       3827
Name: long_passes_per_90_overall, dtype: object
Data type        float64
missing value       3827
Name: long_passes_per90_percentile_overall, dtype: object
Data type        float64
missing value       3827
Name: short_passes_total_overall, dtype: object
Data type        float64
missing value       3827
Name: short_passes_per_90_overall, dtype: object
Data type        float64
missing value       3827
Name: short_passes_per90_percentile_overall, dtype: object
Data type        float64
missing value       3827
Name: key_passes_per_90_overall, dtype: object
Data type        float64
missing value       3827
Name: key_passes_per90_percentile_overall, dtype: object
Data type        float64
missing value       3827
Name: dribbles_total_overall, dtype: object
Data type        float64
missing value       3827
Name: dribbles_per_90_overall, dtype: object
Data type        float64
missing value       3827
Name: dribbles_per90_percentile_overall, dtype: object
Data type        float64
missing value       3827
Name: dribbles_successful_total_overall, dtype: object
Data type        float64
missing value       3827
Name: dribbles_successful_per_90_overall, dtype: object
Data type        float64
missing value       3827
Name: dribbles_successful_percentage_overall, dtype: object
Data type        float64
missing value       3827
Name: chances_created_total_overall, dtype: object
Data type        float64
missing value       3827
Name: chances_created_per_90_overall, dtype: object
Data type        float64
missing value       3827
Name: chances_created_per90_percentile_overall, dtype: object
Data type        float64
missing value       3827
Name: saves_total_overall, dtype: object
Data type        float64
missing value       3827
Name: save_percentage_percentile_overall, dtype: object
Data type        float64
missing value       3827
Name: saves_per_90_overall, dtype: object
Data type        float64
missing value       3827
Name: saves_per90_percentile_overall, dtype: object
Data type        float64
missing value       3827
Name: shots_faced_total_overall, dtype: object
Data type        float64
missing value       3827
Name: shots_per_goal_conceded_overall, dtype: object
Data type        float64
missing value       3827
Name: conceded_per90_percentile_overall, dtype: object
Data type        float64
missing value       3827
Name: shots_faced_per_90_overall, dtype: object
Data type        float64
missing value       3827
Name: shots_faced_per90_percentile_overall, dtype: object
Data type        float64
missing value       4502
Name: xg_faced_per_90_overall, dtype: object
Data type        float64
missing value       4502
Name: xg_faced_per90_percentile_overall, dtype: object
Data type        float64
missing value       4502
Name: xg_faced_per_game_overall, dtype: object
Data type        float64
missing value       4502
Name: xg_faced_total_overall, dtype: object
Data type        float64
missing value       3827
Name: save_percentage_overall, dtype: object
Data type        float64
missing value       3827
Name: pressures_total_overall, dtype: object
Data type        float64
missing value       3827
Name: pressures_per_90_overall, dtype: object
Data type        float64
missing value       3827
Name: pressures_per90_percentile_overall, dtype: object
Data type        float64
missing value       3827
Name: xg_total_overall, dtype: object
Data type        float64
missing value       3827
Name: market_value, dtype: object
Data type        float64
missing value       3827
Name: market_value_percentile, dtype: object
Data type        float64
missing value       3827
Name: pass_completion_rate_overall, dtype: object
Data type        float64
missing value       3827
Name: shot_accuraccy_percentage_overall, dtype: object
Data type        float64
missing value       3827
Name: shot_accuraccy_percentage_percentile_overall, dtype: object
Data type        float64
missing value       3827
Name: dribbled_past_per90_percentile_overall, dtype: object
Data type        float64
missing value       3827
Name: dribbled_past_per_game_overall, dtype: object
Data type        float64
missing value       3827
Name: dribbled_past_per_90_overall, dtype: object
Data type        float64
missing value       3827
Name: dribbled_past_total_overall, dtype: object
Data type        float64
missing value       3827
Name: dribbles_successful_per90_percentile_overall, dtype: object
Data type        float64
missing value       3827
Name: dribbles_successful_percentage_percentile_overall, dtype: object
Data type        float64
missing value       3827
Name: pen_scored_total_overall, dtype: object
Data type        float64
missing value       3827
Name: pen_missed_total_overall, dtype: object
Data type        float64
missing value       3827
Name: inside_box_saves_total_overall, dtype: object
Data type        float64
missing value       3827
Name: blocks_per_game_overall, dtype: object
Data type        float64
missing value       3827
Name: blocks_per_90_overall, dtype: object
Data type        float64
missing value       3827
Name: blocks_total_overall, dtype: object
Data type        float64
missing value       3827
Name: blocks_per90_percentile_overall, dtype: object
Data type        float64
missing value       3827
Name: ratings_total_overall, dtype: object
Data type        float64
missing value       3827
Name: clearances_per_game_overall, dtype: object
Data type        float64
missing value       3827
Name: clearances_per_90_overall, dtype: object
Data type        float64
missing value       3827
Name: clearances_total_overall, dtype: object
Data type        float64
missing value       3827
Name: pen_committed_total_overall, dtype: object
Data type        float64
missing value       3827
Name: pen_save_percentage_overall, dtype: object
Data type        float64
missing value       3827
Name: pen_committed_per_90_overall, dtype: object
Data type        float64
missing value       3827
Name: pen_committed_per90_percentile_overall, dtype: object
Data type        float64
missing value       3827
Name: pen_committed_per_game_overall, dtype: object
Data type        float64
missing value       3827
Name: pens_saved_total_overall, dtype: object
Data type        float64
missing value       3827
Name: pens_taken_total_overall, dtype: object
Data type        float64
missing value       3827
Name: hit_woodwork_total_overall, dtype: object
Data type        float64
missing value       3827
Name: hit_woodwork_per_game_overall, dtype: object
Data type        float64
missing value       3827
Name: hit_woodwork_per_90_overall, dtype: object
Data type        float64
missing value       3827
Name: punches_total_overall, dtype: object
Data type        float64
missing value       3827
Name: punches_per_game_overall, dtype: object
Data type        float64
missing value       3827
Name: punches_per_90_overall, dtype: object
Data type        float64
missing value       3827
Name: offsides_per_90_overall, dtype: object
Data type        float64
missing value       3827
Name: offsides_per_game_overall, dtype: object
Data type        float64
missing value       3827
Name: offsides_total_overall, dtype: object
Data type        float64
missing value       3827
Name: penalties_won_total_overall, dtype: object
Data type        float64
missing value       3827
Name: shot_conversion_rate_overall, dtype: object
Data type        float64
missing value       3827
Name: shot_conversion_rate_percentile_overall, dtype: object
Data type        float64
missing value       3827
Name: minutes_played_percentile_overall, dtype: object
Data type        float64
missing value       3827
Name: matches_played_percentile_overall, dtype: object
Data type        float64
missing value       3827
Name: min_per_goal_percentile_overall, dtype: object
Data type        float64
missing value       3827
Name: min_per_conceded_percentile_overall, dtype: object
Data type        float64
missing value       3827
Name: xa_total_overall, dtype: object
Data type        float64
missing value       3827
Name: xa_per90_percentile_overall, dtype: object
Data type        float64
missing value       3827
Name: xa_per_game_overall, dtype: object
Data type        float64
missing value       3827
Name: xa_per_90_overall, dtype: object
Data type        float64
missing value       3827
Name: npxg_total_overall, dtype: object
Data type        float64
missing value       3827
Name: npxg_per90_percentile_overall, dtype: object
Data type        float64
missing value       3827
Name: npxg_per_game_overall, dtype: object
Data type        float64
missing value       3827
Name: npxg_per_90_overall, dtype: object
Data type        float64
missing value       3827
Name: fouls_drawn_per90_percentile_overall, dtype: object
Data type        float64
missing value       3827

In [97]:
players["rank_in_league_top_midfielders"]

0     -1
1     -1
2     -1
3     -1
4     -1
      ..
817   -1
818   -1
819   -1
820   -1
821   -1
Name: rank_in_league_top_midfielders, Length: 4502, dtype: int64

In [98]:
players=players[["age","birthday_GMT","season","Current Club"]]
players=players.reset_index()

In [99]:
players=players.drop(columns=["index"])
players

      age  birthday_GMT  season  Current Club
0      35          1987    2006       England
1      41          1980    2006   Ivory Coast
2      41          1981    2006   Ivory Coast
3      49          1973    2006  Saudi Arabia
4      42          1980    2006          Togo
...   ...           ...     ...           ...
4497   31          1994    2022       Denmark
4498   39          1986    2022         Japan
4499   26          2000    2022       Morocco
4500   22          2003    2022       Belgium
4501   34          1991    2022        Poland

[4502 rows x 4 columns]

In [100]:
players["age"]=players.apply(lambda row:(row["season"]-row["birthday_GMT"]),axis=1)
players

      age  birthday_GMT  season  Current Club
0      19          1987    2006       England
1      26          1980    2006   Ivory Coast
2      25          1981    2006   Ivory Coast
3      33          1973    2006  Saudi Arabia
4      26          1980    2006          Togo
...   ...           ...     ...           ...
4497   28          1994    2022       Denmark
4498   36          1986    2022         Japan
4499   22          2000    2022       Morocco
4500   19          2003    2022       Belgium
4501   31          1991    2022        Poland

[4502 rows x 4 columns]

## get the essentiel info from matches data

In [101]:
matches

,timestamp,date_GMT,status,attendance,home_team_name,away_team_name,referee,Game Week,Pre-Match PPG (Home),Pre-Match PPG (Away),...,odds_ft_home_team_win,odds_ft_draw,odds_ft_away_team_win,odds_ft_over15,odds_ft_over25,odds_ft_over35,odds_ft_over45,odds_btts_yes,odds_btts_no,stadium_name
0,1149868800,Jun 09 2006 - 4:00pm,complete,66000.0,Germany,Costa Rica,NaN,1.0,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,Allianz Arena
1,1149879600,Jun 09 2006 - 7:00pm,complete,52000.0,Poland,Ecuador,NaN,1.0,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,VELTINS-Arena
2,1149944400,Jun 10 2006 - 1:00pm,complete,48000.0,England,Paraguay,NaN,1.0,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,Commerzbank-Arena
3,1149955200,Jun 10 2006 - 4:00pm,complete,62959.0,Trinidad and Tobago,Sweden,NaN,1.0,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,Signal-Iduna-Park
4,1149966000,Jun 10 2006 - 7:00pm,complete,49480.0,Argentina,Ivory Coast,NaN,1.0,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,Volksparkstadion
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59,1670698800,Dec 10 2022 - 7:00pm,complete,NaN,England,France,Wilton Pereira Sampaio,NaN,2.50,2.25,...,3.10,3.20,2.38,1.32,2.10,3.40,6.3,1.80,1.95,Al Bayt Stadium (Al Khor)
60,1670958000,Dec 13 2022 - 7:00pm,complete,88966.0,Argentina,Croatia,Daniele Orsato,NaN,2.00,1.40,...,1.80,3.40,5.00,1.52,2.48,4.50,9.0,2.25,1.57,Lusail Iconic Stadium (Lusail)
61,1671044400,Dec 14 2022 - 7:00pm,complete,NaN,France,Morocco,César Arturo Ramos Palazuelos,NaN,2.40,2.20,...,1.57,4.00,6.75,1.40,2.25,1.79,9.5,2.25,1.57,Al Bayt Stadium (Al Khor)
62,1671289200,Dec 17 2022 - 3:00pm,complete,NaN,Croatia,Morocco,Abdulrahman Ibrahim Al Jassim,NaN,1.17,1.83,...,2.43,3.40,3.10,1.26,2.07,2.98,5.7,1.67,2.10,Khalifa International Stadium (Al Rayyan (Ar-R...
63,1671375600,Dec 18 2022 - 3:00pm,complete,88966.0,Argentina,France,Szymon Marciniak,NaN,2.17,2.50,...,2.70,2.95,2.65,1.45,2.35,4.30,7.5,2.00,1.75,Lusail Iconic Stadium (Lusail)

In [102]:
matches["date_GMT"]=pd.to_datetime(matches["date_GMT"],errors="coerce")
matches["season"]=matches["date_GMT"].dt.year
matches["hour"]=matches["date_GMT"].dt.hour
matches

/tmp/ipykernel_19227/3995122214.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  matches["date_GMT"]=pd.to_datetime(matches["date_GMT"],errors="coerce")

,timestamp,date_GMT,status,attendance,home_team_name,away_team_name,referee,Game Week,Pre-Match PPG (Home),Pre-Match PPG (Away),...,odds_ft_away_team_win,odds_ft_over15,odds_ft_over25,odds_ft_over35,odds_ft_over45,odds_btts_yes,odds_btts_no,stadium_name,season,hour
0,1149868800,2006-06-09 16:00:00,complete,66000.0,Germany,Costa Rica,NaN,1.0,0.00,0.00,...,0.00,0.00,0.00,0.00,0.0,0.00,0.00,Allianz Arena,2006,16
1,1149879600,2006-06-09 19:00:00,complete,52000.0,Poland,Ecuador,NaN,1.0,0.00,0.00,...,0.00,0.00,0.00,0.00,0.0,0.00,0.00,VELTINS-Arena,2006,19
2,1149944400,2006-06-10 13:00:00,complete,48000.0,England,Paraguay,NaN,1.0,0.00,0.00,...,0.00,0.00,0.00,0.00,0.0,0.00,0.00,Commerzbank-Arena,2006,13
3,1149955200,2006-06-10 16:00:00,complete,62959.0,Trinidad and Tobago,Sweden,NaN,1.0,0.00,0.00,...,0.00,0.00,0.00,0.00,0.0,0.00,0.00,Signal-Iduna-Park,2006,16
4,1149966000,2006-06-10 19:00:00,complete,49480.0,Argentina,Ivory Coast,NaN,1.0,0.00,0.00,...,0.00,0.00,0.00,0.00,0.0,0.00,0.00,Volksparkstadion,2006,19
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59,1670698800,2022-12-10 19:00:00,complete,NaN,England,France,Wilton Pereira Sampaio,NaN,2.50,2.25,...,2.38,1.32,2.10,3.40,6.3,1.80,1.95,Al Bayt Stadium (Al Khor),2022,19
60,1670958000,2022-12-13 19:00:00,complete,88966.0,Argentina,Croatia,Daniele Orsato,NaN,2.00,1.40,...,5.00,1.52,2.48,4.50,9.0,2.25,1.57,Lusail Iconic Stadium (Lusail),2022,19
61,1671044400,2022-12-14 19:00:00,complete,NaN,France,Morocco,César Arturo Ramos Palazuelos,NaN,2.40,2.20,...,6.75,1.40,2.25,1.79,9.5,2.25,1.57,Al Bayt Stadium (Al Khor),2022,19
62,1671289200,2022-12-17 15:00:00,complete,NaN,Croatia,Morocco,Abdulrahman Ibrahim Al Jassim,NaN,1.17,1.83,...,3.10,1.26,2.07,2.98,5.7,1.67,2.10,Khalifa International Stadium (Al Rayyan (Ar-R...,2022,15
63,1671375600,2022-12-18 15:00:00,complete,88966.0,Argentina,France,Szymon Marciniak,NaN,2.17,2.50,...,2.65,1.45,2.35,4.30,7.5,2.00,1.75,Lusail Iconic Stadium (Lusail),2022,15