In [312]:
import numpy as np
import pandas as pd
import os 
import re

## extract the data

In [313]:
pattern1=r"matches"
matches=pd.DataFrame()
players=pd.DataFrame()
data="../data"
for dirc in os.listdir(data):
    path=os.path.join(data,dirc)
    if os.path.isdir(path):
        print(dirc)
        for file in os.listdir(path):
            if file=="players.csv" or file=="player_valuations.csv" :
                continue
            match=re.search(pattern1,file)
            if match:
                target_file=os.path.join(path,file)
                matches2=pd.read_csv(target_file)
                if file=="players":
                    print(file)
                if matches.empty:
                    matches=matches2
                else :
                    matches=pd.concat([matches,matches2])
            else :
                target_file=os.path.join(path,file)
                players2=pd.read_csv(target_file)
                if players.empty:
                    players=players2
                else :
                    players=pd.concat([players,players2])   
                 
matches

2006
additional
2018
2010
2002
2014
2022

,timestamp,date_GMT,status,attendance,home_team_name,away_team_name,referee,Game Week,Pre-Match PPG (Home),Pre-Match PPG (Away),...,odds_ft_home_team_win,odds_ft_draw,odds_ft_away_team_win,odds_ft_over15,odds_ft_over25,odds_ft_over35,odds_ft_over45,odds_btts_yes,odds_btts_no,stadium_name
0,1149868800,Jun 09 2006 - 4:00pm,complete,66000.0,Germany,Costa Rica,NaN,1.0,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,Allianz Arena
1,1149879600,Jun 09 2006 - 7:00pm,complete,52000.0,Poland,Ecuador,NaN,1.0,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,VELTINS-Arena
2,1149944400,Jun 10 2006 - 1:00pm,complete,48000.0,England,Paraguay,NaN,1.0,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,Commerzbank-Arena
3,1149955200,Jun 10 2006 - 4:00pm,complete,62959.0,Trinidad and Tobago,Sweden,NaN,1.0,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,Signal-Iduna-Park
4,1149966000,Jun 10 2006 - 7:00pm,complete,49480.0,Argentina,Ivory Coast,NaN,1.0,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,Volksparkstadion
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59,1670698800,Dec 10 2022 - 7:00pm,complete,NaN,England,France,Wilton Pereira Sampaio,NaN,2.50,2.25,...,3.10,3.20,2.38,1.32,2.10,3.40,6.3,1.80,1.95,Al Bayt Stadium (Al Khor)
60,1670958000,Dec 13 2022 - 7:00pm,complete,88966.0,Argentina,Croatia,Daniele Orsato,NaN,2.00,1.40,...,1.80,3.40,5.00,1.52,2.48,4.50,9.0,2.25,1.57,Lusail Iconic Stadium (Lusail)
61,1671044400,Dec 14 2022 - 7:00pm,complete,NaN,France,Morocco,César Arturo Ramos Palazuelos,NaN,2.40,2.20,...,1.57,4.00,6.75,1.40,2.25,1.79,9.5,2.25,1.57,Al Bayt Stadium (Al Khor)
62,1671289200,Dec 17 2022 - 3:00pm,complete,NaN,Croatia,Morocco,Abdulrahman Ibrahim Al Jassim,NaN,1.17,1.83,...,2.43,3.40,3.10,1.26,2.07,2.98,5.7,1.67,2.10,Khalifa International Stadium (Al Rayyan (Ar-R...
63,1671375600,Dec 18 2022 - 3:00pm,complete,88966.0,Argentina,France,Szymon Marciniak,NaN,2.17,2.50,...,2.70,2.95,2.65,1.45,2.35,4.30,7.5,2.00,1.75,Lusail Iconic Stadium (Lusail)

In [314]:
players

,full_name,age,birthday,birthday_GMT,league,season,position,Current Club,minutes_played_overall,minutes_played_home,...,annual_salary_eur_percentile,clean_sheets_percentage_percentile_overall,min_per_card_percentile_overall,cards_per90_percentile_overall,booked_over05_overall,booked_over05_percentage_overall,booked_over05_percentage_percentile_overall,shirt_number,annual_salary_gbp,annual_salary_usd
0,Aaron Lennon,35,5.455548e+08,1987/04/16,FIFA World Cup 2006 Germany,2006,Midfielder,England,102,102,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Abdoulaye Mu00e9u00eftu00e9,41,3.396636e+08,1980/10/06,FIFA World Cup 2006 Germany,2006,Defender,Ivory Coast,180,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Abdul Kader Keu00efta,41,3.659292e+08,1981/08/06,FIFA World Cup 2006 Germany,2006,Midfielder,Ivory Coast,150,73,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Abdulaziz Mohammed Al Khathran,49,1.129500e+08,1973/07/31,FIFA World Cup 2006 Germany,2006,Midfielder,Saudi Arabia,125,125,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Adékambi Olufadé,42,3.160800e+08,1980/01/07,FIFA World Cup 2006 Germany,2006,Forward,Togo,31,31,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
817,Yussuf Poulsen,31,7.716384e+08,1994/06/15,FIFA World Cup 2022 Qatar,2022,Forward,Denmark,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
818,Yuto Nagatomo,39,5.268672e+08,1986/09/12,FIFA World Cup 2022 Qatar,2022,Defender,Japan,213,156,...,46.0,7.0,21.0,21.0,0.0,0.0,21.0,5.0,0.0,0.0
819,Zakaria Aboukhlal,26,9.508320e+08,2000/02/18,FIFA World Cup 2022 Qatar,2022,Forward,Morocco,73,8,...,46.0,92.0,21.0,21.0,0.0,0.0,21.0,14.0,0.0,0.0
820,Zeno Debast,22,1.066954e+09,2003/10/24,FIFA World Cup 2022 Qatar,2022,Midfielder,Belgium,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
821,Łukasz Skorupski,34,6.734016e+08,1991/05/05,FIFA World Cup 2022 Qatar,2022,Goalkeeper,Poland,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## get essenteil info from players data

In [315]:
players["birthday_GMT"]=pd.to_datetime(players["birthday_GMT"],errors="coerce")
players["birthday_GMT"]=players["birthday_GMT"].dt.year
players

,full_name,age,birthday,birthday_GMT,league,season,position,Current Club,minutes_played_overall,minutes_played_home,...,annual_salary_eur_percentile,clean_sheets_percentage_percentile_overall,min_per_card_percentile_overall,cards_per90_percentile_overall,booked_over05_overall,booked_over05_percentage_overall,booked_over05_percentage_percentile_overall,shirt_number,annual_salary_gbp,annual_salary_usd
0,Aaron Lennon,35,5.455548e+08,1987.0,FIFA World Cup 2006 Germany,2006,Midfielder,England,102,102,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Abdoulaye Mu00e9u00eftu00e9,41,3.396636e+08,1980.0,FIFA World Cup 2006 Germany,2006,Defender,Ivory Coast,180,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Abdul Kader Keu00efta,41,3.659292e+08,1981.0,FIFA World Cup 2006 Germany,2006,Midfielder,Ivory Coast,150,73,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Abdulaziz Mohammed Al Khathran,49,1.129500e+08,1973.0,FIFA World Cup 2006 Germany,2006,Midfielder,Saudi Arabia,125,125,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Adékambi Olufadé,42,3.160800e+08,1980.0,FIFA World Cup 2006 Germany,2006,Forward,Togo,31,31,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
817,Yussuf Poulsen,31,7.716384e+08,1994.0,FIFA World Cup 2022 Qatar,2022,Forward,Denmark,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
818,Yuto Nagatomo,39,5.268672e+08,1986.0,FIFA World Cup 2022 Qatar,2022,Defender,Japan,213,156,...,46.0,7.0,21.0,21.0,0.0,0.0,21.0,5.0,0.0,0.0
819,Zakaria Aboukhlal,26,9.508320e+08,2000.0,FIFA World Cup 2022 Qatar,2022,Forward,Morocco,73,8,...,46.0,92.0,21.0,21.0,0.0,0.0,21.0,14.0,0.0,0.0
820,Zeno Debast,22,1.066954e+09,2003.0,FIFA World Cup 2022 Qatar,2022,Midfielder,Belgium,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
821,Łukasz Skorupski,34,6.734016e+08,1991.0,FIFA World Cup 2022 Qatar,2022,Goalkeeper,Poland,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [316]:
players

,full_name,age,birthday,birthday_GMT,league,season,position,Current Club,minutes_played_overall,minutes_played_home,...,annual_salary_eur_percentile,clean_sheets_percentage_percentile_overall,min_per_card_percentile_overall,cards_per90_percentile_overall,booked_over05_overall,booked_over05_percentage_overall,booked_over05_percentage_percentile_overall,shirt_number,annual_salary_gbp,annual_salary_usd
0,Aaron Lennon,35,5.455548e+08,1987.0,FIFA World Cup 2006 Germany,2006,Midfielder,England,102,102,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Abdoulaye Mu00e9u00eftu00e9,41,3.396636e+08,1980.0,FIFA World Cup 2006 Germany,2006,Defender,Ivory Coast,180,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Abdul Kader Keu00efta,41,3.659292e+08,1981.0,FIFA World Cup 2006 Germany,2006,Midfielder,Ivory Coast,150,73,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Abdulaziz Mohammed Al Khathran,49,1.129500e+08,1973.0,FIFA World Cup 2006 Germany,2006,Midfielder,Saudi Arabia,125,125,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Adékambi Olufadé,42,3.160800e+08,1980.0,FIFA World Cup 2006 Germany,2006,Forward,Togo,31,31,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
817,Yussuf Poulsen,31,7.716384e+08,1994.0,FIFA World Cup 2022 Qatar,2022,Forward,Denmark,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
818,Yuto Nagatomo,39,5.268672e+08,1986.0,FIFA World Cup 2022 Qatar,2022,Defender,Japan,213,156,...,46.0,7.0,21.0,21.0,0.0,0.0,21.0,5.0,0.0,0.0
819,Zakaria Aboukhlal,26,9.508320e+08,2000.0,FIFA World Cup 2022 Qatar,2022,Forward,Morocco,73,8,...,46.0,92.0,21.0,21.0,0.0,0.0,21.0,14.0,0.0,0.0
820,Zeno Debast,22,1.066954e+09,2003.0,FIFA World Cup 2022 Qatar,2022,Midfielder,Belgium,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
821,Łukasz Skorupski,34,6.734016e+08,1991.0,FIFA World Cup 2022 Qatar,2022,Goalkeeper,Poland,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [317]:
players.info()

<class 'pandas.core.frame.DataFrame'>
Index: 89402 entries, 0 to 821
Columns: 271 entries, full_name to annual_salary_usd
dtypes: float64(232), int64(32), object(7)
memory usage: 185.5+ MB

In [318]:
players_summary=pd.DataFrame({
    "Data type":players.dtypes,
    "missing value":players.isna().sum()
    }
)
players_summary

                                            Data type  missing value
full_name                                      object             25
age                                             int64              0
birthday                                      float64            137
birthday_GMT                                  float64            137
league                                         object              0
...                                               ...            ...
booked_over05_percentage_overall              float64          65124
booked_over05_percentage_percentile_overall   float64          65123
shirt_number                                   object          65252
annual_salary_gbp                             float64          65140
annual_salary_usd                             float64          65140

[271 rows x 2 columns]

In [319]:
n=len(players_summary)
for i in range(n):
    print(players_summary.iloc[i])

Data type        object
missing value        25
Name: full_name, dtype: object
Data type        int64
missing value        0
Name: age, dtype: object
Data type        float64
missing value        137
Name: birthday, dtype: object
Data type        float64
missing value        137
Name: birthday_GMT, dtype: object
Data type        object
missing value         0
Name: league, dtype: object
Data type        object
missing value         0
Name: season, dtype: object
Data type        object
missing value         0
Name: position, dtype: object
Data type        object
missing value         0
Name: Current Club, dtype: object
Data type        int64
missing value        0
Name: minutes_played_overall, dtype: object
Data type        int64
missing value        0
Name: minutes_played_home, dtype: object
Data type        int64
missing value        0
Name: minutes_played_away, dtype: object
Data type        object
missing value        82
Name: nationality, dtype: object
Data type        int64
missing value        0
Name: appearances_overall, dtype: object
Data type        int64
missing value        0
Name: appearances_home, dtype: object
Data type        int64
missing value        0
Name: appearances_away, dtype: object
Data type        int64
missing value        0
Name: goals_overall, dtype: object
Data type        int64
missing value        0
Name: goals_home, dtype: object
Data type        int64
missing value        0
Name: goals_away, dtype: object
Data type        int64
missing value        0
Name: assists_overall, dtype: object
Data type        int64
missing value        0
Name: assists_home, dtype: object
Data type        int64
missing value        0
Name: assists_away, dtype: object
Data type        int64
missing value        0
Name: penalty_goals, dtype: object
Data type        int64
missing value        0
Name: penalty_misses, dtype: object
Data type        int64
missing value        0
Name: clean_sheets_overall, dtype: object
Data type        int64
missing value        0
Name: clean_sheets_home, dtype: object
Data type        int64
missing value        0
Name: clean_sheets_away, dtype: object
Data type        int64
missing value        0
Name: conceded_overall, dtype: object
Data type        int64
missing value        0
Name: conceded_home, dtype: object
Data type        int64
missing value        0
Name: conceded_away, dtype: object
Data type        int64
missing value        0
Name: yellow_cards_overall, dtype: object
Data type        int64
missing value        0
Name: red_cards_overall, dtype: object
Data type        float64
missing value          0
Name: goals_involved_per_90_overall, dtype: object
Data type        float64
missing value          0
Name: assists_per_90_overall, dtype: object
Data type        float64
missing value          0
Name: goals_per_90_overall, dtype: object
Data type        float64
missing value          0
Name: goals_per_90_home, dtype: object
Data type        float64
missing value          0
Name: goals_per_90_away, dtype: object
Data type        int64
missing value        0
Name: min_per_goal_overall, dtype: object
Data type        float64
missing value          0
Name: conceded_per_90_overall, dtype: object
Data type        int64
missing value        0
Name: min_per_conceded_overall, dtype: object
Data type        int64
missing value        0
Name: min_per_match, dtype: object
Data type        int64
missing value        0
Name: min_per_card_overall, dtype: object
Data type        int64
missing value        0
Name: min_per_assist_overall, dtype: object
Data type        float64
missing value          0
Name: cards_per_90_overall, dtype: object
Data type        int64
missing value        0
Name: rank_in_league_top_attackers, dtype: object
Data type        int64
missing value        0
Name: rank_in_league_top_midfielders, dtype: object
Data type        int64
missing value        0
Name: rank_in_league_top_defenders, dtype: object
Data type        int64
missing value        0
Name: rank_in_club_top_scorer, dtype: object
Data type        float64
missing value      65140
Name: annual_salary_eur, dtype: object
Data type        float64
missing value      65123
Name: average_rating_overall, dtype: object
Data type        float64
missing value      65123
Name: assists_per_game_overall, dtype: object
Data type        float64
missing value      65123
Name: assists_per90_percentile_overall, dtype: object
Data type        float64
missing value      65123
Name: passes_per_90_overall, dtype: object
Data type        float64
missing value      65123
Name: passes_per_game_overall, dtype: object
Data type        float64
missing value      65123
Name: passes_per90_percentile_overall, dtype: object
Data type        float64
missing value      65123
Name: passes_total_overall, dtype: object
Data type        float64
missing value      65123
Name: passes_completed_per_game_overall, dtype: object
Data type        float64
missing value      65123
Name: passes_completed_total_overall, dtype: object
Data type        float64
missing value      65123
Name: pass_completion_rate_percentile_overall, dtype: object
Data type        float64
missing value      65123
Name: passes_completed_per_90_overall, dtype: object
Data type        float64
missing value      65123
Name: passes_completed_per90_percentile_overall, dtype: object
Data type        float64
missing value      65123
Name: short_passes_per_game_overall, dtype: object
Data type        float64
missing value      65123
Name: long_passes_per_game_overall, dtype: object
Data type        float64
missing value      65123
Name: key_passes_per_game_overall, dtype: object
Data type        float64
missing value      65123
Name: key_passes_total_overall, dtype: object
Data type        float64
missing value      65123
Name: through_passes_per_game_overall, dtype: object
Data type        float64
missing value      65123
Name: crosses_per_game_overall, dtype: object
Data type        float64
missing value      65123
Name: tackles_per_90_overall, dtype: object
Data type        float64
missing value      65123
Name: tackles_per_game_overall, dtype: object
Data type        float64
missing value      65123
Name: tackles_total_overall, dtype: object
Data type        float64
missing value      65123
Name: tackles_successful_per_game_overall, dtype: object
Data type        float64
missing value      65123
Name: dispossesed_per_game_overall, dtype: object
Data type        float64
missing value      65123
Name: possession_regained_per_game_overall, dtype: object
Data type        float64
missing value      65123
Name: pressures_per_game_overall, dtype: object
Data type        float64
missing value      65123
Name: saves_per_game_overall, dtype: object
Data type        float64
missing value      65123
Name: interceptions_per_game_overall, dtype: object
Data type        float64
missing value      65123
Name: dribbles_successful_per_game_overall, dtype: object
Data type        float64
missing value      65123
Name: shots_faced_per_game_overall, dtype: object
Data type        float64
missing value      65123
Name: shots_per_goal_scored_overall, dtype: object
Data type        float64
missing value      65123
Name: shots_per_90_overall, dtype: object
Data type        float64
missing value      65123
Name: shots_off_target_per_game_overall, dtype: object
Data type        float64
missing value      65123
Name: dribbles_per_game_overall, dtype: object
Data type        float64
missing value      65123
Name: distance_travelled_per_game_overall, dtype: object
Data type        float64
missing value      65123
Name: shots_on_target_per_game_overall, dtype: object
Data type        float64
missing value      65123
Name: xg_per_game_overall, dtype: object
Data type        float64
missing value      65123
Name: chances_created_per_game_overall, dtype: object
Data type        float64
missing value      65123
Name: aerial_duels_won_per_game_overall, dtype: object
Data type        float64
missing value      65123
Name: aerial_duels_per_game_overall, dtype: object
Data type        float64
missing value      65123
Name: possession_regained_per_90_overall, dtype: object
Data type        float64
missing value      65140
Name: possession_regained_total_overall, dtype: object
Data type        float64
missing value      65123
Name: possession_regained_per90_percentile_overall, dtype: object
Data type        float64
missing value      89402
Name: additional_info, dtype: object
Data type        float64
missing value      65123
Name: shots_total_overall, dtype: object
Data type        float64
missing value      65123
Name: shots_per_game_overall, dtype: object
Data type        float64
missing value      65123
Name: shots_per90_percentile_overall, dtype: object
Data type        float64
missing value      65123
Name: shots_on_target_total_overall, dtype: object
Data type        float64
missing value      65123
Name: shots_on_target_per_90_overall, dtype: object
Data type        float64
missing value      65123
Name: shots_on_target_per90_percentile_overall, dtype: object
Data type        float64
missing value      65123
Name: shots_off_target_total_overall, dtype: object
Data type        float64
missing value      65123
Name: shots_off_target_per_90_overall, dtype: object
Data type        float64
missing value      65123
Name: shots_off_target_per90_percentile_overall, dtype: object
Data type        float64
missing value      65123
Name: games_subbed_out, dtype: object
Data type        float64
missing value      65123
Name: games_subbed_in, dtype: object
Data type        float64
missing value      65123
Name: games_started, dtype: object
Data type        float64
missing value      65123
Name: tackles_per90_percentile_overall, dtype: object
Data type        float64
missing value      65123
Name: tackles_successful_per_90_overall, dtype: object
Data type        float64
missing value      65123
Name: tackles_successful_per90_percentile_overall, dtype: object
Data type        float64
missing value      65123
Name: tackles_successful_total_overall, dtype: object
Data type        float64
missing value      65123
Name: interceptions_total_overall, dtype: object
Data type        float64
missing value      65123
Name: interceptions_per_90_overall, dtype: object
Data type        float64
missing value      65123
Name: interceptions_per90_percentile_overall, dtype: object
Data type        float64
missing value      65123
Name: crosses_total_overall, dtype: object
Data type        float64
missing value      65123
Name: cross_completion_rate_percentile_overall, dtype: object
Data type        float64
missing value      65123
Name: crosses_per_90_overall, dtype: object
Data type        float64
missing value      65123
Name: crosses_per90_percentile_overall, dtype: object
Data type        float64
missing value      65123
Name: through_passes_total_overall, dtype: object
Data type        float64
missing value      65123
Name: through_passes_per_90_overall, dtype: object
Data type        float64
missing value      65123
Name: through_passes_per90_percentile_overall, dtype: object
Data type        float64
missing value      65123
Name: long_passes_total_overall, dtype: object
Data type        float64
missing value      65123
Name: long_passes_per_90_overall, dtype: object
Data type        float64
missing value      65123
Name: long_passes_per90_percentile_overall, dtype: object
Data type        float64
missing value      65123
Name: short_passes_total_overall, dtype: object
Data type        float64
missing value      65123
Name: short_passes_per_90_overall, dtype: object
Data type        float64
missing value      65123
Name: short_passes_per90_percentile_overall, dtype: object
Data type        float64
missing value      65123
Name: key_passes_per_90_overall, dtype: object
Data type        float64
missing value      65123
Name: key_passes_per90_percentile_overall, dtype: object
Data type        float64
missing value      65123
Name: dribbles_total_overall, dtype: object
Data type        float64
missing value      65123
Name: dribbles_per_90_overall, dtype: object
Data type        float64
missing value      65123
Name: dribbles_per90_percentile_overall, dtype: object
Data type        float64
missing value      65123
Name: dribbles_successful_total_overall, dtype: object
Data type        float64
missing value      65123
Name: dribbles_successful_per_90_overall, dtype: object
Data type        float64
missing value      65123
Name: dribbles_successful_percentage_overall, dtype: object
Data type        float64
missing value      65123
Name: chances_created_total_overall, dtype: object
Data type        float64
missing value      65123
Name: chances_created_per_90_overall, dtype: object
Data type        float64
missing value      65123
Name: chances_created_per90_percentile_overall, dtype: object
Data type        float64
missing value      65123
Name: saves_total_overall, dtype: object
Data type        float64
missing value      65139
Name: save_percentage_percentile_overall, dtype: object
Data type        float64
missing value      65123
Name: saves_per_90_overall, dtype: object
Data type        float64
missing value      65123
Name: saves_per90_percentile_overall, dtype: object
Data type        float64
missing value      65123
Name: shots_faced_total_overall, dtype: object
Data type        float64
missing value      65123
Name: shots_per_goal_conceded_overall, dtype: object
Data type        float64
missing value      65123
Name: conceded_per90_percentile_overall, dtype: object
Data type        float64
missing value      65123
Name: shots_faced_per_90_overall, dtype: object
Data type        float64
missing value      65123
Name: shots_faced_per90_percentile_overall, dtype: object
Data type        float64
missing value      89402
Name: xg_faced_per_90_overall, dtype: object
Data type        float64
missing value      89402
Name: xg_faced_per90_percentile_overall, dtype: object
Data type        float64
missing value      89402
Name: xg_faced_per_game_overall, dtype: object
Data type        float64
missing value      89402
Name: xg_faced_total_overall, dtype: object
Data type        float64
missing value      65123
Name: save_percentage_overall, dtype: object
Data type        float64
missing value      65123
Name: pressures_total_overall, dtype: object
Data type        float64
missing value      65123
Name: pressures_per_90_overall, dtype: object
Data type        float64
missing value      65123
Name: pressures_per90_percentile_overall, dtype: object
Data type        float64
missing value      65123
Name: xg_total_overall, dtype: object
Data type        float64
missing value      65140
Name: market_value, dtype: object
Data type        float64
missing value      65140
Name: market_value_percentile, dtype: object
Data type        float64
missing value      65123
Name: pass_completion_rate_overall, dtype: object
Data type        float64
missing value      65123
Name: shot_accuraccy_percentage_overall, dtype: object
Data type        float64
missing value      65123
Name: shot_accuraccy_percentage_percentile_overall, dtype: object
Data type        float64
missing value      65123
Name: dribbled_past_per90_percentile_overall, dtype: object
Data type        float64
missing value      65123
Name: dribbled_past_per_game_overall, dtype: object
Data type        float64
missing value      65123
Name: dribbled_past_per_90_overall, dtype: object
Data type        float64
missing value      65123
Name: dribbled_past_total_overall, dtype: object
Data type        float64
missing value      65123
Name: dribbles_successful_per90_percentile_overall, dtype: object
Data type        float64
missing value      65123
Name: dribbles_successful_percentage_percentile_overall, dtype: object
Data type        float64
missing value      65123
Name: pen_scored_total_overall, dtype: object
Data type        float64
missing value      65123
Name: pen_missed_total_overall, dtype: object
Data type        float64
missing value      65123
Name: inside_box_saves_total_overall, dtype: object
Data type        float64
missing value      65123
Name: blocks_per_game_overall, dtype: object
Data type        float64
missing value      65123
Name: blocks_per_90_overall, dtype: object
Data type        float64
missing value      65123
Name: blocks_total_overall, dtype: object
Data type        float64
missing value      65123
Name: blocks_per90_percentile_overall, dtype: object
Data type        float64
missing value      65123
Name: ratings_total_overall, dtype: object
Data type        float64
missing value      65123
Name: clearances_per_game_overall, dtype: object
Data type        float64
missing value      65123
Name: clearances_per_90_overall, dtype: object
Data type        float64
missing value      65123
Name: clearances_total_overall, dtype: object
Data type        float64
missing value      65123
Name: pen_committed_total_overall, dtype: object
Data type        float64
missing value      65123
Name: pen_save_percentage_overall, dtype: object
Data type        float64
missing value      65123
Name: pen_committed_per_90_overall, dtype: object
Data type        float64
missing value      65123
Name: pen_committed_per90_percentile_overall, dtype: object
Data type        float64
missing value      65124
Name: pen_committed_per_game_overall, dtype: object
Data type        float64
missing value      65123
Name: pens_saved_total_overall, dtype: object
Data type        float64
missing value      65123
Name: pens_taken_total_overall, dtype: object
Data type        float64
missing value      65123
Name: hit_woodwork_total_overall, dtype: object
Data type        float64
missing value      65124
Name: hit_woodwork_per_game_overall, dtype: object
Data type        float64
missing value      65124
Name: hit_woodwork_per_90_overall, dtype: object
Data type        float64
missing value      65123
Name: punches_total_overall, dtype: object
Data type        float64
missing value      65124
Name: punches_per_game_overall, dtype: object
Data type        float64
missing value      65124
Name: punches_per_90_overall, dtype: object
Data type        float64
missing value      65123
Name: offsides_per_90_overall, dtype: object
Data type        float64
missing value      65123
Name: offsides_per_game_overall, dtype: object
Data type        float64
missing value      65123
Name: offsides_total_overall, dtype: object
Data type        float64
missing value      65123
Name: penalties_won_total_overall, dtype: object
Data type        float64
missing value      65123
Name: shot_conversion_rate_overall, dtype: object
Data type        float64
missing value      65123
Name: shot_conversion_rate_percentile_overall, dtype: object
Data type        float64
missing value      65123
Name: minutes_played_percentile_overall, dtype: object
Data type        float64
missing value      65123
Name: matches_played_percentile_overall, dtype: object
Data type        float64
missing value      65123
Name: min_per_goal_percentile_overall, dtype: object
Data type        float64
missing value      65123
Name: min_per_conceded_percentile_overall, dtype: object
Data type        float64
missing value      65123
Name: xa_total_overall, dtype: object
Data type        float64
missing value      65123
Name: xa_per90_percentile_overall, dtype: object
Data type        float64
missing value      65123
Name: xa_per_game_overall, dtype: object
Data type        float64
missing value      65123
Name: xa_per_90_overall, dtype: object
Data type        float64
missing value      65123
Name: npxg_total_overall, dtype: object
Data type        float64
missing value      65123
Name: npxg_per90_percentile_overall, dtype: object
Data type        float64
missing value      65123
Name: npxg_per_game_overall, dtype: object
Data type        float64
missing value      65123
Name: npxg_per_90_overall, dtype: object
Data type        float64
missing value      65123
Name: fouls_drawn_per90_percentile_overall, dtype: object
Data type        float64
missing value      65123

In [320]:
players["rank_in_league_top_midfielders"]

0     -1
1     -1
2     -1
3     -1
4     -1
      ..
817   -1
818   -1
819   -1
820   -1
821   -1
Name: rank_in_league_top_midfielders, Length: 89402, dtype: int64

In [321]:
players_res=players[["full_name","age","birthday_GMT","season","Current Club"]]

In [322]:
players=players[["age","birthday_GMT","season","Current Club"]]
players=players.reset_index()

In [323]:
players=players.drop(columns=["index"])
players

       age  birthday_GMT season  Current Club
0       35        1987.0   2006       England
1       41        1980.0   2006   Ivory Coast
2       41        1981.0   2006   Ivory Coast
3       49        1973.0   2006  Saudi Arabia
4       42        1980.0   2006          Togo
...    ...           ...    ...           ...
89397   31        1994.0   2022       Denmark
89398   39        1986.0   2022         Japan
89399   26        2000.0   2022       Morocco
89400   22        2003.0   2022       Belgium
89401   34        1991.0   2022        Poland

[89402 rows x 4 columns]

In [324]:
print(players.dtypes)

age               int64
birthday_GMT    float64
season           object
Current Club     object
dtype: object

In [325]:
players["season"]=pd.to_numeric(players["season"], errors="coerce")
players["age"]=players.apply(lambda row:(row["season"]-row["birthday_GMT"]),axis=1)
players

        age  birthday_GMT  season  Current Club
0      19.0        1987.0  2006.0       England
1      26.0        1980.0  2006.0   Ivory Coast
2      25.0        1981.0  2006.0   Ivory Coast
3      33.0        1973.0  2006.0  Saudi Arabia
4      26.0        1980.0  2006.0          Togo
...     ...           ...     ...           ...
89397  28.0        1994.0  2022.0       Denmark
89398  36.0        1986.0  2022.0         Japan
89399  22.0        2000.0  2022.0       Morocco
89400  19.0        2003.0  2022.0       Belgium
89401  31.0        1991.0  2022.0        Poland

[89402 rows x 4 columns]

In [326]:
players=players.groupby(["Current Club","season"])["age"].mean()
players=players.reset_index()
players

         Current Club  season        age
0         Afghanistan  2021.0  27.047619
1         Afghanistan  2022.0  28.000000
2         Afghanistan  2024.0  27.000000
3         Afghanistan  2025.0  27.142857
4         Afghanistan  2026.0  28.592593
...               ...     ...        ...
1875  Étoile du Congo  2021.0  26.333333
1876  Étoile du Congo  2022.0  25.157895
1877  Étoile du Congo  2023.0  25.782609
1878  Étoile du Congo  2025.0  26.424242
1879  Étoile du Congo  2026.0  26.942857

[1880 rows x 3 columns]

## get the essentiel info from matches data

In [327]:
matches

,timestamp,date_GMT,status,attendance,home_team_name,away_team_name,referee,Game Week,Pre-Match PPG (Home),Pre-Match PPG (Away),...,odds_ft_home_team_win,odds_ft_draw,odds_ft_away_team_win,odds_ft_over15,odds_ft_over25,odds_ft_over35,odds_ft_over45,odds_btts_yes,odds_btts_no,stadium_name
0,1149868800,Jun 09 2006 - 4:00pm,complete,66000.0,Germany,Costa Rica,NaN,1.0,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,Allianz Arena
1,1149879600,Jun 09 2006 - 7:00pm,complete,52000.0,Poland,Ecuador,NaN,1.0,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,VELTINS-Arena
2,1149944400,Jun 10 2006 - 1:00pm,complete,48000.0,England,Paraguay,NaN,1.0,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,Commerzbank-Arena
3,1149955200,Jun 10 2006 - 4:00pm,complete,62959.0,Trinidad and Tobago,Sweden,NaN,1.0,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,Signal-Iduna-Park
4,1149966000,Jun 10 2006 - 7:00pm,complete,49480.0,Argentina,Ivory Coast,NaN,1.0,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,Volksparkstadion
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59,1670698800,Dec 10 2022 - 7:00pm,complete,NaN,England,France,Wilton Pereira Sampaio,NaN,2.50,2.25,...,3.10,3.20,2.38,1.32,2.10,3.40,6.3,1.80,1.95,Al Bayt Stadium (Al Khor)
60,1670958000,Dec 13 2022 - 7:00pm,complete,88966.0,Argentina,Croatia,Daniele Orsato,NaN,2.00,1.40,...,1.80,3.40,5.00,1.52,2.48,4.50,9.0,2.25,1.57,Lusail Iconic Stadium (Lusail)
61,1671044400,Dec 14 2022 - 7:00pm,complete,NaN,France,Morocco,César Arturo Ramos Palazuelos,NaN,2.40,2.20,...,1.57,4.00,6.75,1.40,2.25,1.79,9.5,2.25,1.57,Al Bayt Stadium (Al Khor)
62,1671289200,Dec 17 2022 - 3:00pm,complete,NaN,Croatia,Morocco,Abdulrahman Ibrahim Al Jassim,NaN,1.17,1.83,...,2.43,3.40,3.10,1.26,2.07,2.98,5.7,1.67,2.10,Khalifa International Stadium (Al Rayyan (Ar-R...
63,1671375600,Dec 18 2022 - 3:00pm,complete,88966.0,Argentina,France,Szymon Marciniak,NaN,2.17,2.50,...,2.70,2.95,2.65,1.45,2.35,4.30,7.5,2.00,1.75,Lusail Iconic Stadium (Lusail)

In [328]:
matches["date_GMT"]=pd.to_datetime(matches["date_GMT"],errors="coerce")
matches["season"]=matches["date_GMT"].dt.year
matches["hour"]=matches["date_GMT"].dt.hour
matches

/tmp/ipykernel_81450/3995122214.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  matches["date_GMT"]=pd.to_datetime(matches["date_GMT"],errors="coerce")

,timestamp,date_GMT,status,attendance,home_team_name,away_team_name,referee,Game Week,Pre-Match PPG (Home),Pre-Match PPG (Away),...,odds_ft_away_team_win,odds_ft_over15,odds_ft_over25,odds_ft_over35,odds_ft_over45,odds_btts_yes,odds_btts_no,stadium_name,season,hour
0,1149868800,2006-06-09 16:00:00,complete,66000.0,Germany,Costa Rica,NaN,1.0,0.00,0.00,...,0.00,0.00,0.00,0.00,0.0,0.00,0.00,Allianz Arena,2006,16
1,1149879600,2006-06-09 19:00:00,complete,52000.0,Poland,Ecuador,NaN,1.0,0.00,0.00,...,0.00,0.00,0.00,0.00,0.0,0.00,0.00,VELTINS-Arena,2006,19
2,1149944400,2006-06-10 13:00:00,complete,48000.0,England,Paraguay,NaN,1.0,0.00,0.00,...,0.00,0.00,0.00,0.00,0.0,0.00,0.00,Commerzbank-Arena,2006,13
3,1149955200,2006-06-10 16:00:00,complete,62959.0,Trinidad and Tobago,Sweden,NaN,1.0,0.00,0.00,...,0.00,0.00,0.00,0.00,0.0,0.00,0.00,Signal-Iduna-Park,2006,16
4,1149966000,2006-06-10 19:00:00,complete,49480.0,Argentina,Ivory Coast,NaN,1.0,0.00,0.00,...,0.00,0.00,0.00,0.00,0.0,0.00,0.00,Volksparkstadion,2006,19
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59,1670698800,2022-12-10 19:00:00,complete,NaN,England,France,Wilton Pereira Sampaio,NaN,2.50,2.25,...,2.38,1.32,2.10,3.40,6.3,1.80,1.95,Al Bayt Stadium (Al Khor),2022,19
60,1670958000,2022-12-13 19:00:00,complete,88966.0,Argentina,Croatia,Daniele Orsato,NaN,2.00,1.40,...,5.00,1.52,2.48,4.50,9.0,2.25,1.57,Lusail Iconic Stadium (Lusail),2022,19
61,1671044400,2022-12-14 19:00:00,complete,NaN,France,Morocco,César Arturo Ramos Palazuelos,NaN,2.40,2.20,...,6.75,1.40,2.25,1.79,9.5,2.25,1.57,Al Bayt Stadium (Al Khor),2022,19
62,1671289200,2022-12-17 15:00:00,complete,NaN,Croatia,Morocco,Abdulrahman Ibrahim Al Jassim,NaN,1.17,1.83,...,3.10,1.26,2.07,2.98,5.7,1.67,2.10,Khalifa International Stadium (Al Rayyan (Ar-R...,2022,15
63,1671375600,2022-12-18 15:00:00,complete,88966.0,Argentina,France,Szymon Marciniak,NaN,2.17,2.50,...,2.65,1.45,2.35,4.30,7.5,2.00,1.75,Lusail Iconic Stadium (Lusail),2022,15

In [329]:
matches_summary=pd.DataFrame({
    "Data type":matches.dtypes,
    "missing value":matches.isna().sum()
    }
)
n=len(matches_summary)
for i in range(n):
    print(matches_summary.iloc[i])

Data type        int64
missing value        0
Name: timestamp, dtype: object
Data type        datetime64[ns]
missing value                 0
Name: date_GMT, dtype: object
Data type        object
missing value         0
Name: status, dtype: object
Data type        float64
missing value       6180
Name: attendance, dtype: object
Data type        object
missing value         0
Name: home_team_name, dtype: object
Data type        object
missing value         0
Name: away_team_name, dtype: object
Data type        object
missing value      6099
Name: referee, dtype: object
Data type        float64
missing value       4132
Name: Game Week, dtype: object
Data type        float64
missing value          0
Name: Pre-Match PPG (Home), dtype: object
Data type        float64
missing value          0
Name: Pre-Match PPG (Away), dtype: object
Data type        float64
missing value          0
Name: home_ppg, dtype: object
Data type        float64
missing value          0
Name: away_ppg, dtype: object
Data type        int64
missing value        0
Name: home_team_goal_count, dtype: object
Data type        int64
missing value        0
Name: away_team_goal_count, dtype: object
Data type        int64
missing value        0
Name: total_goal_count, dtype: object
Data type        int64
missing value        0
Name: total_goals_at_half_time, dtype: object
Data type        int64
missing value        0
Name: home_team_goal_count_half_time, dtype: object
Data type        int64
missing value        0
Name: away_team_goal_count_half_time, dtype: object
Data type        object
missing value      3284
Name: home_team_goal_timings, dtype: object
Data type        object
missing value      4176
Name: away_team_goal_timings, dtype: object
Data type        int64
missing value        0
Name: home_team_corner_count, dtype: object
Data type        int64
missing value        0
Name: away_team_corner_count, dtype: object
Data type        int64
missing value        0
Name: home_team_yellow_cards, dtype: object
Data type        int64
missing value        0
Name: home_team_red_cards, dtype: object
Data type        int64
missing value        0
Name: away_team_yellow_cards, dtype: object
Data type        int64
missing value        0
Name: away_team_red_cards, dtype: object
Data type        int64
missing value        0
Name: home_team_first_half_cards, dtype: object
Data type        int64
missing value        0
Name: home_team_second_half_cards, dtype: object
Data type        int64
missing value        0
Name: away_team_first_half_cards, dtype: object
Data type        int64
missing value        0
Name: away_team_second_half_cards, dtype: object
Data type        int64
missing value        0
Name: home_team_shots, dtype: object
Data type        int64
missing value        0
Name: away_team_shots, dtype: object
Data type        int64
missing value        0
Name: home_team_shots_on_target, dtype: object
Data type        int64
missing value        0
Name: away_team_shots_on_target, dtype: object
Data type        int64
missing value        0
Name: home_team_shots_off_target, dtype: object
Data type        int64
missing value        0
Name: away_team_shots_off_target, dtype: object
Data type        int64
missing value        0
Name: home_team_fouls, dtype: object
Data type        int64
missing value        0
Name: away_team_fouls, dtype: object
Data type        int64
missing value        0
Name: home_team_possession, dtype: object
Data type        int64
missing value        0
Name: away_team_possession, dtype: object
Data type        float64
missing value          0
Name: Home Team Pre-Match xG, dtype: object
Data type        float64
missing value          0
Name: Away Team Pre-Match xG, dtype: object
Data type        float64
missing value          0
Name: team_a_xg, dtype: object
Data type        float64
missing value          0
Name: team_b_xg, dtype: object
Data type        float64
missing value          0
Name: average_goals_per_match_pre_match, dtype: object
Data type        int64
missing value        0
Name: btts_percentage_pre_match, dtype: object
Data type        int64
missing value        0
Name: over_15_percentage_pre_match, dtype: object
Data type        int64
missing value        0
Name: over_25_percentage_pre_match, dtype: object
Data type        int64
missing value        0
Name: over_35_percentage_pre_match, dtype: object
Data type        int64
missing value        0
Name: over_45_percentage_pre_match, dtype: object
Data type        int64
missing value        0
Name: over_15_HT_FHG_percentage_pre_match, dtype: object
Data type        int64
missing value        0
Name: over_05_HT_FHG_percentage_pre_match, dtype: object
Data type        int64
missing value        0
Name: over_15_2HG_percentage_pre_match, dtype: object
Data type        int64
missing value        0
Name: over_05_2HG_percentage_pre_match, dtype: object
Data type        float64
missing value          0
Name: average_corners_per_match_pre_match, dtype: object
Data type        float64
missing value          0
Name: average_cards_per_match_pre_match, dtype: object
Data type        float64
missing value          0
Name: odds_ft_home_team_win, dtype: object
Data type        float64
missing value          0
Name: odds_ft_draw, dtype: object
Data type        float64
missing value          0
Name: odds_ft_away_team_win, dtype: object
Data type        float64
missing value          0
Name: odds_ft_over15, dtype: object
Data type        float64
missing value          0
Name: odds_ft_over25, dtype: object
Data type        float64
missing value          0
Name: odds_ft_over35, dtype: object
Data type        float64
missing value          0
Name: odds_ft_over45, dtype: object
Data type        float64
missing value          0
Name: odds_btts_yes, dtype: object
Data type        float64
missing value          0
Name: odds_btts_no, dtype: object
Data type        object
missing value      1825
Name: stadium_name, dtype: object
Data type        int32
missing value        0
Name: season, dtype: object
Data type        int32
missing value        0
Name: hour, dtype: object

In [330]:
matches=matches[["home_team_name","away_team_name","home_team_goal_count","away_team_goal_count","home_team_goal_count_half_time","away_team_goal_count_half_time","Home Team Pre-Match xG","Away Team Pre-Match xG","hour","season"]]
matches

,home_team_name,away_team_name,home_team_goal_count,away_team_goal_count,home_team_goal_count_half_time,away_team_goal_count_half_time,Home Team Pre-Match xG,Away Team Pre-Match xG,hour,season
0,Germany,Costa Rica,4,2,2,1,0.00,0.00,16,2006
1,Poland,Ecuador,0,2,0,1,0.00,0.00,19,2006
2,England,Paraguay,1,0,1,0,0.00,0.00,13,2006
3,Trinidad and Tobago,Sweden,0,0,0,0,0.00,0.00,16,2006
4,Argentina,Ivory Coast,2,1,2,0,0.00,0.00,19,2006
...,...,...,...,...,...,...,...,...,...,...
59,England,France,1,2,0,1,1.50,1.97,19,2022
60,Argentina,Croatia,3,0,2,0,1.62,1.28,19,2022
61,France,Morocco,2,0,1,0,1.81,0.88,19,2022
62,Croatia,Morocco,2,1,2,1,1.27,0.98,15,2022
63,Argentina,France,3,3,2,0,1.56,1.72,15,2022

In [331]:
players.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1880 entries, 0 to 1879
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Current Club  1880 non-null   object
 1   season        1880 non-null   float64
 2   age           1880 non-null   float64
dtypes: float64(2), object(1)
memory usage: 44.2+ KB

In [332]:
matches.info()

<class 'pandas.core.frame.DataFrame'>
Index: 8795 entries, 0 to 63
Data columns (total 10 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   home_team_name                  8795 non-null   object
 1   away_team_name                  8795 non-null   object
 2   home_team_goal_count            8795 non-null   int64
 3   away_team_goal_count            8795 non-null   int64
 4   home_team_goal_count_half_time  8795 non-null   int64
 5   away_team_goal_count_half_time  8795 non-null   int64
 6   Home Team Pre-Match xG          8795 non-null   float64
 7   Away Team Pre-Match xG          8795 non-null   float64
 8   hour                            8795 non-null   int32
 9   season                          8795 non-null   int32
dtypes: float64(2), int32(2), int64(4), object(2)
memory usage: 687.1+ KB

In [333]:
matches=matches.merge(
    players,
    left_on=["home_team_name","season"],
    right_on=["Current Club","season"],
    how="left"
)
matches.rename(columns={"age": "home_team_age"}, inplace=True)
matches.drop(columns=["Current Club"], inplace=True)
matches=matches.merge(
    players,
    left_on=["away_team_name","season"],
    right_on=["Current Club","season"],
    how="left"
)
matches.rename(columns={"age": "away_team_age"}, inplace=True)
matches.drop(columns=["Current Club"], inplace=True)
matches

,home_team_name,away_team_name,home_team_goal_count,away_team_goal_count,home_team_goal_count_half_time,away_team_goal_count_half_time,Home Team Pre-Match xG,Away Team Pre-Match xG,hour,season,home_team_age,away_team_age
0,Germany,Costa Rica,4,2,2,1,0.00,0.00,16,2006,26.956522,28.086957
1,Poland,Ecuador,0,2,0,1,0.00,0.00,19,2006,27.173913,27.000000
2,England,Paraguay,1,0,1,0,0.00,0.00,13,2006,25.869565,27.173913
3,Trinidad and Tobago,Sweden,0,0,0,0,0.00,0.00,16,2006,29.565217,28.173913
4,Argentina,Ivory Coast,2,1,2,0,0.00,0.00,19,2006,26.565217,25.956522
...,...,...,...,...,...,...,...,...,...,...,...,...
8790,England,France,1,2,0,1,1.50,1.97,19,2022,26.376471,27.452381
8791,Argentina,Croatia,3,0,2,0,1.62,1.28,19,2022,27.491525,27.531915
8792,France,Morocco,2,0,1,0,1.81,0.88,19,2022,27.452381,26.809524
8793,Croatia,Morocco,2,1,2,1,1.27,0.98,15,2022,27.531915,26.809524
8794,Argentina,France,3,3,2,0,1.56,1.72,15,2022,27.491525,27.452381

In [334]:
print(players.loc[(players["Current Club"]=="Germany") & (players["season"]==2006),"age"])

626    26.956522
Name: age, dtype: float64

In [335]:
matches.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8795 entries, 0 to 8794
Data columns (total 12 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   home_team_name                  8795 non-null   object
 1   away_team_name                  8795 non-null   object
 2   home_team_goal_count            8795 non-null   int64
 3   away_team_goal_count            8795 non-null   int64
 4   home_team_goal_count_half_time  8795 non-null   int64
 5   away_team_goal_count_half_time  8795 non-null   int64
 6   Home Team Pre-Match xG          8795 non-null   float64
 7   Away Team Pre-Match xG          8795 non-null   float64
 8   hour                            8795 non-null   int32
 9   season                          8795 non-null   int32
 10  home_team_age                   7452 non-null   float64
 11  away_team_age                   7392 non-null   float64
dtypes: float64(4), int32(2), int64(4), object(2)
memory usage: 755.9+ KB

In [336]:
matches=matches.dropna()
matches.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6794 entries, 0 to 8794
Data columns (total 12 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   home_team_name                  6794 non-null   object
 1   away_team_name                  6794 non-null   object
 2   home_team_goal_count            6794 non-null   int64
 3   away_team_goal_count            6794 non-null   int64
 4   home_team_goal_count_half_time  6794 non-null   int64
 5   away_team_goal_count_half_time  6794 non-null   int64
 6   Home Team Pre-Match xG          6794 non-null   float64
 7   Away Team Pre-Match xG          6794 non-null   float64
 8   hour                            6794 non-null   int32
 9   season                          6794 non-null   int32
 10  home_team_age                   6794 non-null   float64
 11  away_team_age                   6794 non-null   float64
dtypes: float64(4), int32(2), int64(4), object(2)
memory usage: 636.9+ KB

In [337]:
df=pd.read_csv("../data/additional/players.csv")
df_value=pd.read_csv("../data/additional/player_valuations.csv")

In [338]:
df

,player_id,first_name,last_name,name,last_season,current_club_id,player_code,country_of_birth,city_of_birth,country_of_citizenship,...,agent_name,image_url,international_caps,international_goals,current_national_team_id,url,current_club_domestic_competition_id,current_club_name,market_value_in_eur,highest_market_value_in_eur
0,10,Miroslav,Klose,Miroslav Klose,2015,398,miroslav-klose,Poland,Opole,Germany,...,ASBW Sport Marketing,https://img.a.transfermarkt.technology/portrai...,NaN,NaN,NaN,https://www.transfermarkt.co.uk/miroslav-klose...,IT1,Società Sportiva Lazio S.p.A.,1000000.0,30000000.0
1,26,Roman,Weidenfeller,Roman Weidenfeller,2017,16,roman-weidenfeller,Germany,Diez,Germany,...,Neubauer 13 GmbH,https://img.a.transfermarkt.technology/portrai...,NaN,NaN,NaN,https://www.transfermarkt.co.uk/roman-weidenfe...,L1,Borussia Dortmund,750000.0,8000000.0
2,65,Dimitar,Berbatov,Dimitar Berbatov,2015,1091,dimitar-berbatov,Bulgaria,Blagoevgrad,Bulgaria,...,CSKA-AS-23 Ltd.,https://img.a.transfermarkt.technology/portrai...,NaN,NaN,NaN,https://www.transfermarkt.co.uk/dimitar-berbat...,GR1,Panthessalonikios Athlitikos Omilos Konstantin...,1000000.0,34500000.0
3,77,NaN,Lúcio,Lúcio,2012,506,lucio,Brazil,Brasília,Brazil,...,NaN,https://img.a.transfermarkt.technology/portrai...,NaN,NaN,NaN,https://www.transfermarkt.co.uk/lucio/profil/s...,IT1,Juventus Football Club,200000.0,24500000.0
4,80,Tom,Starke,Tom Starke,2017,27,tom-starke,East Germany (GDR),Freital,Germany,...,IFM,https://img.a.transfermarkt.technology/portrai...,NaN,NaN,NaN,https://www.transfermarkt.co.uk/tom-starke/pro...,L1,FC Bayern München,100000.0,3000000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37574,1494766,Saikuba,Jarju,Saikuba Jarju,2025,152,saikuba-jarju,NaN,NaN,The Gambia,...,NaN,https://img.a.transfermarkt.technology/portrai...,NaN,NaN,NaN,https://www.transfermarkt.co.uk/saikuba-jarju/...,TR1,Samsunspor,NaN,NaN
37575,1497653,Bara,Sapoko Ndiaye,Bara Sapoko Ndiaye,2025,27,bara-sapoko-ndiaye,NaN,NaN,Senegal,...,4FC,https://img.a.transfermarkt.technology/portrai...,NaN,NaN,NaN,https://www.transfermarkt.co.uk/bara-sapoko-nd...,L1,FC Bayern München,300000.0,300000.0
37576,1500143,Moussa,Kone,Moussa Kone,2025,6646,moussa-kone,Cote d'Ivoire,Daloa,Cote d'Ivoire,...,Tamegnon Consulting,https://img.a.transfermarkt.technology/portrai...,NaN,NaN,NaN,https://www.transfermarkt.co.uk/moussa-kone/pr...,TR1,Fatih Karagümrük Sportif Faaliyetler San. Tic....,100000.0,100000.0
37577,1507561,Mouhamadou,Sall,Mouhamadou Sall,2025,3508,mouhamadou-sall,NaN,NaN,Senegal,...,NaN,https://img.a.transfermarkt.technology/portrai...,NaN,NaN,NaN,https://www.transfermarkt.co.uk/mouhamadou-sal...,BE1,Sportvereniging Zulte Waregem,100000.0,100000.0
37578,1510255,Miguel,Silva,Miguel Silva,2025,979,miguel-silva,Portugal,Guimarães,Portugal,...,NaN,https://img.a.transfermarkt.technology/portrai...,NaN,NaN,NaN,https://www.transfermarkt.co.uk/miguel-silva/p...,PO1,Moreirense Futebol Clube,100000.0,100000.0

In [339]:
df=df[["player_id","name"]]

In [340]:
df_value

,player_id,date,market_value_in_eur,current_club_name,current_club_id,player_club_domestic_competition_id
0,405973,2000-01-20,150000,Unknown,3057.0,BE1
1,342216,2001-07-20,100000,Unknown,1241.0,SC1
2,3132,2003-12-09,400000,Dynamo Kyiv,126.0,TR1
3,6893,2003-12-15,900000,Galatasaray,984.0,GB1
4,10,2004-10-04,7000000,SV Werder Bremen,398.0,IT1
...,...,...,...,...,...,...
526180,1291835,2026-03-23,100000,Rukh Lviv U19,83932.0,NaN
526181,1293298,2026-03-23,150000,Kryvbas Kryvyi Rig U19,93057.0,NaN
526182,1293692,2026-03-23,50000,FC Oleksandriya-2,120273.0,NaN
526183,1346771,2026-03-23,100000,Rukh Lviv U19,83932.0,NaN
526184,1447744,2026-03-23,100000,Rukh Lviv,48726.0,UKR1

In [341]:
df=df.merge(
    df_value[["market_value_in_eur","player_id"]],
    on="player_id",
    how="left"
)
df

        player_id                name  market_value_in_eur
0              10      Miroslav Klose            7000000.0
1              10      Miroslav Klose            9000000.0
2              10      Miroslav Klose           12000000.0
3              10      Miroslav Klose           15000000.0
4              10      Miroslav Klose           20000000.0
...           ...                 ...                  ...
530455    1494766       Saikuba Jarju                  NaN
530456    1497653  Bara Sapoko Ndiaye             300000.0
530457    1500143         Moussa Kone             100000.0
530458    1507561     Mouhamadou Sall             100000.0
530459    1510255        Miguel Silva             100000.0

[530460 rows x 3 columns]

In [342]:
df=df.drop_duplicates(subset="player_id")
df=df.reset_index()
df=df.drop(columns=["index"])
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 37579 entries, 0 to 37578
Data columns (total 3 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   player_id            37579 non-null  int64
 1   name                 37579 non-null  object
 2   market_value_in_eur  32561 non-null  float64
dtypes: float64(1), int64(1), object(1)
memory usage: 880.9+ KB

In [343]:
print(players_res[players_res["full_name"] == "Miroslav Klose"])

          full_name  age  birthday_GMT season Current Club
497  Miroslav Klose   44        1978.0   2006      Germany
485  Miroslav Klose   44        1978.0   2010      Germany
467  Miroslav Klose   44        1978.0   2002      Germany
510  Miroslav Klose   44        1978.0   2014      Germany

In [344]:
players_res["full_name"]=players_res["full_name"].str.lower().str.strip()
df["name"]=df["name"].str.lower().str.strip()

/tmp/ipykernel_81450/2234801557.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  players_res["full_name"]=players_res["full_name"].str.lower().str.strip()

In [345]:
players_res=players_res.merge(
    df[["name", "market_value_in_eur"]],
    left_on="full_name",
    right_on="name",
    how="left"
)
players_res

,full_name,age,birthday_GMT,season,Current Club,name,market_value_in_eur
0,aaron lennon,35,1987.0,2006,England,aaron lennon,300000.0
1,abdoulaye mu00e9u00eftu00e9,41,1980.0,2006,Ivory Coast,NaN,NaN
2,abdul kader keu00efta,41,1981.0,2006,Ivory Coast,NaN,NaN
3,abdulaziz mohammed al khathran,49,1973.0,2006,Saudi Arabia,NaN,NaN
4,adékambi olufadé,42,1980.0,2006,Togo,NaN,NaN
...,...,...,...,...,...,...,...
90455,yussuf poulsen,31,1994.0,2022,Denmark,yussuf poulsen,50000.0
90456,yuto nagatomo,39,1986.0,2022,Japan,yuto nagatomo,150000.0
90457,zakaria aboukhlal,26,2000.0,2022,Morocco,zakaria aboukhlal,100000.0
90458,zeno debast,22,2003.0,2022,Belgium,zeno debast,400000.0
90459,łukasz skorupski,34,1991.0,2022,Poland,NaN,NaN

In [346]:
players_res.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 90460 entries, 0 to 90459
Data columns (total 7 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   full_name            90435 non-null  object
 1   age                  90460 non-null  int64
 2   birthday_GMT         90323 non-null  float64
 3   season               90460 non-null  object
 4   Current Club         90460 non-null  object
 5   name                 38255 non-null  object
 6   market_value_in_eur  32554 non-null  float64
dtypes: float64(2), int64(1), object(4)
memory usage: 4.8+ MB

In [347]:
players_res=players_res.dropna(subset=["market_value_in_eur"])
players_res.info()

<class 'pandas.core.frame.DataFrame'>
Index: 32554 entries, 0 to 90458
Data columns (total 7 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   full_name            32554 non-null  object
 1   age                  32554 non-null  int64
 2   birthday_GMT         32546 non-null  float64
 3   season               32554 non-null  object
 4   Current Club         32554 non-null  object
 5   name                 32554 non-null  object
 6   market_value_in_eur  32554 non-null  float64
dtypes: float64(2), int64(1), object(4)
memory usage: 2.0+ MB

In [348]:
players_res=players_res.groupby(["season","Current Club"])["market_value_in_eur"].sum()
players_res=players_res.reset_index()
players_res

         season Current Club  market_value_in_eur
0          2002      Belgium           25000000.0
1          2002      Croatia            2350000.0
2          2002      Denmark            3500000.0
3          2002      England          165000000.0
4          2002       France           20150000.0
...         ...          ...                  ...
1739  2024/2025       Sweden            8240000.0
1740  2024/2025  Switzerland            3800000.0
1741  2024/2025       Turkey            3900000.0
1742  2024/2025      Ukraine            5425000.0
1743  2024/2025        Wales           14900000.0

[1744 rows x 3 columns]

In [349]:
players=players_res.merge(
    players_res[["market_value_in_eur","season","Current Club"]],
    on=["season","Current Club"],
    how="left"
    
)
players

         season Current Club  market_value_in_eur_x  market_value_in_eur_y
0          2002      Belgium             25000000.0             25000000.0
1          2002      Croatia              2350000.0              2350000.0
2          2002      Denmark              3500000.0              3500000.0
3          2002      England            165000000.0            165000000.0
4          2002       France             20150000.0             20150000.0
...         ...          ...                    ...                    ...
1739  2024/2025       Sweden              8240000.0              8240000.0
1740  2024/2025  Switzerland              3800000.0              3800000.0
1741  2024/2025       Turkey              3900000.0              3900000.0
1742  2024/2025      Ukraine              5425000.0              5425000.0
1743  2024/2025        Wales             14900000.0             14900000.0

[1744 rows x 4 columns]

In [350]:
players=players.drop(columns=["market_value_in_eur_y"])
players.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1744 entries, 0 to 1743
Data columns (total 3 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   season                 1744 non-null   object
 1   Current Club           1744 non-null   object
 2   market_value_in_eur_x  1744 non-null   float64
dtypes: float64(1), object(2)
memory usage: 41.0+ KB

In [351]:
matches=matches.merge(
    players[["market_value_in_eur_x","season","Current Club"]]
        .rename(columns={"market_value_in_eur_x": "away_value"}),
    left_on=["season","away_team_name"],
    right_on=["season","Current Club"],
    how="left"
)
matches=matches.drop(columns=["Current Club"])
matches=matches.merge(
    players[["market_value_in_eur_x","season","Current Club"]]
        .rename(columns={"market_value_in_eur_x": "home_value"}),
    left_on=["season","home_team_name"],
    right_on=["season","Current Club"],
    how="left"
)
matches=matches.drop(columns=["Current Club"])
matches

,home_team_name,away_team_name,home_team_goal_count,away_team_goal_count,home_team_goal_count_half_time,away_team_goal_count_half_time,Home Team Pre-Match xG,Away Team Pre-Match xG,hour,season,home_team_age,away_team_age,away_value,home_value
0,Germany,Costa Rica,4,2,2,1,0.00,0.00,16,2006,26.956522,28.086957,NaN,54650000.0
1,Poland,Ecuador,0,2,0,1,0.00,0.00,19,2006,27.173913,27.000000,2250000.0,2350000.0
2,England,Paraguay,1,0,1,0,0.00,0.00,13,2006,25.869565,27.173913,10330000.0,234100000.0
3,Trinidad and Tobago,Sweden,0,0,0,0,0.00,0.00,16,2006,29.565217,28.173913,42750000.0,50000.0
4,Argentina,Ivory Coast,2,1,2,0,0.00,0.00,19,2006,26.565217,25.956522,NaN,14050000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6789,England,France,1,2,0,1,1.50,1.97,19,2022,26.376471,27.452381,61725000.0,96150000.0
6790,Argentina,Croatia,3,0,2,0,1.62,1.28,19,2022,27.491525,27.531915,15600000.0,71725000.0
6791,France,Morocco,2,0,1,0,1.81,0.88,19,2022,27.452381,26.809524,14150000.0,61725000.0
6792,Croatia,Morocco,2,1,2,1,1.27,0.98,15,2022,27.531915,26.809524,14150000.0,15600000.0
6793,Argentina,France,3,3,2,0,1.56,1.72,15,2022,27.491525,27.452381,61725000.0,71725000.0

In [352]:
matches.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6794 entries, 0 to 6793
Data columns (total 14 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   home_team_name                  6794 non-null   object
 1   away_team_name                  6794 non-null   object
 2   home_team_goal_count            6794 non-null   int64
 3   away_team_goal_count            6794 non-null   int64
 4   home_team_goal_count_half_time  6794 non-null   int64
 5   away_team_goal_count_half_time  6794 non-null   int64
 6   Home Team Pre-Match xG          6794 non-null   float64
 7   Away Team Pre-Match xG          6794 non-null   float64
 8   hour                            6794 non-null   int32
 9   season                          6794 non-null   object
 10  home_team_age                   6794 non-null   float64
 11  away_team_age                   6794 non-null   float64
 12  away_value                      5647 non-null   float64
 13  home_value                      5716 non-null   float64
dtypes: float64(6), int32(1), int64(4), object(3)
memory usage: 716.7+ KB

In [353]:
matches=matches.dropna()
matches.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4965 entries, 1 to 6793
Data columns (total 14 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   home_team_name                  4965 non-null   object
 1   away_team_name                  4965 non-null   object
 2   home_team_goal_count            4965 non-null   int64
 3   away_team_goal_count            4965 non-null   int64
 4   home_team_goal_count_half_time  4965 non-null   int64
 5   away_team_goal_count_half_time  4965 non-null   int64
 6   Home Team Pre-Match xG          4965 non-null   float64
 7   Away Team Pre-Match xG          4965 non-null   float64
 8   hour                            4965 non-null   int32
 9   season                          4965 non-null   object
 10  home_team_age                   4965 non-null   float64
 11  away_team_age                   4965 non-null   float64
 12  away_value                      4965 non-null   float64
 13  home_value                      4965 non-null   float64
dtypes: float64(6), int32(1), int64(4), object(3)
memory usage: 562.4+ KB

In [354]:
print(len(matches[(matches["Away Team Pre-Match xG"]==0) | (matches["Home Team Pre-Match xG"]==0)]))
print(len(matches[(matches["Away Team Pre-Match xG"]==0) & (matches["Home Team Pre-Match xG"]==0)]))
print(len(matches[(matches["away_team_goal_count"]==0) | (matches["home_team_goal_count"]==0)]))
print(len(matches[(matches["away_team_goal_count"]==0) & (matches["home_team_goal_count"]==0)]))

2616
2117
2937
796

In [355]:
matches["away_value"]=matches["away_value"]/1e8
matches["home_value"]=matches["home_value"]/1e8
matches

/tmp/ipykernel_81450/4281075010.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  matches["away_value"]=matches["away_value"]/1e8
/tmp/ipykernel_81450/4281075010.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  matches["home_value"]=matches["home_value"]/1e8

,home_team_name,away_team_name,home_team_goal_count,away_team_goal_count,home_team_goal_count_half_time,away_team_goal_count_half_time,Home Team Pre-Match xG,Away Team Pre-Match xG,hour,season,home_team_age,away_team_age,away_value,home_value
1,Poland,Ecuador,0,2,0,1,0.00,0.00,19,2006,27.173913,27.000000,0.02250,0.02350
2,England,Paraguay,1,0,1,0,0.00,0.00,13,2006,25.869565,27.173913,0.10330,2.34100
3,Trinidad and Tobago,Sweden,0,0,0,0,0.00,0.00,16,2006,29.565217,28.173913,0.42750,0.00050
5,Serbia and Montenegro,Netherlands,0,1,0,1,0.00,0.00,13,2006,28.478261,27.130435,0.65050,0.06825
9,USMNT,Czech Republic,0,3,0,2,0.00,0.00,16,2006,28.608696,28.869565,0.06000,0.05750
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6789,England,France,1,2,0,1,1.50,1.97,19,2022,26.376471,27.452381,0.61725,0.96150
6790,Argentina,Croatia,3,0,2,0,1.62,1.28,19,2022,27.491525,27.531915,0.15600,0.71725
6791,France,Morocco,2,0,1,0,1.81,0.88,19,2022,27.452381,26.809524,0.14150,0.61725
6792,Croatia,Morocco,2,1,2,1,1.27,0.98,15,2022,27.531915,26.809524,0.14150,0.15600
6793,Argentina,France,3,3,2,0,1.56,1.72,15,2022,27.491525,27.452381,0.61725,0.71725

In [356]:
matches=matches.reset_index()
matches=matches.drop(columns=["index"])

In [357]:
matches=matches.drop(columns=["Away Team Pre-Match xG","Home Team Pre-Match xG","home_team_goal_count_half_time","away_team_goal_count_half_time"])
matches

,home_team_name,away_team_name,home_team_goal_count,away_team_goal_count,hour,season,home_team_age,away_team_age,away_value,home_value
0,Poland,Ecuador,0,2,19,2006,27.173913,27.000000,0.02250,0.02350
1,England,Paraguay,1,0,13,2006,25.869565,27.173913,0.10330,2.34100
2,Trinidad and Tobago,Sweden,0,0,16,2006,29.565217,28.173913,0.42750,0.00050
3,Serbia and Montenegro,Netherlands,0,1,13,2006,28.478261,27.130435,0.65050,0.06825
4,USMNT,Czech Republic,0,3,16,2006,28.608696,28.869565,0.06000,0.05750
...,...,...,...,...,...,...,...,...,...,...
4960,England,France,1,2,19,2022,26.376471,27.452381,0.61725,0.96150
4961,Argentina,Croatia,3,0,19,2022,27.491525,27.531915,0.15600,0.71725
4962,France,Morocco,2,0,19,2022,27.452381,26.809524,0.14150,0.61725
4963,Croatia,Morocco,2,1,15,2022,27.531915,26.809524,0.14150,0.15600
4964,Argentina,France,3,3,15,2022,27.491525,27.452381,0.61725,0.71725

In [358]:
rank=pd.read_csv("../data/fifa_ranking-2024-06-20.csv")
rank

,rank,country_full,country_abrv,total_points,previous_points,rank_change,confederation,rank_date
0,140.0,Brunei Darussalam,BRU,2.00,0.00,140,AFC,1992-12-31
1,33.0,Portugal,POR,38.00,0.00,33,UEFA,1992-12-31
2,32.0,Zambia,ZAM,38.00,0.00,32,CAF,1992-12-31
3,31.0,Greece,GRE,38.00,0.00,31,UEFA,1992-12-31
4,30.0,Algeria,ALG,39.00,0.00,30,CAF,1992-12-31
...,...,...,...,...,...,...,...,...
67467,137.0,Kuwait,KUW,1098.42,1085.46,-2,AFC,2024-06-20
67468,136.0,Lithuania,LTU,1100.66,1095.23,-1,UEFA,2024-06-20
67469,135.0,Malaysia,MAS,1107.58,1094.54,-3,AFC,2024-06-20
67470,133.0,Solomon Islands,SOL,1111.02,1111.02,1,OFC,2024-06-20
67471,1.0,Argentina,ARG,1860.14,1858.00,0,CONMEBOL,2024-06-20

In [359]:
rank["rank_date"]=pd.to_datetime(rank["rank_date"],errors="coerce")
rank["rank_date"]=rank["rank_date"].dt.year
rank["rank_date"]=pd.to_numeric(rank["rank_date"],errors="coerce")
rank=rank.rename(columns={"rank_date":"season"})
rank=rank[rank["season"]>=2001]
rank

,rank,country_full,country_abrv,total_points,previous_points,rank_change,confederation,season
14987,198.0,US Virgin Islands,VIR,33.00,33.00,0,CONCACAF,2001
14988,92.0,Armenia,ARM,441.00,441.00,2,UEFA,2001
14989,91.0,Gabon,GAB,442.00,442.00,2,CAF,2001
14990,90.0,New Zealand,NZL,443.00,441.00,-1,OFC,2001
14991,89.0,Liberia,LBR,448.00,428.00,-6,CAF,2001
...,...,...,...,...,...,...,...,...
67467,137.0,Kuwait,KUW,1098.42,1085.46,-2,AFC,2024
67468,136.0,Lithuania,LTU,1100.66,1095.23,-1,UEFA,2024
67469,135.0,Malaysia,MAS,1107.58,1094.54,-3,AFC,2024
67470,133.0,Solomon Islands,SOL,1111.02,1111.02,1,OFC,2024
67471,1.0,Argentina,ARG,1860.14,1858.00,0,CONMEBOL,2024

In [360]:
rank =rank.groupby(["season", "country_full"], as_index=False).agg({"total_points": "mean","rank": "mean"})
rank

      season    country_full  total_points        rank
0       2001         Albania    470.750000   84.083333
1       2001         Algeria    491.416667   77.166667
2       2001  American Samoa     13.166667  201.666667
3       2001         Andorra    257.250000  143.666667
4       2001          Angola    553.833333   54.333333
...      ...             ...           ...         ...
4993    2024         Vietnam   1175.713333  112.000000
4994    2024           Wales   1524.886667   29.000000
4995    2024           Yemen   1022.076667  154.000000
4996    2024          Zambia   1270.790000   87.666667
4997    2024        Zimbabwe   1136.920000  125.000000

[4998 rows x 4 columns]

In [361]:
rank=rank.reset_index()
rank=rank.drop(columns=["index"])
rank.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4998 entries, 0 to 4997
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   season        4998 non-null   int32
 1   country_full  4998 non-null   object
 2   total_points  4998 non-null   float64
 3   rank          4997 non-null   float64
dtypes: float64(2), int32(1), object(1)
memory usage: 136.8+ KB

In [362]:
matches=matches.merge(
    rank[["country_full","total_points","rank","season"]].rename(columns={"total_points":"away_points","rank":"away_rank"}),
    left_on=["season","away_team_name"],
    right_on=["season","country_full"],
    how="left"
)
matches=matches.drop(columns=["country_full"])
matches=matches.merge(
    rank[["country_full","total_points","rank","season"]].rename(columns={"total_points":"home_points","rank":"home_rank"}),
    left_on=["season","home_team_name"],
    right_on=["season","country_full"],
    how="left"
)
matches=matches.drop(columns=["country_full"])
matches

,home_team_name,away_team_name,home_team_goal_count,away_team_goal_count,hour,season,home_team_age,away_team_age,away_value,home_value,away_points,away_rank,home_points,home_rank
0,Poland,Ecuador,0,2,19,2006,27.173913,27.000000,0.02250,0.02350,727.636364,33.727273,755.454545,27.181818
1,England,Paraguay,1,0,13,2006,25.869565,27.173913,0.10330,2.34100,750.454545,29.090909,1108.090909,6.909091
2,Trinidad and Tobago,Sweden,0,0,16,2006,29.565217,28.173913,0.42750,0.00050,832.909091,16.454545,513.090909,62.363636
3,Serbia and Montenegro,Netherlands,0,1,13,2006,28.478261,27.130435,0.65050,0.06825,1073.181818,4.909091,630.833333,44.333333
4,USMNT,Czech Republic,0,3,16,2006,28.608696,28.869565,0.06000,0.05750,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4960,England,France,1,2,19,2022,26.376471,27.452381,0.61725,0.96150,1781.478333,3.500000,1749.135000,5.000000
4961,Argentina,Croatia,3,0,19,2022,27.491525,27.531915,0.15600,0.71725,1646.568333,13.333333,1780.946667,3.166667
4962,France,Morocco,2,0,19,2022,27.452381,26.809524,0.14150,0.61725,1575.400000,21.000000,1781.478333,3.500000
4963,Croatia,Morocco,2,1,15,2022,27.531915,26.809524,0.14150,0.15600,1575.400000,21.000000,1646.568333,13.333333
4964,Argentina,France,3,3,15,2022,27.491525,27.452381,0.61725,0.71725,1781.478333,3.500000,1780.946667,3.166667

In [363]:
matches.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4965 entries, 0 to 4964
Data columns (total 14 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   home_team_name        4965 non-null   object
 1   away_team_name        4965 non-null   object
 2   home_team_goal_count  4965 non-null   int64
 3   away_team_goal_count  4965 non-null   int64
 4   hour                  4965 non-null   int32
 5   season                4965 non-null   object
 6   home_team_age         4965 non-null   float64
 7   away_team_age         4965 non-null   float64
 8   away_value            4965 non-null   float64
 9   home_value            4965 non-null   float64
 10  away_points           3792 non-null   float64
 11  away_rank             3792 non-null   float64
 12  home_points           3786 non-null   float64
 13  home_rank             3786 non-null   float64
dtypes: float64(8), int32(1), int64(2), object(3)
memory usage: 523.8+ KB

In [364]:
matches=matches.dropna()
matches.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3410 entries, 0 to 4964
Data columns (total 14 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   home_team_name        3410 non-null   object
 1   away_team_name        3410 non-null   object
 2   home_team_goal_count  3410 non-null   int64
 3   away_team_goal_count  3410 non-null   int64
 4   hour                  3410 non-null   int32
 5   season                3410 non-null   object
 6   home_team_age         3410 non-null   float64
 7   away_team_age         3410 non-null   float64
 8   away_value            3410 non-null   float64
 9   home_value            3410 non-null   float64
 10  away_points           3410 non-null   float64
 11  away_rank             3410 non-null   float64
 12  home_points           3410 non-null   float64
 13  home_rank             3410 non-null   float64
dtypes: float64(8), int32(1), int64(2), object(3)
memory usage: 386.3+ KB

In [365]:
y=matches[["home_team_goal_count","away_team_goal_count"]]
x=matches.drop(columns=["home_team_goal_count","away_team_goal_count","season"])
x.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3410 entries, 0 to 4964
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   home_team_name  3410 non-null   object
 1   away_team_name  3410 non-null   object
 2   hour            3410 non-null   int32
 3   home_team_age   3410 non-null   float64
 4   away_team_age   3410 non-null   float64
 5   away_value      3410 non-null   float64
 6   home_value      3410 non-null   float64
 7   away_points     3410 non-null   float64
 8   away_rank       3410 non-null   float64
 9   home_points     3410 non-null   float64
 10  home_rank       3410 non-null   float64
dtypes: float64(8), int32(1), object(2)
memory usage: 306.4+ KB

In [366]:
y.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3410 entries, 0 to 4964
Data columns (total 2 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   home_team_goal_count  3410 non-null   int64
 1   away_team_goal_count  3410 non-null   int64
dtypes: int64(2)
memory usage: 79.9 KB

In [367]:
from sklearn.preprocessing import LabelEncoder
enco=LabelEncoder()
x["home_team_id"]=enco.fit_transform(x["home_team_name"])
x["away_team_id"]=enco.fit_transform(x["away_team_name"])
x=x.drop(columns=["home_team_name","away_team_name"])
x

,hour,home_team_age,away_team_age,away_value,home_value,away_points,away_rank,home_points,home_rank,home_team_id,away_team_id
0,19,27.173913,27.000000,0.02250,0.02350,727.636364,33.727273,755.454545,27.181818,91,32
1,13,25.869565,27.173913,0.10330,2.34100,750.454545,29.090909,1108.090909,6.909091,33,90
2,16,29.565217,28.173913,0.42750,0.00050,832.909091,16.454545,513.090909,62.363636,118,113
3,13,28.478261,27.130435,0.65050,0.06825,1073.181818,4.909091,630.833333,44.333333,103,81
5,19,28.782609,25.347826,0.15700,1.52000,726.181818,36.272727,1173.636364,7.090909,55,43
...,...,...,...,...,...,...,...,...,...,...,...
4960,19,26.376471,27.452381,0.61725,0.96150,1781.478333,3.500000,1749.135000,5.000000,33,39
4961,19,27.491525,27.531915,0.15600,0.71725,1646.568333,13.333333,1780.946667,3.166667,5,27
4962,19,27.452381,26.809524,0.14150,0.61725,1575.400000,21.000000,1781.478333,3.500000,38,79
4963,15,27.531915,26.809524,0.14150,0.15600,1575.400000,21.000000,1646.568333,13.333333,26,79
4964,15,27.491525,27.452381,0.61725,0.71725,1781.478333,3.500000,1780.946667,3.166667,5,39

In [370]:
print(matches[matches["away_team_name"]=="Argentina"])
print(x[x["away_team_id"]==5])

     home_team_name away_team_name  home_team_goal_count  \
22      Netherlands      Argentina                     0
36          Germany      Argentina                     1
344          Brazil      Argentina                     0
389          Russia      Argentina                     0
458           Qatar      Argentina                     0
463       Venezuela      Argentina                     0
466          Brazil      Argentina                     2
796           Chile      Argentina                     0
924          Brazil      Argentina                     0
1098      Indonesia      Argentina                     0
1368        Morocco      Argentina                     0
1432          Chile      Argentina                     0
1453        Germany      Argentina                     2
1466        Ecuador      Argentina                     1
1482         Brazil      Argentina                     0
2979       Colombia      Argentina                     2
2982      Venezuela      Argentina                     1
2985         Brazil      Argentina                     0
2994       Paraguay      Argentina                     0
3008        Uruguay      Argentina                     0
3015          Chile      Argentina                     1
3025        Ecuador      Argentina                     1
3673          Spain      Argentina                     6
3751         Israel      Argentina                     0
3780       Colombia      Argentina                     0
3785           Iraq      Argentina                     0
4738        Nigeria      Argentina                     1
4748         France      Argentina                     4
4794         Greece      Argentina                     0
4881        Nigeria      Argentina                     2
4901    Netherlands      Argentina                     0
4903        Germany      Argentina                     1
4940         Poland      Argentina                     0
4958    Netherlands      Argentina                     2

      away_team_goal_count  hour season  home_team_age  away_team_age  \
22                       0    19   2006      27.130435      26.565217
36                       1    15   2006      26.956522      26.565217
344                      1    10   2017      27.941176      27.184211
389                      1    13   2017      27.842105      27.184211
458                      2    19   2019      25.683544      26.445946
463                      2    19   2019      25.645161      26.445946
466                      0     0   2019      26.542857      26.445946
796                      1     1   2024      28.781818      28.517241
924                      0    11   2022      27.666667      27.491525
1098                     2    12   2023      24.944444      27.617647
1368                     1    19   2019      27.735294      26.445946
1432                     0     2   2019      28.114286      26.445946
1453                     2    18   2019      25.166667      26.445946
1466                     6    14   2019      26.100000      26.445946
1482                     1    17   2019      26.542857      26.445946
2979                     2    23   2021      27.964286      27.500000
2982                     3     0   2021      26.321429      27.500000
2985                     0    19   2021      27.280000      27.500000
2994                     0    23   2021      27.178571      27.500000
3008                     1    23   2021      27.346154      27.500000
3015                     2     0   2022      27.022727      27.491525
3025                     1    23   2022      24.939394      27.491525
3673                     1    19   2018      27.333333      27.641026
3751                     0    18   2018      28.000000      27.641026
3780                     0     0   2018      27.000000      27.641026
3785                     4    18   2018      24.850000      27.641026
4738                     2    18   2018      25.238095      27.641026
4748                     3    14   2018      26.103448      27.641026
4794                     2    18   2010      28.043478      27.565217
4881                     3    16   2014      25.869565      28.826087
4901                     0    20   2014      26.434783      28.826087
4903                     0    19   2014      26.217391      28.826087
4940                     2    19   2022      26.875000      27.491525
4958                     2    19   2022      27.247191      27.491525

      away_value  home_value  away_points  away_rank  home_points   home_rank
22       0.14050     0.65050  1163.272727   4.363636  1073.181818    4.909091
36       0.14050     0.54650  1163.272727   4.363636  1026.727273   12.727273
344      0.49692     0.67400  1501.916667   2.583333  1586.416667    1.666667
389      0.49692     0.07290  1501.916667   2.583333   568.916667   62.000000
458      0.67400     0.00050  1603.875000  10.000000  1391.125000   57.000000
463      0.67400     0.05925  1603.875000  10.000000  1500.500000   27.750000
466      0.67400     1.09475  1603.875000  10.000000  1702.125000    2.875000
796      0.61000     0.04250  1857.780000   1.000000  1492.553333   41.333333
924      0.71725     0.76750  1780.946667   3.166667  1835.550000    1.166667
1098     0.47100     0.00500  1850.212857   1.000000  1055.967143  147.571429
1368     0.67400     0.12250  1603.875000  10.000000  1448.875000   42.875000
1432     0.67400     0.19900  1603.875000  10.000000  1572.625000   15.750000
1453     0.67400     0.05675  1603.875000  10.000000  1582.750000   14.625000
1466     0.67400     0.12400  1603.875000  10.000000  1371.000000   62.125000
1482     0.67400     1.09475  1603.875000  10.000000  1702.125000    2.875000
2979     0.25175     0.03275  1700.681250   6.375000  1608.931250   15.500000
2982     0.25175     0.00775  1700.681250   6.375000  1456.206250   43.125000
2985     0.25175     0.35675  1700.681250   6.375000  1788.845000    2.375000
2994     0.25175     0.05600  1700.681250   6.375000  1470.770000   37.125000
3008     0.25175     0.09750  1700.681250   6.375000  1627.025000   12.500000
3015     0.71725     0.08475  1780.946667   3.166667  1519.300000   28.666667
3025     0.71725     0.09700  1780.946667   3.166667  1463.408333   43.833333
3673     1.02625     1.02525  1480.833333   7.666667  1433.083333    7.916667
3751     1.02625     0.05725  1480.833333   7.666667   830.333333   93.750000
3780     1.02625     0.15825  1480.833333   7.666667  1341.333333   13.916667
3785     1.02625     0.00200  1480.833333   7.666667   853.583333   87.083333
4738     1.02625     0.08900  1480.833333   7.666667  1052.416667   47.750000
4748     1.02625     0.28100  1480.833333   7.666667  1490.333333    4.833333
4794     0.08750     0.14975  1213.000000   6.363636  1006.909091   11.636364
4881     0.22425     0.07825  1395.750000   3.250000   646.416667   41.583333
4901     0.22425     0.44675  1395.750000   3.250000  1233.500000    8.333333
4903     0.22425     0.23225  1395.750000   3.250000  1524.333333    1.500000
4940     0.71725     0.13250  1780.946667   3.166667  1545.933333   25.666667
4958     0.71725     0.20875  1780.946667   3.166667  1684.440000    8.333333
      hour  home_team_age  away_team_age  away_value  home_value  away_points  \
3641    22           25.5      24.470588     0.00175       0.005   688.416667

       away_rank  home_points  home_rank  home_team_id  away_team_id
3641  129.833333  1034.333333  52.916667            56             5